---

<span style='color:red'>

# Python Review - Introduction

---
---
---

<span style='color:red'>

## 1. VARIABLES

---
---

<span style='color:red'>
    
### 1.1. Variable Naming Best Practices

In [1]:
# Camel Case - Test Variable Case
testVariableCase = 'Vanilla Ice Cream'

In [2]:
# Pascal Case - Test Variable Case
TestVariableCase = 'Chocolate Ice Cream'

In [3]:
# Snake Case - Test Variable Case
test_variable_case = 'Lemon Ice Cream'

---

In [4]:
testvar = 'Heavy Metal Rules!'
test_var = 'Heavy Metal Rules!'
_test_var = 'Heavy Metal Rules!' # Special variable or of a special use
test_Var = 'Heavy Metal Rules!'
TestVar = 'Heavy Metal Rules!'
test_var2 = 'Metallica Rules!'
test_var3 = 'Iron Maiden Rules!'

---

In [5]:
2Test_Var = 'OMG!!! Your are Wrong!!!'

SyntaxError: invalid decimal literal (ipython-input-1461035433.py, line 1)

In [6]:
test-var2 = 'OMG!!! Your are Wrong!!!'

SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='? (ipython-input-1016940882.py, line 1)

In [7]:
Test Var2 = 'OMG!!! Your are Wrong!!!'

SyntaxError: invalid syntax (ipython-input-2994068131.py, line 1)

In [8]:
test,var2 = 'OMG!!! Your are Wrong!!!'

ValueError: too many values to unpack (expected 2)

---
---
---

<span style='color:red'>
    
## 2. DATA TYPES

---
---

<span style='color:red'>
    
### 2.1. SETS

In [9]:
first_set = {1, 2, 3}

print(first_set)

{1, 2, 3}

In [10]:
second_set = {1, 2, 'Hey!'}
print(second_set)

{1, 2, 'Hey!'}

In [11]:
third_set = {1, 2, 3, 2, 1, 2, 3, 1, 2, 3, 2, 1, 2, 3, 2, 1}
print(third_set)

{1, 2, 3}

In [12]:
forth_set = {[1, 2, 3], 1, 2, 3}

TypeError: unhashable type: 'list'

---
<div style='background-color:rgba(117, 250, 90, 0.45); padding:15px;'>

**NOTE:**

Sets require that their items be hashable. In python the data types that are Hashable are `String`, `Numbers` and `Tuples`, because they can not change their value contents.

Therefore `Dictionaries` and `Lists` are not Hashable. So we can use it on SETS.

</div>

---

In [ ]:
forth_set = {(1, 2, 3), 1, 2, 3} # since a tuple is Hashable, there is no problem.
forth_set

{(1, 2, 3), 1, 2, 3}

In [ ]:
fifth_set = {7, 7, 1, 1, 3, 3, 'Carrot', 'Carrot'}
fifth_set

{1, 3, 7, 'Carrot'}

---

In [ ]:
fifth_set.update(3)

TypeError: 'int' object is not iterable

In [ ]:
fifth_set.update([3, 2, 1]) # we update values only using iterable data types.
fifth_set

{1, 2, 3, 7, 'Carrot'}

---

In [ ]:
fifth_set.discard(2)
fifth_set

{1, 3, 7, 'Carrot'}

In [ ]:
fifth_set.discard(5) # There are no Error Messages by discarting unexisting values on a SET.
fifth_set

{1, 3, 7, 'Carrot'}

In [ ]:
fifth_set.remove(1)
fifth_set

{3, 7, 'Carrot'}

In [ ]:
fifth_set.remove(2) # the number "2" does not exist in the SET.
fifth_set

KeyError: 2

---

In [ ]:
set_1 = {1, 2 , 3, 4, 5}
set_2 = {4, 5, 6, 7, 8}

In [ ]:
print(set_1 | set_2) # Union of the TWO SETS

{1, 2, 3, 4, 5, 6, 7, 8}

In [ ]:
print(set_1 & set_2) # Intersection of the TWO SETS.

{4, 5}

In [ ]:
print(set_1 - set_2) # Difference between the TWO SETS.

{1, 2, 3}

In [ ]:
print(set_2 - set_1) # Difference between the TWO SETS.

{8, 6, 7}

In [ ]:
print(set_1 ^ set_2) # Symmetric Difference
# - It shows only the values that are in one set, not both.

{1, 2, 3, 6, 7, 8}

---
---
---

<span style='color:red'>
    
## 3. OPERATORS

---
---

<span style='color:red'>
    
### 3.1. Identity and Bitwise Operators

In [ ]:
# Example of Identity Operator
x = [1, 8, 'Love']
y = [1, 8, 'Love']
z = x

In [ ]:
x is z

True

In [ ]:
x is y # are they in the same place of memory?

False

In [ ]:
x == y # Do they have the same values?

True

---

In [ ]:
# Example of Bitwise Operator
a = 20
b = 5

In [ ]:
bin(b)

'0b101'

In [ ]:
bin(a)

'0b10100'

In [ ]:
a & b

4

In [ ]:
bin(a & b)

'0b100'

In [ ]:
c = ~a
c

-21

In [ ]:
bin(c)

'-0b10101'

---
---
---

<span style='color:red'>
    
## 4. STATEMENTS

---
---

<span style='color:red'>

### 4.1. Nested IF ELSE Statements

In [ ]:
grade = 99

if grade >= 90:
    if grade >= 97:
        print(str(grade) + " = A+")
    elif grade >= 93:
        print(str(grade) + " = A")
    else:
        print(str(grade) + " = A-")
elif grade >= 80:
    if grade >= 87:
        print(str(grade) + " = B+")
    elif grade >= 83:
        print(str(grade) + " = B")
    else:
        print(str(grade) + " = B-")
elif grade >= 70:
    if grade >= 77:
        print(str(grade) + " = C+")
    elif grade >= 73:
        print(str(grade) + " = C")
    else:
        print(str(grade) + " = C-")
elif grade >= 60:
    if grade >= 67:
        print(str(grade) + " = D+")
    elif grade >= 63:
        print(str(grade) + " = D")
    else:
        print(str(grade) + " = D-")
else:
    print(str(grade) + " = F")

99 = A+

---
---

<span style='color:red'>
    
### 4.2. Nested FOR Loops

In [ ]:
greetings = ['Hey', 'Howdy', 'Sup', 'Hello']

x = 0
y = 0

for word in greetings:
    x += 1
    for letter in word:
        print('x =', x, ',   y =', y, '   -->', letter)
        y += 1

x = 1 ,   y = 0    --> H
x = 1 ,   y = 1    --> e
x = 1 ,   y = 2    --> y
x = 2 ,   y = 3    --> H
x = 2 ,   y = 4    --> o
x = 2 ,   y = 5    --> w
x = 2 ,   y = 6    --> d
x = 2 ,   y = 7    --> y
x = 3 ,   y = 8    --> S
x = 3 ,   y = 9    --> u
x = 3 ,   y = 10    --> p
x = 4 ,   y = 11    --> H
x = 4 ,   y = 12    --> e
x = 4 ,   y = 13    --> l
x = 4 ,   y = 14    --> l
x = 4 ,   y = 15    --> o

---
---

<span style='color:red'>
    
### 4.3. Break, Continue, Else, Pass

In [ ]:
# Break - Example 1
counter = 0

while counter <= 10:
    print(counter)
    if counter == 6:
        break
    counter += 1

0
1
2
3
4
5
6

In [ ]:
# Break - Example 2
integers = [1, 2, 3, 4, 5, 6, 7]

for num in integers:
    power_of_num = num**num
    if power_of_num > 3000:
        break
    print(power_of_num)

1
4
27
256

In [ ]:
# Continue - Example 1
number = 0

while number < 5:
    number = number + 1
    if number == 3:
        continue
    print(number)

1
2
4
5

In [ ]:
# Continue - Example 2
integers = [1, 2, 3, 4, 5, 6, 7]

for num in integers:
    power_of_num = num**num
    if 200 <= power_of_num <= 3300:
        continue
    print(power_of_num)

1
4
27
46656
823543

In [ ]:
# Else - Example 1
counter = 0

while counter <=10:
    if counter == 6.5:
        break
    print(counter)
    counter += 1
else:
    print('No Breaks Found')

0
1
2
3
4
5
6
7
8
9
10
No Breaks Found

In [ ]:
# Else - Example 2
integers = [1, 2, 3, 4, 5]

for num in integers:
    power_of_num = num**num
    if power_of_num > 4000:
        break
    print(power_of_num)
else:
    power_of_num = num**num
    print(power_of_num+1)

1
4
27
256
3125
3126

In [ ]:
# Pass - Example 1
integers = [1, 2, 3, 4, 5]

for num in integers:
    pass

---
---

<span style='color:red'>
    
### 4.4. Nested While Loops

In [ ]:
number = 0
while number <= 5:
    print(number)
    inner_number = 0
    while inner_number < 3:
        print(inner_number)
        inner_number += 1
    number += 1
    print('---')

0
0
1
2
---
1
0
1
2
---
2
0
1
2
---
3
0
1
2
---
4
0
1
2
---
5
0
1
2
---

In [ ]:
number = 0
while number <= 5:
    print(number)
    inner_number = 0
    while inner_number < 3:
        inner_number += 1
        if inner_number == 2:
            continue
        print(inner_number)
    else:
        print('Inner While Loop Ended')
    number += 1
else:
    print('Outer While Loop Ended')

0
1
3
Inner While Loop Ended
1
1
3
Inner While Loop Ended
2
1
3
Inner While Loop Ended
3
1
3
Inner While Loop Ended
4
1
3
Inner While Loop Ended
5
1
3
Inner While Loop Ended
Outer While Loop Ended

---
---

<span style='color:red'>
    
### 4.5. List Comprehension

In [ ]:
flavors = ['Vanilla', 'Chocolate', 'Chocolate Fudge', 'Strawberry', 'Choco Swirl']
choco_flavors = []

for flavor in flavors:
    if 'Choco' in flavor:
        choco_flavors.append(flavor)
print(choco_flavors)

['Chocolate', 'Chocolate Fudge', 'Choco Swirl']

In [ ]:
choco_flavors2 = [flavor for flavor in flavors if 'Choco' in flavor]
print(choco_flavors2)

['Chocolate', 'Chocolate Fudge', 'Choco Swirl']

In [ ]:
new_list = [x**2 for x in range(10) if x % 2 == 0]
print(new_list)

[0, 4, 16, 36, 64]

---

---

---

<span style='color:red'>
    
## 5. FUNCTIONS

---
---

<span style='color:red'>
    
### 5.1. Default and Arbitrary Arguments

In [ ]:
def num_squared(number, power=3):
    print(number**power)

num_squared(3)

27

---

In [ ]:
args_tuple = (5, 6, 1, 2, 3, 4)

def arg_func(*number):
    print(number[0] * number[1])

arg_func(*args_tuple)

30

In [ ]:
print('Example 1:')
arg_func(*(3,4, 5, 6, 7))
print('-'*90)

print('Example 2:')
arg_func(*[7, 3, 6, 8, 9, 1])
print('-'*90)

print('Example 3:')
arg_func(*{3, 6, 9, 1})
print('-'*90)

Example 1:
12
------------------------------------------------------------------------------------------
Example 2:
21
------------------------------------------------------------------------------------------
Example 3:
27
------------------------------------------------------------------------------------------

In [ ]:
tuple_1 = ('John', 'Mikey', 'Sally')

def number_args(*word):
    print("Hello", word[1], ' - Nice to meet you!')

number_args(*tuple_1)

Hello Mikey  - Nice to meet you!


---

---



<span style='color:red'>

### 5.2. Arbitrary Keyword Arguments

In [ ]:
# **Kwargs

def number_kwargs(**kwargs):
    print(kwargs['Greeting'], kwargs['Name'])

In [ ]:
number_kwargs(Greeting='Howdy!', Name='Milton')

Howdy! Milton

---

In [ ]:
def number_kwargs2(**Names):
    for key, value in Names.items():
        print(f'{key} : {value}')

In [ ]:
number_kwargs2(Name1 = 'Milton', Name2='Marcela', Name3='Valentina', Name4="Bertha")

Name1 : Milton
Name2 : Marcela
Name3 : Valentina
Name4 : Bertha

In [ ]:
my_dict = {'1':'Milton', '2':'Marcela', '3':'Valentina', '4':'Rodolfo', '5':'Gianely', '6':'Mia'}

number_kwargs2(**my_dict)

1 : Milton
2 : Marcela
3 : Valentina
4 : Rodolfo
5 : Gianely
6 : Mia

---

In [ ]:
def wild_function(one, *two, **three):
    print(one)
    print(two[0], two[2])
    print(three.values())

wild_function(33, *['Hi', 45, 'year old guy'], **my_dict)

33
Hi year old guy
dict_values(['Milton', 'Marcela', 'Valentina', 'Rodolfo', 'Gianely', 'Mia'])

---
---


<span style='color:red'>

### 5.3. Lambda Function

</span>

Lambda functions, also known as anonymous functions, allow you to create small, one-line functions without a formal function definition. They are typically used for simple and short operations where a named function is not necessary. Lambda functions are defined using the lambda keyword followed by the function's parameters and a single expression.

In [ ]:
lambda x: x**2

In [ ]:
(lambda x: x**2)(6)

36

---
---
---

<span style='color:red'>
    
## 6. WORKING WITH FILES

---
---

<span style='color:red'>

### 6.1. Creating a File

In [ ]:
open('files/1.Fake_File.txt', mode='x')

FileExistsError: [Errno 17] File exists: 'files/1.Fake_File.txt'

In [ ]:
write_file = open('files/1.Fake_File.txt', mode='w')

In [ ]:
write_file = open('files/1.Fake_File.csv', mode='w')

In [ ]:
write_file = open('files/1.Fake_File.tsv', mode='w')

In [ ]:
write_file = open('files/1.Fake_File.json', mode='w')

---
---

<span style='color:red'>
    
### 6.2. Reading, Writing and Closing Files

In [ ]:
# Step 1: We read the existing file...
read_file = open('files/1.Fake_File.txt', mode='r')

print(read_file.read())
read_file.close()

In [ ]:
# Step 2: We now write something to the same file...
write_file = open('files/1.Fake_File.txt', mode='w')

write_file.write('This is the first time I am writing to a file using Python! Woohoo!')
write_file.close()

In [ ]:
# Step 3: Now I read again the same file...
read_file = open('files/1.Fake_File.txt', mode='r')

print(read_file.read())

This is the first time I am writing to a file using Python! Woohoo!

In [ ]:
read_file.close()

---
---

<span style='color:red'>

### 6.3. Context Managers

In [ ]:
read_file = open('files/1.Fake_File.txt', mode='r')
print(read_file.read())
read_file.close()

This is the first time I am writing to a file using Python! Woohoo!

In [ ]:
# Another way to do this task is this...
read_file = open('files/1.Fake_File.txt', mode='w')
try:
    read_file.write('Hey!')
except Exception as e:
    print(e)
finally:
    read_file.close()

In [ ]:
# The improved way to read files is using Context Managers
with open('files/1.Fake_File.txt', mode='w') as write_file:
    write_file.write('This is our first time using a CONTEXT MANAGER!!! GREAT MILTON!!!')

In [ ]:
with open('files/1.Fake_File.txt', mode='r') as read_file:
    print(read_file.read())

This is our first time using a CONTEXT MANAGER!!! GREAT MILTON!!!

---
---


<span style='color:red'>

### 6.4. Writing and Appending to a File

In [ ]:
# STEP 1: First we write somethin to a new file...
with open('files/2.NewFile.txt', mode='w') as write_file:
    write_file.write('This is the first sentences in this file.')

In [ ]:
# STEP 2: Then we read what we have just wrote...
with open('files/2.NewFile.txt', mode='r') as read_file:
    print(read_file.read())

This is the first sentences in this file.

In [ ]:
# STEP 3: Now we will append some new text
with open('files/2.NewFile.txt', mode='a') as appended_file:
    appended_file.write('\nThis is the second sentence in this new file.')

In [ ]:
# STEP 4: we read again what we have wrote...
with open('files/2.NewFile.txt', mode='r') as read_file:
    print(read_file.read())

This is the first sentences in this file.
This is the second sentence in this new file.

In [ ]:
text = """
This is now the third line.
Opps now this is the fourth line.
Noway!!! now we have the fifth line.
:)

"""

with open('files/2.NewFile.txt', mode='a') as write_file:
    write_file.write(text)

In [ ]:
with open('files/2.NewFile.txt', mode='r') as read_file:
    print(read_file.read())

This is the first sentences in this file.
This is the second sentence in this new file.
This is now the third line.
Opps now this is the fourth line.
Noway!!! now we have the fifth line.
:)

---

In [ ]:
my_list = 'Column1, Column2, Column3'

with open('files/3.CSVFile.csv', 'w') as write_file:
    write_file.write(my_list)

In [ ]:
my_text2 = '\none data, two data, three data.'

with open('files/3.CSVFile.csv', 'a') as appended_file:
    appended_file.write(my_text2)

---

---

In [ ]:
import csv

col_names = ['Name', 'Job', 'Age']
data = [['Milton Valle', 'Machine Learning Engineer', '45'],
        ['Boris Castellon', 'Data Engineer', '34'],
        ['Daniela Roman', 'Data Analyst', '33']]

with open('files/3.CSVFile.csv', mode='w', newline='') as write_file:
    mv_writer = csv.writer(write_file)
    mv_writer.writerow(col_names)
    mv_writer.writerows(data)

---

In [ ]:
my_dict = [{'Name':'Milton V.', 'Job':'ML Engineer', 'Age':45},
          {'Name':'Boris C.', 'Job':'Data Engineer', 'Age':34},
          {'Name':'Daniela R.', 'Job':'Data Analyst', 'Age':33}]

with open('files/3.CSV_DictionaryFile.csv', 'w', newline='') as write_file:
    mv_writer = csv.DictWriter(write_file, col_names)
    mv_writer.writeheader()
    mv_writer.writerows(my_dict)

---

In [ ]:
import json

col_names = ['Name', 'Job', 'Age']
my_dict = [{'Name':'Milton V. L.', 'Job':'M.L. Engineer Jr.', 'Age':45},
          {'Name':'Boris C. G.', 'Job':'Data Engineer Jr.', 'Age':34},
          {'Name':'Daniela R. R.', 'Job':'Data Analyst Jr.', 'Age':33}]

with open('files/3.JSON_File.json', 'w', newline='') as write_file:
    json.dump(my_dict, write_file)

---
---

<span style='color:red'>
    
### 6.5. Creating a Folder

In [ ]:
import os

In [ ]:
os.mkdir('files/Example_Folder')

FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'files/Example_Folder'

In [ ]:
if not os.path.exists('files/Example_Folder2'):
    os.mkdir('files/Example_Folder2')

In [ ]:
if not os.path.exists('files/Example_Folder3'):
    os.makedirs('files/Example_Folder3/SubFolder1/SubFolder2/SubFolder3')

---
---

<span style='color:red'>
    
### 6.6. Copying and Moving Files

In [ ]:
import os
import shutil

In [ ]:
path = 'files/1.Fake_File.csv'

shutil.move(path, 'files/Example_Folder/1.Fake_File.csv')

'files/Example_Folder/1.Fake_File.csv'

In [ ]:
path = 'files/1.Fake_File.txt'

shutil.copy(path, 'files/Example_Folder2/1.Fake_File_New.txt')

'files/Example_Folder2/1.Fake_File_New.txt'

---
---

<span style='color:red'>
    
### 6.7. Pandas 101 - Opening Files with Pandas

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('files/Example_Folder3/countries of the world.csv')
df

             Country                               Region
0       Afghanistan         ASIA (EX. NEAR EAST)
1           Albania   EASTERN EUROPE
2           Algeria   NORTHERN AFRICA
3    American Samoa   OCEANIA
4           Andorra   WESTERN EUROPE
..               ...                                  ...
222       West Bank   NEAR EAST
223  Western Sahara   NORTHERN AFRICA
224           Yemen   NEAR EAST
225          Zambia   SUB-SAHARAN AFRICA
226        Zimbabwe   SUB-SAHARAN AFRICA

[227 rows x 2 columns]

In [ ]:
#with open('files/Example_Folder3/countries of the world.csv', 'r') as read_file:
#    print(read_file.read())

In [ ]:
dfj = pd.read_json('files/Example_Folder3/json_sample.json')
dfj

,12 Strong,A Fantastic Woman (Una Mujer Fantástica),All The Money In The World,Bilal: A New Breed Of Hero,Call Me By Your Name,Darkest Hour,Den Of Thieves,Ferdinand,Fifty Shades Freed,Film Stars Don'T Die In Liverpool,...,The 15:17 To Paris,The Commuter,The Disaster Artist,The Greatest Showman,The Insult (L'Insulte),The Post,The Shape Of Water,"Three Billboards Outside Ebbing, Missouri",Till The End Of The World,Winchester
0,"{'Genre': 'Action', 'Gross': '$453,173', 'IMDB...","{'popcornscore': 83, 'rating': 'R', 'tomatosco...","{'popcornscore': 71, 'rating': 'R', 'tomatosco...","{'popcornscore': 91, 'rating': 'PG13', 'tomato...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': 84, 'rating': 'PG13', 'tomato...","{'Genre': 'Action', 'Gross': '$491,898', 'IMDB...","{'popcornscore': 49, 'rating': 'PG', 'tomatosc...","{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 69, 'rating': 'R', 'tomatosco...",...,"{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 48, 'rating': 'PG13', 'tomato...","{'popcornscore': 89, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$627,248', 'I...","{'popcornscore': 86, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$463,228', 'I...","{'Genre': 'Adventure', 'Gross': '$448,287', 'I...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': -1, 'rating': 'NR', 'tomatosc...","{'Genre': 'Biography', 'Gross': '$696,786', 'I..."

In [ ]:
df3 = pd.read_excel('files/Example_Folder3/world_population_excel_workbook.xlsx')
df3

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572,11655,12182,13142,14723,13454,11315,9377,142,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El AaiÃºn,Africa,575986,556048,491824,413296,270375,178529,116775,76371,266000,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614,32284046,28516545,24743946,18628700,13375121,9204938,6843607,527968,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675,18927715,16248230,13792086,9891136,7686401,5720438,4281671,752612,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537,15669666,14154937,12839771,11834676,10113893,7049926,5202918,390757,41.7665,1.0204,0.20

In [ ]:
df4 = pd.read_excel('files/Example_Folder3/world_population_excel_workbook.xlsx', sheet_name='Sheet1')
df4

     Rank CCA3            Country           Capital
0      36  AFG        Afghanistan             Kabul
1     138  ALB            Albania            Tirana
2      34  DZA            Algeria           Algiers
3     213  ASM     American Samoa         Pago Pago
4     203  AND            Andorra  Andorra la Vella
..    ...  ...                ...               ...
229   226  WLF  Wallis and Futuna          Mata-Utu
230   172  ESH     Western Sahara         El AaiÃºn
231    46  YEM              Yemen             Sanaa
232    63  ZMB             Zambia            Lusaka
233    74  ZWE           Zimbabwe            Harare

[234 rows x 4 columns]

---
---

<span style='color:red'>
    
### 6.8. Pandas 101 - Manipulating Data in a DataFrame

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel('files/Example_Folder3/world_population_excel_workbook.xlsx', sheet_name='Sheet1')
df

     Rank CCA3            Country           Capital
0      36  AFG        Afghanistan             Kabul
1     138  ALB            Albania            Tirana
2      34  DZA            Algeria           Algiers
3     213  ASM     American Samoa         Pago Pago
4     203  AND            Andorra  Andorra la Vella
..    ...  ...                ...               ...
229   226  WLF  Wallis and Futuna          Mata-Utu
230   172  ESH     Western Sahara         El AaiÃºn
231    46  YEM              Yemen             Sanaa
232    63  ZMB             Zambia            Lusaka
233    74  ZWE           Zimbabwe            Harare

[234 rows x 4 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     234 non-null    int64
 1   CCA3     234 non-null    object
 2   Country  234 non-null    object
 3   Capital  234 non-null    object
dtypes: int64(1), object(3)
memory usage: 7.4+ KB

In [ ]:
df.shape

(234, 4)

In [ ]:
df.head(9)

   Rank CCA3              Country           Capital
0    36  AFG          Afghanistan             Kabul
1   138  ALB              Albania            Tirana
2    34  DZA              Algeria           Algiers
3   213  ASM       American Samoa         Pago Pago
4   203  AND              Andorra  Andorra la Vella
5    42  AGO               Angola            Luanda
6   224  AIA             Anguilla        The Valley
7   201  ATG  Antigua and Barbuda    Saint Johnâ€™s
8    33  ARG            Argentina      Buenos Aires

In [ ]:
df.tail(6)

     Rank CCA3            Country    Capital
228    16  VNM            Vietnam      Hanoi
229   226  WLF  Wallis and Futuna   Mata-Utu
230   172  ESH     Western Sahara  El AaiÃºn
231    46  YEM              Yemen      Sanaa
232    63  ZMB             Zambia     Lusaka
233    74  ZWE           Zimbabwe     Harare

In [ ]:
df['Rank']

0       36
1      138
2       34
3      213
4      203
      ...
229    226
230    172
231     46
232     63
233     74
Name: Rank, Length: 234, dtype: int64

In [ ]:
df.iloc[1]

Rank           138
CCA3           ALB
Country    Albania
Capital     Tirana
Name: 1, dtype: object

In [ ]:
df.loc[1]

Rank           138
CCA3           ALB
Country    Albania
Capital     Tirana
Name: 1, dtype: object

In [ ]:
df1 = pd.read_excel('files/Example_Folder3/world_population_excel_workbook.xlsx',
             sheet_name='Sheet1', index_col='Country')
df1

                   Rank CCA3           Capital
Country
Afghanistan          36  AFG             Kabul
Albania             138  ALB            Tirana
Algeria              34  DZA           Algiers
American Samoa      213  ASM         Pago Pago
Andorra             203  AND  Andorra la Vella
...                 ...  ...               ...
Wallis and Futuna   226  WLF          Mata-Utu
Western Sahara      172  ESH         El AaiÃºn
Yemen                46  YEM             Sanaa
Zambia               63  ZMB            Lusaka
Zimbabwe             74  ZWE            Harare

[234 rows x 3 columns]

In [ ]:
df1.loc['Albania']

Rank          138
CCA3          ALB
Capital    Tirana
Name: Albania, dtype: object

In [ ]:
df1.iloc[1]

Rank          138
CCA3          ALB
Capital    Tirana
Name: Albania, dtype: object

In [ ]:
df[df['Country'].str.contains('United')]

     Rank CCA3                       Country           Capital
219    97  ARE          United Arab Emirates         Abu Dhabi
220    21  GBR                United Kingdom            London
221     3  USA                 United States  Washington, D.C.
222   200  VIR  United States Virgin Islands  Charlotte Amalie

In [ ]:
df[df['Rank'] <= 10].sort_values(by=['Rank'])

     Rank CCA3        Country           Capital
41      1  CHN          China           Beijing
92      2  IND          India         New Delhi
221     3  USA  United States  Washington, D.C.
93      4  IDN      Indonesia           Jakarta
156     5  PAK       Pakistan         Islamabad
149     6  NGA        Nigeria             Abuja
27      7  BRA         Brazil          Brasilia
16      8  BGD     Bangladesh             Dhaka
171     9  RUS         Russia            Moscow
131    10  MEX         Mexico       Mexico City

In [ ]:
df[df['Rank'] <= 10].sort_values(by=['Rank'], ascending=False)

     Rank CCA3        Country           Capital
131    10  MEX         Mexico       Mexico City
171     9  RUS         Russia            Moscow
16      8  BGD     Bangladesh             Dhaka
27      7  BRA         Brazil          Brasilia
149     6  NGA        Nigeria             Abuja
156     5  PAK       Pakistan         Islamabad
93      4  IDN      Indonesia           Jakarta
221     3  USA  United States  Washington, D.C.
92      2  IND          India         New Delhi
41      1  CHN          China           Beijing

In [ ]:
df5 = df.copy()

In [ ]:
df5[df5['Rank'] <= 10].sort_values(by=["Rank"], ascending=False, inplace=True)

C:\Users\Milton Valle_Pro\AppData\Local\Temp\ipykernel_3912\620586860.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5[df5['Rank'] <= 10].sort_values(by=["Rank"], ascending=False, inplace=True)

---

In [ ]:
df6 = pd.read_csv('files/Example_Folder3/world_population.csv')
df6

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [ ]:
df6.columns

Index(['Rank', 'CCA3', 'Country', 'Capital', 'Continent', '2022 Population',
       '2020 Population', '2015 Population', '2010 Population',
       '2000 Population', '1990 Population', '1980 Population',
       '1970 Population', 'Area (km²)', 'Density (per km²)', 'Growth Rate',
       'World Population Percentage'],
      dtype='object')

In [ ]:
grouped_df = df6.groupby('Continent')[['2022 Population',
       '2020 Population', '2015 Population', '2010 Population',
       '2000 Population', '1990 Population', '1980 Population',
       '1970 Population', 'Area (km²)', 'Density (per km²)', 'Growth Rate',
       'World Population Percentage']]

grouped_df.mean()

,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Continent,,,,,,,,,,,,
Africa,2.545588e+07,2.387144e+07,2.141970e+07,1.889820e+07,1.459837e+07,1.137696e+07,8.586032e+06,6.567175e+06,5.378793e+05,126.406569,1.021180,0.313509
Asia,9.632739e+07,9.495513e+07,8.916500e+07,8.908777e+07,8.058084e+07,4.864000e+07,4.027833e+07,4.383988e+07,6.427628e+05,1025.024136,1.009384,1.183800
Europe,1.505537e+07,1.491584e+07,1.502745e+07,1.471228e+07,1.481769e+07,1.478520e+07,1.420000e+07,1.311848e+07,4.602082e+05,663.324742,1.002256,0.186600
North America,1.500740e+07,1.485591e+07,1.425960e+07,1.356802e+07,1.215174e+07,1.053166e+07,9.207334e+06,7.885865e+06,6.061044e+05,272.494118,1.004285,0.187750
Oceania,2.046386e+06,1.910149e+06,1.756664e+06,1.613164e+06,1.357512e+06,1.162775e+06,9.965322e+05,8.469683e+05,3.702209e+05,132.543065,1.007383,0.023913
South America,3.120119e+07,3.082357e+07,2.950960e+07,2.678940e+07,2.501589e+07,2.122474e+07,1.727064e+07,1.378194e+07,1.301303e+06,20.971979,1.007957,0.391429

In [ ]:
grouped_df.count()

,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Continent,,,,,,,,,,,,
Africa,56,57,54,54,56,56,56,55,56,55,56,57
Asia,49,49,50,47,46,48,48,48,50,50,50,50
Europe,49,50,49,50,49,48,48,50,50,50,50,50
North America,40,40,40,40,40,40,40,40,40,38,39,40
Oceania,22,23,23,23,23,23,23,23,23,23,23,23
South America,14,14,14,13,13,14,14,14,13,14,14,14

---
---

<span style='color:red'>
    
### 6.9. Pandas 101 - Exporting Data Using Pandas

In [ ]:
export_df = grouped_df.mean()
export_df.to_csv('files/Example_Folder3/Grouped_df_mean.csv')

In [ ]:
export_df.to_excel('files/Example_Folder3/Grouped_df_mean.xlsx')

---

---
---

<span style='color:red'>
    
# 7. HANDLING ERRORS AND EXCEPTIONS

---
---

<span style='color:red'>
    
## 7.1. Try Except Basics

In [ ]:
x = 10
y = 20

print(x)

10

In [ ]:
try:
    print(x)
except NameError:
    print('Variable not defined')
except:
    print('There was an error!')

print('This is more code we want to run...')

10
This is more code we want to run...

In [ ]:
print(hola)

NameError: name 'hola' is not defined

In [ ]:
try:
    print(hola)
except NameError:
    print('Variable not defined')
except:
    print('There was an error!')

print('This is more code we want to run...')

Variable not defined
This is more code we want to run...

In [ ]:
try:
    print(hola)
except Exception as e:
    print(e)
except NameError:
    print('Variable not defined')
except:
    print('There was an error!')

print('This is more code we want to run...')

name 'hola' is not defined
This is more code we want to run...

In [ ]:
try:
    print(x)
except Exception as e:
    print(e)
except NameError:
    print('Variable not defined')
except:
    print('There was an error!')
else:
    print("ELSE WAS TRIGGERED")

print('This is more code we want to run...')

10
ELSE WAS TRIGGERED
This is more code we want to run...

In [ ]:
try:
    print(hola)
except Exception as e:
    print(e)
except NameError:
    print('Variable not defined')
except:
    print('There was an error!')
else:
    print("ELSE WAS TRIGGERED")

print('This is more code we want to run...')

name 'hola' is not defined
This is more code we want to run...

In [ ]:
try:
    print(x)
except Exception as e:
    print(e)
except NameError:
    print('Variable not defined')
except:
    print('There was an error!')
else:
    print("ELSE WAS TRIGGERED")
finally:
    print('FINALLY!!!')

10
ELSE WAS TRIGGERED
FINALLY!!!

In [ ]:
try:
    print(hola)
except Exception as e:
    print(e)
except NameError:
    print('Variable not defined')
except:
    print('There was an error!')
else:
    print("ELSE WAS TRIGGERED")
finally:
    print('FINALLY!!!')

name 'hola' is not defined
FINALLY!!!

---
---

<span style='color:red'>
    
## 7.2. Try Except with Files

In [ ]:
path = 'Try-Except_Folder/MainFile.txt'

try:
    with open('Try-Except_Folder/NewData2.txt', 'r') as read_file:
        main_message = read_file.read()
        print('    - Variable Created! :)')
except Exception as e:
    print(e)
else:
    with open(path, 'a', newline='\n') as append_file:
        append_file.write(main_message)
finally:
    print("    ...Now we will print the Appended 'MainFile.txt'\n")
    with open(path, 'r') as read_file:
        print(read_file.read())

[Errno 2] No such file or directory: 'Try-Except_Folder/NewData2.txt'
    ...Now we will print the Appended 'MainFile.txt'

This is from my Main File!

Yay! :)

In [ ]:
path = 'Try-Except_Folder/MainFile.txt'

try:
    with open('Try-Except_Folder/NewData.txt', 'r') as read_file:
        main_message = read_file.read()
        print('    - Variable Created! :)')
except Exception as e:
    print(e)
else:
    with open(path, 'a', newline='\n') as append_file:
        append_file.write(main_message)
finally:
    print("    ...Now we will print the Appended 'MainFile.txt'\n")
    with open(path, 'r') as read_file:
        print(read_file.read())

    - Variable Created! :)
    ...Now we will print the Appended 'MainFile.txt'

This is from my Main File!

Yay! :)


This is data we wanted to append.