---

---
---

<span style='color:red'>

# WEB SCRAPING

---
---
---

<span style='color:red'>

## 1. Beautiful Soup and Requests

In [1]:
from bs4 import BeautifulSoup
import requests

In [2]:
url = 'https://webscraper.io/test-sites/e-commerce/allinone/phones'

In [3]:
requests.get(url)

In [4]:
page = requests.get(url)

In [5]:
soup = BeautifulSoup(page.text, 'html')

In [6]:
print(soup)

<!DOCTYPE html>

<html lang="en">
<head>
<!-- Google Tag Manager -->
<script nonce="zghyGUKys2buBC2u1bNxyCQXnXDzEJed">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>Allinone | Web Scraper Test Sites</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=b504eb6c3f627c4a2887e7f92d2e2723" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=bc6c0d86aeabab8583f9814643f23faa" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/e-commerce/allinone/phones" rel="canonical"/>
<meta content="Allinone | Web Scraper Test Sites" property="og:title"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/e-commerce/allinone/phones" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script defer="" src="/js/app.js?id=d58701ba9d2d08185240f2ddbf489d15"></script>
</meta></meta></head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" src="/img/logo_white.svg"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500"></i>
							Install
						</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>
</header>
<div class="wrapper">
<div class="formenu-here container-fluid">
</div>
<div class="container-fluid blog-hero">
<div class="container">
<div class="row">
<div class="col-lg-12">
<h1>Test Sites</h1>
</div>
</div>
</div>
</div>
<div class="container test-site">
<div class="row">
<div class="col-lg-3 sidebar">
<div class="navbar-light sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
<ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a class="nav-link" href="/test-sites/e-commerce/allinone" itemprop="url"><span itemprop="name">Home</span></a>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/computers" itemprop="url">
<span itemprop="name">Computers</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
<li class="nav-item active">
<a aria-label="Navigation category" class="category-link nav-link active" href="/test-sites/e-commerce/allinone/phones" itemprop="url">
<span itemprop="name">Phones</span>
<i aria-hidden="true" class="ws-icon ws-icon-down"></i>
</a>
<ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/allinone/phones/touch" itemprop="url">
<span itemprop="name">Touch</span>
</a>
</li>
</ul>
</li>
</ul>
</div>
</div>
</div>
<div class="col-lg-9">
<h2 class="page-header">Phones category</h2>
<h3>Top items being scraped right now</h3>
<div class="row">
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$499.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/6" itemprop="name" title="Ubuntu Edge">
						Ubuntu Edge
					</a>
</h4>
<p class="description card-text" itemprop="description">Sapphire glass</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="1">
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$899.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/7" itemprop="name" title="Iphone">
						Iphone
					</a>
</h4>
<p class="description card-text" itemprop="description">White</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">10</span> reviews
				</p>
<p data-rating="1">
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$899.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/9" itemprop="name" title="Iphone">
						Iphone
					</a>
</h4>
<p class="description card-text" itemprop="description">Black</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">1</span> reviews
				</p>
<p data-rating="1">
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
</div>
<div id="static-pagination">
</div>
</div>
</div>
</div>
<div class="clearfix"></div>
<div class="push"></div>
</div>
<div class="container-fluid footer" id="layout-footer">
<div class="container">
<div class="row">
<div class="col-lg-3">
<ul>
<li><p>Products</p></li>
<li>
<a href="/">Web Scraper browser extension</a>
</li>
<li>
<a href="/cloud-scraper">Web Scraper Cloud</a>
</li>
</ul>
</div>
<div class="col-lg-3">
<ul>
<li><p>Company</p></li>
<li>
<a href="/about-us">About us</a>
</li>
<li>
<a href="/contact">Contact</a>
</li>
<li>
<a href="/privacy-policy">Website Privacy Policy</a>
</li>
<li>
<a href="/extension-privacy-policy">Browser Extension Privacy Policy</a>
</li>
<li>
<a href="https://webscraper.io/downloads/Web_Scraper_Media_Kit.zip">Media kit</a>
</li>
<li><a href="/jobs">Jobs</a></li>
</ul>
</div>
<div class="col-lg-3">
<ul>
<li><p>Resources</p></li>
<li><a href="/blog">Blog</a></li>
<li>
<a href="/documentation">Documentation</a>
</li>
<li>
<a href="/tutorials">Video Tutorials</a>
</li>
<li>
<a href="/screenshots">Screenshots</a>
</li>
<li>
<a href="/test-sites">Test Sites</a>
</li>
<li>
<a href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
<li>
<a href="https://status.webscraper.io/" rel="noopener" target="_blank">Status</a>
</li>
</ul>
</div>
<div class="col-lg-3">
<ul>
<li><p>CONTACT US</p></li>
<li>
<a href="mailto:info@webscraper.io">info@webscraper.io</a>
</li>
<li>Ubelu 5-71,<br/> Adazi, Latvia, LV-2164</li>
</ul>
<ul class="smedia">
<li>
<a aria-label="Web Scraper on Facebook" href="https://www.facebook.com/webscraperio/" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-facebook-f"></i>
</a>
</li>
<li>
<a aria-label="Web Scraper on X" href="https://twitter.com/webscraperio" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-twitter"></i>
</a>
</li>
<li>
<a aria-label="Web Scraper on LinkedIn" href="https://lv.linkedin.com/company/web-scraper" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-linkedin"></i>
</a>
</li>
<li>
<a aria-label="Web Scraper on Youtube" href="https://youtube.com/@WebScraper/videos" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-youtube"></i>
</a>
</li>
<li>
<a aria-label="Download the Web Scraper extension" class="install-extension browser-icon-dark" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-chrome-dark"></i>
</a>
</li>
</ul>
</div>
</div>
<div class="row">
<div class="col-lg-12">
<p class="copyright">Copyright © 2025
					<b>Web Scraper</b> | All rights reserved</p>
</div>
</div>
</div>
</div>
</body>
</html>

---

In [7]:
soup_pretty = soup.prettify()
print(soup_pretty)

<!DOCTYPE html>
<html lang="en">
 <head>
  <!-- Google Tag Manager -->
  <script nonce="zghyGUKys2buBC2u1bNxyCQXnXDzEJed">
   (function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');
  </script>
  <!-- End Google Tag Manager -->
  <title>
   Allinone | Web Scraper Test Sites
  </title>
  <meta charset="utf-8"/>
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
  <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
   <meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">
    <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
    <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
    <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
    <link href="/icon.svg" rel="icon" type="image/svg+xml"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <link href="https://fonts.googleapis.com" rel="preconnect"/>
    <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;900&amp;display=swap" rel="stylesheet"/>
    <link href="/css/app.css?id=b504eb6c3f627c4a2887e7f92d2e2723" rel="stylesheet"/>
    <link href="/css/ws-icons.font.css?id=bc6c0d86aeabab8583f9814643f23faa" rel="stylesheet"/>
    <link href="https://webscraper.io/test-sites/e-commerce/allinone/phones" rel="canonical"/>
    <meta content="Allinone | Web Scraper Test Sites" property="og:title"/>
    <meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
    <meta content="website" property="og:type"/>
    <meta content="https://webscraper.io/test-sites/e-commerce/allinone/phones" property="og:url"/>
    <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
    <script defer="" src="/js/app.js?id=d58701ba9d2d08185240f2ddbf489d15">
    </script>
   </meta>
  </meta>
 </head>
 <body>
  <!-- Google Tag Manager (noscript) -->
  <noscript>
   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <!-- End Google Tag Manager (noscript) -->
  <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
   <div class="container">
    <div class="navbar-header">
     <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
       <span class="visually-hidden">
        Toggle navigation
       </span>
       <span class="icon-bar top-bar">
       </span>
       <span class="icon-bar middle-bar">
       </span>
       <span class="icon-bar bottom-bar">
       </span>
       <span class="icon-bar extra-bottom-bar">
       </span>
      </button>
     </a>
     <div class="navbar-brand">
      <a href="/">
       <img alt="Web Scraper" src="/img/logo_white.svg"/>
      </a>
     </div>
    </div>
    <div class="side-collapse in">
     <nav class="navbar-collapse collapse" id="navbar" role="navigation">
      <ul class="nav navbar-nav navbar-right">
       <li class="nav-item">
        <a class="nav-link menuitm" href="/">
         <p>
          Web Scraper
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
         <p>
          Cloud Scraper
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
         <p>
          Pricing
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item dropdown">
        <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
         <p>
          Learn
          <i class="ws-icon ws-icon-down">
          </i>
         </p>
         <span class="crta">
         </span>
        </button>
        <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
         <li>
          <a class="dropdown-item" href="/documentation">
           Documentation
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="/tutorials">
           Video Tutorials
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="/test-sites">
           Test Sites
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">
           Forum
          </a>
         </li>
        </ul>
       </li>
       <li class="nav-item">
        <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" target="_blank">
         <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500">
         </i>
         Install
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">
         Cloud Login
        </a>
       </li>
      </ul>
     </nav>
    </div>
   </div>
  </header>
  <div class="wrapper">
   <div class="formenu-here container-fluid">
   </div>
   <div class="container-fluid blog-hero">
    <div class="container">
     <div class="row">
      <div class="col-lg-12">
       <h1>
        Test Sites
       </h1>
      </div>
     </div>
    </div>
   </div>
   <div class="container test-site">
    <div class="row">
     <div class="col-lg-3 sidebar">
      <div class="navbar-light sidebar" role="navigation">
       <div class="sidebar-nav navbar-collapse">
        <ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
         <li class="nav-item">
          <a class="nav-link" href="/test-sites/e-commerce/allinone" itemprop="url">
           <span itemprop="name">
            Home
           </span>
          </a>
         </li>
         <li class="nav-item">
          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/computers" itemprop="url">
           <span itemprop="name">
            Computers
           </span>
           <i aria-hidden="true" class="ws-icon ws-icon-right">
           </i>
          </a>
         </li>
         <li class="nav-item active">
          <a aria-label="Navigation category" class="category-link nav-link active" href="/test-sites/e-commerce/allinone/phones" itemprop="url">
           <span itemprop="name">
            Phones
           </span>
           <i aria-hidden="true" class="ws-icon ws-icon-down">
           </i>
          </a>
          <ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
           <li class="nav-item">
            <a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/allinone/phones/touch" itemprop="url">
             <span itemprop="name">
              Touch
             </span>
            </a>
           </li>
          </ul>
         </li>
        </ul>
       </div>
      </div>
     </div>
     <div class="col-lg-9">
      <h2 class="page-header">
       Phones category
      </h2>
      <h3>
       Top items being scraped right now
      </h3>
      <div class="row">
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $499.99
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/6" itemprop="name" title="Ubuntu Edge">
             Ubuntu Edge
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            Sapphire glass
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             2
            </span>
            reviews
           </p>
           <p data-rating="1">
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $899.99
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/7" itemprop="name" title="Iphone">
             Iphone
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            White
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             10
            </span>
            reviews
           </p>
           <p data-rating="1">
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $899.99
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/9" itemprop="name" title="Iphone">
             Iphone
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            Black
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             1
            </span>
            reviews
           </p>
           <p data-rating="1">
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
      </div>
      <div id="static-pagination">
      </div>
     </div>
    </div>
   </div>
   <div class="clearfix">
   </div>
   <div class="push">
   </div>
  </div>
  <div class="container-fluid footer" id="layout-footer">
   <div class="container">
    <div class="row">
     <div class="col-lg-3">
      <ul>
       <li>
        <p>
         Products
        </p>
       </li>
       <li>
        <a href="/">
         Web Scraper browser extension
        </a>
       </li>
       <li>
        <a href="/cloud-scraper">
         Web Scraper Cloud
        </a>
       </li>
      </ul>
     </div>
     <div class="col-lg-3">
      <ul>
       <li>
        <p>
         Company
        </p>
       </li>
       <li>
        <a href="/about-us">
         About us
        </a>
       </li>
       <li>
        <a href="/contact">
         Contact
        </a>
       </li>
       <li>
        <a href="/privacy-policy">
         Website Privacy Policy
        </a>
       </li>
       <li>
        <a href="/extension-privacy-policy">
         Browser Extension Privacy Policy
        </a>
       </li>
       <li>
        <a href="https://webscraper.io/downloads/Web_Scraper_Media_Kit.zip">
         Media kit
        </a>
       </li>
       <li>
        <a href="/jobs">
         Jobs
        </a>
       </li>
      </ul>
     </div>
     <div class="col-lg-3">
      <ul>
       <li>
        <p>
         Resources
        </p>
       </li>
       <li>
        <a href="/blog">
         Blog
        </a>
       </li>
       <li>
        <a href="/documentation">
         Documentation
        </a>
       </li>
       <li>
        <a href="/tutorials">
         Video Tutorials
        </a>
       </li>
       <li>
        <a href="/screenshots">
         Screenshots
        </a>
       </li>
       <li>
        <a href="/test-sites">
         Test Sites
        </a>
       </li>
       <li>
        <a href="https://forum.webscraper.io/" rel="noopener" target="_blank">
         Forum
        </a>
       </li>
       <li>
        <a href="https://status.webscraper.io/" rel="noopener" target="_blank">
         Status
        </a>
       </li>
      </ul>
     </div>
     <div class="col-lg-3">
      <ul>
       <li>
        <p>
         CONTACT US
        </p>
       </li>
       <li>
        <a href="mailto:info@webscraper.io">
         info@webscraper.io
        </a>
       </li>
       <li>
        Ubelu 5-71,
        <br/>
        Adazi, Latvia, LV-2164
       </li>
      </ul>
      <ul class="smedia">
       <li>
        <a aria-label="Web Scraper on Facebook" href="https://www.facebook.com/webscraperio/" rel="noopener" target="_blank">
         <i class="ws-icon ws-icon-facebook-f">
         </i>
        </a>
       </li>
       <li>
        <a aria-label="Web Scraper on X" href="https://twitter.com/webscraperio" rel="noopener" target="_blank">
         <i class="ws-icon ws-icon-twitter">
         </i>
        </a>
       </li>
       <li>
        <a aria-label="Web Scraper on LinkedIn" href="https://lv.linkedin.com/company/web-scraper" rel="noopener" target="_blank">
         <i class="ws-icon ws-icon-linkedin">
         </i>
        </a>
       </li>
       <li>
        <a aria-label="Web Scraper on Youtube" href="https://youtube.com/@WebScraper/videos" rel="noopener" target="_blank">
         <i class="ws-icon ws-icon-youtube">
         </i>
        </a>
       </li>
       <li>
        <a aria-label="Download the Web Scraper extension" class="install-extension browser-icon-dark" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
         <i class="ws-icon ws-icon-chrome-dark">
         </i>
        </a>
       </li>
      </ul>
     </div>
    </div>
    <div class="row">
     <div class="col-lg-12">
      <p class="copyright">
       Copyright © 2025
       <b>
        Web Scraper
       </b>
       | All rights reserved
      </p>
     </div>
    </div>
   </div>
  </div>
 </body>
</html>

---
---

<span style='color:red'>

## 2. Tags, Variable Strings, & Attributes

In [8]:
from bs4 import BeautifulSoup
import requests

In [9]:
url = 'https://webscraper.io/test-sites/e-commerce/allinone/phones'

page = requests.get(url)

soup = BeautifulSoup(page.text, 'html')
pretty_soup = soup.prettify()

print(pretty_soup)

<!DOCTYPE html>
<html lang="en">
 <head>
  <!-- Google Tag Manager -->
  <script nonce="zghyGUKys2buBC2u1bNxyCQXnXDzEJed">
   (function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');
  </script>
  <!-- End Google Tag Manager -->
  <title>
   Allinone | Web Scraper Test Sites
  </title>
  <meta charset="utf-8"/>
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
  <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
   <meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">
    <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
    <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
    <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
    <link href="/icon.svg" rel="icon" type="image/svg+xml"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <link href="https://fonts.googleapis.com" rel="preconnect"/>
    <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;900&amp;display=swap" rel="stylesheet"/>
    <link href="/css/app.css?id=b504eb6c3f627c4a2887e7f92d2e2723" rel="stylesheet"/>
    <link href="/css/ws-icons.font.css?id=bc6c0d86aeabab8583f9814643f23faa" rel="stylesheet"/>
    <link href="https://webscraper.io/test-sites/e-commerce/allinone/phones" rel="canonical"/>
    <meta content="Allinone | Web Scraper Test Sites" property="og:title"/>
    <meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
    <meta content="website" property="og:type"/>
    <meta content="https://webscraper.io/test-sites/e-commerce/allinone/phones" property="og:url"/>
    <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
    <script defer="" src="/js/app.js?id=d58701ba9d2d08185240f2ddbf489d15">
    </script>
   </meta>
  </meta>
 </head>
 <body>
  <!-- Google Tag Manager (noscript) -->
  <noscript>
   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <!-- End Google Tag Manager (noscript) -->
  <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
   <div class="container">
    <div class="navbar-header">
     <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
       <span class="visually-hidden">
        Toggle navigation
       </span>
       <span class="icon-bar top-bar">
       </span>
       <span class="icon-bar middle-bar">
       </span>
       <span class="icon-bar bottom-bar">
       </span>
       <span class="icon-bar extra-bottom-bar">
       </span>
      </button>
     </a>
     <div class="navbar-brand">
      <a href="/">
       <img alt="Web Scraper" src="/img/logo_white.svg"/>
      </a>
     </div>
    </div>
    <div class="side-collapse in">
     <nav class="navbar-collapse collapse" id="navbar" role="navigation">
      <ul class="nav navbar-nav navbar-right">
       <li class="nav-item">
        <a class="nav-link menuitm" href="/">
         <p>
          Web Scraper
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
         <p>
          Cloud Scraper
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
         <p>
          Pricing
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item dropdown">
        <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
         <p>
          Learn
          <i class="ws-icon ws-icon-down">
          </i>
         </p>
         <span class="crta">
         </span>
        </button>
        <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
         <li>
          <a class="dropdown-item" href="/documentation">
           Documentation
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="/tutorials">
           Video Tutorials
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="/test-sites">
           Test Sites
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">
           Forum
          </a>
         </li>
        </ul>
       </li>
       <li class="nav-item">
        <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" target="_blank">
         <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500">
         </i>
         Install
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">
         Cloud Login
        </a>
       </li>
      </ul>
     </nav>
    </div>
   </div>
  </header>
  <div class="wrapper">
   <div class="formenu-here container-fluid">
   </div>
   <div class="container-fluid blog-hero">
    <div class="container">
     <div class="row">
      <div class="col-lg-12">
       <h1>
        Test Sites
       </h1>
      </div>
     </div>
    </div>
   </div>
   <div class="container test-site">
    <div class="row">
     <div class="col-lg-3 sidebar">
      <div class="navbar-light sidebar" role="navigation">
       <div class="sidebar-nav navbar-collapse">
        <ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
         <li class="nav-item">
          <a class="nav-link" href="/test-sites/e-commerce/allinone" itemprop="url">
           <span itemprop="name">
            Home
           </span>
          </a>
         </li>
         <li class="nav-item">
          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/computers" itemprop="url">
           <span itemprop="name">
            Computers
           </span>
           <i aria-hidden="true" class="ws-icon ws-icon-right">
           </i>
          </a>
         </li>
         <li class="nav-item active">
          <a aria-label="Navigation category" class="category-link nav-link active" href="/test-sites/e-commerce/allinone/phones" itemprop="url">
           <span itemprop="name">
            Phones
           </span>
           <i aria-hidden="true" class="ws-icon ws-icon-down">
           </i>
          </a>
          <ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
           <li class="nav-item">
            <a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/allinone/phones/touch" itemprop="url">
             <span itemprop="name">
              Touch
             </span>
            </a>
           </li>
          </ul>
         </li>
        </ul>
       </div>
      </div>
     </div>
     <div class="col-lg-9">
      <h2 class="page-header">
       Phones category
      </h2>
      <h3>
       Top items being scraped right now
      </h3>
      <div class="row">
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $499.99
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/6" itemprop="name" title="Ubuntu Edge">
             Ubuntu Edge
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            Sapphire glass
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             2
            </span>
            reviews
           </p>
           <p data-rating="1">
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $899.99
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/7" itemprop="name" title="Iphone">
             Iphone
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            White
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             10
            </span>
            reviews
           </p>
           <p data-rating="1">
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $899.99
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/9" itemprop="name" title="Iphone">
             Iphone
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            Black
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             1
            </span>
            reviews
           </p>
           <p data-rating="1">
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
      </div>
      <div id="static-pagination">
      </div>
     </div>
    </div>
   </div>
   <div class="clearfix">
   </div>
   <div class="push">
   </div>
  </div>
  <div class="container-fluid footer" id="layout-footer">
   <div class="container">
    <div class="row">
     <div class="col-lg-3">
      <ul>
       <li>
        <p>
         Products
        </p>
       </li>
       <li>
        <a href="/">
         Web Scraper browser extension
        </a>
       </li>
       <li>
        <a href="/cloud-scraper">
         Web Scraper Cloud
        </a>
       </li>
      </ul>
     </div>
     <div class="col-lg-3">
      <ul>
       <li>
        <p>
         Company
        </p>
       </li>
       <li>
        <a href="/about-us">
         About us
        </a>
       </li>
       <li>
        <a href="/contact">
         Contact
        </a>
       </li>
       <li>
        <a href="/privacy-policy">
         Website Privacy Policy
        </a>
       </li>
       <li>
        <a href="/extension-privacy-policy">
         Browser Extension Privacy Policy
        </a>
       </li>
       <li>
        <a href="https://webscraper.io/downloads/Web_Scraper_Media_Kit.zip">
         Media kit
        </a>
       </li>
       <li>
        <a href="/jobs">
         Jobs
        </a>
       </li>
      </ul>
     </div>
     <div class="col-lg-3">
      <ul>
       <li>
        <p>
         Resources
        </p>
       </li>
       <li>
        <a href="/blog">
         Blog
        </a>
       </li>
       <li>
        <a href="/documentation">
         Documentation
        </a>
       </li>
       <li>
        <a href="/tutorials">
         Video Tutorials
        </a>
       </li>
       <li>
        <a href="/screenshots">
         Screenshots
        </a>
       </li>
       <li>
        <a href="/test-sites">
         Test Sites
        </a>
       </li>
       <li>
        <a href="https://forum.webscraper.io/" rel="noopener" target="_blank">
         Forum
        </a>
       </li>
       <li>
        <a href="https://status.webscraper.io/" rel="noopener" target="_blank">
         Status
        </a>
       </li>
      </ul>
     </div>
     <div class="col-lg-3">
      <ul>
       <li>
        <p>
         CONTACT US
        </p>
       </li>
       <li>
        <a href="mailto:info@webscraper.io">
         info@webscraper.io
        </a>
       </li>
       <li>
        Ubelu 5-71,
        <br/>
        Adazi, Latvia, LV-2164
       </li>
      </ul>
      <ul class="smedia">
       <li>
        <a aria-label="Web Scraper on Facebook" href="https://www.facebook.com/webscraperio/" rel="noopener" target="_blank">
         <i class="ws-icon ws-icon-facebook-f">
         </i>
        </a>
       </li>
       <li>
        <a aria-label="Web Scraper on X" href="https://twitter.com/webscraperio" rel="noopener" target="_blank">
         <i class="ws-icon ws-icon-twitter">
         </i>
        </a>
       </li>
       <li>
        <a aria-label="Web Scraper on LinkedIn" href="https://lv.linkedin.com/company/web-scraper" rel="noopener" target="_blank">
         <i class="ws-icon ws-icon-linkedin">
         </i>
        </a>
       </li>
       <li>
        <a aria-label="Web Scraper on Youtube" href="https://youtube.com/@WebScraper/videos" rel="noopener" target="_blank">
         <i class="ws-icon ws-icon-youtube">
         </i>
        </a>
       </li>
       <li>
        <a aria-label="Download the Web Scraper extension" class="install-extension browser-icon-dark" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
         <i class="ws-icon ws-icon-chrome-dark">
         </i>
        </a>
       </li>
      </ul>
     </div>
    </div>
    <div class="row">
     <div class="col-lg-12">
      <p class="copyright">
       Copyright © 2025
       <b>
        Web Scraper
       </b>
       | All rights reserved
      </p>
     </div>
    </div>
   </div>
  </div>
 </body>
</html>

In [10]:
soup.head

<head>
<!-- Google Tag Manager -->
<script nonce="zghyGUKys2buBC2u1bNxyCQXnXDzEJed">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>Allinone | Web Scraper Test Sites</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=b504eb6c3f627c4a2887e7f92d2e2723" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=bc6c0d86aeabab8583f9814643f23faa" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/e-commerce/allinone/phones" rel="canonical"/>
<meta content="Allinone | Web Scraper Test Sites" property="og:title"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/e-commerce/allinone/phones" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script defer="" src="/js/app.js?id=d58701ba9d2d08185240f2ddbf489d15"></script>
</meta></meta></head>

In [11]:
soup.header

<header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" src="/img/logo_white.svg"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500"></i>
							Install
						</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>
</header>

In [12]:
soup.h1

In [13]:
soup.h1.string

'Test Sites'

In [14]:
soup.title

In [15]:
soup.title.string

'Allinone | Web Scraper Test Sites'

In [16]:
soup.title.name

'title'

In [17]:
soup.header.attrs

{'role': 'banner',
 'class': ['navbar',
  'fixed-top',
  'navbar-expand-lg',
  'navbar-dark',
  'navbar-static',
  'svg-background'],
 'id': 'navbar-top'}

In [18]:
soup.h4.attrs

{'class': ['price', 'float-end', 'card-title', 'pull-right'],
 'itemprop': 'offers',
 'itemscope': '',
 'itemtype': 'https://schema.org/Offer'}

In [19]:
soup.h4.contents

['\n',
 <span itemprop="price">$499.99</span>,
 '\n',
 <meta content="USD" itemprop="priceCurrency"/>,
 '\n']

In [20]:
soup.h4.extend

<bound method PageElement.extend of <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$499.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>>

---
---

<span style='color:red'>

## 3. Find and Find_All

In [ ]:
from bs4 import BeautifulSoup
import requests

In [21]:
url = 'https://webscraper.io/test-sites/e-commerce/allinone/phones'

page = requests.get(url)
soup = BeautifulSoup(page.text, 'html.parser')

print(soup)

<!DOCTYPE html>

<html lang="en">
<head>
<!-- Google Tag Manager -->
<script nonce="zghyGUKys2buBC2u1bNxyCQXnXDzEJed">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>Allinone | Web Scraper Test Sites</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=b504eb6c3f627c4a2887e7f92d2e2723" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=bc6c0d86aeabab8583f9814643f23faa" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/e-commerce/allinone/phones" rel="canonical"/>
<meta content="Allinone | Web Scraper Test Sites" property="og:title"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/e-commerce/allinone/phones" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script defer="" src="/js/app.js?id=d58701ba9d2d08185240f2ddbf489d15"></script>
</meta></meta></head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" src="/img/logo_white.svg"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500"></i>
							Install
						</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>
</header>
<div class="wrapper">
<div class="formenu-here container-fluid">
</div>
<div class="container-fluid blog-hero">
<div class="container">
<div class="row">
<div class="col-lg-12">
<h1>Test Sites</h1>
</div>
</div>
</div>
</div>
<div class="container test-site">
<div class="row">
<div class="col-lg-3 sidebar">
<div class="navbar-light sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
<ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a class="nav-link" href="/test-sites/e-commerce/allinone" itemprop="url"><span itemprop="name">Home</span></a>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/computers" itemprop="url">
<span itemprop="name">Computers</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
<li class="nav-item active">
<a aria-label="Navigation category" class="category-link nav-link active" href="/test-sites/e-commerce/allinone/phones" itemprop="url">
<span itemprop="name">Phones</span>
<i aria-hidden="true" class="ws-icon ws-icon-down"></i>
</a>
<ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/allinone/phones/touch" itemprop="url">
<span itemprop="name">Touch</span>
</a>
</li>
</ul>
</li>
</ul>
</div>
</div>
</div>
<div class="col-lg-9">
<h2 class="page-header">Phones category</h2>
<h3>Top items being scraped right now</h3>
<div class="row">
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$499.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/6" itemprop="name" title="Ubuntu Edge">
						Ubuntu Edge
					</a>
</h4>
<p class="description card-text" itemprop="description">Sapphire glass</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="1">
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$899.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/7" itemprop="name" title="Iphone">
						Iphone
					</a>
</h4>
<p class="description card-text" itemprop="description">White</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">10</span> reviews
				</p>
<p data-rating="1">
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$899.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/9" itemprop="name" title="Iphone">
						Iphone
					</a>
</h4>
<p class="description card-text" itemprop="description">Black</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">1</span> reviews
				</p>
<p data-rating="1">
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
</div>
<div id="static-pagination">
</div>
</div>
</div>
</div>
<div class="clearfix"></div>
<div class="push"></div>
</div>
<div class="container-fluid footer" id="layout-footer">
<div class="container">
<div class="row">
<div class="col-lg-3">
<ul>
<li><p>Products</p></li>
<li>
<a href="/">Web Scraper browser extension</a>
</li>
<li>
<a href="/cloud-scraper">Web Scraper Cloud</a>
</li>
</ul>
</div>
<div class="col-lg-3">
<ul>
<li><p>Company</p></li>
<li>
<a href="/about-us">About us</a>
</li>
<li>
<a href="/contact">Contact</a>
</li>
<li>
<a href="/privacy-policy">Website Privacy Policy</a>
</li>
<li>
<a href="/extension-privacy-policy">Browser Extension Privacy Policy</a>
</li>
<li>
<a href="https://webscraper.io/downloads/Web_Scraper_Media_Kit.zip">Media kit</a>
</li>
<li><a href="/jobs">Jobs</a></li>
</ul>
</div>
<div class="col-lg-3">
<ul>
<li><p>Resources</p></li>
<li><a href="/blog">Blog</a></li>
<li>
<a href="/documentation">Documentation</a>
</li>
<li>
<a href="/tutorials">Video Tutorials</a>
</li>
<li>
<a href="/screenshots">Screenshots</a>
</li>
<li>
<a href="/test-sites">Test Sites</a>
</li>
<li>
<a href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
<li>
<a href="https://status.webscraper.io/" rel="noopener" target="_blank">Status</a>
</li>
</ul>
</div>
<div class="col-lg-3">
<ul>
<li><p>CONTACT US</p></li>
<li>
<a href="mailto:info@webscraper.io">info@webscraper.io</a>
</li>
<li>Ubelu 5-71,<br/> Adazi, Latvia, LV-2164</li>
</ul>
<ul class="smedia">
<li>
<a aria-label="Web Scraper on Facebook" href="https://www.facebook.com/webscraperio/" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-facebook-f"></i>
</a>
</li>
<li>
<a aria-label="Web Scraper on X" href="https://twitter.com/webscraperio" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-twitter"></i>
</a>
</li>
<li>
<a aria-label="Web Scraper on LinkedIn" href="https://lv.linkedin.com/company/web-scraper" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-linkedin"></i>
</a>
</li>
<li>
<a aria-label="Web Scraper on Youtube" href="https://youtube.com/@WebScraper/videos" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-youtube"></i>
</a>
</li>
<li>
<a aria-label="Download the Web Scraper extension" class="install-extension browser-icon-dark" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-chrome-dark"></i>
</a>
</li>
</ul>
</div>
</div>
<div class="row">
<div class="col-lg-12">
<p class="copyright">Copyright © 2025
					<b>Web Scraper</b> | All rights reserved</p>
</div>
</div>
</div>
</div>
</body>
</html>

In [22]:
soup.find('h1')

In [23]:
soup.find('h4')

<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$499.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>

In [24]:
soup.find('h4', 'span')

In [25]:
soup.find('h4', {'class':'price float-end card-title pull-right'})

<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$499.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>

In [26]:
soup.find('h4', 'price float-end card-title pull-right')

<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$499.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>

In [28]:
soup.find('a', class_='title')

<a class="title" href="/test-sites/e-commerce/allinone/product/6" itemprop="name" title="Ubuntu Edge">
						Ubuntu Edge
					</a>

In [29]:
soup.find_all('h4')

[<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$499.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>,
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/6" itemprop="name" title="Ubuntu Edge">
 						Ubuntu Edge
 					</a>
 </h4>,
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$899.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>,
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/7" itemprop="name" title="Iphone">
 						Iphone
 					</a>
 </h4>,
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$899.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>,
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/9" itemprop="name" title="Iphone">
 						Iphone
 					</a>
 </h4>]

In [30]:
soup.find_all('h4', 'price float-end card-title pull-right')

[<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$499.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>,
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$899.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>,
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$899.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>]

In [31]:
soup.find_all('a', 'title')

[<a class="title" href="/test-sites/e-commerce/allinone/product/6" itemprop="name" title="Ubuntu Edge">
 						Ubuntu Edge
 					</a>,
 <a class="title" href="/test-sites/e-commerce/allinone/product/7" itemprop="name" title="Iphone">
 						Iphone
 					</a>,
 <a class="title" href="/test-sites/e-commerce/allinone/product/9" itemprop="name" title="Iphone">
 						Iphone
 					</a>]

In [32]:
soup.find_all('a', 'title')[:2]

[<a class="title" href="/test-sites/e-commerce/allinone/product/6" itemprop="name" title="Ubuntu Edge">
 						Ubuntu Edge
 					</a>,
 <a class="title" href="/test-sites/e-commerce/allinone/product/7" itemprop="name" title="Iphone">
 						Iphone
 					</a>]

In [33]:
soup.find_all(title = True)

[<a class="title" href="/test-sites/e-commerce/allinone/product/6" itemprop="name" title="Ubuntu Edge">
 						Ubuntu Edge
 					</a>,
 <a class="title" href="/test-sites/e-commerce/allinone/product/7" itemprop="name" title="Iphone">
 						Iphone
 					</a>,
 <a class="title" href="/test-sites/e-commerce/allinone/product/9" itemprop="name" title="Iphone">
 						Iphone
 					</a>]

In [34]:
soup.find_all(title = False)

[<html lang="en">
 <head>
 <!-- Google Tag Manager -->
 <script nonce="zghyGUKys2buBC2u1bNxyCQXnXDzEJed">(function (w, d, s, l, i) {
 		w[l] = w[l] || [];
 		w[l].push({
 			'gtm.start':
 				new Date().getTime(), event: 'gtm.js'
 		});
 		var f = d.getElementsByTagName(s)[0],
 			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
 		j.async = true;
 		j.src =
 			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
 		f.parentNode.insertBefore(j, f);
 	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
 <!-- End Google Tag Manager -->
 <title>Allinone | Web Scraper Test Sites</title>
 <meta charset="utf-8"/>
 <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
 <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
 <meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">
 <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
 <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
 <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
 <link href="/icon.svg" rel="icon" type="image/svg+xml"/>
 <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
 <link href="https://fonts.googleapis.com" rel="preconnect"/>
 <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
 <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
 <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;900&amp;display=swap" rel="stylesheet"/>
 <link href="/css/app.css?id=b504eb6c3f627c4a2887e7f92d2e2723" rel="stylesheet"/>
 <link href="/css/ws-icons.font.css?id=bc6c0d86aeabab8583f9814643f23faa" rel="stylesheet"/>
 <link href="https://webscraper.io/test-sites/e-commerce/allinone/phones" rel="canonical"/>
 <meta content="Allinone | Web Scraper Test Sites" property="og:title"/>
 <meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
 <meta content="website" property="og:type"/>
 <meta content="https://webscraper.io/test-sites/e-commerce/allinone/phones" property="og:url"/>
 <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
 <script defer="" src="/js/app.js?id=d58701ba9d2d08185240f2ddbf489d15"></script>
 </meta></meta></head>
 <body>
 <!-- Google Tag Manager (noscript) -->
 <noscript>
 <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
 </noscript>
 <!-- End Google Tag Manager (noscript) -->
 <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
 <div class="container">
 <div class="navbar-header">
 <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
 <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
 <span class="visually-hidden">Toggle navigation</span>
 <span class="icon-bar top-bar"></span>
 <span class="icon-bar middle-bar"></span>
 <span class="icon-bar bottom-bar"></span>
 <span class="icon-bar extra-bottom-bar"></span>
 </button>
 </a>
 <div class="navbar-brand">
 <a href="/"><img alt="Web Scraper" src="/img/logo_white.svg"/></a>
 </div>
 </div>
 <div class="side-collapse in">
 <nav class="navbar-collapse collapse" id="navbar" role="navigation">
 <ul class="nav navbar-nav navbar-right">
 <li class="nav-item">
 <a class="nav-link menuitm" href="/">
 <p>Web Scraper</p>
 <div class="crta"></div>
 </a>
 </li>
 <li class="nav-item">
 <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
 <p>Cloud Scraper</p>
 <div class="crta"></div>
 </a>
 </li>
 <li class="nav-item">
 <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
 <p>Pricing</p>
 <div class="crta"></div>
 </a>
 </li>
 <li class="nav-item dropdown">
 <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
 <p>
 								Learn
 								<i class="ws-icon ws-icon-down"></i>
 </p>
 <span class="crta"></span>
 </button>
 <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
 <li>
 <a class="dropdown-item" href="/documentation">Documentation</a>
 </li>
 <li>
 <a class="dropdown-item" href="/tutorials">Video Tutorials</a>
 </li>
 <li>
 <a class="dropdown-item" href="/test-sites">Test Sites</a>
 </li>
 <li>
 <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
 </li>
 </ul>
 </li>
 <li class="nav-item">
 <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" target="_blank">
 <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500"></i>
 							Install
 						</a>
 </li>
 <li class="nav-item">
 <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
 </li>
 </ul>
 </nav>
 </div>
 </div>
 </header>
 <div class="wrapper">
 <div class="formenu-here container-fluid">
 </div>
 <div class="container-fluid blog-hero">
 <div class="container">
 <div class="row">
 <div class="col-lg-12">
 <h1>Test Sites</h1>
 </div>
 </div>
 </div>
 </div>
 <div class="container test-site">
 <div class="row">
 <div class="col-lg-3 sidebar">
 <div class="navbar-light sidebar" role="navigation">
 <div class="sidebar-nav navbar-collapse">
 <ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
 <li class="nav-item">
 <a class="nav-link" href="/test-sites/e-commerce/allinone" itemprop="url"><span itemprop="name">Home</span></a>
 </li>
 <li class="nav-item">
 <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/computers" itemprop="url">
 <span itemprop="name">Computers</span>
 <i aria-hidden="true" class="ws-icon ws-icon-right"></i>
 </a>
 </li>
 <li class="nav-item active">
 <a aria-label="Navigation category" class="category-link nav-link active" href="/test-sites/e-commerce/allinone/phones" itemprop="url">
 <span itemprop="name">Phones</span>
 <i aria-hidden="true" class="ws-icon ws-icon-down"></i>
 </a>
 <ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
 <li class="nav-item">
 <a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/allinone/phones/touch" itemprop="url">
 <span itemprop="name">Touch</span>
 </a>
 </li>
 </ul>
 </li>
 </ul>
 </div>
 </div>
 </div>
 <div class="col-lg-9">
 <h2 class="page-header">Phones category</h2>
 <h3>Top items being scraped right now</h3>
 <div class="row">
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$499.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/6" itemprop="name" title="Ubuntu Edge">
 						Ubuntu Edge
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Sapphire glass</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$899.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/7" itemprop="name" title="Iphone">
 						Iphone
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">White</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">10</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$899.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/9" itemprop="name" title="Iphone">
 						Iphone
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Black</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">1</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>
 </div>
 <div id="static-pagination">
 </div>
 </div>
 </div>
 </div>
 <div class="clearfix"></div>
 <div class="push"></div>
 </div>
 <div class="container-fluid footer" id="layout-footer">
 <div class="container">
 <div class="row">
 <div class="col-lg-3">
 <ul>
 <li><p>Products</p></li>
 <li>
 <a href="/">Web Scraper browser extension</a>
 </li>
 <li>
 <a href="/cloud-scraper">Web Scraper Cloud</a>
 </li>
 </ul>
 </div>
 <div class="col-lg-3">
 <ul>
 <li><p>Company</p></li>
 <li>
 <a href="/about-us">About us</a>
 </li>
 <li>
 <a href="/contact">Contact</a>
 </li>
 <li>
 <a href="/privacy-policy">Website Privacy Policy</a>
 </li>
 <li>
 <a href="/extension-privacy-policy">Browser Extension Privacy Policy</a>
 </li>
 <li>
 <a href="https://webscraper.io/downloads/Web_Scraper_Media_Kit.zip">Media kit</a>
 </li>
 <li><a href="/jobs">Jobs</a></li>
 </ul>
 </div>
 <div class="col-lg-3">
 <ul>
 <li><p>Resources</p></li>
 <li><a href="/blog">Blog</a></li>
 <li>
 <a href="/documentation">Documentation</a>
 </li>
 <li>
 <a href="/tutorials">Video Tutorials</a>
 </li>
 <li>
 <a href="/screenshots">Screenshots</a>
 </li>
 <li>
 <a href="/test-sites">Test Sites</a>
 </li>
 <li>
 <a href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
 </li>
 <li>
 <a href="https://status.webscraper.io/" rel="noopener" target="_blank">Status</a>
 </li>
 </ul>
 </div>
 <div class="col-lg-3">
 <ul>
 <li><p>CONTACT US</p></li>
 <li>
 <a href="mailto:info@webscraper.io">info@webscraper.io</a>
 </li>
 <li>Ubelu 5-71,<br/> Adazi, Latvia, LV-2164</li>
 </ul>
 <ul class="smedia">
 <li>
 <a aria-label="Web Scraper on Facebook" href="https://www.facebook.com/webscraperio/" rel="noopener" target="_blank">
 <i class="ws-icon ws-icon-facebook-f"></i>
 </a>
 </li>
 <li>
 <a aria-label="Web Scraper on X" href="https://twitter.com/webscraperio" rel="noopener" target="_blank">
 <i class="ws-icon ws-icon-twitter"></i>
 </a>
 </li>
 <li>
 <a aria-label="Web Scraper on LinkedIn" href="https://lv.linkedin.com/company/web-scraper" rel="noopener" target="_blank">
 <i class="ws-icon ws-icon-linkedin"></i>
 </a>
 </li>
 <li>
 <a aria-label="Web Scraper on Youtube" href="https://youtube.com/@WebScraper/videos" rel="noopener" target="_blank">
 <i class="ws-icon ws-icon-youtube"></i>
 </a>
 </li>
 <li>
 <a aria-label="Download the Web Scraper extension" class="install-extension browser-icon-dark" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
 <i class="ws-icon ws-icon-chrome-dark"></i>
 </a>
 </li>
 </ul>
 </div>
 </div>
 <div class="row">
 <div class="col-lg-12">
 <p class="copyright">Copyright © 2025
 					<b>Web Scraper</b> | All rights reserved</p>
 </div>
 </div>
 </div>
 </div>
 </body>
 </html>,
 <head>
 <!-- Google Tag Manager -->
 <script nonce="zghyGUKys2buBC2u1bNxyCQXnXDzEJed">(function (w, d, s, l, i) {
 		w[l] = w[l] || [];
 		w[l].push({
 			'gtm.start':
 				new Date().getTime(), event: 'gtm.js'
 		});
 		var f = d.getElementsByTagName(s)[0],
 			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
 		j.async = true;
 		j.src =
 			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
 		f.parentNode.insertBefore(j, f);
 	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
 <!-- End Google Tag Manager -->
 <title>Allinone | Web Scraper Test Sites</title>
 <meta charset="utf-8"/>
 <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
 <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
 <meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">
 <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
 <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
 <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
 <link href="/icon.svg" rel="icon" type="image/svg+xml"/>
 <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
 <link href="https://fonts.googleapis.com" rel="preconnect"/>
 <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
 <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
 <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;900&amp;display=swap" rel="stylesheet"/>
 <link href="/css/app.css?id=b504eb6c3f627c4a2887e7f92d2e2723" rel="stylesheet"/>
 <link href="/css/ws-icons.font.css?id=bc6c0d86aeabab8583f9814643f23faa" rel="stylesheet"/>
 <link href="https://webscraper.io/test-sites/e-commerce/allinone/phones" rel="canonical"/>
 <meta content="Allinone | Web Scraper Test Sites" property="og:title"/>
 <meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
 <meta content="website" property="og:type"/>
 <meta content="https://webscraper.io/test-sites/e-commerce/allinone/phones" property="og:url"/>
 <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
 <script defer="" src="/js/app.js?id=d58701ba9d2d08185240f2ddbf489d15"></script>
 </meta></meta></head>,
 <script nonce="zghyGUKys2buBC2u1bNxyCQXnXDzEJed">(function (w, d, s, l, i) {
 		w[l] = w[l] || [];
 		w[l].push({
 			'gtm.start':
 				new Date().getTime(), event: 'gtm.js'
 		});
 		var f = d.getElementsByTagName(s)[0],
 			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
 		j.async = true;
 		j.src =
 			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
 		f.parentNode.insertBefore(j, f);
 	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>,
 <title>Allinone | Web Scraper Test Sites</title>,
 <meta charset="utf-8"/>,
 <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>,
 <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
 <meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">
 <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
 <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
 <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
 <link href="/icon.svg" rel="icon" type="image/svg+xml"/>
 <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
 <link href="https://fonts.googleapis.com" rel="preconnect"/>
 <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
 <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
 <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;900&amp;display=swap" rel="stylesheet"/>
 <link href="/css/app.css?id=b504eb6c3f627c4a2887e7f92d2e2723" rel="stylesheet"/>
 <link href="/css/ws-icons.font.css?id=bc6c0d86aeabab8583f9814643f23faa" rel="stylesheet"/>
 <link href="https://webscraper.io/test-sites/e-commerce/allinone/phones" rel="canonical"/>
 <meta content="Allinone | Web Scraper Test Sites" property="og:title"/>
 <meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
 <meta content="website" property="og:type"/>
 <meta content="https://webscraper.io/test-sites/e-commerce/allinone/phones" property="og:url"/>
 <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
 <script defer="" src="/js/app.js?id=d58701ba9d2d08185240f2ddbf489d15"></script>
 </meta></meta>,
 <meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">
 <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
 <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
 <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
 <link href="/icon.svg" rel="icon" type="image/svg+xml"/>
 <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
 <link href="https://fonts.googleapis.com" rel="preconnect"/>
 <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
 <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
 <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;900&amp;display=swap" rel="stylesheet"/>
 <link href="/css/app.css?id=b504eb6c3f627c4a2887e7f92d2e2723" rel="stylesheet"/>
 <link href="/css/ws-icons.font.css?id=bc6c0d86aeabab8583f9814643f23faa" rel="stylesheet"/>
 <link href="https://webscraper.io/test-sites/e-commerce/allinone/phones" rel="canonical"/>
 <meta content="Allinone | Web Scraper Test Sites" property="og:title"/>
 <meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
 <meta content="website" property="og:type"/>
 <meta content="https://webscraper.io/test-sites/e-commerce/allinone/phones" property="og:url"/>
 <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>

In [35]:
soup.find_all('a', attrs={'title':'Iphone'})

[<a class="title" href="/test-sites/e-commerce/allinone/product/7" itemprop="name" title="Iphone">
 						Iphone
 					</a>,
 <a class="title" href="/test-sites/e-commerce/allinone/product/9" itemprop="name" title="Iphone">
 						Iphone
 					</a>]

In [36]:
soup.find('a', class_='title')

<a class="title" href="/test-sites/e-commerce/allinone/product/6" itemprop="name" title="Ubuntu Edge">
						Ubuntu Edge
					</a>

In [37]:
soup.find('span', class_='price')

---
---

<span style='color:red'>

## 4. Getting Text from a Website

In [38]:
from bs4 import BeautifulSoup
import requests

In [39]:
url = 'https://webscraper.io/test-sites/e-commerce/allinone/phones'

page = requests.get(url)
soup = BeautifulSoup(page.text, 'html')

In [40]:
phone_prices = soup.find_all('h4', 'pull-right')
phone_prices

[<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$899.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>,
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$899.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>,
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$899.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>]

In [47]:
phone_prices2 = soup.find_all('span', itemprop='price')
phone_prices2

[<span itemprop="price">$899.99</span>,
 <span itemprop="price">$899.99</span>,
 <span itemprop="price">$899.99</span>]

---
---

In [60]:
phone_names = soup.find_all('a', 'title')
phone_names

[<a class="title" href="/test-sites/e-commerce/allinone/product/7" itemprop="name" title="Iphone">
 						Iphone
 					</a>,
 <a class="title" href="/test-sites/e-commerce/allinone/product/9" itemprop="name" title="Iphone">
 						Iphone
 					</a>,
 <a class="title" href="/test-sites/e-commerce/allinone/product/8" itemprop="name" title="Iphone">
 						Iphone
 					</a>]

In [65]:
all_prices = [prices.text.strip() for prices in phone_prices]
all_prices

['$899.99', '$899.99', '$899.99']

In [67]:
all_names = [name.text.strip() for name in phone_names]
all_names

['Iphone', 'Iphone', 'Iphone']

In [68]:
import pandas as pd

In [69]:
pd.DataFrame(data=all_prices, index=all_names, columns=['Price'])

          Price
Iphone  $899.99
Iphone  $899.99
Iphone  $899.99

---
---

<span style='color:red'>

## 5. Scraping Data From a Real Website

In [70]:
from bs4 import BeautifulSoup
import requests

In [71]:
url = 'https://www.worldometers.info/world-population/population-by-country/'
page = requests.get(url)
soup = BeautifulSoup(page.text, 'html')
print(soup)

<!DOCTYPE html>
<html lang="en"> <head><meta charset="utf-8"/><meta content="IE=edge" http-equiv="X-UA-Compatible"/><meta content="width=device-width, initial-scale=1" name="viewport"/><title>Population by Country (2025) - Worldometer</title><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-ZDP3BFSX60"></script> <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() {
        dataLayer.push(arguments);
    }
    gtag("js", new Date());
    gtag("config", "G-ZDP3BFSX60");
</script><script crossorigin="anonymous" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3701697624350410"></script> <script async="" src="https://securepubads.g.doubleclick.net/tag/js/gpt.js"></script> <link crossorigin="" href="https://a.pub.network/" rel="preconnect"/><link crossorigin="" href="https://b.pub.network/" rel="preconnect"/><link crossorigin="" href="https://c.pub.network/" rel="preconnect"/><link crossorigin="" href="https://d.pub.network/" rel="preconnect"/><link crossorigin="" href="https://c.amazon-adsystem.com" rel="preconnect"/><link crossorigin="" href="https://s.amazon-adsystem.com" rel="preconnect"/><link crossorigin="" href="https://btloader.com/" rel="preconnect"/><link crossorigin="" href="https://api.btloader.com/" rel="preconnect"/><link crossorigin="" href="https://cdn.confiant-integrations.net" rel="preconnect"/><!-- Below is a link to a CSS file that accounts for Cumulative Layout Shift --><!-- The file is intended to eliminate the layout shifts that are seen when ads load into the page. If you don't want to use this, simply remove this file --><!-- To find out more about CLS, visit https://web.dev/vitals/ --><link href="https://a.pub.network/worldometers-info/cls.css" rel="stylesheet"/><script data-cfasync="false" type="text/javascript">
    var freestar = freestar || {};

    freestar.queue = freestar.queue || [];

    freestar.config = freestar.config || {};
    freestar.config.enabled_slots = [];

    freestar.initCallback = function () {
        freestar.config.enabled_slots.length === 0
            ? (freestar.initCallbackCalled = false)
            : freestar.newAdSlots(freestar.config.enabled_slots);
    };
</script><script async="" data-cfasync="false" src="https://a.pub.network/worldometers-info/pubfig.min.js"></script><meta content="en" property="og:locale"/><meta content="website" property="og:type"/><meta content="http://www.worldometers.info/world-population/population-by-country/" property="og:url"/><meta content="Worldometer" property="og:site_name"/><meta content="Population by Country (2025) - Worldometer" property="og:title"/><meta content="List of countries and dependencies in the world ranked by population, from the most populated. Growth rate, median age, fertility rate, area, density, population density, urbanization, urban population, share of world population." property="og:description"/><meta content="https://www.worldometers.info/img/worldometers-fb.jpg" property="og:image"/><link href="/favicon/favicon.ico" rel="shortcut icon" type="image/x-icon"/><link href="/favicon/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/><link href="/favicon/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/><link href="/favicon/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/><link href="/favicon/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/><link href="/favicon/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/><link href="/favicon/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/><link href="/favicon/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/><link href="/favicon/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/><link href="/favicon/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/><link href="/favicon/android-icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/><link href="/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/><link href="/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/><link href="/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/><link href="/favicon/manifest.json" rel="manifest"/><meta content="#ffffff" name="msapplication-TileColor"/><meta content="/favicon/ms-icon-144x144.png" name="msapplication-TileImage"/><meta content="#ffffff" name="theme-color"/><link href="https://fonts.googleapis.com" rel="preconnect"/><link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/><link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&amp;family=Open+Sans:ital,wght@0,300..800;1,300..800&amp;family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&amp;display=swap" rel="stylesheet"/><meta content="List of countries and dependencies in the world ranked by population, from the most populated. Growth rate, median age, fertility rate, area, density, population density, urbanization, urban population, share of world population." name="description"/><script src="/_astro/base-layout.astro_astro_type_script_index_0_lang.Dx6cZNtg.js" type="module"></script><!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries --><!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]--><link href="/_astro/_about_.CoKkjGQQ.css" rel="stylesheet"/><script src="/_astro/page.DpYsPiLh.js" type="module"></script><style>/*! tailwindcss v4.0.7 | MIT License | https://tailwindcss.com */table.datatable tbody tr:nth-child(odd){background-color:var(--color-zinc-100)}table.datatable:not(.datatable-table) thead th [data-sorting-icon]{display:none}table.datatable thead .datatable-sorter{cursor:pointer;justify-content:space-between;align-items:center;gap:calc(var(--spacing)*1);width:100%;display:flex}table.datatable thead .datatable-sorter span{text-align:start}table.datatable :target td{background-color:var(--color-yellow-100)}.datatable-wrapper .datatable-top{margin-bottom:calc(var(--spacing)*3);align-items:flex-start;gap:calc(var(--spacing)*1);flex-direction:column;display:flex}.datatable-wrapper .datatable-top .datatable-search{margin-inline-start:auto}.datatable-wrapper .datatable-input,.datatable-wrapper .datatable-selector{border-radius:var(--radius-sm);border-style:var(--tw-border-style);border-width:1px;border-color:var(--color-zinc-200);padding-inline:calc(var(--spacing)*2);padding-block:calc(var(--spacing)*1.5);outline-color:var(--color-lime-500)}.datatable-wrapper .datatable-input{justify-content:flex-end;min-width:16rem}@media (width>=640px){.datatable-wrapper .datatable-top{flex-direction:row;align-items:center}}.datatable-wrapper .datatable-bottom{margin-top:calc(var(--spacing)*3);justify-content:space-between;align-items:flex-start;gap:calc(var(--spacing)*1);flex-direction:column;display:flex}@media (width>=640px){.datatable-wrapper .datatable-bottom{flex-direction:row;align-items:center}}.datatable-wrapper .datatable-bottom .datatable-pagination-list{color:var(--color-zinc-500);align-items:center;display:flex}.datatable-wrapper .datatable-bottom .datatable-pagination-list-item-link{border-block-style:var(--tw-border-style);border-block-width:1px;border-inline-end-style:var(--tw-border-style);border-inline-end-width:1px;border-color:var(--color-zinc-200);padding-inline:calc(var(--spacing)*3);padding-block:calc(var(--spacing)*.5);align-items:center;display:flex}.datatable-wrapper .datatable-bottom .datatable-active{background-color:var(--color-zinc-100)}.datatable-wrapper .datatable-bottom .datatable-hidden{cursor:not-allowed;opacity:.5}.datatable-wrapper .datatable-bottom .datatable-pagination-list-item:not(.datatable-active):not(.datatable-disabled):hover{cursor:pointer;background-color:var(--color-zinc-100);text-decoration-line:underline}.datatable-wrapper .datatable-bottom .datatable-pagination-list-item:first-of-type .datatable-pagination-list-item-link{border-left-style:var(--tw-border-style);border-left-width:1px;border-start-start-radius:.25rem;border-end-start-radius:.25rem}.datatable-wrapper .datatable-bottom .datatable-pagination-list-item:last-of-type .datatable-pagination-list-item-link{border-start-end-radius:.25rem;border-end-end-radius:.25rem}.datatable-container{overflow-x:auto}@property --tw-border-style{syntax:"*";inherits:false;initial-value:solid}
</style></head> <body class="font-body text-base"> <div class="flex flex-col"> <div class="shrink-0" data-astro-transition-persist="astro-yfdmylyz-1"> <header class="border-b"> <nav class="container py-4"> <div class="flex items-center gap-16 justify-between md:justify-start"> <div class="shrink-0"> <a href="/"> <img alt="Worldometer Logo" src="/img/worldometers-logo.gif" title="Worldometer" width="200"/> </a> </div> <div class="items-center gap-4 hidden md:flex"> <a class="transition-all duration-200 text-zinc-400 hover:text-zinc-800" href="/population/"><p>Population</p></a> <button class="inline-flex items-center border focus:outline-none focus:ring-4 rounded-sm cursor-pointer focus:ring-zinc-200 transition-all duration-200 text-zinc-900 bg-white border-zinc-300 hover:bg-zinc-100 px-4 py-1.5 text-sm gap-1" data-dropdown-offset-distance="4" data-dropdown-placement="bottom" data-dropdown-toggle="header-nav-more" id="header-nav-more-trigger" type="button"> <p>More</p> <svg aria-hidden="true" class="size-2 text-zinc-800 mt-0.5" fill="currentColor" viewbox="0 0 16 10" xmlns="http://www.w3.org/2000/svg"> <path d="M15.434 1.235A2 2 0 0 0 13.586 0H2.414A2 2 0 0 0 1 3.414L6.586 9a2 2 0 0 0 2.828 0L15 3.414a2 2 0 0 0 .434-2.179Z"></path> </svg> </button> <div class="z-10 hidden border bg-white divide-y divide-zinc-100 rounded-sm shadow-lg w-44" id="header-nav-more"> <ul aria-labelledby="header-nav-more-trigger" class="text-sm"> <p><li class="*:block *:px-4 *:py-1 *:hover:bg-zinc-100"> <a class="transition-all duration-200" href="/co2-emissions/">CO2 emissions</a> </li>
<li class="*:block *:px-4 *:py-1 *:hover:bg-zinc-100"> <a class="transition-all duration-200" href="/coronavirus">Coronavirus</a> </li>
<li class="*:block *:px-4 *:py-1 *:hover:bg-zinc-100"> <a class="transition-all duration-200" href="/geography/countries-of-the-world/">Countries</a> </li>
<li class="*:block *:px-4 *:py-1 *:hover:bg-zinc-100"> <a class="transition-all duration-200" href="/energy/">Energy</a> </li>
<li class="*:block *:px-4 *:py-1 *:hover:bg-zinc-100"> <a class="transition-all duration-200" href="/geography/flags-of-the-world/">Flags</a> </li>
<li class="*:block *:px-4 *:py-1 *:hover:bg-zinc-100"> <a class="transition-all duration-200" href="/food-agriculture/">Food &amp; Agriculture</a> </li>
<li class="*:block *:px-4 *:py-1 *:hover:bg-zinc-100"> <a class="transition-all duration-200" href="/gdp/gdp-by-country/">GDP by country</a> </li>
<li class="*:block *:px-4 *:py-1 *:hover:bg-zinc-100"> <a class="transition-all duration-200" href="/water/">Water</a> </li>
<li class="*:block *:px-4 *:py-1 *:hover:bg-zinc-100"> <a class="transition-all duration-200" href="/world-map/">World Map</a> </li></p> </ul> </div> </div> <div class="md:hidden flex items-center gap-12"> <button aria-controls="mobile-menu" aria-expanded="false" class="inline-flex items-center border focus:outline-none focus:ring-4 rounded-sm cursor-pointer focus:ring-zinc-200 transition-all duration-200 text-zinc-900 bg-white border-zinc-300 hover:bg-zinc-100 p-1.5 text-base" data-v2-collapse-toggle="mobile-menu" type="button"> <svg aria-hidden="true" class="size-4" fill="none" viewbox="0 0 17 14" xmlns="http://www.w3.org/2000/svg"> <path d="M1 1h15M1 7h15M1 13h15" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </button> <script>
(function() {
  function Collapse(targetEl, triggerEl, options) {
    options = options || {};
    this._targetEl = targetEl;
    this._triggerEl = triggerEl;
    this.onCollapse = options.onCollapse || function() {};
    this.onExpand = options.onExpand || function() {};
    this.onToggle = options.onToggle || function() {};
    if (this._triggerEl.hasAttribute('aria-expanded')) {
      this._visible = this._triggerEl.getAttribute('aria-expanded') === 'true';
    } else {
      this._visible = !targetEl.classList.contains('hidden');
    }
    this._init();
  }
  Collapse.prototype._init = function() {
    if (this._triggerEl && this._targetEl) {
      this._clickHandler = this.toggle.bind(this);
      this._triggerEl.addEventListener('click', this._clickHandler);
    }
  };
  Collapse.prototype.destroy = function() {
    if (this._triggerEl) {
      this._triggerEl.removeEventListener('click', this._clickHandler);
    }
  };
  Collapse.prototype.collapse = function() {
    if (!this._targetEl) return;
    this._targetEl.style.overflow = 'hidden';
    var currentHeight = this._targetEl.scrollHeight;
    this._targetEl.style.height = currentHeight + 'px';
    this._targetEl.offsetHeight;
    this._targetEl.style.transition = 'height 0.35s ease';
    this._targetEl.style.height = '0px';
    var self = this;
    this._targetEl.addEventListener('transitionend', function handler() {
      self._targetEl.classList.add('hidden');
      self._targetEl.style.height = '';
      self._targetEl.style.overflow = '';
      self._targetEl.removeEventListener('transitionend', handler);
    });
    if (this._triggerEl) {
      this._triggerEl.setAttribute('aria-expanded', 'false');
    }
    this._visible = false;
    this.onCollapse();
  };

  Collapse.prototype.expand = function() {
    if (!this._targetEl) return;
    this._targetEl.classList.remove('hidden');
    this._targetEl.style.overflow = 'hidden';
    this._targetEl.style.height = '0px';
    this._targetEl.offsetHeight;
    this._targetEl.style.transition = 'height 0.35s ease';
    var targetHeight = this._targetEl.scrollHeight;
    this._targetEl.style.height = targetHeight + 'px';
    var self = this;
    this._targetEl.addEventListener('transitionend', function handler() {
      self._targetEl.style.height = '';
      self._targetEl.style.overflow = '';
      self._targetEl.style.transition = '';
      self._targetEl.removeEventListener('transitionend', handler);
    });
    if (this._triggerEl) {
      this._triggerEl.setAttribute('aria-expanded', 'true');
    }
    this._visible = true;
    this.onExpand();
  };

  Collapse.prototype.toggle = function() {
    if (this._visible) {
      this.collapse();
    } else {
      this.expand();
    }
    this.onToggle();
  };

  function initCollapses() {
    var triggers = document.querySelectorAll('[data-v2-collapse-toggle]');
    Array.prototype.forEach.call(triggers, function(triggerEl) {
      var targetId = triggerEl.getAttribute('data-v2-collapse-toggle');
      var targetEl = document.getElementById(targetId);
      if (targetEl) {
        new Collapse(targetEl, triggerEl);
      } else {
        console.error('Target element with id "' + targetId + '" does not exist.');
      }
    });
  }
  document.addEventListener('DOMContentLoaded', function() {
    initCollapses();
  });
})();
</script> </div> </div> <ul class="hidden border-t mt-4 w-full" id="mobile-menu"> <p><li class="*:block *:px-4 *:py-1 *:hover:bg-zinc-100"> <a class="transition-all duration-200" href="/population/">Population</a> </li></p> <p><li class="*:block *:px-4 *:py-1 *:hover:bg-zinc-100"> <a class="transition-all duration-200" href="/co2-emissions/">CO2 emissions</a> </li>
<li class="*:block *:px-4 *:py-1 *:hover:bg-zinc-100"> <a class="transition-all duration-200" href="/coronavirus">Coronavirus</a> </li>
<li class="*:block *:px-4 *:py-1 *:hover:bg-zinc-100"> <a class="transition-all duration-200" href="/geography/countries-of-the-world/">Countries</a> </li>
<li class="*:block *:px-4 *:py-1 *:hover:bg-zinc-100"> <a class="transition-all duration-200" href="/energy/">Energy</a> </li>
<li class="*:block *:px-4 *:py-1 *:hover:bg-zinc-100"> <a class="transition-all duration-200" href="/geography/flags-of-the-world/">Flags</a> </li>
<li class="*:block *:px-4 *:py-1 *:hover:bg-zinc-100"> <a class="transition-all duration-200" href="/food-agriculture/">Food &amp; Agriculture</a> </li>
<li class="*:block *:px-4 *:py-1 *:hover:bg-zinc-100"> <a class="transition-all duration-200" href="/gdp/gdp-by-country/">GDP by country</a> </li>
<li class="*:block *:px-4 *:py-1 *:hover:bg-zinc-100"> <a class="transition-all duration-200" href="/water/">Water</a> </li>
<li class="*:block *:px-4 *:py-1 *:hover:bg-zinc-100"> <a class="transition-all duration-200" href="/world-map/">World Map</a> </li></p> </ul> </nav> </header> </div> <div class="container py-4 grow min-h-[500px]"> <div class="bg-zinc-100 rounded-sm py-2 px-4 mb-1 text-sm"> <nav aria-label="Breadcrumb" class="flex"> <ul class="flex flex-wrap items-center gap-x-2 gap-y-1"> <li class="inline-flex items-center text-zinc-500"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500 underline" href="/">W</a> </li>
<li aria-hidden="true" class="text-zinc-400">/</li><li class="inline-flex items-center text-zinc-500"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500 underline" href="/population/">Population</a> </li>
<li aria-hidden="true" class="text-zinc-400">/</li><li class="inline-flex items-center text-zinc-500"> Population by Country </li> </ul> </nav> </div><div class="prose max-w-none text-sm/5 md:text-base/6 prose-table:text-sm/5 md:prose-table:text-base/6 prose-headings:font-medium prose-headings:mt-10 prose-h1:text-4xl prose-h1:font-medium prose-h1:mb-8 prose-h2:text-3xl prose-h3:text-2xl prose-tr:border-0 prose-thead:border-0 prose-img:mb-0 prose-a:font-inherit prose-li:my-0.5"> <h1 id="countries-in-the-world-by-population-latestyearpopulation">Countries in the world by population (2025)</h1><p>This list includes both <strong>countries</strong> and <strong>dependent territories</strong>. Data based on the latest <em>United Nations Population Division</em> estimates.<br/>
Click on the name of the country or dependency for current estimates (live population clock), historical data, and projected figures.<br/>

In [72]:
columns_draft = soup.find_all('span')
columns_draft

[<span>#</span>,
 <span>Country (or<br/>dependency)</span>,
 <span>Population<br/>(2025)</span>,
 <span>Yearly<br/>Change</span>,
 <span>Net<br/>Change</span>,
 <span>Density<br/>(P/Km²)</span>,
 <span>Land Area<br/>(Km²)</span>,
 <span>Migrants<br/>(net)</span>,
 <span>Fert.<br/>Rate</span>,
 <span>Median<br/>Age</span>,
 <span>Urban<br/>Pop %</span>,
 <span>World<br/>Share</span>]

In [73]:
columns = [column.text for column in columns_draft]
columns

['#',
 'Country (ordependency)',
 'Population(2025)',
 'YearlyChange',
 'NetChange',
 'Density(P/Km²)',
 'Land Area(Km²)',
 'Migrants(net)',
 'Fert.Rate',
 'MedianAge',
 'UrbanPop %',
 'WorldShare']

---

In [74]:
data_draft = soup.find_all('tr')
data_draft

[<tr> <th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true"> <span>#</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true"> <span>Country (or<br/>dependency)</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Population<br/>(2025)</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Yearly<br/>Change</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Net<br/>Change</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Density<br/>(P/Km²)</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Land Area<br/>(Km²)</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Migrants<br/>(net)</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Fert.<br/>Rate</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Median<br/>Age</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Urban<br/>Pop %</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>World<br/>Share</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th> </tr>,
 <tr id="india"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 1 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="india" href="/world-population/india-population/">India</a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="1463865525"> 1,463,865,525 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="89"> 0.89% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="12929734"> 12,929,734 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="492.35518920755146"> 492 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="2973190"> 2,973,190 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-495753"> −495,753 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="19430"> 1.94 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="288290"> 28.8 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="3708"> 37.1% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1778"> 17.78% </td> </tr>,
 <tr id="china"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 2 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="china" href="/world-population/china-population/">China</a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="1416096094"> 1,416,096,094 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-23"> −0.23% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-3225184"> −3,225,184 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="150.8376935712246"> 151 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="9388211"> 9,388,211 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-268126"> −268,126 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="10210"> 1.02 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="401080"> 40.1 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="6755"> 67.5% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1720"> 17.20% </td> </tr>,
 <tr id="us"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 3 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="us" href="/world-population/us-population/">United States</a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="347275807"> 347,275,807 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="54"> 0.54% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1849236"> 1,849,236 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="37.96434480979336"> 38 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="9147420"> 9,147,420 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1230663"> 1,230,663 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="16230"> 1.62 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="385010"> 38.5 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="8276"> 82.8% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="422"> 4.22% </td> </tr>,
 <tr id="indonesia"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 4 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="indonesia" href="/world-population/indonesia-population/">Indonesia</a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="285721236"> 285,721,236 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="79"> 0.79% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="2233305"> 2,233,305 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="157.72022941426496"> 158 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1811570"> 1,811,570 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-39509"> −39,509 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="20960"> 2.1 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="303790"> 30.4 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="5963"> 59.6% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="347"> 3.47% </td> </tr>,
 <tr id="pakistan"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 5 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="pakistan" href="/world-population/pakistan-population/">Pakistan</a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="255219554"> 255,219,554 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="157"> 1.57% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="3950390"> 3,950,390 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="331.07559412619344"> 331 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="770880"> 770,880 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-1235336"> −1,235,336 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="34950"> 3.5 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="206030"> 20.6 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="3439"> 34.4% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="310"> 3.10% </td> </tr>,
 <tr id="nigeria"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 6 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="nigeria" href="/world-population/nigeria-population/">Nigeria</a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="237527782"> 237,527,782 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="208"> 2.08% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="4848304"> 4,848,304 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="260.79886469690484"> 261 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="910770"> 910,770 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-15258"> −15,258 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="42970"> 4.3 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="181420"> 18.1 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="5486"> 54.9% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="289"> 2.89% </td> </tr>,
 <tr id="brazil"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 7 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="brazil" href="/world-population/brazil-population/">Brazil</a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="212812405"> 212,812,405 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="38"> 0.38% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="813832"> 813,832 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="25.461694228620242"> 25 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="8358140"> 8,358,140 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-217283"> −217,283 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="16000"> 1.6 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="348180"> 34.8 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="9137"> 91.4% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="259"> 2.59% </td> </tr>,
 <tr id="bangladesh"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 8 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="bangladesh" href="/world-population/bangladesh-population/">Bangladesh</a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="175686899"> 175,686,899 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="122"> 1.22% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="2124535"> 2,124,535 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1349.6727279711147"> 1,350 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="130170"> 130,170 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-402100"> −402,100 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="21140"> 2.11 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="259770"> 26 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="4260"> 42.6% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="213"> 2.13% </td> </tr>,
 <tr id="russia"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 9 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="russia" href="/world-population/russia-population/">Russia</a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="143997393"> 143,997,393 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-57"> −0.57% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-823030"> −823,030 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="8.792729807344138"> 9 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="16376870"> 16,376,870 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-251822"> −251,822 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="14650"> 1.47 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="402970"> 40.3 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="7504"> 75% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="175"> 1.75% </td> </tr>,
 <tr id="ethiopia"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 10 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="ethiopia" href="/world-population/ethiopia-population/">Ethiopia</a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="135472051"> 135,472,051 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="258"> 2.58% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="3412284"> 3,412,284 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="135.472051"> 135 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1000000"> 1,000,000 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="24054"> 24,054 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="38060"> 3.81 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="191330"> 19.1 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="2250"> 22.5% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="165"> 1.65% </td> </tr>,

In [75]:
total_data = []

for row in data_draft:
    row_data = row.find_all('td')
    data = [single_data.text for single_data in row_data]
    total_data.append(data)

for line in total_data[1:]:
    print(line)

[' 1 ', ' India ', ' 1,463,865,525 ', ' 0.89% ', ' 12,929,734 ', ' 492 ', ' 2,973,190 ', ' −495,753 ', ' 1.94 ', ' 28.8 ', ' 37.1% ', ' 17.78% ']
[' 2 ', ' China ', ' 1,416,096,094 ', ' −0.23% ', ' −3,225,184 ', ' 151 ', ' 9,388,211 ', ' −268,126 ', ' 1.02 ', ' 40.1 ', ' 67.5% ', ' 17.20% ']
[' 3 ', ' United States ', ' 347,275,807 ', ' 0.54% ', ' 1,849,236 ', ' 38 ', ' 9,147,420 ', ' 1,230,663 ', ' 1.62 ', ' 38.5 ', ' 82.8% ', ' 4.22% ']
[' 4 ', ' Indonesia ', ' 285,721,236 ', ' 0.79% ', ' 2,233,305 ', ' 158 ', ' 1,811,570 ', ' −39,509 ', ' 2.1 ', ' 30.4 ', ' 59.6% ', ' 3.47% ']
[' 5 ', ' Pakistan ', ' 255,219,554 ', ' 1.57% ', ' 3,950,390 ', ' 331 ', ' 770,880 ', ' −1,235,336 ', ' 3.5 ', ' 20.6 ', ' 34.4% ', ' 3.10% ']
[' 6 ', ' Nigeria ', ' 237,527,782 ', ' 2.08% ', ' 4,848,304 ', ' 261 ', ' 910,770 ', ' −15,258 ', ' 4.3 ', ' 18.1 ', ' 54.9% ', ' 2.89% ']
[' 7 ', ' Brazil ', ' 212,812,405 ', ' 0.38% ', ' 813,832 ', ' 25 ', ' 8,358,140 ', ' −217,283 ', ' 1.6 ', ' 34.8 ', ' 91.4% ', ' 2.59% ']
[' 8 ', ' Bangladesh ', ' 175,686,899 ', ' 1.22% ', ' 2,124,535 ', ' 1,350 ', ' 130,170 ', ' −402,100 ', ' 2.11 ', ' 26 ', ' 42.6% ', ' 2.13% ']
[' 9 ', ' Russia ', ' 143,997,393 ', ' −0.57% ', ' −823,030 ', ' 9 ', ' 16,376,870 ', ' −251,822 ', ' 1.47 ', ' 40.3 ', ' 75% ', ' 1.75% ']
[' 10 ', ' Ethiopia ', ' 135,472,051 ', ' 2.58% ', ' 3,412,284 ', ' 135 ', ' 1,000,000 ', ' 24,054 ', ' 3.81 ', ' 19.1 ', ' 22.5% ', ' 1.65% ']
[' 11 ', ' Mexico ', ' 131,946,900 ', ' 0.83% ', ' 1,085,893 ', ' 68 ', ' 1,943,950 ', ' −108,037 ', ' 1.87 ', ' 29.6 ', ' 87.9% ', ' 1.60% ']
[' 12 ', ' Japan ', ' 123,103,479 ', ' −0.52% ', ' −649,562 ', ' 338 ', ' 364,555 ', ' 140,579 ', ' 1.23 ', ' 49.8 ', ' 93.1% ', ' 1.50% ']
[' 13 ', ' Egypt ', ' 118,365,995 ', ' 1.57% ', ' 1,827,737 ', ' 119 ', ' 995,450 ', ' −57,305 ', ' 2.71 ', ' 24.5 ', ' 40.9% ', ' 1.44% ']
[' 14 ', ' Philippines ', ' 116,786,962 ', ' 0.81% ', ' 943,292 ', ' 392 ', ' 298,170 ', ' −149,315 ', ' 1.88 ', ' 26.1 ', ' 49.3% ', ' 1.42% ']
[' 15 ', ' DR Congo ', ' 112,832,473 ', ' 3.25% ', ' 3,556,208 ', ' 50 ', ' 2,267,050 ', ' −27,309 ', ' 5.9 ', ' 15.8 ', ' 45% ', ' 1.37% ']
[' 16 ', ' Vietnam ', ' 101,598,527 ', ' 0.6% ', ' 610,841 ', ' 328 ', ' 310,070 ', ' −48,171 ', ' 1.88 ', ' 33.4 ', ' 41.4% ', ' 1.23% ']
[' 17 ', ' Iran ', ' 92,417,681 ', ' 0.93% ', ' 849,943 ', ' 57 ', ' 1,628,550 ', ' 116,786 ', ' 1.67 ', ' 34 ', ' 73.3% ', ' 1.12% ']
[' 18 ', ' Turkey ', ' 87,685,426 ', ' 0.24% ', ' 211,621 ', ' 114 ', ' 769,630 ', ' −258,205 ', ' 1.62 ', ' 33.5 ', ' 76.9% ', ' 1.07% ']
[' 19 ', ' Germany ', ' 84,075,075 ', ' −0.56% ', ' −477,167 ', ' 241 ', ' 348,560 ', ' −334,072 ', ' 1.46 ', ' 45.5 ', ' 76.5% ', ' 1.02% ']
[' 20 ', ' Thailand ', ' 71,619,863 ', ' −0.07% ', ' −48,148 ', ' 140 ', ' 510,890 ', ' 27,509 ', ' 1.2 ', ' 40.6 ', ' 53.5% ', ' 0.87% ']
[' 21 ', ' Tanzania ', ' 70,545,865 ', ' 2.9% ', ' 1,985,708 ', ' 80 ', ' 885,800 ', ' −12,730 ', ' 4.47 ', ' 17.5 ', ' 40% ', ' 0.86% ']
[' 22 ', ' United Kingdom ', ' 69,551,332 ', ' 0.6% ', ' 413,140 ', ' 287 ', ' 241,930 ', ' 389,911 ', ' 1.54 ', ' 40.1 ', ' 84.5% ', ' 0.84% ']
[' 23 ', ' France ', ' 66,650,804 ', ' 0.15% ', ' 102,274 ', ' 122 ', ' 547,557 ', ' 91,737 ', ' 1.64 ', ' 42.3 ', ' 82.5% ', ' 0.81% ']
[' 24 ', ' South Africa ', ' 64,747,319 ', ' 1.16% ', ' 740,132 ', ' 53 ', ' 1,213,090 ', ' 146,370 ', ' 2.19 ', ' 28.7 ', ' 66.6% ', ' 0.79% ']
[' 25 ', ' Italy ', ' 59,146,260 ', ' −0.33% ', ' −196,607 ', ' 201 ', ' 294,140 ', ' 75,448 ', ' 1.21 ', ' 48.2 ', ' 72% ', ' 0.72% ']
[' 26 ', ' Kenya ', ' 57,532,493 ', ' 1.95% ', ' 1,099,549 ', ' 101 ', ' 569,140 ', ' −27,330 ', ' 3.12 ', ' 20 ', ' 31.9% ', ' 0.70% ']
[' 27 ', ' Myanmar ', ' 54,850,648 ', ' 0.64% ', ' 350,557 ', ' 84 ', ' 653,290 ', ' −39,661 ', ' 2.08 ', ' 30.1 ', ' 34.1% ', ' 0.67% ']
[' 28 ', ' Colombia ', ' 53,425,635 ', ' 1.02% ', ' 539,272 ', ' 48 ', ' 1,109,500 ', ' 129,139 ', ' 1.62 ', ' 32.5 ', ' 80.5% ', ' 0.65% ']
[' 29 ', ' South Korea ', ' 51,667,029 ', ' −0.1% ', ' −50,561 ', ' 531 ', ' 97,230 ', ' 65,731 ', ' 0.75 ', ' 45.6 ', ' 82.4% ', ' 0.63% ']
[' 30 ', ' Sudan ', ' 51,662,147 ', ' 2.4% ', ' 1,213,184 ', ' 29 ', ' 1,765,048 ', ' 291,469 ', ' 4.19 ', ' 18.5 ', ' 35.3% ', ' 0.63% ']
[' 31 ', ' Uganda ', ' 51,384,894 ', ' 2.74% ', ' 1,369,802 ', ' 257 ', ' 199,810 ', ' −119,059 ', ' 4.06 ', ' 16.9 ', ' 30% ', ' 0.62% ']
[' 32 ', ' Spain ', ' 47,889,958 ', ' −0.04% ', ' −20,568 ', ' 96 ', ' 498,800 ', ' 96,630 ', ' 1.23 ', ' 45.9 ', ' 79.3% ', ' 0.58% ']
[' 33 ', ' Algeria ', ' 47,435,312 ', ' 1.33% ', ' 621,004 ', ' 20 ', ' 2,381,740 ', ' −27,531 ', ' 2.67 ', ' 28.6 ', ' 74.4% ', ' 0.58% ']
[' 34 ', ' Iraq ', ' 47,020,774 ', ' 2.13% ', ' 978,759 ', ' 108 ', ' 434,320 ', ' −1,064 ', ' 3.17 ', ' 20.8 ', ' 72.4% ', ' 0.57% ']
[' 35 ', ' Argentina ', ' 45,851,378 ', ' 0.34% ', ' 155,219 ', ' 17 ', ' 2,736,690 ', ' 2,859 ', ' 1.5 ', ' 32.9 ', ' 96% ', ' 0.56% ']
[' 36 ', ' Afghanistan ', ' 43,844,111 ', ' 2.81% ', ' 1,196,619 ', ' 67 ', ' 652,860 ', ' −74,404 ', ' 4.66 ', ' 17.3 ', ' 26.7% ', ' 0.53% ']
[' 37 ', ' Yemen ', ' 41,773,878 ', ' 2.93% ', ' 1,190,714 ', ' 79 ', ' 527,970 ', ' −16,291 ', ' 4.41 ', ' 18.4 ', ' 33% ', ' 0.51% ']
[' 38 ', ' Canada ', ' 40,126,723 ', ' 0.97% ', ' 384,293 ', ' 4 ', ' 9,093,510 ', ' 326,204 ', ' 1.33 ', ' 40.6 ', ' 80.2% ', ' 0.49% ']
[' 39 ', ' Angola ', ' 39,040,039 ', ' 3.05% ', ' 1,154,190 ', ' 31 ', ' 1,246,700 ', ' −3,524 ', ' 4.95 ', ' 16.6 ', ' 68.8% ', ' 0.47% ']
[' 40 ', ' Ukraine ', ' 38,980,376 ', ' 2.96% ', ' 1,120,155 ', ' 67 ', ' 579,320 ', ' 1,702,358 ', ' 1 ', ' 41.8 ', ' 76.8% ', ' 0.47% ']
[' 41 ', ' Morocco ', ' 38,430,770 ', ' 0.92% ', ' 349,597 ', ' 86 ', ' 446,300 ', ' −56,254 ', ' 2.18 ', ' 29.8 ', ' 67.3% ', ' 0.47% ']
[' 42 ', ' Poland ', ' 38,140,910 ', ' −1.03% ', ' −398,291 ', ' 125 ', ' 306,230 ', ' −330,820 ', ' 1.31 ', ' 42.5 ', ' 59.2% ', ' 0.46% ']
[' 43 ', ' Uzbekistan ', ' 37,053,428 ', ' 1.9% ', ' 691,569 ', ' 87 ', ' 425,400 ', ' −6,987 ', ' 3.45 ', ' 27 ', ' 48.1% ', ' 0.45% ']
[' 44 ', ' Malaysia ', ' 35,977,838 ', ' 1.18% ', ' 420,165 ', ' 110 ', ' 328,550 ', ' 166,615 ', ' 1.53 ', ' 31 ', ' 77.4% ', ' 0.44% ']
[' 45 ', ' Mozambique ', ' 35,631,653 ', ' 2.89% ', ' 999,887 ', ' 45 ', ' 786,380 ', ' −65,573 ', ' 4.62 ', ' 16.5 ', ' 41.6% ', ' 0.43% ']
[' 46 ', ' Ghana ', ' 35,064,272 ', ' 1.85% ', ' 636,858 ', ' 154 ', ' 227,540 ', ' −17,079 ', ' 3.3 ', ' 21.3 ', ' 58.6% ', ' 0.43% ']
[' 47 ', ' Peru ', ' 34,576,665 ', ' 1.05% ', ' 358,817 ', ' 27 ', ' 1,280,000 ', ' 11,931 ', ' 1.94 ', ' 30.2 ', ' 80.6% ', ' 0.42% ']
[' 48 ', ' Saudi Arabia ', ' 34,566,328 ', ' 1.78% ', ' 603,571 ', ' 16 ', ' 2,149,690 ', ' 119,738 ', ' 2.29 ', ' 29.6 ', ' 92.1% ', ' 0.42% ']
[' 49 ', ' Madagascar ', ' 32,740,678 ', ' 2.43% ', ' 775,722 ', ' 56 ', ' 581,795 ', ' −2,227 ', ' 3.85 ', ' 19.2 ', ' 40.3% ', ' 0.40% ']
[' 50 ', " Côte d'Ivoire ", ' 32,711,547 ', ' 2.43% ', ' 777,317 ', ' 103 ', ' 318,000 ', ' 11,305 ', ' 4.17 ', ' 18.3 ', ' 49% ', ' 0.40% ']
[' 51 ', ' Cameroon ', ' 29,879,337 ', ' 2.59% ', ' 755,593 ', ' 63 ', ' 472,710 ', ' −15,379 ', ' 4.18 ', ' 18 ', ' 59.4% ', ' 0.36% ']
[' 52 ', ' Nepal ', ' 29,618,118 ', ' −0.11% ', ' −32,936 ', ' 207 ', ' 143,350 ', ' −364,699 ', ' 1.94 ', ' 25.3 ', ' 24.5% ', ' 0.36% ']
[' 53 ', ' Venezuela ', ' 28,516,896 ', ' 0.39% ', ' 111,353 ', ' 32 ', ' 882,050 ', ' −100,467 ', ' 2.06 ', ' 29.4 ', ' ', ' 0.35% ']
[' 54 ', ' Niger ', ' 27,917,831 ', ' 3.28% ', ' 885,419 ', ' 22 ', ' 1,266,700 ', ' −7,704 ', ' 5.79 ', ' 15.6 ', ' 18.2% ', ' 0.34% ']
[' 55 ', ' Australia ', ' 26,974,026 ', ' 0.98% ', ' 260,821 ', ' 4 ', ' 7,682,300 ', ' 137,109 ', ' 1.64 ', ' 38.3 ', ' 86.5% ', ' 0.33% ']
[' 56 ', ' North Korea ', ' 26,571,036 ', ' 0.27% ', ' 72,213 ', ' 221 ', ' 120,410 ', ' −2,787 ', ' 1.77 ', ' 36.5 ', ' 63.3% ', ' 0.32% ']
[' 57 ', ' Syria ', ' 25,620,427 ', ' 3.84% ', ' 947,667 ', ' 140 ', ' 183,630 ', ' 421,693 ', ' 2.66 ', ' 23.3 ', ' 53.6% ', ' 0.31% ']
[' 58 ', ' Mali ', ' 25,198,821 ', ' 2.94% ', ' 720,226 ', ' 21 ', ' 1,220,190 ', ' −48,019 ', ' 5.42 ', ' 15.7 ', ' 44.4% ', ' 0.31% ']
[' 59 ', ' Burkina Faso ', ' 24,074,580 ', ' 2.23% ', ' 525,799 ', ' 88 ', ' 273,600 ', ' −27,130 ', ' 4 ', ' 17.7 ', ' 33.7% ', ' 0.29% ']
[' 60 ', ' Sri Lanka ', ' 23,229,470 ', ' 0.54% ', ' 125,905 ', ' 370 ', ' 62,710 ', ' −30,724 ', ' 1.94 ', ' 33.3 ', ' 18.1% ', ' 0.28% ']
[' 61 ', ' Taiwan ', ' 23,112,793 ', ' −0.44% ', ' −101,169 ', ' 653 ', ' 35,410 ', ' −20,947 ', ' 0.86 ', ' 44.8 ', ' 84% ', ' 0.28% ']
[' 62 ', ' Malawi ', ' 22,216,120 ', ' 2.59% ', ' 560,834 ', ' 236 ', ' 94,280 ', ' −5,628 ', ' 3.53 ', ' 18.1 ', ' 19.8% ', ' 0.27% ']
[' 63 ', ' Zambia ', ' 21,913,874 ', ' 2.81% ', ' 598,918 ', ' 29 ', ' 743,390 ', ' 6,562 ', ' 3.97 ', ' 17.9 ', ' 46.8% ', ' 0.27% ']
[' 64 ', ' Chad ', ' 21,003,705 ', ' 3.47% ', ' 704,582 ', ' 17 ', ' 1,259,200 ', ' −123,104 ', ' 5.94 ', ' 15.8 ', ' 22.4% ', ' 0.26% ']
[' 65 ', ' Kazakhstan ', ' 20,843,754 ', ' 1.22% ', ' 251,183 ', ' 8 ', ' 2,699,700 ', ' −8,834 ', ' 2.95 ', ' 29.7 ', ' 55.1% ', ' 0.25% ']
[' 66 ', ' Chile ', ' 19,859,921 ', ' 0.48% ', ' 95,150 ', ' 27 ', ' 743,532 ', ' 51,712 ', ' 1.13 ', ' 36.9 ', ' 84.8% ', ' 0.24% ']
[' 67 ', ' Somalia ', ' 19,654,739 ', ' 3.4% ', ' 645,588 ', ' 31 ', ' 627,340 ', ' 12,077 ', ' 5.91 ', ' 15.6 ', ' 46.6% ', ' 0.24% ']
[' 68 ', ' Senegal ', ' 18,931,966 ', ' 2.32% ', ' 429,982 ', ' 98 ', ' 192,530 ', ' −12,636 ', ' 3.71 ', ' 19.6 ', ' 52.3% ', ' 0.23% ']
[' 69 ', ' Romania ', ' 18,908,650 ', ' −0.56% ', ' −106,438 ', ' 82 ', ' 230,170 ', ' −29,041 ', ' 1.71 ', ' 43.2 ', ' 55.2% ', ' 0.23% ']
[' 70 ', ' Guatemala ', ' 18,687,881 ', ' 1.53% ', ' 281,522 ', ' 174 ', ' 107,160 ', ' −7,959 ', ' 2.26 ', ' 23.4 ', ' 56.6% ', ' 0.23% ']
[' 71 ', ' Netherlands ', ' 18,346,819 ', ' 0.65% ', ' 118,077 ', ' 544 ', ' 33,720 ', ' 104,681 ', ' 1.44 ', ' 41.5 ', ' 88.9% ', ' 0.22% ']
[' 72 ', ' Ecuador ', ' 18,289,896 ', ' 0.85% ', ' 154,418 ', ' 74 ', ' 248,360 ', ' −17,219 ', ' 1.79 ', ' 29.3 ', ' 66% ', ' 0.22% ']
[' 73 ', ' Cambodia ', ' 17,847,982 ', ' 1.19% ', ' 209,181 ', ' 101 ', ' 176,520 ', ' −31,469 ', ' 2.51 ', ' 26.2 ', ' 26.5% ', ' 0.22% ']
[' 74 ', ' Zimbabwe ', ' 16,950,795 ', ' 1.9% ', ' 316,422 ', ' 44 ', ' 386,850 ', ' −54,555 ', ' 3.62 ', ' 18.1 ', ' 37.9% ', ' 0.21% ']
[' 75 ', ' Guinea ', ' 15,099,727 ', ' 2.34% ', ' 344,942 ', ' 61 ', ' 245,720 ', ' −16,282 ', ' 4.04 ', ' 18.3 ', ' 40.3% ', ' 0.18% ']
[' 76 ', ' Benin ', ' 14,814,460 ', ' 2.43% ', ' 351,736 ', ' 131 ', ' 112,760 ', ' −7,847 ', ' 4.42 ', ' 18 ', ' 47.8% ', ' 0.18% ']
[' 77 ', ' Rwanda ', ' 14,569,341 ', ' 2.19% ', ' 312,774 ', ' 591 ', ' 24,670 ', ' 6,282 ', ' 3.59 ', ' 19.9 ', ' 18.3% ', ' 0.18% ']
[' 78 ', ' Burundi ', ' 14,390,003 ', ' 2.44% ', ' 342,217 ', ' 560 ', ' 25,680 ', ' −34,727 ', ' 4.67 ', ' 16.4 ', ' 14.9% ', ' 0.17% ']
[' 79 ', ' Bolivia ', ' 12,581,843 ', ' 1.36% ', ' 168,528 ', ' 12 ', ' 1,083,300 ', ' −3,179 ', ' 2.5 ', ' 25.2 ', ' 70.6% ', ' 0.15% ']
[' 80 ', ' Tunisia ', ' 12,348,573 ', ' 0.58% ', ' 71,464 ', ' 79 ', ' 155,360 ', ' −14,523 ', ' 1.8 ', ' 32.9 ', ' 71.7% ', ' 0.15% ']
[' 81 ', ' South Sudan ', ' 12,188,788 ', ' 2.05% ', ' 245,380 ', ' 20 ', ' 610,952 ', ' 6,145 ', ' 3.71 ', ' 18.7 ', ' 27.7% ', ' 0.15% ']
[' 82 ', ' Haiti ', ' 11,906,095 ', ' 1.13% ', ' 133,538 ', ' 432 ', ' 27,560 ', ' −32,052 ', ' 2.59 ', ' 24.1 ', ' 61.7% ', ' 0.14% ']
[' 83 ', ' Belgium ', ' 11,758,603 ', ' 0.17% ', ' 19,840 ', ' 388 ', ' 30,280 ', ' 31,989 ', ' 1.39 ', ' 41.9 ', ' 98.8% ', ' 0.14% ']
[' 84 ', ' Jordan ', ' 11,520,684 ', ' −0.28% ', ' −32,192 ', ' 130 ', ' 88,780 ', ' −303,267 ', ' 2.57 ', ' 24.7 ', ' 85.1% ', ' 0.14% ']
[' 85 ', ' Dominican Republic ', ' 11,520,487 ', ' 0.81% ', ' 92,930 ', ' 238 ', ' 48,320 ', ' −35,306 ', ' 2.19 ', ' 28.3 ', ' 86.4% ', ' 0.14% ']
[' 86 ', ' United Arab Emirates ', ' 11,346,000 ', ' 2.89% ', ' 318,871 ', ' 136 ', ' 83,600 ', ' 158,634 ', ' 1.21 ', ' 31.6 ', ' 81.1% ', ' 0.14% ']
[' 87 ', ' Honduras ', ' 11,005,850 ', ' 1.66% ', ' 180,147 ', ' 98 ', ' 111,890 ', ' −4,778 ', ' 2.45 ', ' 24.2 ', ' 58.3% ', ' 0.13% ']
[' 88 ', ' Cuba ', ' 10,937,203 ', ' −0.39% ', ' −42,580 ', ' 103 ', ' 106,440 ', ' −22,244 ', ' 1.45 ', ' 42.2 ', ' 81.9% ', ' 0.13% ']
[' 89 ', ' Tajikistan ', ' 10,786,734 ', ' 1.85% ', ' 195,807 ', ' 77 ', ' 139,960 ', ' −21,606 ', ' 2.99 ', ' 22.2 ', ' 27.7% ', ' 0.13% ']
[' 90 ', ' Papua New Guinea ', ' 10,762,817 ', ' 1.76% ', ' 186,315 ', ' 24 ', ' 452,860 ', ' −284 ', ' 3.03 ', ' 22.8 ', ' 12.6% ', ' 0.13% ']
[' 91 ', ' Sweden ', ' 10,656,633 ', ' 0.47% ', ' 49,634 ', ' 26 ', ' 410,340 ', ' 47,079 ', ' 1.44 ', ' 40.3 ', ' 87.4% ', ' 0.13% ']
[' 92 ', ' Czech Republic (Czechia) ', ' 10,609,239 ', ' −1.18% ', ' −126,620 ', ' 137 ', ' 77,240 ', ' −112,188 ', ' 1.47 ', ' 43.8 ', ' 75% ', ' 0.13% ']
[' 93 ', ' Portugal ', ' 10,411,834 ', ' −0.13% ', ' −13,458 ', ' 114 ', ' 91,590 ', ' 16,472 ', ' 1.52 ', ' 46.9 ', ' 66.5% ', ' 0.13% ']
[' 94 ', ' Azerbaijan ', ' 10,397,713 ', ' 0.59% ', ' 61,136 ', ' 126 ', ' 82,658 ', ' 8,731 ', ' 1.67 ', ' 33.6 ', ' 58.7% ', ' 0.13% ']
[' 95 ', ' Greece ', ' 9,938,844 ', ' −1.08% ', ' −108,973 ', ' 77 ', ' 128,900 ', ' 16,636 ', ' 1.34 ', ' 46.8 ', ' 89.5% ', ' 0.12% ']
[' 96 ', ' Togo ', ' 9,721,608 ', ' 2.17% ', ' 206,372 ', ' 179 ', ' 54,390 ', ' −15,010 ', ' 4.07 ', ' 19.1 ', ' 44.2% ', ' 0.12% ']
[' 97 ', ' Hungary ', ' 9,632,287 ', ' −0.45% ', ' −43,848 ', ' 106 ', ' 90,530 ', ' −16,331 ', ' 1.5 ', ' 43.9 ', ' 72% ', ' 0.12% ']
[' 98 ', ' Israel ', ' 9,517,181 ', ' 1.39% ', ' 130,160 ', ' 440 ', ' 21,640 ', ' 11,466 ', ' 2.75 ', ' 29.2 ', ' 91.4% ', ' 0.12% ']
[' 99 ', ' Austria ', ' 9,113,574 ', ' −0.08% ', ' −7,239 ', ' 111 ', ' 82,409 ', ' 11,254 ', ' 1.33 ', ' 43.6 ', ' 58.6% ', ' 0.11% ']
[' 100 ', ' Belarus ', ' 8,997,603 ', ' −0.65% ', ' −59,093 ', ' 44 ', ' 202,910 ', ' −3,020 ', ' 1.23 ', ' 41.3 ', ' 84.4% ', ' 0.11% ']
[' 101 ', ' Switzerland ', ' 8,967,407 ', ' 0.51% ', ' 45,426 ', ' 227 ', ' 39,516 ', ' 37,253 ', ' 1.44 ', ' 42.9 ', ' 74.4% ', ' 0.11% ']
[' 102 ', ' Sierra Leone ', ' 8,819,794 ', ' 2.06% ', ' 177,772 ', ' 122 ', ' 72,180 ', ' −11,309 ', ' 3.61 ', ' 19.7 ', ' 45.5% ', ' 0.11% ']
[' 103 ', ' Laos ', ' 7,873,046 ', ' 1.33% ', ' 103,227 ', ' 34 ', ' 230,800 ', ' −10,645 ', ' 2.36 ', ' 24.9 ', ' 38.3% ', ' 0.096% ']
[' 104 ', ' Turkmenistan ', ' 7,618,847 ', ' 1.66% ', ' 124,349 ', ' 16 ', ' 469,930 ', ' 13,268 ', ' 2.63 ', ' 26.9 ', ' 46.5% ', ' 0.093% ']
[' 105 ', ' Libya ', ' 7,458,555 ', ' 1.05% ', ' 77,532 ', ' 4 ', ' 1,759,540 ', ' −172 ', ' 2.25 ', ' 27.7 ', ' 77.5% ', ' 0.091% ']
[' 106 ', ' Hong Kong ', ' 7,396,076 ', ' −0.25% ', ' −18,833 ', ' 7,044 ', ' 1,050 ', ' 17,863 ', ' 0.73 ', ' 47.4 ', ' ', ' 0.090% ']
[' 107 ', ' Kyrgyzstan ', ' 7,295,034 ', ' 1.52% ', ' 109,025 ', ' 38 ', ' 191,800 ', ' 1,815 ', ' 2.75 ', ' 25.4 ', ' 35.3% ', ' 0.089% ']
[' 108 ', ' Paraguay ', ' 7,013,078 ', ' 1.21% ', ' 83,925 ', ' 18 ', ' 397,300 ', ' −12,423 ', ' 2.4 ', ' 27 ', ' 68% ', ' 0.085% ']
[' 109 ', ' Nicaragua ', ' 7,007,502 ', ' 1.32% ', ' 91,362 ', ' 58 ', ' 120,340 ', ' −8,371 ', ' 2.18 ', ' 26 ', ' 58.1% ', ' 0.085% ']
[' 110 ', ' Bulgaria ', ' 6,714,560 ', ' −0.64% ', ' −43,129 ', ' 62 ', ' 108,560 ', ' −2,961 ', ' 1.74 ', ' 44.8 ', ' 77.1% ', ' 0.082% ']
[' 111 ', ' Serbia ', ' 6,689,039 ', ' −0.7% ', ' −47,177 ', ' 76 ', ' 87,460 ', ' −13,086 ', ' 1.5 ', ' 44.4 ', ' 73.6% ', ' 0.081% ']
[' 112 ', ' Congo ', ' 6,484,437 ', ' 2.39% ', ' 151,476 ', ' 19 ', ' 341,500 ', ' −2,999 ', ' 4.05 ', ' 18.6 ', ' 69.8% ', ' 0.079% ']
[' 113 ', ' El Salvador ', ' 6,365,503 ', ' 0.43% ', ' 27,310 ', ' 307 ', ' 20,720 ', ' −23,934 ', ' 1.75 ', ' 27.9 ', ' 79.9% ', ' 0.077% ']
[' 114 ', ' Denmark ', ' 6,002,507 ', ' 0.42% ', ' 25,095 ', ' 141 ', ' 42,430 ', ' 22,103 ', ' 1.52 ', ' 41.3 ', ' 87.4% ', ' 0.073% ']
[' 115 ', ' Singapore ', ' 5,870,750 ', ' 0.66% ', ' 38,363 ', ' 8,387 ', ' 700 ', ' 16,892 ', ' 0.96 ', ' 36.2 ', ' ', ' 0.071% ']
[' 116 ', ' Lebanon ', ' 5,849,421 ', ' 0.75% ', ' 43,459 ', ' 572 ', ' 10,230 ', ' −10,230 ', ' 2.21 ', ' 28.8 ', ' 86% ', ' 0.071% ']
[' 117 ', ' Liberia ', ' 5,731,206 ', ' 2.11% ', ' 118,389 ', ' 60 ', ' 96,320 ', ' −9,870 ', ' 3.79 ', ' 18.8 ', ' 55% ', ' 0.070% ']
[' 118 ', ' Finland ', ' 5,623,329 ', ' 0.11% ', ' 6,019 ', ' 19 ', ' 303,890 ', ' 18,246 ', ' 1.3 ', ' 43.2 ', ' 86.7% ', ' 0.068% ']
[' 119 ', ' Norway ', ' 5,623,071 ', ' 0.83% ', ' 46,411 ', ' 15 ', ' 365,268 ', ' 29,798 ', ' 1.42 ', ' 39.8 ', ' 85.9% ', ' 0.068% ']
[' 120 ', ' State of Palestine ', ' 5,589,623 ', ' 1.71% ', ' 94,180 ', ' 929 ', ' 6,020 ', ' −23,156 ', ' 3.19 ', ' 20.1 ', ' 84.2% ', ' 0.068% ']
[' 121 ', ' Central African Republic ', ' 5,513,282 ', ' 3.43% ', ' 182,592 ', ' 9 ', ' 622,980 ', ' −14,693 ', ' 5.81 ', ' 14.5 ', ' 44.5% ', ' 0.067% ']
[' 122 ', ' Oman ', ' 5,494,691 ', ' 4.04% ', ' 213,153 ', ' 18 ', ' 309,500 ', ' 113,734 ', ' 2.48 ', ' 29.7 ', ' 90.8% ', ' 0.067% ']
[' 123 ', ' Slovakia ', ' 5,474,881 ', ' −0.58% ', ' −31,879 ', ' 114 ', ' 48,088 ', ' −31,377 ', ' 1.57 ', ' 42.3 ', ' 54% ', ' 0.067% ']
[' 124 ', ' Mauritania ', ' 5,315,065 ', ' 2.82% ', ' 145,670 ', ' 5 ', ' 1,030,700 ', ' −5,044 ', ' 4.56 ', ' 17.4 ', ' 60.3% ', ' 0.065% ']
[' 125 ', ' Ireland ', ' 5,308,039 ', ' 1.01% ', ' 53,022 ', ' 77 ', ' 68,890 ', ' 35,417 ', ' 1.6 ', ' 39 ', ' 62.1% ', ' 0.064% ']
[' 126 ', ' New Zealand ', ' 5,251,899 ', ' 0.73% ', ' 37,955 ', ' 20 ', ' 263,310 ', ' 17,403 ', ' 1.65 ', ' 37.7 ', ' 83.6% ', ' 0.064% ']
[' 127 ', ' Costa Rica ', ' 5,152,950 ', ' 0.45% ', ' 23,040 ', ' 101 ', ' 51,060 ', ' 1,000 ', ' 1.31 ', ' 35.2 ', ' 85.2% ', ' 0.063% ']
[' 128 ', ' Kuwait ', ' 5,026,078 ', ' 1.86% ', ' 91,571 ', ' 282 ', ' 17,820 ', ' 42,775 ', ' 1.5 ', ' 34.8 ', ' 91.6% ', ' 0.061% ']
[' 129 ', ' Panama ', ' 4,571,189 ', ' 1.23% ', ' 55,612 ', ' 61 ', ' 74,340 ', ' 6,151 ', ' 2.09 ', ' 30.3 ', ' 70.7% ', ' 0.056% ']
[' 130 ', ' Croatia ', ' 3,848,160 ', ' −0.7% ', ' −27,165 ', ' 69 ', ' 55,960 ', ' −3,481 ', ' 1.47 ', ' 45.3 ', ' 61.7% ', ' 0.047% ']
[' 131 ', ' Georgia ', ' 3,806,671 ', ' −0.03% ', ' −999 ', ' 55 ', ' 69,490 ', ' 1,283 ', ' 1.79 ', ' 37.3 ', ' 62% ', ' 0.046% ']
[' 132 ', ' Eritrea ', ' 3,607,003 ', ' 2.02% ', ' 71,400 ', ' 36 ', ' 101,000 ', ' −6,698 ', ' 3.61 ', ' 19.2 ', ' 74.8% ', ' 0.044% ']
[' 133 ', ' Mongolia ', ' 3,517,100 ', ' 1.2% ', ' 41,560 ', ' 2 ', ' 1,553,560 ', ' 79 ', ' 2.58 ', ' 26.9 ', ' 67.2% ', ' 0.043% ']
[' 134 ', ' Uruguay ', ' 3,384,688 ', ' −0.06% ', ' −1,900 ', ' 19 ', ' 175,020 ', ' −1,338 ', ' 1.39 ', ' 36.4 ', ' ', ' 0.041% ']
[' 135 ', ' Puerto Rico ', ' 3,235,289 ', ' −0.21% ', ' −6,915 ', ' 365 ', ' 8,870 ', ' 5,495 ', ' 0.94 ', ' 45.8 ', ' ', ' 0.039% ']
[' 136 ', ' Bosnia and Herzegovina ', ' 3,140,095 ', ' −0.76% ', ' −24,158 ', ' 62 ', ' 51,000 ', ' −6,994 ', ' 1.5 ', ' 45.7 ', ' 56.3% ', ' 0.038% ']
[' 137 ', ' Qatar ', ' 3,115,889 ', ' 2.21% ', ' 67,466 ', ' 268 ', ' 11,610 ', ' 36,288 ', ' 1.7 ', ' 33.5 ', ' 96.6% ', ' 0.038% ']
[' 138 ', ' Namibia ', ' 3,092,816 ', ' 2.07% ', ' 62,685 ', ' 4 ', ' 823,290 ', ' 1,866 ', ' 3.17 ', ' 21.3 ', ' 54.4% ', ' 0.038% ']
[' 139 ', ' Moldova ', ' 2,996,106 ', ' −1.28% ', ' −38,855 ', ' 91 ', ' 32,850 ', ' −29,766 ', ' 1.72 ', ' 38.6 ', ' 57.7% ', ' 0.036% ']
[' 140 ', ' Armenia ', ' 2,952,365 ', ' −0.72% ', ' −21,475 ', ' 104 ', ' 28,470 ', ' −29,013 ', ' 1.71 ', ' 36.6 ', ' 63.8% ', ' 0.036% ']
[' 141 ', ' Jamaica ', ' 2,837,077 ', ' −0.07% ', ' −2,098 ', ' 262 ', ' 10,830 ', ' −11,053 ', ' 1.34 ', ' 32.8 ', ' 60.2% ', ' 0.034% ']
[' 142 ', ' Lithuania ', ' 2,830,144 ', ' −1.01% ', ' −28,966 ', ' 45 ', ' 62,674 ', ' −24,618 ', ' 1.22 ', ' 42.3 ', ' 68.2% ', ' 0.034% ']
[' 143 ', ' Gambia ', ' 2,822,093 ', ' 2.25% ', ' 62,105 ', ' 279 ', ' 10,120 ', ' −2,984 ', ' 3.8 ', ' 18.6 ', ' 61.3% ', ' 0.034% ']

In [76]:
import pandas as pd

In [77]:
df = pd.DataFrame(data=total_data[1:], columns=columns)
df

,#,Country (ordependency),Population(2025),YearlyChange,NetChange,Density(P/Km²),Land Area(Km²),Migrants(net),Fert.Rate,MedianAge,UrbanPop %,WorldShare
0,1,India,"1,463,865,525",0.89%,"12,929,734",492,"2,973,190","−495,753",1.94,28.8,37.1%,17.78%
1,2,China,"1,416,096,094",−0.23%,"−3,225,184",151,"9,388,211","−268,126",1.02,40.1,67.5%,17.20%
2,3,United States,"347,275,807",0.54%,"1,849,236",38,"9,147,420","1,230,663",1.62,38.5,82.8%,4.22%
3,4,Indonesia,"285,721,236",0.79%,"2,233,305",158,"1,811,570","−39,509",2.1,30.4,59.6%,3.47%
4,5,Pakistan,"255,219,554",1.57%,"3,950,390",331,"770,880","−1,235,336",3.5,20.6,34.4%,3.10%
...,...,...,...,...,...,...,...,...,...,...,...,...
228,229,Montserrat,"4,359",−0.68%,−30,44,100,−9,1.45,41.6,11.5%,0.000053%
229,230,Falkland Islands,"3,469",−0.03%,−1,0,"12,170",−17,1.7,42.8,68%,0.000042%
230,231,Tokelau,"2,608",4.07%,102,261,10,53,2.57,27.3,,0.000032%
231,232,Niue,"1,821",0.11%,2,7,260,3,2.46,35.7,44.5%,0.000022%
232,233,Holy See,501,1.01%,5,"1,253",0,13,1,57.4,,0.0000061%

In [78]:
df = df.set_index(keys='#')
df

,Country (ordependency),Population(2025),YearlyChange,NetChange,Density(P/Km²),Land Area(Km²),Migrants(net),Fert.Rate,MedianAge,UrbanPop %,WorldShare
#,,,,,,,,,,,
1,India,"1,463,865,525",0.89%,"12,929,734",492,"2,973,190","−495,753",1.94,28.8,37.1%,17.78%
2,China,"1,416,096,094",−0.23%,"−3,225,184",151,"9,388,211","−268,126",1.02,40.1,67.5%,17.20%
3,United States,"347,275,807",0.54%,"1,849,236",38,"9,147,420","1,230,663",1.62,38.5,82.8%,4.22%
4,Indonesia,"285,721,236",0.79%,"2,233,305",158,"1,811,570","−39,509",2.1,30.4,59.6%,3.47%
5,Pakistan,"255,219,554",1.57%,"3,950,390",331,"770,880","−1,235,336",3.5,20.6,34.4%,3.10%
...,...,...,...,...,...,...,...,...,...,...,...
229,Montserrat,"4,359",−0.68%,−30,44,100,−9,1.45,41.6,11.5%,0.000053%
230,Falkland Islands,"3,469",−0.03%,−1,0,"12,170",−17,1.7,42.8,68%,0.000042%
231,Tokelau,"2,608",4.07%,102,261,10,53,2.57,27.3,,0.000032%
232,Niue,"1,821",0.11%,2,7,260,3,2.46,35.7,44.5%,0.000022%
233,Holy See,501,1.01%,5,"1,253",0,13,1,57.4,,0.0000061%

In [ ]:
df.to_csv('World_Population_Scraped.csv', index=False)