<span style='color:red'>

# PANDAS SERIES AND DATAFRAMES

</span>

---

<span style='color:red'>
    
# 1. Series and DataFrame Introduction
    
</span>

<span style='color:red'>
    
## 1.1. Series
    
</span>

---

<div style='background-color:lightgray; padding:15px;'>

<span style='color:green'>

A Series is essentially a one-dimensional labeled array that can hold data of any type (integers, floats, strings, etc.). It is similar to a column in a spreadsheet or a single column of data in a database table. A Series has two main components:

 - **Data**: This is a NumPy array that holds the actual values or elements of the Series.
 
 
 - **Index**: This is a label or identifier for each element in the Series. By default, it is a sequence of integers from 0 to N-1, where N is the length of the Series. However, you can customize the index to be any set of labels, such as strings or dates, making Series highly versatile.

</div>

---

---

<span style='color:red'>
    
## 1.2. DataFrame
    
</span>

---

<div style='background-color:lightgray; padding:15px;'>

<span style='color:green'>

A DataFrame is a two-dimensional tabular data structure in pandas. It is similar to a spreadsheet or a SQL table. It consists of rows and columns, where each column is a Series. DataFrames are incredibly powerful and flexible for handling and analyzing structured data. Key features of a DataFrame include:

 - **Rows and Columns**: Rows represent individual records or observations, while columns represent variables or attributes.

 - **Index**: DataFrames have both row and column indexes, which can be customized. The column index is also known as column labels.

 - **Heterogeneous Data**: Each column in a DataFrame can contain data of different types, including integers, floats, strings, or even other complex data structures.

</div>

---

<span style='color:red'>

# 2. NUMPY ARRAYS AND PANDAS SERIES

</span>

<span style='color:red'>
    
## 2.1. NumPy Array
    
</span>

---

<div style='background-color:lightgray; padding:15px;'>

<span style='color:green'>
    
 * NumPy arrays are homogeneous, which means they can only store data of a single data type (e.g., integers, floats). This uniformity in data type allows for more efficient computation.

 * NumPy arrays are essential for performing mathematical and logical operations on large datasets and are commonly used in scientific computing, data analysis, and machine learning.

 * You can create a NumPy array from a Python list or other iterable.

</div>

---

<span style='color:red'>
    
## 2.2. Pandas Series
    
</span>

---

<div style='background-color:lightgray; padding:15px;'>

<span style='color:green'>
    
 * A pandas Series is essentially a one-dimensional array, similar to a NumPy array. However, it includes an index that labels each element in the Series, making it possible to access data using these labels.

 * Pandas Series can store data of different types (*integers, floats, strings*) within the same Series. This allows for greater flexibility when dealing with real-world datasets.

 * Series are commonly used in data preprocessing and analysis, as well as in time series data, and they can be used as columns in pandas DataFrames.

</div>

---

In [1]:
import numpy as np
import pandas as pd

---

<span style='color:orange'>
    
**I will start working with NumPy...**


---

In [2]:
my_list = [10, 25, 35]

In [3]:
x = np.array(my_list)
print(x)  # the index is implied on this np.array

[10 25 35]

In [4]:
x

array([10, 25, 35])

In [5]:
type(x)

numpy.ndarray

---

<span style='color:orange'>

    
**Now it's time to start working with Pandas Series...**

---

In [6]:
y = pd.Series(my_list)  # Here the index is placed at the left column

print(y)

0    10
1    25
2    35
dtype: int64

In [7]:
type(y)

pandas.core.series.Series

In [8]:
index_values = ['Best', '2nd Best', '3rd Best']

my_list = [10, 25, 35]

In [9]:
one = pd.Series(data=my_list, index=index_values)
one

Best        10
2nd Best    25
3rd Best    35
dtype: int64

In [10]:
index_values2 = ['Best', '2nd Best', '4th Best']
my_list2 = [10, 30, 40]

two = pd.Series(data=my_list2, index=index_values2)
two

Best        10
2nd Best    30
4th Best    40
dtype: int64

In [11]:
total = one + two
total

2nd Best    55.0
3rd Best     NaN
4th Best     NaN
Best        20.0
dtype: float64

In [12]:
total['Best']

np.float64(20.0)

In [13]:
total.iloc[0]

np.float64(55.0)

In [14]:
type(total)

pandas.core.series.Series

---

<span style='color:red'>
    
## 2.3. Pandas DataFrames
    
</span>

---

In [15]:
import pandas as pd

index_values = ['Best', '2nd Best', '3rd Best']
my_list = [10, 25, 35]

one = pd.Series(data=my_list, index=index_values)
one

Best        10
2nd Best    25
3rd Best    35
dtype: int64

In [16]:
index_values2 = ['Best', '2nd Best', '4th Best']
my_list2 = [10, 25, 40]

two = pd.Series(data=my_list2, index=index_values2)
two

Best        10
2nd Best    25
4th Best    40
dtype: int64

In [17]:
df = pd.DataFrame(data={'Series 1':one, 'Series 2':two})
df

          Series 1  Series 2
2nd Best      25.0      25.0
3rd Best      35.0       NaN
4th Best       NaN      40.0
Best          10.0      10.0

In [18]:
ice_cream = [['MCC', 1], ['Butterscoth', 2], ['Butter Pecan', 3]]

In [19]:
pd.DataFrame(data=ice_cream, index=['Flavor 1', 'Flavor 2', 'Flavor 3'], columns=('Flavor', 'Scoops'))

                Flavor  Scoops
Flavor 1           MCC       1
Flavor 2   Butterscoth       2
Flavor 3  Butter Pecan       3

In [20]:
pd.DataFrame(data=ice_cream, columns=('Flavor', 'Scoops'))

         Flavor  Scoops
0           MCC       1
1   Butterscoth       2
2  Butter Pecan       3

In [21]:
pd.DataFrame(data=ice_cream)

              0  1
0           MCC  1
1   Butterscoth  2
2  Butter Pecan  3