---
---
---

<span style='color:red'>

# WORKING WITH FILES

</span>

---
---
---

---
---
---
<span style='color:red'>

# 1. IMPORTING `CSV` FILES

</span>

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('datasets/parks_and_recreation.csv')
df

    employee_id    first_name     last_name   age  gender  birth_date
0             1        Leslie         Knope  44.0  Female   9/25/1979
1             3           Tom     Haverford  36.0    Male    3/4/1987
2             4         April       Ludgate  29.0  Female   3/27/1994
3             6         Donna        Meagle  46.0  Female   7/30/1977
4             7           Ann       Perkins  35.0  Female   12/1/1988
5             8         Chris       Traeger  43.0    Male  11/11/1980
6             9           Ben         Wyatt  38.0    Male   7/26/1985
7            10          Andy         Dwyer  34.0    Male   3/25/1989
8            11          Mark  Brendanawicz  40.0    Male   6/14/1983
9            12         Craig  Middlebrooks  37.0    Male   7/27/1986
10           13  Jean-Ralphio    Saperstein   NaN     NaN         NaN

In [ ]:
df1 = pd.read_csv('datasets/parks_and_recreation.tsv')
df1

   employee_id\tfirst_name\tlast_name\tage\tgender\tbirth_date
0             1\tLeslie\tKnope\t44\tFemale\t9/25/1979
1               3\tTom\tHaverford\t36\tMale\t3/4/1987
2            4\tApril\tLudgate\t29\tFemale\t3/27/1994
3             6\tDonna\tMeagle\t46\tFemale\t7/30/1977
4              7\tAnn\tPerkins\t35\tFemale\t12/1/1988
5             8\tChris\tTraeger\t43\tMale\t11/11/1980
6                  9\tBen\tWyatt\t38\tMale\t7/26/1985
7                10\tAndy\tDwyer\t34\tMale\t3/25/1989
8         11\tMark\tBrendanawicz\t40\tMale\t6/14/1983
9        12\tCraig\tMiddlebrooks\t37\tMale\t7/27/1986
10     13\tJean-Ralphio\tSaperstein\tNULL\tNULL\tNULL

In [ ]:
df1 = pd.read_csv('datasets/parks_and_recreation.tsv', sep='\t')
df1

    employee_id    first_name     last_name   age  gender  birth_date
0             1        Leslie         Knope  44.0  Female   9/25/1979
1             3           Tom     Haverford  36.0    Male    3/4/1987
2             4         April       Ludgate  29.0  Female   3/27/1994
3             6         Donna        Meagle  46.0  Female   7/30/1977
4             7           Ann       Perkins  35.0  Female   12/1/1988
5             8         Chris       Traeger  43.0    Male  11/11/1980
6             9           Ben         Wyatt  38.0    Male   7/26/1985
7            10          Andy         Dwyer  34.0    Male   3/25/1989
8            11          Mark  Brendanawicz  40.0    Male   6/14/1983
9            12         Craig  Middlebrooks  37.0    Male   7/27/1986
10           13  Jean-Ralphio    Saperstein   NaN     NaN         NaN

In [ ]:
df2 = pd.read_csv('datasets/parks_and_recreation.csv', header=None)
df2

              0             1             2    3       4           5
0   employee_id    first_name     last_name  age  gender  birth_date
1             1        Leslie         Knope   44  Female   9/25/1979
2             3           Tom     Haverford   36    Male    3/4/1987
3             4         April       Ludgate   29  Female   3/27/1994
4             6         Donna        Meagle   46  Female   7/30/1977
5             7           Ann       Perkins   35  Female   12/1/1988
6             8         Chris       Traeger   43    Male  11/11/1980
7             9           Ben         Wyatt   38    Male   7/26/1985
8            10          Andy         Dwyer   34    Male   3/25/1989
9            11          Mark  Brendanawicz   40    Male   6/14/1983
10           12         Craig  Middlebrooks   37    Male   7/27/1986
11           13  Jean-Ralphio    Saperstein  NaN     NaN         NaN

In [ ]:
df3 = pd.read_csv('datasets/parks_and_recreation.csv', index_col='employee_id')
df3

               first_name     last_name   age  gender  birth_date
employee_id
1                  Leslie         Knope  44.0  Female   9/25/1979
3                     Tom     Haverford  36.0    Male    3/4/1987
4                   April       Ludgate  29.0  Female   3/27/1994
6                   Donna        Meagle  46.0  Female   7/30/1977
7                     Ann       Perkins  35.0  Female   12/1/1988
8                   Chris       Traeger  43.0    Male  11/11/1980
9                     Ben         Wyatt  38.0    Male   7/26/1985
10                   Andy         Dwyer  34.0    Male   3/25/1989
11                   Mark  Brendanawicz  40.0    Male   6/14/1983
12                  Craig  Middlebrooks  37.0    Male   7/27/1986
13           Jean-Ralphio    Saperstein   NaN     NaN         NaN

In [ ]:
df4 = pd.read_csv('datasets/parks_and_recreation.csv', index_col='employee_id',
                  usecols=['employee_id', 'first_name', 'last_name'])
df4

               first_name     last_name
employee_id
1                  Leslie         Knope
3                     Tom     Haverford
4                   April       Ludgate
6                   Donna        Meagle
7                     Ann       Perkins
8                   Chris       Traeger
9                     Ben         Wyatt
10                   Andy         Dwyer
11                   Mark  Brendanawicz
12                  Craig  Middlebrooks
13           Jean-Ralphio    Saperstein

---

<span style='color:orange'>
    
**Sometimes there are CSV files that has no format like the following...**

---

<center><img src='Images/01.png' width=750></center>

---

<span style='color:orange'>
    
If we want to open this files, we will get this...

---

In [ ]:
df5 = pd.read_csv('datasets/parks_and_recreation_strange_data.csv')
df5

,This is our Data,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,Leslie,Knope,44.0,Female,9/25/1979
3,3.0,Tom,Haverford,36.0,Male,3/4/1987
4,4.0,April,Ludgate,29.0,Female,3/27/1994
5,6.0,Donna,Meagle,46.0,Female,7/30/1977
6,7.0,Ann,Perkins,35.0,Female,12/1/1988
7,8.0,Chris,Traeger,43.0,Male,11/11/1980
8,9.0,Ben,Wyatt,38.0,Male,7/26/1985
9,10.0,Andy,Dwyer,34.0,Male,3/25/1989
10,11.0,Mark,Brendanawicz,40.0,Male,6/14/1983
11,12.0,Craig,Middlebrooks,37.0,Male,7/27/1986
12,13.0,Jean-Ralphio,Saperstein,NaN,NaN,NaN

---

<span style='color:orange'>
    
... in order to fix this issues we can open this types files following this steps...

---

In [ ]:
df6 = pd.read_csv('datasets/parks_and_recreation_strange_data.csv', skiprows=[0, 1, 2])
df6

    1        Leslie         Knope    44  Female   9/25/1979
0   3           Tom     Haverford  36.0    Male    3/4/1987
1   4         April       Ludgate  29.0  Female   3/27/1994
2   6         Donna        Meagle  46.0  Female   7/30/1977
3   7           Ann       Perkins  35.0  Female   12/1/1988
4   8         Chris       Traeger  43.0    Male  11/11/1980
5   9           Ben         Wyatt  38.0    Male   7/26/1985
6  10          Andy         Dwyer  34.0    Male   3/25/1989
7  11          Mark  Brendanawicz  40.0    Male   6/14/1983
8  12         Craig  Middlebrooks  37.0    Male   7/27/1986
9  13  Jean-Ralphio    Saperstein   NaN     NaN         NaN

In [ ]:
df7 = pd.read_csv('datasets/parks_and_recreation_strange_data.csv', skiprows=[0, 1, 2], header=None)
df7

     0             1             2     3       4           5
0    1        Leslie         Knope  44.0  Female   9/25/1979
1    3           Tom     Haverford  36.0    Male    3/4/1987
2    4         April       Ludgate  29.0  Female   3/27/1994
3    6         Donna        Meagle  46.0  Female   7/30/1977
4    7           Ann       Perkins  35.0  Female   12/1/1988
5    8         Chris       Traeger  43.0    Male  11/11/1980
6    9           Ben         Wyatt  38.0    Male   7/26/1985
7   10          Andy         Dwyer  34.0    Male   3/25/1989
8   11          Mark  Brendanawicz  40.0    Male   6/14/1983
9   12         Craig  Middlebrooks  37.0    Male   7/27/1986
10  13  Jean-Ralphio    Saperstein   NaN     NaN         NaN

---

<span style='color:orange'>
    
This time we got as the header the first row of data, so we need to fix this issue...

---

In [ ]:
df8 = pd.read_csv('datasets/parks_and_recreation_strange_data.csv', skiprows=[0,1,2],
                  names=['employee_id', 'first_name', 'last_name', 'age', 'gender', 'birth_date'])
df8

    employee_id    first_name     last_name   age  gender  birth_date
0             1        Leslie         Knope  44.0  Female   9/25/1979
1             3           Tom     Haverford  36.0    Male    3/4/1987
2             4         April       Ludgate  29.0  Female   3/27/1994
3             6         Donna        Meagle  46.0  Female   7/30/1977
4             7           Ann       Perkins  35.0  Female   12/1/1988
5             8         Chris       Traeger  43.0    Male  11/11/1980
6             9           Ben         Wyatt  38.0    Male   7/26/1985
7            10          Andy         Dwyer  34.0    Male   3/25/1989
8            11          Mark  Brendanawicz  40.0    Male   6/14/1983
9            12         Craig  Middlebrooks  37.0    Male   7/27/1986
10           13  Jean-Ralphio    Saperstein   NaN     NaN         NaN

---
---
---

<span style='color:red'>

# 2. IMMPORTING DIFFERENT FILE TYPES

</span>

---
---
<span style='color:red'>

## 2.1. Reading a `JSON` File

</span>

---

In [ ]:
df_json = pd.read_json('datasets/parks_and_recreation.json')
df_json

    employee_id    first_name     last_name   age  gender  birth_date
0             1        Leslie         Knope  44.0  Female   9/25/1979
1             3           Tom     Haverford  36.0    Male    3/4/1987
2             4         April       Ludgate  29.0  Female   3/27/1994
3             6         Donna        Meagle  46.0  Female   7/30/1977
4             7           Ann       Perkins  35.0  Female   12/1/1988
5             8         Chris       Traeger  43.0    Male  11/11/1980
6             9           Ben         Wyatt  38.0    Male   7/26/1985
7            10          Andy         Dwyer  34.0    Male   3/25/1989
8            11          Mark  Brendanawicz  40.0    Male   6/14/1983
9            12         Craig  Middlebrooks  37.0    Male   7/27/1986
10           13  Jean-Ralphio    Saperstein   NaN    None        None

In [ ]:
df_json2 = pd.read_csv('datasets/parks_and_recreation.json')  # ERROR MESSAGE!!!
df_json2

ParserError: Error tokenizing data. C error: Expected 1 fields in line 3, saw 2

---
---

<span style='color:red'>

## 2.2. Reading a `TXT` File

</span>

---

In [ ]:
df_txt = pd.read_table('datasets/parks_and_recreation.txt')
df_txt

    employee_id    first_name     last_name   age  gender  birth_date
0             1        Leslie         Knope  44.0  Female   9/25/1979
1             3           Tom     Haverford  36.0    Male    3/4/1987
2             4         April       Ludgate  29.0  Female   3/27/1994
3             6         Donna        Meagle  46.0  Female   7/30/1977
4             7           Ann       Perkins  35.0  Female   12/1/1988
5             8         Chris       Traeger  43.0    Male  11/11/1980
6             9           Ben         Wyatt  38.0    Male   7/26/1985
7            10          Andy         Dwyer  34.0    Male   3/25/1989
8            11          Mark  Brendanawicz  40.0    Male   6/14/1983
9            12         Craig  Middlebrooks  37.0    Male   7/27/1986
10           13  Jean-Ralphio    Saperstein   NaN     NaN         NaN

In [ ]:
df_txt2 = pd.read_csv('datasets/parks_and_recreation.txt')
df_txt2

   employee_id\tfirst_name\tlast_name\tage\tgender\tbirth_date
0             1\tLeslie\tKnope\t44\tFemale\t9/25/1979
1               3\tTom\tHaverford\t36\tMale\t3/4/1987
2            4\tApril\tLudgate\t29\tFemale\t3/27/1994
3             6\tDonna\tMeagle\t46\tFemale\t7/30/1977
4              7\tAnn\tPerkins\t35\tFemale\t12/1/1988
5             8\tChris\tTraeger\t43\tMale\t11/11/1980
6                  9\tBen\tWyatt\t38\tMale\t7/26/1985
7                10\tAndy\tDwyer\t34\tMale\t3/25/1989
8         11\tMark\tBrendanawicz\t40\tMale\t6/14/1983
9        12\tCraig\tMiddlebrooks\t37\tMale\t7/27/1986
10     13\tJean-Ralphio\tSaperstein\tNULL\tNULL\tNULL

---

<span style='color:orange'>

We can also **read a CSV file** from `pd.read_table` command, take a look at the following piece of code

---

In [ ]:
df_txt_csv = pd.read_table('datasets/parks_and_recreation.csv', sep=',')
df_txt_csv

    employee_id    first_name     last_name   age  gender  birth_date
0             1        Leslie         Knope  44.0  Female   9/25/1979
1             3           Tom     Haverford  36.0    Male    3/4/1987
2             4         April       Ludgate  29.0  Female   3/27/1994
3             6         Donna        Meagle  46.0  Female   7/30/1977
4             7           Ann       Perkins  35.0  Female   12/1/1988
5             8         Chris       Traeger  43.0    Male  11/11/1980
6             9           Ben         Wyatt  38.0    Male   7/26/1985
7            10          Andy         Dwyer  34.0    Male   3/25/1989
8            11          Mark  Brendanawicz  40.0    Male   6/14/1983
9            12         Craig  Middlebrooks  37.0    Male   7/27/1986
10           13  Jean-Ralphio    Saperstein   NaN     NaN         NaN

---
---


<span style='color:red'>

## 2.3. Reading an `EXCEL` File

</span>

---



<center><img src='Images/02.png' width=780></center>

---

In [ ]:
# !pip install openpyxl

In [ ]:
df_xlsx = pd.read_excel('datasets/parks_and_recreation.xlsx', sheet_name='demographics')
df_xlsx

    employee_id    first_name     last_name   age  gender birth_date
0             1        Leslie         Knope  44.0  Female 1979-09-25
1             3           Tom     Haverford  36.0    Male 1987-03-04
2             4         April       Ludgate  29.0  Female 1994-03-27
3             6         Donna        Meagle  46.0  Female 1977-07-30
4             7           Ann       Perkins  35.0  Female 1988-12-01
5             8         Chris       Traeger  43.0    Male 1980-11-11
6             9           Ben         Wyatt  38.0    Male 1985-07-26
7            10          Andy         Dwyer  34.0    Male 1989-03-25
8            11          Mark  Brendanawicz  40.0    Male 1983-06-14
9            12         Craig  Middlebrooks  37.0    Male 1986-07-27
10           13  Jean-Ralphio    Saperstein   NaN     NaN        NaT

---
---
---

<span style='color:green'>

# 3. CONNECTING TO A DATABASE

</span>

---
---

In [ ]:
# !pip install mysql-connector-python

---

If this is the first time we are going to use a mySQL data base, then we first need to install `mysql-connector`. So let's follow the next steps.

<center><img src='Images/03.png' width=750></center>

---

In [ ]:
import pandas as pd
import mysql.connector

---

<span style='color:orange'>

We need to configure the `users and privileges` of **MySQL**. by typing the next code...


---

In [ ]:
connect = mysql.connector.connect(
host= 'localhost',
user = 'root',
password = 'MV_SQL&AnBuild=13-Jun-2024',
database = 'bakery'
)

---

<span style='color:orange'>
    
...The next step is to **write a `query`* of the database we want to read...

---

In [ ]:
query = 'SELECT * FROM bakery.customers'

---

<span style='color:orange'>

**Now we are all set to call the database from `MySQL`...**

---

In [ ]:
pd.read_sql(query, connect)

C:\Users\Milton Valle_Pro\AppData\Local\Temp\ipykernel_19760\3034383182.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, connect)

,customer_id,first_name,last_name,birth_date,phone,address,city,state,total_money_spent
0,100101,Kevin,Malone,1989-04-28,635-573-9754,1229 Main Street,Scranton,PA,11000
1,100102,Charles,Xavier,1965-04-11,729-287-9456,123 North Hill Drive,Dallas,TX,947
2,100103,Finley,Danish,1999-02-07,126-583-7856,432 Hilly Road,Austin,TX,534
3,100104,Obi,Kenobi,1921-04-22,975-357-7663,101 Alpine Avenue,New York,NY,3567
4,100105,Don,Draper,1948-11-07,None,12 South Main Lane,San Francisco,CA,195
5,100106,Frodo,Baggins,2001-09-04,None,1 Pastery Lane,Chicago,IL,56
6,100107,Michael,Scott,1978-08-20,235-357-3464,987 Croissant Street,Scranton,PA,2536
7,100108,Maggie,Muffin,2001-07-06,906-485-1542,701 North Street,Sarasota,FL,1009
8,100109,Kelly,Kapoor,1987-05-30,674-357-9151,62810 Julip Lane,Scranton,PA,540
9,100110,Anakin,Skywalker,1934-10-15,346-458-3370,122 South Street,Charleston,SC,36

---

<span style='color:orange'>
    
When we will finish working with the database read from `MySQL`. It's very important to **CLOSE THE CONECTION** in order to avoid spending unnecesarily memory of our computer...

---

In [ ]:
connect.close()

---

---
---
---

<span style='color:red'>

# 4. EXPORTING DATA

</span>

---
---

In [ ]:
import pandas as pd

In [ ]:
df9 = pd.read_csv('datasets/parks_and_recreation.csv')
df9

    employee_id    first_name     last_name   age  gender  birth_date
0             1        Leslie         Knope  44.0  Female   9/25/1979
1             3           Tom     Haverford  36.0    Male    3/4/1987
2             4         April       Ludgate  29.0  Female   3/27/1994
3             6         Donna        Meagle  46.0  Female   7/30/1977
4             7           Ann       Perkins  35.0  Female   12/1/1988
5             8         Chris       Traeger  43.0    Male  11/11/1980
6             9           Ben         Wyatt  38.0    Male   7/26/1985
7            10          Andy         Dwyer  34.0    Male   3/25/1989
8            11          Mark  Brendanawicz  40.0    Male   6/14/1983
9            12         Craig  Middlebrooks  37.0    Male   7/27/1986
10           13  Jean-Ralphio    Saperstein   NaN     NaN         NaN

---
---

<span style='color:red'>

## 4.1. Exporting a `CSV` File

</span>

---

---

<span style='color:orange'>
    
In order to export a DataFrame we only need to use the command **`to_csv`**. As we show in the following code

---

In [ ]:
# this line of code exports the whole DataFrame
df9.to_csv('Exports/My_csv_file.csv', index=False)

In [ ]:
# This new line of code exports only the columns 'first_name' and 'last_name'
df9.to_csv('Exports/My_reduced_csv_file.csv', index=False, columns=['first_name', 'last_name'])

---
---

<span style='color:red'>

## 4.2. Exporting a `XLSX` File

</span>

---

In [ ]:
df9.to_excel('Exports/My_excel.xlsx', index=False, sheet_name='Employees')

---
---

<span style='color:red'>

## 4.3. Exporting a `JSON` File

</span>

---

In [ ]:
df9.to_json('Exports/My_json_file.json')