<span style='color:red'>

# TITLE: `GROUP BY AND AGGREGATING`

</span>

---
---
---

<span style='color:red'>

# 1. GROUP BY AND AGGREGATIONS INTRODUCTION

---
---

<span style='color:red'>

## 1.1. Grouping in Pandas

</span>

---

<div style='background-color:lightgray; padding:15px;'>

<span style='color:green'>

1. **Definition:**

    * Grouping involves dividing a DataFrame into groups based on values in one or more columns.

2. **Key Components:**

    * **Grouping Column(s):** The column(s) used to define the groups.
  
    * **GroupBy Object:** The result of the grouping operation, representing the grouped data.

3. **GroupBy Object:**

    * Acts as an intermediary that allows you to apply various aggregation functions on each group.

</div>

---

---
---

<span style='color:red'>
    
## 1.2. Aggregations in Pandas

</span>

---

<div style='background-color:lightgray; padding:15px;'>

<span style='color:green'>
    
1. **Definition:**

    * Aggregations involve performing a calculation on a group of data points, resulting in a single aggregated value.


2. **Common Aggregation Functions:**

    * **Sum:** Computes the sum of values in a group.
  
    * **Mean (Average):** Computes the mean or average of values in a group.
  
    * **Count:** Counts the number of non-null values in a group.
  
    * **Min and Max:** Find the minimum and maximum values in a group.
  
    * **Custom Functions:** You can apply custom aggregation functions.
  


</div>

---

---
---
---

<span style='color:red'>

# 2. BASICS OF GROUP BY

---

In [3]:
import pandas as pd

In [ ]:
df = pd.read_csv('datasets/banking.csv')
df.info()

In [ ]:
df

In [ ]:
df.groupby(by='marital')[['age', 'outstanding_balance']].sum()

In [ ]:
df.groupby(by='job')['age'].mean().reset_index()

In [ ]:
df.groupby('job').describe()

---
---
---

<span style='color:red'>

# 2. AGGREGATIONS WITH GROUP BY

---

In [ ]:
df = pd.read_csv('datasets/banking.csv')
df.info()

In [ ]:
df

In [ ]:
df.groupby(by='education')['outstanding_balance'].min()

In [ ]:
df.groupby(by='education')['outstanding_balance'].max()

In [ ]:
df.groupby(by='education')['outstanding_balance'].mean()

In [ ]:
df.groupby(by='education')['outstanding_balance'].sum().sort_values(ascending=False)

In [ ]:
df.groupby(by='education')['outstanding_balance'].count().sort_values(ascending=False)

In [ ]:
df.groupby(by='education')['outstanding_balance'].median().sort_values(ascending=False)

In [ ]:
output = df.groupby(by='education').agg({'outstanding_balance':['sum', 'count', 'mean', 'median', 'min', 'max']})
output

---

<span style='color:orange'>

**SOMETHING TO REMEMBER:**

TAKE A LOOK AT THE CALCULATION FORMAT OF THE "AVERAGE" COLUMN. **`IT'S SOMETHING NEW TO LEARN`**

---

In [ ]:
output['average'] = ((output['outstanding_balance']['sum']) / (output['outstanding_balance']['count'])) * 100
output.sort_values(by='average', ascending=False)

---

<span style='color:orange'>

**SOMETHING TO REMEMBER:**

TAKE A LOOK AT THE RENAMING OF THE COLUMNS FORMAT. **`IT'S SOMETHING NEW TO LEARN TOO.`**

---

In [ ]:
df.groupby(by='education').agg(sum_balance = ('outstanding_balance', 'sum'), count_balance = ('outstanding_balance', 'count'))

---
---
---

<span style='color:red'>

# 3. GROUP BY ON MULTIPLE COLUMNS

---

In [ ]:
df = pd.read_csv('datasets/banking.csv')
df

In [ ]:
df.groupby(by=['job', 'marital'])['outstanding_balance'].sum()

In [ ]:
df.groupby(by=['job', 'marital'])['outstanding_balance'].sum().reset_index()

In [ ]:
df[df['job'] == 'management'].groupby(by=['job', 'marital'])['outstanding_balance'].sum().reset_index()

In [ ]:
df.groupby(by=['education', 'personal_loan'])['outstanding_balance'].mean()

In [ ]:
new_df = df.groupby(by=['education', 'personal_loan'])['outstanding_balance'].mean().reset_index()
new_df

---
---
---

<span style='color:red'>

# 4. TRANSFORM WITH GROUP BY **

---

In [4]:
df = pd.read_csv('datasets/banking.csv')

In [5]:
sub_df = df[:500]
sub_df

,age,job,marital,education,default,outstanding_balance,housing_loan,personal_loan
0,58,management,married,tertiary,no,2143,yes,no
1,44,technician,single,secondary,no,29,yes,no
2,33,entrepreneur,married,secondary,no,2,yes,yes
3,47,blue-collar,married,unknown,no,1506,yes,no
4,33,unknown,single,unknown,no,1,no,no
...,...,...,...,...,...,...,...,...
495,39,admin.,single,secondary,no,0,yes,no
496,39,blue-collar,divorced,secondary,no,42,yes,no
497,50,blue-collar,divorced,secondary,no,41,yes,no
498,44,blue-collar,married,secondary,no,-99,yes,no
499,37,technician,single,secondary,no,17,yes,no

---

<span style='color:orange'>

**SOMETHING TO REMEMBER:**

Using the TRANSFORM method, we can fill a new column with the information generated with the "groupby", take a look in the cell behind

</span>

---

In [6]:
sub_df['avergage_balance_per_job'] = sub_df.groupby(by='job')['outstanding_balance'].transform('mean')
sub_df

/tmp/ipython-input-1589393360.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_df['avergage_balance_per_job'] = sub_df.groupby(by='job')['outstanding_balance'].transform('mean')

,age,job,marital,education,default,outstanding_balance,housing_loan,personal_loan,avergage_balance_per_job
0,58,management,married,tertiary,no,2143,yes,no,1082.815789
1,44,technician,single,secondary,no,29,yes,no,1121.407407
2,33,entrepreneur,married,secondary,no,2,yes,yes,299.714286
3,47,blue-collar,married,unknown,no,1506,yes,no,423.521429
4,33,unknown,single,unknown,no,1,no,no,18.666667
...,...,...,...,...,...,...,...,...,...
495,39,admin.,single,secondary,no,0,yes,no,235.300000
496,39,blue-collar,divorced,secondary,no,42,yes,no,423.521429
497,50,blue-collar,divorced,secondary,no,41,yes,no,423.521429
498,44,blue-collar,married,secondary,no,-99,yes,no,423.521429
499,37,technician,single,secondary,no,17,yes,no,1121.407407

---

<div style='background-color:lightgray; padding:15px;'>
    
<span style='color:orange'>**SOMETHING TO REMEMBER:**</span>

<span style='color:brown'>
    
Trying to obtain the same result, without using the TRANSFORM method will led us to a failed creation of a new column. Take a look a the cell below...</span>

<span style='color:green'>

This problem happens because with the code below we only are producing 12 data rows. And there is no way to establish a relationship with the new column we want to create within the DataFrame "sub_df".

</span>

</div>
---

In [7]:
sub_df['average_balance_per_job2'] = sub_df.groupby(by='job')['outstanding_balance'].mean()
sub_df

/tmp/ipython-input-4268069329.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_df['average_balance_per_job2'] = sub_df.groupby(by='job')['outstanding_balance'].mean()

,age,job,marital,education,default,outstanding_balance,housing_loan,personal_loan,avergage_balance_per_job,average_balance_per_job2
0,58,management,married,tertiary,no,2143,yes,no,1082.815789,NaN
1,44,technician,single,secondary,no,29,yes,no,1121.407407,NaN
2,33,entrepreneur,married,secondary,no,2,yes,yes,299.714286,NaN
3,47,blue-collar,married,unknown,no,1506,yes,no,423.521429,NaN
4,33,unknown,single,unknown,no,1,no,no,18.666667,NaN
...,...,...,...,...,...,...,...,...,...,...
495,39,admin.,single,secondary,no,0,yes,no,235.300000,NaN
496,39,blue-collar,divorced,secondary,no,42,yes,no,423.521429,NaN
497,50,blue-collar,divorced,secondary,no,41,yes,no,423.521429,NaN
498,44,blue-collar,married,secondary,no,-99,yes,no,423.521429,NaN
499,37,technician,single,secondary,no,17,yes,no,1121.407407,NaN

In [8]:
# This sub-DataFrame is what we are obtaining, on the earlier example...
sub_df.groupby(by='job')['outstanding_balance'].mean()

job
admin.            235.300000
blue-collar       423.521429
entrepreneur      299.714286
housemaid         446.600000
management       1082.815789
retired           330.250000
self-employed      60.363636
services          553.016667
student           164.166667
technician       1121.407407
unemployed        637.100000
unknown            18.666667
Name: outstanding_balance, dtype: float64

---

In [9]:
df = pd.read_csv('datasets/banking.csv')

new_df = df[:500]

new_df['avg_balance_per_job'] = new_df.groupby(by='job')['outstanding_balance'].transform('mean')
new_df

/tmp/ipython-input-3519499679.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['avg_balance_per_job'] = new_df.groupby(by='job')['outstanding_balance'].transform('mean')

,age,job,marital,education,default,outstanding_balance,housing_loan,personal_loan,avg_balance_per_job
0,58,management,married,tertiary,no,2143,yes,no,1082.815789
1,44,technician,single,secondary,no,29,yes,no,1121.407407
2,33,entrepreneur,married,secondary,no,2,yes,yes,299.714286
3,47,blue-collar,married,unknown,no,1506,yes,no,423.521429
4,33,unknown,single,unknown,no,1,no,no,18.666667
...,...,...,...,...,...,...,...,...,...
495,39,admin.,single,secondary,no,0,yes,no,235.300000
496,39,blue-collar,divorced,secondary,no,42,yes,no,423.521429
497,50,blue-collar,divorced,secondary,no,41,yes,no,423.521429
498,44,blue-collar,married,secondary,no,-99,yes,no,423.521429
499,37,technician,single,secondary,no,17,yes,no,1121.407407

---

<span style='color:orange'>

**SOMETHING TO REMEMBER:** Using Lambda Function

</span>

---

In [10]:
new_df['above/below_avg'] = new_df.groupby('job')['outstanding_balance'].transform(lambda x: x - x.mean())
new_df

/tmp/ipython-input-2072236749.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['above/below_avg'] = new_df.groupby('job')['outstanding_balance'].transform(lambda x: x - x.mean())

,age,job,marital,education,default,outstanding_balance,housing_loan,personal_loan,avg_balance_per_job,above/below_avg
0,58,management,married,tertiary,no,2143,yes,no,1082.815789,1060.184211
1,44,technician,single,secondary,no,29,yes,no,1121.407407,-1092.407407
2,33,entrepreneur,married,secondary,no,2,yes,yes,299.714286,-297.714286
3,47,blue-collar,married,unknown,no,1506,yes,no,423.521429,1082.478571
4,33,unknown,single,unknown,no,1,no,no,18.666667,-17.666667
...,...,...,...,...,...,...,...,...,...,...
495,39,admin.,single,secondary,no,0,yes,no,235.300000,-235.300000
496,39,blue-collar,divorced,secondary,no,42,yes,no,423.521429,-381.521429
497,50,blue-collar,divorced,secondary,no,41,yes,no,423.521429,-382.521429
498,44,blue-collar,married,secondary,no,-99,yes,no,423.521429,-522.521429
499,37,technician,single,secondary,no,17,yes,no,1121.407407,-1104.407407

In [ ]:
new_df['avg_balance_with_loan'] = new_df[new_df['housing_loan'] == 'yes'].groupby('job')['outstanding_balance'].transform('mean')
new_df