<span style='color:red'>

# TITLE: `JOINING DATAFRAMES`

</span>

---
---
---

<span style='color:red'>

# 1. JOINS INTRODUCTION

---
---

<span style='color:red'>

## 1.1. Joining DataFrames

</span>

---

<span style='color:green'>
    
1. Jining DataFrames refers to combining two or more DataFrames together into one.

2. There are several different ways to join DataFrames in Pandas: **`concat()`**, **`merge()`** and **`join()`**

</span>

<center><img src='images/04.png' width=720></center>

---

---
---

<span style='color:red'>

## 1.2. concat() Function

</span>



<span style='color:green'>
    
1. **`concat()`** function in pandas concatenates two or more Pandas objects along a particular axis

---

<center><img src='images/05.png' width=720></center>

---

---
---

<span style='color:red'>

## 1.3. merge() Function

</span>



<span style='color:green'>
    
1. **`merge()`** function is more versatile and allows you to merge DataFrames on a key.

2. You can also merge on multiple keys by passing a list of column names.

3. Two main parameters used are **`on`** and **`how`**.

4. **`on`** indicates a common column that the DataFrames will be joined on.

5. **`how`** specifies the kind of join that will be used.

---

<center><img src='images/06.png' width=840></center>

---

---
---

<span style='color:red'>

## 1.4. join() Function

</span>



<span style='color:green'>
    
1. **`join()`** function in Pandas is used to combine columns of two potentially differently-indexed DataFrames into a single result DataFrame.

2. It is equivalent to merge <span style='color:red'>**but operates on indices instead.**

---

<center><img src='images/07.png' width=540></center>

---

---
---
---

<span style='color:red'>

# 2. BASICS OF MERGE AND JOIN

In [1]:
import pandas as pd

In [2]:
data1 = {
    'employee_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'name': ['Michael Scott', 'Jim Halpert', 'Pam Beesly', 'Dwight Schrute', 'Angela Martin', 'Kevin Malone', 'Oscar Martinez', 'Stanley Hudson'],
    'job_title': ['Regional Manager', 'Sales Representative', 'Receptionist', 'Assistant to the Regional Manager', 'Head of Accounting', 'Accountant', 'Accountant', 'Sales Representative'],
    'salary': [100000, 60000, 55000, 65000, 60000, 55000, 55000, 60000]
}

df1 = pd.DataFrame(data1)

data2 = {
    'employee_id': [1, 2, 3, 5, 6, 7, 8, 9],
    'name': ['Michael Scott', 'Jim Halpert', 'Pam Beesly', 'Angela Martin', 'Kevin Malone', 'Oscar Martinez', 'Stanley Hudson', 'Phyllis Vance'],
    'department': ['Management', 'Sales', 'Reception', 'Accounting', 'Accounting', 'Accounting', 'Sales', 'Sales']
}

df2 = pd.DataFrame(data2)

In [3]:
df1

   employee_id            name                          job_title  salary
0            1   Michael Scott                   Regional Manager  100000
1            2     Jim Halpert               Sales Representative   60000
2            3      Pam Beesly                       Receptionist   55000
3            4  Dwight Schrute  Assistant to the Regional Manager   65000
4            5   Angela Martin                 Head of Accounting   60000
5            6    Kevin Malone                         Accountant   55000
6            7  Oscar Martinez                         Accountant   55000
7            8  Stanley Hudson               Sales Representative   60000

In [4]:
df2

   employee_id            name  department
0            1   Michael Scott  Management
1            2     Jim Halpert       Sales
2            3      Pam Beesly   Reception
3            5   Angela Martin  Accounting
4            6    Kevin Malone  Accounting
5            7  Oscar Martinez  Accounting
6            8  Stanley Hudson       Sales
7            9   Phyllis Vance       Sales

---
---

<span style='color:red'>

## 2.1. Use of `merge()` Function

</span>

In [5]:
df1.merge(df2, how='left')

,employee_id,name,job_title,salary,department
0,1,Michael Scott,Regional Manager,100000,Management
1,2,Jim Halpert,Sales Representative,60000,Sales
2,3,Pam Beesly,Receptionist,55000,Reception
3,4,Dwight Schrute,Assistant to the Regional Manager,65000,NaN
4,5,Angela Martin,Head of Accounting,60000,Accounting
5,6,Kevin Malone,Accountant,55000,Accounting
6,7,Oscar Martinez,Accountant,55000,Accounting
7,8,Stanley Hudson,Sales Representative,60000,Sales

In [6]:
df1.merge(df2, how='right')

   employee_id            name             job_title    salary  department
0            1   Michael Scott      Regional Manager  100000.0  Management
1            2     Jim Halpert  Sales Representative   60000.0       Sales
2            3      Pam Beesly          Receptionist   55000.0   Reception
3            5   Angela Martin    Head of Accounting   60000.0  Accounting
4            6    Kevin Malone            Accountant   55000.0  Accounting
5            7  Oscar Martinez            Accountant   55000.0  Accounting
6            8  Stanley Hudson  Sales Representative   60000.0       Sales
7            9   Phyllis Vance                   NaN       NaN       Sales

In [7]:
df1.merge(df2, how='outer')

,employee_id,name,job_title,salary,department
0,1,Michael Scott,Regional Manager,100000.0,Management
1,2,Jim Halpert,Sales Representative,60000.0,Sales
2,3,Pam Beesly,Receptionist,55000.0,Reception
3,4,Dwight Schrute,Assistant to the Regional Manager,65000.0,NaN
4,5,Angela Martin,Head of Accounting,60000.0,Accounting
5,6,Kevin Malone,Accountant,55000.0,Accounting
6,7,Oscar Martinez,Accountant,55000.0,Accounting
7,8,Stanley Hudson,Sales Representative,60000.0,Sales
8,9,Phyllis Vance,NaN,NaN,Sales

In [8]:
df1.merge(df2, how='outer', on='employee_id')

,employee_id,name_x,job_title,salary,name_y,department
0,1,Michael Scott,Regional Manager,100000.0,Michael Scott,Management
1,2,Jim Halpert,Sales Representative,60000.0,Jim Halpert,Sales
2,3,Pam Beesly,Receptionist,55000.0,Pam Beesly,Reception
3,4,Dwight Schrute,Assistant to the Regional Manager,65000.0,NaN,NaN
4,5,Angela Martin,Head of Accounting,60000.0,Angela Martin,Accounting
5,6,Kevin Malone,Accountant,55000.0,Kevin Malone,Accounting
6,7,Oscar Martinez,Accountant,55000.0,Oscar Martinez,Accounting
7,8,Stanley Hudson,Sales Representative,60000.0,Stanley Hudson,Sales
8,9,NaN,NaN,NaN,Phyllis Vance,Sales

In [9]:
df1.merge(df2, how='outer', on=['employee_id', 'name'])

,employee_id,name,job_title,salary,department
0,1,Michael Scott,Regional Manager,100000.0,Management
1,2,Jim Halpert,Sales Representative,60000.0,Sales
2,3,Pam Beesly,Receptionist,55000.0,Reception
3,4,Dwight Schrute,Assistant to the Regional Manager,65000.0,NaN
4,5,Angela Martin,Head of Accounting,60000.0,Accounting
5,6,Kevin Malone,Accountant,55000.0,Accounting
6,7,Oscar Martinez,Accountant,55000.0,Accounting
7,8,Stanley Hudson,Sales Representative,60000.0,Sales
8,9,Phyllis Vance,NaN,NaN,Sales

In [11]:
data3 = {
    'emp_id': [1, 2, 3, 5, 6, 7, 8, 9],
    'name': ['Michael Scott', 'Jim Halpert', 'Pam Beesly', 'Angela Martin', 'Kevin Malone', 'Oscar Martinez', 'Stanley Hudson', 'Phyllis Vance'],
    'department': ['Management', 'Sales', 'Reception', 'Accounting', 'Accounting', 'Accounting', 'Sales', 'Sales']
}

df3 = pd.DataFrame(data3)
df3

   emp_id            name  department
0       1   Michael Scott  Management
1       2     Jim Halpert       Sales
2       3      Pam Beesly   Reception
3       5   Angela Martin  Accounting
4       6    Kevin Malone  Accounting
5       7  Oscar Martinez  Accounting
6       8  Stanley Hudson       Sales
7       9   Phyllis Vance       Sales

In [12]:
df1.merge(df3, how='outer', left_on='employee_id', right_on='emp_id')

,employee_id,name_x,job_title,salary,emp_id,name_y,department
0,1.0,Michael Scott,Regional Manager,100000.0,1.0,Michael Scott,Management
1,2.0,Jim Halpert,Sales Representative,60000.0,2.0,Jim Halpert,Sales
2,3.0,Pam Beesly,Receptionist,55000.0,3.0,Pam Beesly,Reception
3,4.0,Dwight Schrute,Assistant to the Regional Manager,65000.0,NaN,NaN,NaN
4,5.0,Angela Martin,Head of Accounting,60000.0,5.0,Angela Martin,Accounting
5,6.0,Kevin Malone,Accountant,55000.0,6.0,Kevin Malone,Accounting
6,7.0,Oscar Martinez,Accountant,55000.0,7.0,Oscar Martinez,Accounting
7,8.0,Stanley Hudson,Sales Representative,60000.0,8.0,Stanley Hudson,Sales
8,NaN,NaN,NaN,NaN,9.0,Phyllis Vance,Sales

In [ ]:
# It is not possible to use in the same line of code the parameters 'on' and 'left_on' with 'right_on'
# This causes a 'MergeError', as you can see below...

df1.merge(df3, how='outer', on='name', left_on='employee_id', right_on='emp_id')

---
---

<span style='color:red'>

## 2.2. Use of `join()` Function

</span>

In [13]:
df1.join(df2, how='inner', lsuffix='_df1', rsuffix='_df2')

,employee_id_df1,name_df1,job_title,salary,employee_id_df2,name_df2,department
0,1,Michael Scott,Regional Manager,100000,1,Michael Scott,Management
1,2,Jim Halpert,Sales Representative,60000,2,Jim Halpert,Sales
2,3,Pam Beesly,Receptionist,55000,3,Pam Beesly,Reception
3,4,Dwight Schrute,Assistant to the Regional Manager,65000,5,Angela Martin,Accounting
4,5,Angela Martin,Head of Accounting,60000,6,Kevin Malone,Accounting
5,6,Kevin Malone,Accountant,55000,7,Oscar Martinez,Accounting
6,7,Oscar Martinez,Accountant,55000,8,Stanley Hudson,Sales
7,8,Stanley Hudson,Sales Representative,60000,9,Phyllis Vance,Sales

---

<span style='color:orange'>

The upper cell shows messy data, so that is not the correct way of joining both dataframes...

---

In [14]:
df1.set_index('employee_id', inplace = True)
df3.set_index('emp_id', inplace=True)

In [15]:
df1

                       name                          job_title  salary
employee_id
1             Michael Scott                   Regional Manager  100000
2               Jim Halpert               Sales Representative   60000
3                Pam Beesly                       Receptionist   55000
4            Dwight Schrute  Assistant to the Regional Manager   65000
5             Angela Martin                 Head of Accounting   60000
6              Kevin Malone                         Accountant   55000
7            Oscar Martinez                         Accountant   55000
8            Stanley Hudson               Sales Representative   60000

In [16]:
df3

                  name  department
emp_id
1        Michael Scott  Management
2          Jim Halpert       Sales
3           Pam Beesly   Reception
5        Angela Martin  Accounting
6         Kevin Malone  Accounting
7       Oscar Martinez  Accounting
8       Stanley Hudson       Sales
9        Phyllis Vance       Sales

In [17]:
df1.join(df3, how='outer', lsuffix='_df1', rsuffix='_df2')

,name_df1,job_title,salary,name_df2,department
1,Michael Scott,Regional Manager,100000.0,Michael Scott,Management
2,Jim Halpert,Sales Representative,60000.0,Jim Halpert,Sales
3,Pam Beesly,Receptionist,55000.0,Pam Beesly,Reception
4,Dwight Schrute,Assistant to the Regional Manager,65000.0,NaN,NaN
5,Angela Martin,Head of Accounting,60000.0,Angela Martin,Accounting
6,Kevin Malone,Accountant,55000.0,Kevin Malone,Accounting
7,Oscar Martinez,Accountant,55000.0,Oscar Martinez,Accounting
8,Stanley Hudson,Sales Representative,60000.0,Stanley Hudson,Sales
9,NaN,NaN,NaN,Phyllis Vance,Sales

---

<span style='color:yellow'>**VERY IMPORTANT TO REMEMBER...**</span>

<span style='color:orange'>

The functions **`merge()`** is most commonly used, because more than 90% of the time we will try to make a union of two or more DataFrames based on the COLUMNS.</span> 

<span style='color:red'>

And not based on the INDEXES as the **`join()`** function requires.

---

---
---
---

<span style='color:red'>

# 3. MERGE OPERATIONS

In [18]:
data1 = {
    'employee_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'name': ['Michael Scott', 'Jim Halpert', 'Pam Beesly', 'Dwight Schrute', 'Angela Martin', 'Kevin Malone', 'Oscar Martinez', 'Stanley Hudson'],
    'job_title': ['Regional Manager', 'Sales Representative', 'Receptionist', 'Assistant to the Regional Manager', 'Head of Accounting', 'Accountant', 'Accountant', 'Sales Representative'],
    'salary': [100000, 60000, 55000, 65000, 60000, 55000, 55000, 60000]
}

df1 = pd.DataFrame(data1)

data2 = {
    'employee_id': [1, 2, 3, 5, 6, 7, 8, 9],
    'name': ['Michael Scott', 'Jim Halpert', 'Pam Beesly', 'Angela Martin', 'Kevin Malone', 'Oscar Martinez', 'Stanley Hudson', 'Phyllis Vance'],
    'department': ['Management', 'Sales', 'Reception', 'Accounting', 'Accounting', 'Accounting', 'Sales', 'Sales']
}

df2 = pd.DataFrame(data2)


data3 = {
    'employee_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'name': ['Michael Scott', 'Creed Bratton', 'Pam Beesly', 'Dwight Schrute', 'Angela Martin', 'Kevin Malone', 'Oscar Martinez', 'Stanley Hudson'],
    'job_title': ['Regional Manager', 'Sales Representative', 'Receptionist', 'Assistant to the Regional Manager', 'Head of Accounting', 'Accountant', 'Accountant', 'Sales Representative'],
    'salary': [100000, 60000, 55000, 65000, 60000, 55000, 55000, 60000]
}

df3 = pd.DataFrame(data3)

In [19]:
pd.merge(df1, df2, on='employee_id', how='inner')

,employee_id,name_x,job_title,salary,name_y,department
0,1,Michael Scott,Regional Manager,100000,Michael Scott,Management
1,2,Jim Halpert,Sales Representative,60000,Jim Halpert,Sales
2,3,Pam Beesly,Receptionist,55000,Pam Beesly,Reception
3,5,Angela Martin,Head of Accounting,60000,Angela Martin,Accounting
4,6,Kevin Malone,Accountant,55000,Kevin Malone,Accounting
5,7,Oscar Martinez,Accountant,55000,Oscar Martinez,Accounting
6,8,Stanley Hudson,Sales Representative,60000,Stanley Hudson,Sales

In [20]:
# One way to avoid the 'name_x' and 'name_y' columns is this...

pd.merge(df1, df2, on=['employee_id', 'name'], how='outer')

,employee_id,name,job_title,salary,department
0,1,Michael Scott,Regional Manager,100000.0,Management
1,2,Jim Halpert,Sales Representative,60000.0,Sales
2,3,Pam Beesly,Receptionist,55000.0,Reception
3,4,Dwight Schrute,Assistant to the Regional Manager,65000.0,NaN
4,5,Angela Martin,Head of Accounting,60000.0,Accounting
5,6,Kevin Malone,Accountant,55000.0,Accounting
6,7,Oscar Martinez,Accountant,55000.0,Accounting
7,8,Stanley Hudson,Sales Representative,60000.0,Sales
8,9,Phyllis Vance,NaN,NaN,Sales

In [21]:
# Another way to do the same is...

pd.merge(df1, df2[['employee_id', 'department']], on='employee_id', how='outer')

,employee_id,name,job_title,salary,department
0,1,Michael Scott,Regional Manager,100000.0,Management
1,2,Jim Halpert,Sales Representative,60000.0,Sales
2,3,Pam Beesly,Receptionist,55000.0,Reception
3,4,Dwight Schrute,Assistant to the Regional Manager,65000.0,NaN
4,5,Angela Martin,Head of Accounting,60000.0,Accounting
5,6,Kevin Malone,Accountant,55000.0,Accounting
6,7,Oscar Martinez,Accountant,55000.0,Accounting
7,8,Stanley Hudson,Sales Representative,60000.0,Sales
8,9,NaN,NaN,NaN,Sales

In [22]:
# And finally one last way to do the same is...

pd.merge(df1[['employee_id', 'job_title', 'salary']], df2, on='employee_id', how='outer')

,employee_id,job_title,salary,name,department
0,1,Regional Manager,100000.0,Michael Scott,Management
1,2,Sales Representative,60000.0,Jim Halpert,Sales
2,3,Receptionist,55000.0,Pam Beesly,Reception
3,4,Assistant to the Regional Manager,65000.0,NaN,NaN
4,5,Head of Accounting,60000.0,Angela Martin,Accounting
5,6,Accountant,55000.0,Kevin Malone,Accounting
6,7,Accountant,55000.0,Oscar Martinez,Accounting
7,8,Sales Representative,60000.0,Stanley Hudson,Sales
8,9,NaN,NaN,Phyllis Vance,Sales

In [23]:
pd.merge(df1, df2, on='employee_id', how='outer', suffixes=('_1', '_2'))

,employee_id,name_1,job_title,salary,name_2,department
0,1,Michael Scott,Regional Manager,100000.0,Michael Scott,Management
1,2,Jim Halpert,Sales Representative,60000.0,Jim Halpert,Sales
2,3,Pam Beesly,Receptionist,55000.0,Pam Beesly,Reception
3,4,Dwight Schrute,Assistant to the Regional Manager,65000.0,NaN,NaN
4,5,Angela Martin,Head of Accounting,60000.0,Angela Martin,Accounting
5,6,Kevin Malone,Accountant,55000.0,Kevin Malone,Accounting
6,7,Oscar Martinez,Accountant,55000.0,Oscar Martinez,Accounting
7,8,Stanley Hudson,Sales Representative,60000.0,Stanley Hudson,Sales
8,9,NaN,NaN,NaN,Phyllis Vance,Sales

In [24]:
df1.merge(df2, on='employee_id', how='outer', suffixes=('_1', '_2'), indicator=True)

,employee_id,name_1,job_title,salary,name_2,department,_merge
0,1,Michael Scott,Regional Manager,100000.0,Michael Scott,Management,both
1,2,Jim Halpert,Sales Representative,60000.0,Jim Halpert,Sales,both
2,3,Pam Beesly,Receptionist,55000.0,Pam Beesly,Reception,both
3,4,Dwight Schrute,Assistant to the Regional Manager,65000.0,NaN,NaN,left_only
4,5,Angela Martin,Head of Accounting,60000.0,Angela Martin,Accounting,both
5,6,Kevin Malone,Accountant,55000.0,Kevin Malone,Accounting,both
6,7,Oscar Martinez,Accountant,55000.0,Oscar Martinez,Accounting,both
7,8,Stanley Hudson,Sales Representative,60000.0,Stanley Hudson,Sales,both
8,9,NaN,NaN,NaN,Phyllis Vance,Sales,right_only

---

In [25]:
df2.head()

   employee_id           name  department
0            1  Michael Scott  Management
1            2    Jim Halpert       Sales
2            3     Pam Beesly   Reception
3            5  Angela Martin  Accounting
4            6   Kevin Malone  Accounting

In [26]:
df3.head()

   employee_id            name                          job_title  salary
0            1   Michael Scott                   Regional Manager  100000
1            2   Creed Bratton               Sales Representative   60000
2            3      Pam Beesly                       Receptionist   55000
3            4  Dwight Schrute  Assistant to the Regional Manager   65000
4            5   Angela Martin                 Head of Accounting   60000

In [27]:
df3.merge(df2, on='employee_id', how='outer', indicator=True)

,employee_id,name_x,job_title,salary,name_y,department,_merge
0,1,Michael Scott,Regional Manager,100000.0,Michael Scott,Management,both
1,2,Creed Bratton,Sales Representative,60000.0,Jim Halpert,Sales,both
2,3,Pam Beesly,Receptionist,55000.0,Pam Beesly,Reception,both
3,4,Dwight Schrute,Assistant to the Regional Manager,65000.0,NaN,NaN,left_only
4,5,Angela Martin,Head of Accounting,60000.0,Angela Martin,Accounting,both
5,6,Kevin Malone,Accountant,55000.0,Kevin Malone,Accounting,both
6,7,Oscar Martinez,Accountant,55000.0,Oscar Martinez,Accounting,both
7,8,Stanley Hudson,Sales Representative,60000.0,Stanley Hudson,Sales,both
8,9,NaN,NaN,NaN,Phyllis Vance,Sales,right_only

---

<span style='color:orange'>Take a look a the index '1'. That row has to different names on it.

---

In [28]:
# With this line of code the incongruency of the name in the row No. 2 has dissapired. 
# There is no 'Creed Bratton' and there is no 'Jim Halpert' either...

pd.merge(df3, df2, on=['employee_id', 'name'], how='inner')

   employee_id            name             job_title  salary  department
0            1   Michael Scott      Regional Manager  100000  Management
1            3      Pam Beesly          Receptionist   55000   Reception
2            5   Angela Martin    Head of Accounting   60000  Accounting
3            6    Kevin Malone            Accountant   55000  Accounting
4            7  Oscar Martinez            Accountant   55000  Accounting
5            8  Stanley Hudson  Sales Representative   60000       Sales

In [29]:
# But if we use the parameter "outer" on 'how', now both names appear. 
# Nevertheless the "employee_id" No.2 is assigned to both names...

pd.merge(df3, df2, on=['employee_id', 'name'], how='outer')

,employee_id,name,job_title,salary,department
0,1,Michael Scott,Regional Manager,100000.0,Management
1,2,Creed Bratton,Sales Representative,60000.0,NaN
2,2,Jim Halpert,NaN,NaN,Sales
3,3,Pam Beesly,Receptionist,55000.0,Reception
4,4,Dwight Schrute,Assistant to the Regional Manager,65000.0,NaN
5,5,Angela Martin,Head of Accounting,60000.0,Accounting
6,6,Kevin Malone,Accountant,55000.0,Accounting
7,7,Oscar Martinez,Accountant,55000.0,Accounting
8,8,Stanley Hudson,Sales Representative,60000.0,Sales
9,9,Phyllis Vance,NaN,NaN,Sales

---
---
---

<span style='color:red'>

# 4. PRACTICE QUESTION # 1

---

<center><img src='images/08.png' width=720></center>

---

<center><img src='images/09.png' width=750></center>

---

---
---
---

<span style='color:red'>

# 5. MERGING MULTIPLE DATAFRAMES

In [30]:
data1 = {
    'employee_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'name': ['Michael Scott', 'Jim Halpert', 'Pam Beesly', 'Dwight Schrute', 'Angela Martin', 'Kevin Malone', 'Oscar Martinez', 'Stanley Hudson'],
    'job_title': ['Regional Manager', 'Sales Representative', 'Receptionist', 'Assistant to the Regional Manager', 'Head of Accounting', 'Accountant', 'Accountant', 'Sales Representative'],
    'salary': [100000, 60000, 55000, 65000, 60000, 55000, 55000, 60000]}
demographics = pd.DataFrame(data1)


data2 = {
    'employee_id': [1, 2, 3, 5, 6, 7, 8, 9],
    'name': ['Michael Scott', 'Jim Halpert', 'Pam Beesly', 'Angela Martin', 'Kevin Malone', 'Oscar Martinez', 'Stanley Hudson', 'Phyllis Vance'],
    'department_id': [1, 2, 3, 4, 4, 4, 2, 2]}
name_dep = pd.DataFrame(data2)


data3 = {
    'employee_id': [1, 2, 3, 4, 5, 6, 7, 8, 9],
    'manager_id': [None, 1, 1, 1, 1, 4, 4, 1, 1]}
manager = pd.DataFrame(data3)


data4 = {
    'department_id': [1, 2, 3, 4],
    'department': ['Management', 'Sales', 'Reception', 'Accounting']}
department = pd.DataFrame(data4)

In [31]:
# I will take a look first to the 'manager'DF
manager

   employee_id  manager_id
0            1         NaN
1            2         1.0
2            3         1.0
3            4         1.0
4            5         1.0
5            6         4.0
6            7         4.0
7            8         1.0
8            9         1.0

In [32]:
# neet to make changes on the 'manager_id' column...
manager['manager_id'] = manager['manager_id'].astype('Int64')
manager

   employee_id  manager_id
0            1        <NA>
1            2           1
2            3           1
3            4           1
4            5           1
5            6           4
6            7           4
7            8           1
8            9           1

In [33]:
# Now I will take a look at 'department' DF
department

   department_id  department
0              1  Management
1              2       Sales
2              3   Reception
3              4  Accounting

In [34]:
name_dep

   employee_id            name  department_id
0            1   Michael Scott              1
1            2     Jim Halpert              2
2            3      Pam Beesly              3
3            5   Angela Martin              4
4            6    Kevin Malone              4
5            7  Oscar Martinez              4
6            8  Stanley Hudson              2
7            9   Phyllis Vance              2

In [35]:
demographics

   employee_id            name                          job_title  salary
0            1   Michael Scott                   Regional Manager  100000
1            2     Jim Halpert               Sales Representative   60000
2            3      Pam Beesly                       Receptionist   55000
3            4  Dwight Schrute  Assistant to the Regional Manager   65000
4            5   Angela Martin                 Head of Accounting   60000
5            6    Kevin Malone                         Accountant   55000
6            7  Oscar Martinez                         Accountant   55000
7            8  Stanley Hudson               Sales Representative   60000

In [36]:
final_df = demographics.merge(name_dep, 
                              on=['employee_id', 'name'], 
                              how='outer').merge(department, on='department_id', 
                                                 how='outer').merge(manager, on='employee_id', how='outer')

final_df

,employee_id,name,job_title,salary,department_id,department,manager_id
0,1,Michael Scott,Regional Manager,100000.0,1.0,Management,<NA>
1,2,Jim Halpert,Sales Representative,60000.0,2.0,Sales,1
2,3,Pam Beesly,Receptionist,55000.0,3.0,Reception,1
3,4,Dwight Schrute,Assistant to the Regional Manager,65000.0,NaN,NaN,1
4,5,Angela Martin,Head of Accounting,60000.0,4.0,Accounting,1
5,6,Kevin Malone,Accountant,55000.0,4.0,Accounting,4
6,7,Oscar Martinez,Accountant,55000.0,4.0,Accounting,4
7,8,Stanley Hudson,Sales Representative,60000.0,2.0,Sales,1
8,9,Phyllis Vance,NaN,NaN,2.0,Sales,1

---

In [37]:
final_df['department_id'] = final_df['department_id'].astype('Int64')
final_df

,employee_id,name,job_title,salary,department_id,department,manager_id
0,1,Michael Scott,Regional Manager,100000.0,1,Management,<NA>
1,2,Jim Halpert,Sales Representative,60000.0,2,Sales,1
2,3,Pam Beesly,Receptionist,55000.0,3,Reception,1
3,4,Dwight Schrute,Assistant to the Regional Manager,65000.0,<NA>,NaN,1
4,5,Angela Martin,Head of Accounting,60000.0,4,Accounting,1
5,6,Kevin Malone,Accountant,55000.0,4,Accounting,4
6,7,Oscar Martinez,Accountant,55000.0,4,Accounting,4
7,8,Stanley Hudson,Sales Representative,60000.0,2,Sales,1
8,9,Phyllis Vance,NaN,NaN,2,Sales,1

---
---
---

<span style='color:red'>

# 6. CONCATENATION

In [38]:
data1 = {
    'employee_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'name': ['Michael Scott', 'Jim Halpert', 'Pam Beesly', 'Dwight Schrute', 'Angela Martin', 'Kevin Malone', 'Oscar Martinez', 'Stanley Hudson'],
    'job_title': ['Regional Manager', 'Sales Representative', 'Receptionist', 'Assistant to the Regional Manager', 'Head of Accounting', 'Accountant', 'Accountant', 'Sales Representative'],
    'salary': [100000, 60000, 55000, 65000, 60000, 55000, 55000, 60000]}
df1 = pd.DataFrame(data1)

data2 = {
    'employee_id': [1, 2, 3, 5, 6, 7, 8, 9],
    'name': ['Michael Scott', 'Jim Halpert', 'Pam Beesly', 'Angela Martin', 'Kevin Malone', 'Oscar Martinez', 'Stanley Hudson', 'Phyllis Vance'],
    'department': ['Management', 'Sales', 'Reception', 'Accounting', 'Accounting', 'Accounting', 'Sales', 'Sales']}
df2 = pd.DataFrame(data2)

In [39]:
df1

   employee_id            name                          job_title  salary
0            1   Michael Scott                   Regional Manager  100000
1            2     Jim Halpert               Sales Representative   60000
2            3      Pam Beesly                       Receptionist   55000
3            4  Dwight Schrute  Assistant to the Regional Manager   65000
4            5   Angela Martin                 Head of Accounting   60000
5            6    Kevin Malone                         Accountant   55000
6            7  Oscar Martinez                         Accountant   55000
7            8  Stanley Hudson               Sales Representative   60000

In [40]:
df2

   employee_id            name  department
0            1   Michael Scott  Management
1            2     Jim Halpert       Sales
2            3      Pam Beesly   Reception
3            5   Angela Martin  Accounting
4            6    Kevin Malone  Accounting
5            7  Oscar Martinez  Accounting
6            8  Stanley Hudson       Sales
7            9   Phyllis Vance       Sales

In [41]:
pd.concat([df1, df2])

,employee_id,name,job_title,salary,department
0,1,Michael Scott,Regional Manager,100000.0,NaN
1,2,Jim Halpert,Sales Representative,60000.0,NaN
2,3,Pam Beesly,Receptionist,55000.0,NaN
3,4,Dwight Schrute,Assistant to the Regional Manager,65000.0,NaN
4,5,Angela Martin,Head of Accounting,60000.0,NaN
5,6,Kevin Malone,Accountant,55000.0,NaN
6,7,Oscar Martinez,Accountant,55000.0,NaN
7,8,Stanley Hudson,Sales Representative,60000.0,NaN
0,1,Michael Scott,NaN,NaN,Management
1,2,Jim Halpert,NaN,NaN,Sales
2,3,Pam Beesly,NaN,NaN,Reception
3,5,Angela Martin,NaN,NaN,Accounting
4,6,Kevin Malone,NaN,NaN,Accounting
5,7,Oscar Martinez,NaN,NaN,Accounting
6,8,Stanley Hudson,NaN,NaN,Sales
7,9,Phyllis Vance,NaN,NaN,Sales

In [42]:
pd.concat([df1, df2], axis=1)

,employee_id,name,job_title,salary,employee_id,name,department
0,1,Michael Scott,Regional Manager,100000,1,Michael Scott,Management
1,2,Jim Halpert,Sales Representative,60000,2,Jim Halpert,Sales
2,3,Pam Beesly,Receptionist,55000,3,Pam Beesly,Reception
3,4,Dwight Schrute,Assistant to the Regional Manager,65000,5,Angela Martin,Accounting
4,5,Angela Martin,Head of Accounting,60000,6,Kevin Malone,Accounting
5,6,Kevin Malone,Accountant,55000,7,Oscar Martinez,Accounting
6,7,Oscar Martinez,Accountant,55000,8,Stanley Hudson,Sales
7,8,Stanley Hudson,Sales Representative,60000,9,Phyllis Vance,Sales

In [43]:
pd.concat([df1.set_index('employee_id'), df2.set_index('employee_id')], axis=1)

,name,job_title,salary,name,department
employee_id,,,,,
1,Michael Scott,Regional Manager,100000.0,Michael Scott,Management
2,Jim Halpert,Sales Representative,60000.0,Jim Halpert,Sales
3,Pam Beesly,Receptionist,55000.0,Pam Beesly,Reception
4,Dwight Schrute,Assistant to the Regional Manager,65000.0,NaN,NaN
5,Angela Martin,Head of Accounting,60000.0,Angela Martin,Accounting
6,Kevin Malone,Accountant,55000.0,Kevin Malone,Accounting
7,Oscar Martinez,Accountant,55000.0,Oscar Martinez,Accounting
8,Stanley Hudson,Sales Representative,60000.0,Stanley Hudson,Sales
9,NaN,NaN,NaN,Phyllis Vance,Sales

In [44]:
edit_df = pd.concat([df1[['employee_id', 'name']], df2[['employee_id', 'name']]], axis=0)
edit_df

   employee_id            name
0            1   Michael Scott
1            2     Jim Halpert
2            3      Pam Beesly
3            4  Dwight Schrute
4            5   Angela Martin
5            6    Kevin Malone
6            7  Oscar Martinez
7            8  Stanley Hudson
0            1   Michael Scott
1            2     Jim Halpert
2            3      Pam Beesly
3            5   Angela Martin
4            6    Kevin Malone
5            7  Oscar Martinez
6            8  Stanley Hudson
7            9   Phyllis Vance

In [45]:
# Now I will drop duplicated data...

edit_df.drop_duplicates(inplace=True)
edit_df

   employee_id            name
0            1   Michael Scott
1            2     Jim Halpert
2            3      Pam Beesly
3            4  Dwight Schrute
4            5   Angela Martin
5            6    Kevin Malone
6            7  Oscar Martinez
7            8  Stanley Hudson
7            9   Phyllis Vance

In [46]:
# now it's necessary to reset the index...
edit_df.reset_index(inplace=True, drop=True)
edit_df

   employee_id            name
0            1   Michael Scott
1            2     Jim Halpert
2            3      Pam Beesly
3            4  Dwight Schrute
4            5   Angela Martin
5            6    Kevin Malone
6            7  Oscar Martinez
7            8  Stanley Hudson
8            9   Phyllis Vance

In [47]:
ex2 = pd.concat([df1, df2], axis=0)
ex2

,employee_id,name,job_title,salary,department
0,1,Michael Scott,Regional Manager,100000.0,NaN
1,2,Jim Halpert,Sales Representative,60000.0,NaN
2,3,Pam Beesly,Receptionist,55000.0,NaN
3,4,Dwight Schrute,Assistant to the Regional Manager,65000.0,NaN
4,5,Angela Martin,Head of Accounting,60000.0,NaN
5,6,Kevin Malone,Accountant,55000.0,NaN
6,7,Oscar Martinez,Accountant,55000.0,NaN
7,8,Stanley Hudson,Sales Representative,60000.0,NaN
0,1,Michael Scott,NaN,NaN,Management
1,2,Jim Halpert,NaN,NaN,Sales
2,3,Pam Beesly,NaN,NaN,Reception
3,5,Angela Martin,NaN,NaN,Accounting
4,6,Kevin Malone,NaN,NaN,Accounting
5,7,Oscar Martinez,NaN,NaN,Accounting
6,8,Stanley Hudson,NaN,NaN,Sales
7,9,Phyllis Vance,NaN,NaN,Sales

In [48]:
ex3 = pd.concat([df1, df2], axis=0, ignore_index=True)
ex3

,employee_id,name,job_title,salary,department
0,1,Michael Scott,Regional Manager,100000.0,NaN
1,2,Jim Halpert,Sales Representative,60000.0,NaN
2,3,Pam Beesly,Receptionist,55000.0,NaN
3,4,Dwight Schrute,Assistant to the Regional Manager,65000.0,NaN
4,5,Angela Martin,Head of Accounting,60000.0,NaN
5,6,Kevin Malone,Accountant,55000.0,NaN
6,7,Oscar Martinez,Accountant,55000.0,NaN
7,8,Stanley Hudson,Sales Representative,60000.0,NaN
8,1,Michael Scott,NaN,NaN,Management
9,2,Jim Halpert,NaN,NaN,Sales
10,3,Pam Beesly,NaN,NaN,Reception
11,5,Angela Martin,NaN,NaN,Accounting
12,6,Kevin Malone,NaN,NaN,Accounting
13,7,Oscar Martinez,NaN,NaN,Accounting
14,8,Stanley Hudson,NaN,NaN,Sales
15,9,Phyllis Vance,NaN,NaN,Sales

In [49]:
ex4 = pd.concat([df1, df2], keys=['DF1', 'DF2'])
ex4

       employee_id            name                          job_title  \
DF1 0            1   Michael Scott                   Regional Manager
    1            2     Jim Halpert               Sales Representative
    2            3      Pam Beesly                       Receptionist
    3            4  Dwight Schrute  Assistant to the Regional Manager
    4            5   Angela Martin                 Head of Accounting
    5            6    Kevin Malone                         Accountant
    6            7  Oscar Martinez                         Accountant
    7            8  Stanley Hudson               Sales Representative
DF2 0            1   Michael Scott                                NaN
    1            2     Jim Halpert                                NaN
    2            3      Pam Beesly                                NaN
    3            5   Angela Martin                                NaN
    4            6    Kevin Malone                                NaN
    5            7  Oscar Martinez                                NaN
    6            8  Stanley Hudson                                NaN
    7            9   Phyllis Vance                                NaN

         salary  department
DF1 0  100000.0         NaN
    1   60000.0         NaN
    2   55000.0         NaN
    3   65000.0         NaN
    4   60000.0         NaN
    5   55000.0         NaN
    6   55000.0         NaN
    7   60000.0         NaN
DF2 0       NaN  Management
    1       NaN       Sales
    2       NaN   Reception
    3       NaN  Accounting
    4       NaN  Accounting
    5       NaN  Accounting
    6       NaN       Sales
    7       NaN       Sales

---
---
---

<span style='color:red'>

# 7. PRACTICE QUESTION # 2

---

<center><img src='images/10.png' width=720</center>

---

<center><img src='images/11.png' width=750</center>

---