<span style='color:red'>

# TITLE: `DATA CLEANING AND PREPROCESSING`

</span>

---
---
---

<span style='color:red'>

# 1. DATA CLEANING INTRODUCTION

---

<div style='background-color:lightgray; padding:15px;'>

<span style='color:black'>

1. Data Cleaning refers to taking the raw data and making it more usable for the end product.

2. Data may need to be cleaned if there are missing values, duplicates, incongruent data formats, and others.

3. **NOTE:** Data Cleaning is a continuous process and not done just at the beginning of a project.

---

<center><img src='images/12.png' width=570></center>

---

</div>

---

---
---
---

<span style='color:red'>

# 2. DEALING WITH DUPLICATES

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = {
    'Transaction ID': [101, 102, 103, 103, 104, 105, 106],
    'Customer Name': ['Harry Potter', 'Hermione Granger', 'Ron Weasley', 'Ron Weasley', 
                      'Draco Malfoy', 'Luna Lovegood', 'Draco Malfoy'],
    'Wand': ['Elder Wand', 'Vine Wood', 'Hawthorn', 'Hawthorn', 'Dragon Heartstring', 
             'Thestral Tail Hair', 'Dragon Heartstring'],
    'Price': [100, 75, 50, 50, 80, 60, 80]}

df_duplicated = pd.DataFrame(data)
df_duplicated

   Transaction ID     Customer Name                Wand  Price
0             101      Harry Potter          Elder Wand    100
1             102  Hermione Granger           Vine Wood     75
2             103       Ron Weasley            Hawthorn     50
3             103       Ron Weasley            Hawthorn     50
4             104      Draco Malfoy  Dragon Heartstring     80
5             105     Luna Lovegood  Thestral Tail Hair     60
6             106      Draco Malfoy  Dragon Heartstring     80

In [3]:
df_duplicated.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6    False
dtype: bool

In [4]:
df_duplicated[df_duplicated['Transaction ID'].duplicated()]

   Transaction ID Customer Name      Wand  Price
3             103   Ron Weasley  Hawthorn     50

In [5]:
df_duplicated.drop_duplicates(inplace=True)

df_duplicated

   Transaction ID     Customer Name                Wand  Price
0             101      Harry Potter          Elder Wand    100
1             102  Hermione Granger           Vine Wood     75
2             103       Ron Weasley            Hawthorn     50
4             104      Draco Malfoy  Dragon Heartstring     80
5             105     Luna Lovegood  Thestral Tail Hair     60
6             106      Draco Malfoy  Dragon Heartstring     80

---

In [6]:
data2 = {
    'First Name': ['Harry', 'Hermione', 'Ron', 'Harry', 'Draco', 'Luna', 'Harry'],
    'Last Name': ['Potter', 'Granger', 'Weasley', 'Potter', 'Malfoy', 'Lovegood', 
                  'Potter'],
    'Hogwarts House': ['Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', 
                       'Slytherin', 'Ravenclaw', 'Gryffindor'],
    'Favorite Class': ['Defense Against the Dark Arts', 'Potions', 'Charms', 
                       'Quidditch', 'Transfiguration', 'Care of Magical Creatures', 
                       'Herbology']}
Class_List = pd.DataFrame(data2)
Class_List

  First Name Last Name Hogwarts House                 Favorite Class
0      Harry    Potter     Gryffindor  Defense Against the Dark Arts
1   Hermione   Granger     Gryffindor                        Potions
2        Ron   Weasley     Gryffindor                         Charms
3      Harry    Potter     Gryffindor                      Quidditch
4      Draco    Malfoy      Slytherin                Transfiguration
5       Luna  Lovegood      Ravenclaw      Care of Magical Creatures
6      Harry    Potter     Gryffindor                      Herbology

In [7]:
Class_List[Class_List.duplicated()].sum()

First Name        0
Last Name         0
Hogwarts House    0
Favorite Class    0
dtype: object

In [8]:
# I want to see where are the duplicated data...

Class_List[Class_List[['First Name', 'Last Name']].duplicated()]

  First Name Last Name Hogwarts House Favorite Class
3      Harry    Potter     Gryffindor      Quidditch
6      Harry    Potter     Gryffindor      Herbology

In [9]:
# Removing the 4th and 7th row of the dataset(duplicated data)

Class_List.drop_duplicates(subset=['First Name', 'Last Name'], 
                           keep='first')

  First Name Last Name Hogwarts House                 Favorite Class
0      Harry    Potter     Gryffindor  Defense Against the Dark Arts
1   Hermione   Granger     Gryffindor                        Potions
2        Ron   Weasley     Gryffindor                         Charms
4      Draco    Malfoy      Slytherin                Transfiguration
5       Luna  Lovegood      Ravenclaw      Care of Magical Creatures

In [10]:
# Removing the 1st and 4th row of duplicated data...

Class_List.drop_duplicates(subset=['First Name', 'Last Name'], 
                           keep='last')

  First Name Last Name Hogwarts House             Favorite Class
1   Hermione   Granger     Gryffindor                    Potions
2        Ron   Weasley     Gryffindor                     Charms
4      Draco    Malfoy      Slytherin            Transfiguration
5       Luna  Lovegood      Ravenclaw  Care of Magical Creatures
6      Harry    Potter     Gryffindor                  Herbology

In [11]:
# Removing all the duplicated data in "First Name" and "Last Name"

Class_List.drop_duplicates(subset=['First Name', 'Last Name'], 
                           keep=False)

  First Name Last Name Hogwarts House             Favorite Class
1   Hermione   Granger     Gryffindor                    Potions
2        Ron   Weasley     Gryffindor                     Charms
4      Draco    Malfoy      Slytherin            Transfiguration
5       Luna  Lovegood      Ravenclaw  Care of Magical Creatures

---
---

<span style='color:green'>

## *** Exploring Functions and Instances of DataFrames

In [12]:
Class_List.T

,0,1,2,3,4,5,6
First Name,Harry,Hermione,Ron,Harry,Draco,Luna,Harry
Last Name,Potter,Granger,Weasley,Potter,Malfoy,Lovegood,Potter
Hogwarts House,Gryffindor,Gryffindor,Gryffindor,Gryffindor,Slytherin,Ravenclaw,Gryffindor
Favorite Class,Defense Against the Dark Arts,Potions,Charms,Quidditch,Transfiguration,Care of Magical Creatures,Herbology

In [13]:
Class_List.transpose()

,0,1,2,3,4,5,6
First Name,Harry,Hermione,Ron,Harry,Draco,Luna,Harry
Last Name,Potter,Granger,Weasley,Potter,Malfoy,Lovegood,Potter
Hogwarts House,Gryffindor,Gryffindor,Gryffindor,Gryffindor,Slytherin,Ravenclaw,Gryffindor
Favorite Class,Defense Against the Dark Arts,Potions,Charms,Quidditch,Transfiguration,Care of Magical Creatures,Herbology

---

In [14]:
multicol = pd.MultiIndex.from_tuples([('weight', 'kg'), 
                                      ('height', 'cm')])
df_multi_level_cols = pd.DataFrame([[10.5, 33.6], [6.9, 30.9]], 
                                   index=['Milo', 'Aby'],columns=multicol)
df_multi_level_cols

     weight height
         kg     cm
Milo   10.5   33.6
Aby     6.9   30.9

In [15]:
df_multi_level_cols.stack(future_stack=True)

         weight  height
Milo kg    10.5     NaN
     cm     NaN    33.6
Aby  kg     6.9     NaN
     cm     NaN    30.9

In [16]:
df_multi_level_cols.stack(future_stack=True, 
                          level=0)

               kg    cm
Milo weight  10.5   NaN
     height   NaN  33.6
Aby  weight   6.9   NaN
     height   NaN  30.9

In [17]:
df_multi_level_cols.stack(future_stack=True,
                          level=[0, 1])

Milo  weight  kg    10.5
      height  cm    33.6
Aby   weight  kg     6.9
      height  cm    30.9
dtype: float64

In [19]:
res = df_multi_level_cols.stack(future_stack=True,
                                level=[1, 0])
res

Milo  kg  weight    10.5
      cm  height    33.6
Aby   kg  weight     6.9
      cm  height    30.9
dtype: float64

In [20]:
type(res)

pandas.core.series.Series

In [21]:
res.unstack(level=0)

           Milo   Aby
cm height  33.6  30.9
kg weight  10.5   6.9

In [22]:
res.unstack(level=1)

               cm    kg
Milo height  33.6   NaN
     weight   NaN  10.5
Aby  height  30.9   NaN
     weight   NaN   6.9

In [23]:
res.unstack(level=2)

         height  weight
Milo cm    33.6     NaN
     kg     NaN    10.5
Aby  cm    30.9     NaN
     kg     NaN     6.9

In [24]:
res.unstack(level=[0,2])

     Milo           Aby
   weight height weight height
cm    NaN   33.6    NaN   30.9
kg   10.5    NaN    6.9    NaN

In [25]:
res.unstack(level=[2, 0])

   weight height weight height
     Milo   Milo    Aby    Aby
cm    NaN   33.6    NaN   30.9
kg   10.5    NaN    6.9    NaN

In [26]:
res.unstack(level=[0, 1])

        Milo        Aby
          kg    cm   kg    cm
height   NaN  33.6  NaN  30.9
weight  10.5   NaN  6.9   NaN

---
---
---

<span style='color:green'>

# 3. PRACTICE LAB - Duplicate Emails

---

<div style='background-color:lightgray; padding:15px;'>
    
<span style='color:green'>
    
**Duplicate Emails**

There's recently been an error on our server where some emails were duplicated. We need to identify those emails so we can remove the duplicates.

Write a query to report all the duplicate emails and how many times they are in the database.

Output should be in alphabetical order.

</div>

---

In [27]:
emails = pd.DataFrame({'id':[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
                        'email': ['alex@gmail.com', 
                                  'Gregory@yahoo.com', 
                                  'analystbuilder@gmail.com', 
                                  'sally@aol.com', 
                                  'ted@gmail.com', 
                                  'Kevin@yahoo.com', 
                                  'Jennifer@yahoo.com', 
                                  'alex@gmail.com', 
                                  'Larry@gmail.com', 
                                  'Ted@yahoo.com', 
                                  'analystbuilder@gmail.com']})
emails

    id                     email
0    1            alex@gmail.com
1    2         Gregory@yahoo.com
2    3  analystbuilder@gmail.com
3    4             sally@aol.com
4    5             ted@gmail.com
5    6           Kevin@yahoo.com
6    7        Jennifer@yahoo.com
7    8            alex@gmail.com
8    9           Larry@gmail.com
9   10             Ted@yahoo.com
10  11  analystbuilder@gmail.com

In [28]:
count_emails = emails.value_counts('email')
count_emails

email
analystbuilder@gmail.com    2
alex@gmail.com              2
Gregory@yahoo.com           1
Jennifer@yahoo.com          1
Kevin@yahoo.com             1
Ted@yahoo.com               1
Larry@gmail.com             1
sally@aol.com               1
ted@gmail.com               1
Name: count, dtype: int64

In [29]:
final_report = count_emails.reset_index().head(2)
final_report

                      email  count
0  analystbuilder@gmail.com      2
1            alex@gmail.com      2

---

In [30]:
filtered_emails = emails.value_counts('email').reset_index()
filtered_emails

                      email  count
0  analystbuilder@gmail.com      2
1            alex@gmail.com      2
2         Gregory@yahoo.com      1
3        Jennifer@yahoo.com      1
4           Kevin@yahoo.com      1
5             Ted@yahoo.com      1
6           Larry@gmail.com      1
7             sally@aol.com      1
8             ted@gmail.com      1

In [31]:
result = filtered_emails[filtered_emails['count'] > 1]
result

                      email  count
0  analystbuilder@gmail.com      2
1            alex@gmail.com      2

---

In [32]:
result2 = emails.groupby('email').count().sort_values('id', 
                                                      ascending=False).reset_index()
result2[result2['id'] > 1]

                      email  id
0  analystbuilder@gmail.com   2
1            alex@gmail.com   2

---
---
---

<span style='color:red'>

# 4. STANDARAZING DATA

In [33]:
# Scenario No. 1
data1 = {
    'student_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'full_name': ['Harry Potter', 'Hermione Granger', 'Ron Weasley', 'Draco Malfoy', 
                  'Luna Lovegood', 'Neville Longbottom', 'Ginny Weasley', 
                  'Fred Weasley', 'George Weasley', 'Cho Chang'],
    'phone_number': ['(123) 456-7890', '555-123-4567', '9876543210', '123.456.7890', 
                     '(123)-4567890', '987-654-3210', '123 456 7890', '1234567890', 
                     '+7890123456', '012-345-6789']}
Bad_Numbers = pd.DataFrame(data1)

# ----------------------------------------------------------------------------------
# Scenario No. 2
data2 = {
    'Full Name': ['Harry Potter', 'Hermione Granger', 'Ron Weasley', 'Draco Malfoy', 
                  'Luna Lovegood', 'Gregory Goyle'],
    'Voldemort_Bad': ['Y', 'yes', 'Yes', 'No', 'OK', 'nope!']}
Voldy = pd.DataFrame(data2)

# ----------------------------------------------------------------------------------
# Scenario No. 3
data3 = {
    'First Name': ['Harry', 'Hermione', 'Ron', 'Hermione', 'Ronald', 'Harry', 
                   'Hermion', 'Ron'],
    'Last Name': ['Potter', 'Granger', 'Weasley', 'Grangar', 'Weasly', 'Poter', 
                  'Graner', 'Weaseley'],
    'Age': [18, 17, 18, 17, 18, 18, 17, 18],
    'Social Security Number': ['123-45-6789', '987-65-4321', '555-55-5555', 
                               '987-65-4321', '555-55-5555', '123-45-6789', 
                               '987-65-4321', '555-55-5555']}
Hogwarts_Students = pd.DataFrame(data3)

# ----------------------------------------------------------------------------------
# Scenario No. 4
data4 = {
    'First Name': ['Harry', 'Hermione?', 'Ron', 'Hermione', 'Ron_', 'Harry!', 
                   'Hermione', 'Ron'],
    'Last Name': ['"Potter"', 'Granger', 'Weasley', 'Granger', 'Weasley...', 
                  'Potter', 'Granger', 'Weasley'],
    'Age': [18, 17, 18, 17, 18, 18, 17, 18]}
Hogwarts_Students2 = pd.DataFrame(data4)

---
---

<span style='color:red'>

## 4.1. Scenario No.1 - Phone Numbers Mismatch

In [34]:
Bad_Numbers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   student_id    10 non-null     int64
 1   full_name     10 non-null     object
 2   phone_number  10 non-null     object
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes

In [35]:
Bad_Numbers

   student_id           full_name    phone_number
0           1        Harry Potter  (123) 456-7890
1           2    Hermione Granger    555-123-4567
2           3         Ron Weasley      9876543210
3           4        Draco Malfoy    123.456.7890
4           5       Luna Lovegood   (123)-4567890
5           6  Neville Longbottom    987-654-3210
6           7       Ginny Weasley    123 456 7890
7           8        Fred Weasley      1234567890
8           9      George Weasley     +7890123456
9          10           Cho Chang    012-345-6789

In [36]:
Bad_Numbers['phone_number'].str.replace(r'\D', '', 
                                        regex=True)

0    1234567890
1    5551234567
2    9876543210
3    1234567890
4    1234567890
5    9876543210
6    1234567890
7    1234567890
8    7890123456
9    0123456789
Name: phone_number, dtype: object

In [37]:
Bad_Numbers['phone_number'] = Bad_Numbers[
            'phone_number'].str.replace(r'\D','', regex=True)
Bad_Numbers

   student_id           full_name phone_number
0           1        Harry Potter   1234567890
1           2    Hermione Granger   5551234567
2           3         Ron Weasley   9876543210
3           4        Draco Malfoy   1234567890
4           5       Luna Lovegood   1234567890
5           6  Neville Longbottom   9876543210
6           7       Ginny Weasley   1234567890
7           8        Fred Weasley   1234567890
8           9      George Weasley   7890123456
9          10           Cho Chang   0123456789

In [38]:
# if the dataset is huge, we can use the next line of code to verify if the 'phone_number' has 10 digits

len(Bad_Numbers[Bad_Numbers[
    'phone_number'].str.len() != 10])

0

In [39]:
# Reformatting the 'phone_number' column
Bad_Numbers['phone_number'] = Bad_Numbers[
            'phone_number'].str[:3] + '-' + Bad_Numbers[
            'phone_number'].str[3:6] + '-' + Bad_Numbers[
            'phone_number'].str[6:]
Bad_Numbers

   student_id           full_name  phone_number
0           1        Harry Potter  123-456-7890
1           2    Hermione Granger  555-123-4567
2           3         Ron Weasley  987-654-3210
3           4        Draco Malfoy  123-456-7890
4           5       Luna Lovegood  123-456-7890
5           6  Neville Longbottom  987-654-3210
6           7       Ginny Weasley  123-456-7890
7           8        Fred Weasley  123-456-7890
8           9      George Weasley  789-012-3456
9          10           Cho Chang  012-345-6789

---
---

<span style='color:red'>

## 4.2. Scenario No.2 - 'Yes' & 'No' Mismatching

In [40]:
Voldy

          Full Name Voldemort_Bad
0      Harry Potter             Y
1  Hermione Granger           yes
2       Ron Weasley           Yes
3      Draco Malfoy            No
4     Luna Lovegood            OK
5     Gregory Goyle         nope!

In [41]:
Voldy['Voldemort_Bad'].apply(
    lambda x: 'Yes' if x.startswith(('Y', 'y', 'O')) 
                    else ('No' if x.startswith(('N', 'n')) else x)
)

0    Yes
1    Yes
2    Yes
3     No
4    Yes
5     No
Name: Voldemort_Bad, dtype: object

In [42]:
Voldy['Voldemort_Bad'] = Voldy['Voldemort_Bad'].apply(
    lambda x: 'Yes' if x.startswith(('Y', 'y', 'O')) 
                    else ('No' if x.startswith(('N', 'n')) else x)
)
Voldy

          Full Name Voldemort_Bad
0      Harry Potter           Yes
1  Hermione Granger           Yes
2       Ron Weasley           Yes
3      Draco Malfoy            No
4     Luna Lovegood           Yes
5     Gregory Goyle            No

In [43]:
Voldy.groupby(by='Voldemort_Bad').count()

               Full Name
Voldemort_Bad
No                     2
Yes                    4

---
---

<span style='color:red'>

## 4.3. Scenario No.3 - Bad Spelling Names

In [44]:
Hogwarts_Students

  First Name Last Name  Age Social Security Number
0      Harry    Potter   18            123-45-6789
1   Hermione   Granger   17            987-65-4321
2        Ron   Weasley   18            555-55-5555
3   Hermione   Grangar   17            987-65-4321
4     Ronald    Weasly   18            555-55-5555
5      Harry     Poter   18            123-45-6789
6    Hermion    Graner   17            987-65-4321
7        Ron  Weaseley   18            555-55-5555

---

<span style='color:orange'>

The upper DataFrame shows that one same person has different spellings of their names and last names...

...so I will look a way to group people by the "Social Security Number"

---

In [45]:
Hogwarts_Students.groupby(by='Social Security Number').ngroup()

0    0
1    2
2    1
3    2
4    1
5    0
6    2
7    1
dtype: int64

In [46]:
Hogwarts_Students['Same_SS_Number'] = Hogwarts_Students.groupby(
                                    'Social Security Number').ngroup()
Hogwarts_Students

  First Name Last Name  Age Social Security Number  Same_SS_Number
0      Harry    Potter   18            123-45-6789               0
1   Hermione   Granger   17            987-65-4321               2
2        Ron   Weasley   18            555-55-5555               1
3   Hermione   Grangar   17            987-65-4321               2
4     Ronald    Weasly   18            555-55-5555               1
5      Harry     Poter   18            123-45-6789               0
6    Hermion    Graner   17            987-65-4321               2
7        Ron  Weaseley   18            555-55-5555               1

In [47]:
Hogwarts_Students.groupby(by='Same_SS_Number')[[
                'First Name', 'Last Name']].value_counts().reset_index()

   Same_SS_Number First Name Last Name  count
0               0      Harry     Poter      1
1               0      Harry    Potter      1
2               1        Ron  Weaseley      1
3               1        Ron   Weasley      1
4               1     Ronald    Weasly      1
5               2    Hermion    Graner      1
6               2   Hermione   Grangar      1
7               2   Hermione   Granger      1

In [48]:
Hogwarts_Students['Name_Substring'] = Hogwarts_Students[
    'First Name'].str[:3] + Hogwarts_Students['Last Name'].str[:3]
Hogwarts_Students

,First Name,Last Name,Age,Social Security Number,Same_SS_Number,Name_Substring
0,Harry,Potter,18,123-45-6789,0,HarPot
1,Hermione,Granger,17,987-65-4321,2,HerGra
2,Ron,Weasley,18,555-55-5555,1,RonWea
3,Hermione,Grangar,17,987-65-4321,2,HerGra
4,Ronald,Weasly,18,555-55-5555,1,RonWea
5,Harry,Poter,18,123-45-6789,0,HarPot
6,Hermion,Graner,17,987-65-4321,2,HerGra
7,Ron,Weaseley,18,555-55-5555,1,RonWea

In [49]:
Hogwarts_Students['Same_SS_Number_2'] = Hogwarts_Students.groupby(
                        'Name_Substring').ngroup() + 1
Hogwarts_Students

,First Name,Last Name,Age,Social Security Number,Same_SS_Number,Name_Substring,Same_SS_Number_2
0,Harry,Potter,18,123-45-6789,0,HarPot,1
1,Hermione,Granger,17,987-65-4321,2,HerGra,2
2,Ron,Weasley,18,555-55-5555,1,RonWea,3
3,Hermione,Grangar,17,987-65-4321,2,HerGra,2
4,Ronald,Weasly,18,555-55-5555,1,RonWea,3
5,Harry,Poter,18,123-45-6789,0,HarPot,1
6,Hermion,Graner,17,987-65-4321,2,HerGra,2
7,Ron,Weaseley,18,555-55-5555,1,RonWea,3

---
---

<span style='color:red'>

## 4.4. Scenario No.4 - Special Characters on Names

In [50]:
Hogwarts_Students2

  First Name   Last Name  Age
0      Harry    "Potter"   18
1  Hermione?     Granger   17
2        Ron     Weasley   18
3   Hermione     Granger   17
4       Ron_  Weasley...   18
5     Harry!      Potter   18
6   Hermione     Granger   17
7        Ron     Weasley   18

In [51]:
Hogwarts_Students2['First Name'].str.replace(
                    '[^a-zA-Z]', '', regex=True)

0       Harry
1    Hermione
2         Ron
3    Hermione
4         Ron
5       Harry
6    Hermione
7         Ron
Name: First Name, dtype: object

In [52]:
Hogwarts_Students2['First Name'] = Hogwarts_Students2[
                    'First Name'].str.replace('[^a-zA-Z]', '', regex=True)
Hogwarts_Students2

  First Name   Last Name  Age
0      Harry    "Potter"   18
1   Hermione     Granger   17
2        Ron     Weasley   18
3   Hermione     Granger   17
4        Ron  Weasley...   18
5      Harry      Potter   18
6   Hermione     Granger   17
7        Ron     Weasley   18

In [53]:
Hogwarts_Students2['Last Name'].str.replace(
                    '[^a-zA-Z]', '', regex=True)

0     Potter
1    Granger
2    Weasley
3    Granger
4    Weasley
5     Potter
6    Granger
7    Weasley
Name: Last Name, dtype: object

In [54]:
Hogwarts_Students2['Last Name'] = Hogwarts_Students2[
                    'Last Name'].str.replace('[^a-zA-Z]', '', regex=True)
Hogwarts_Students2

  First Name Last Name  Age
0      Harry    Potter   18
1   Hermione   Granger   17
2        Ron   Weasley   18
3   Hermione   Granger   17
4        Ron   Weasley   18
5      Harry    Potter   18
6   Hermione   Granger   17
7        Ron   Weasley   18

---
---
---

<span style='color:green'>

# 5. PRACTICE LAB - TMI (Too Much Information)

---

<span style='color:orange'>
    
**TMI (Too Much Information)**

Often when you're working with customer information you'll want to sell that data to a third party. Sometimes it is illegal to give away sensitive information such as a full name.

Here you are given a table that contains a customer ID and their full name.

Return the customer ID with only the first name of each customer.

---

In [55]:
data = {'customer_id':[1001, 1002, 1003, 1004, 1005, 1006],
        'full_name':['John McGary', 'Sally Sue', 'Jenny McBlue', 
                     'Craig Johnson', 'Henry Hue', 'Alex Freebird']}

data_lab = pd.DataFrame(data)
data_lab

   customer_id      full_name
0         1001    John McGary
1         1002      Sally Sue
2         1003   Jenny McBlue
3         1004  Craig Johnson
4         1005      Henry Hue
5         1006  Alex Freebird

In [56]:
data_lab['full_name'].str.extract(r'(\w+)\s\w+')

       0
0   John
1  Sally
2  Jenny
3  Craig
4  Henry
5   Alex

In [57]:
data_lab['first_name'] = data_lab[
            'full_name'].str.extract(r'(\w+)\s\w+')
data_lab

   customer_id      full_name first_name
0         1001    John McGary       John
1         1002      Sally Sue      Sally
2         1003   Jenny McBlue      Jenny
3         1004  Craig Johnson      Craig
4         1005      Henry Hue      Henry
5         1006  Alex Freebird       Alex

In [58]:
data_lab['full_name'].str.extract(r'\w+\s(\w+)')

          0
0    McGary
1       Sue
2    McBlue
3   Johnson
4       Hue
5  Freebird

In [59]:
data_lab['last_name'] = data_lab[
            'full_name'].str.extract(r'\w+\s(\w+)')
data_lab

   customer_id      full_name first_name last_name
0         1001    John McGary       John    McGary
1         1002      Sally Sue      Sally       Sue
2         1003   Jenny McBlue      Jenny    McBlue
3         1004  Craig Johnson      Craig   Johnson
4         1005      Henry Hue      Henry       Hue
5         1006  Alex Freebird       Alex  Freebird

In [60]:
result = data_lab[['customer_id', 'first_name', 'last_name']]
result

   customer_id first_name last_name
0         1001       John    McGary
1         1002      Sally       Sue
2         1003      Jenny    McBlue
3         1004      Craig   Johnson
4         1005      Henry       Hue
5         1006       Alex  Freebird

<span style='color:green'>


<div style='background-color:lightgray; padding:15px;'>
    
**`Understanding extract() Method`**

The `extract()` method is a powerful tool for extracting captured groups from strings within a Pandas Series or Index using regular expressions. It's particularly useful when you need to pull out specific parts of text based on a defined pattern.

**Key Features:**

  1. `Capturing Groups:` The core of `extract()` lies in its use of capturing groups within regular expressions. Capturing groups are defined by parentheses `(...)` in your regex pattern.  Each group captures a portion of the matched text.

  2. `DataFrame Output:` The extract() method returns a DataFrame, where each captured group becomes a separate column.

  3. `Handling Multiple Matches:` If a row matches multiple times, extract() returns NaN for that row.

</div>

In [61]:
data = pd.Series(['apple-123', 'banana-456', 'cherry-789'])

# Extract the part after the hyphen
result1 = data.str.extract(r'-(\d+)')

print(result1)

     0
0  123
1  456
2  789

In [62]:
result2 = data.str.extract(r'\w+\-(\d+)')
result2

     0
0  123
1  456
2  789

In [63]:
result3 = data.str.extract(r'\-(\d+)')
result3

     0
0  123
1  456
2  789

In [64]:
data = pd.Series(['name=John,age=30', 
                  'name=Alice,age=25', 
                  'name=Bob,age=35'])
data

0     name=John,age=30
1    name=Alice,age=25
2      name=Bob,age=35
dtype: object

In [65]:
# Extract name and age
result = data.str.extract(r'name=(\w+),age=(\d+)')

print(type(result))
result

<class 'pandas.core.frame.DataFrame'>

       0   1
0   John  30
1  Alice  25
2    Bob  35

In [66]:
data = pd.Series(['name=John,age=30', 
                  'name=Alice,age=25', 
                  'name=Bob,age=35'])

# Extract name and age with named groups
result = data.str.extract(r'name=(?P<Name>\w+),age=(?P<Age>\d+)')

print(result)

    Name Age
0   John  30
1  Alice  25
2    Bob  35

---
---
---

<span style='color:red'>

# 6. SPLITTING AND COMBINING COLUMNS

In [67]:
# Scenario 1:
data = {
    'student_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'full_name': ['Harry Potter', 'Hermione Granger', 'Ron Weasley', 
                  'Draco Malfoy', 'Luna Lovegood', 'Neville Longbottom', 
                  'Ginny Weasley', 'Fred Weasley', 'George Weasley', 
                  'Cho Chang'],
    'is_alive': ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 
                 'Yes', 'No', 'Yes', 'Yes']}
dead_or_alive = pd.DataFrame(data)

# ----------------------------------------------------------------------------------
# Scenario 2:
data = {
    'student_id': [1, 2, 3, 4, 5, 6, 7, 8, 9],
    'full_name': ['Harry Potter', 'Hermione Granger', 'Ron Weasley', 
                  'Draco Malfoy', 'Luna Lovegood', 'Neville Longbottom', 
                  'Ginny Weasley', 'Fred Weasley', 'George Weasley'],
    'address': ['12 Grimmauld Place, London, England', 
                '4 Privet Drive, Surrey, England', 
                'The Burrow, Devon, England', 
                '124 Slitheren Street, Wiltshire, England', 
                '869 Light Way, London, England', 
                '4834 Street, Hampshire, England', 
                'The Burrow, Devon, England', 
                'The Burrow, Devon, England', 
                'The Burrow, Devon, England']}
Student_Address = pd.DataFrame(data)

# ----------------------------------------------------------------------------------
# Scenario 3:
data = {
    'First Name': ['Harry', 'Hermione', 'Ron', 'Draco', 'Luna', 'Neville', 
                   'Ginny', 'Fred', 'George'],
    'Last Name': ['Potter', 'Granger', 'Weasley', 'Malfoy', 'Lovegood', 
                  'Longbottom', 'Weasley', 'Weasley', 'Weasley'],
    'Hogwarts House': ['Gryffindor', 'Gryffindor', 'Gryffindor', 
                       'Slytherin', 'Ravenclaw', 'Gryffindor', 'Gryffindor', 
                       'Gryffindor', 'Gryffindor']}
Combine_Names = pd.DataFrame(data)

---
---

<span style='color:red'>

## 6.1. Scenario No.1 - Split Full Name

In [68]:
dead_or_alive

   student_id           full_name is_alive
0           1        Harry Potter      Yes
1           2    Hermione Granger      Yes
2           3         Ron Weasley      Yes
3           4        Draco Malfoy      Yes
4           5       Luna Lovegood      Yes
5           6  Neville Longbottom      Yes
6           7       Ginny Weasley      Yes
7           8        Fred Weasley       No
8           9      George Weasley      Yes
9          10           Cho Chang      Yes

In [69]:
# In this example we will separate the 'full_name' column into two columns
dead_or_alive['full_name'].str.split(' ', 
                                     expand=True)

          0           1
0     Harry      Potter
1  Hermione     Granger
2       Ron     Weasley
3     Draco      Malfoy
4      Luna    Lovegood
5   Neville  Longbottom
6     Ginny     Weasley
7      Fred     Weasley
8    George     Weasley
9       Cho       Chang

In [70]:
dead_or_alive[['first_name', 'last_name']] = dead_or_alive[
                'full_name'].str.split(' ', n=1, expand=True)
dead_or_alive

   student_id           full_name is_alive first_name   last_name
0           1        Harry Potter      Yes      Harry      Potter
1           2    Hermione Granger      Yes   Hermione     Granger
2           3         Ron Weasley      Yes        Ron     Weasley
3           4        Draco Malfoy      Yes      Draco      Malfoy
4           5       Luna Lovegood      Yes       Luna    Lovegood
5           6  Neville Longbottom      Yes    Neville  Longbottom
6           7       Ginny Weasley      Yes      Ginny     Weasley
7           8        Fred Weasley       No       Fred     Weasley
8           9      George Weasley      Yes     George     Weasley
9          10           Cho Chang      Yes        Cho       Chang

---
---

<span style='color:red'>

## 6.2. Scenario No.2 - Split Full Address

In [71]:
Student_Address

   student_id           full_name                                   address
0           1        Harry Potter       12 Grimmauld Place, London, England
1           2    Hermione Granger           4 Privet Drive, Surrey, England
2           3         Ron Weasley                The Burrow, Devon, England
3           4        Draco Malfoy  124 Slitheren Street, Wiltshire, England
4           5       Luna Lovegood            869 Light Way, London, England
5           6  Neville Longbottom           4834 Street, Hampshire, England
6           7       Ginny Weasley                The Burrow, Devon, England
7           8        Fred Weasley                The Burrow, Devon, England
8           9      George Weasley                The Burrow, Devon, England

In [72]:
Student_Address['address'].str.split(',', 
                                     n=2, expand=True)

                      0           1         2
0    12 Grimmauld Place      London   England
1        4 Privet Drive      Surrey   England
2            The Burrow       Devon   England
3  124 Slitheren Street   Wiltshire   England
4         869 Light Way      London   England
5           4834 Street   Hampshire   England
6            The Burrow       Devon   England
7            The Burrow       Devon   England
8            The Burrow       Devon   England

In [73]:
Student_Address[['st_address', 
                 'City', 'Country']] = Student_Address[
                    'address'].str.split(',', n=2, expand=True)
Student_Address

,student_id,full_name,address,st_address,City,Country
0,1,Harry Potter,"12 Grimmauld Place, London, England",12 Grimmauld Place,London,England
1,2,Hermione Granger,"4 Privet Drive, Surrey, England",4 Privet Drive,Surrey,England
2,3,Ron Weasley,"The Burrow, Devon, England",The Burrow,Devon,England
3,4,Draco Malfoy,"124 Slitheren Street, Wiltshire, England",124 Slitheren Street,Wiltshire,England
4,5,Luna Lovegood,"869 Light Way, London, England",869 Light Way,London,England
5,6,Neville Longbottom,"4834 Street, Hampshire, England",4834 Street,Hampshire,England
6,7,Ginny Weasley,"The Burrow, Devon, England",The Burrow,Devon,England
7,8,Fred Weasley,"The Burrow, Devon, England",The Burrow,Devon,England
8,9,George Weasley,"The Burrow, Devon, England",The Burrow,Devon,England

---
---

<span style='color:red'>

## 6.2. Scenario No.3 - Combine Columns

In [74]:
Combine_Names

  First Name   Last Name Hogwarts House
0      Harry      Potter     Gryffindor
1   Hermione     Granger     Gryffindor
2        Ron     Weasley     Gryffindor
3      Draco      Malfoy      Slytherin
4       Luna    Lovegood      Ravenclaw
5    Neville  Longbottom     Gryffindor
6      Ginny     Weasley     Gryffindor
7       Fred     Weasley     Gryffindor
8     George     Weasley     Gryffindor

In [75]:
Combine_Names['First Name'] + ' ' + Combine_Names['Last Name']

0          Harry Potter
1      Hermione Granger
2           Ron Weasley
3          Draco Malfoy
4         Luna Lovegood
5    Neville Longbottom
6         Ginny Weasley
7          Fred Weasley
8        George Weasley
dtype: object

In [76]:
Combine_Names['Full Name'] = Combine_Names[
                'First Name'] + ' ' + Combine_Names['Last Name']
Combine_Names

  First Name   Last Name Hogwarts House           Full Name
0      Harry      Potter     Gryffindor        Harry Potter
1   Hermione     Granger     Gryffindor    Hermione Granger
2        Ron     Weasley     Gryffindor         Ron Weasley
3      Draco      Malfoy      Slytherin        Draco Malfoy
4       Luna    Lovegood      Ravenclaw       Luna Lovegood
5    Neville  Longbottom     Gryffindor  Neville Longbottom
6      Ginny     Weasley     Gryffindor       Ginny Weasley
7       Fred     Weasley     Gryffindor        Fred Weasley
8     George     Weasley     Gryffindor      George Weasley

In [77]:
# Now using Concat
pd.concat([Combine_Names['First Name'], 
           Combine_Names['Last Name']], axis=1).apply(' '.join, axis=1)

0          Harry Potter
1      Hermione Granger
2           Ron Weasley
3          Draco Malfoy
4         Luna Lovegood
5    Neville Longbottom
6         Ginny Weasley
7          Fred Weasley
8        George Weasley
dtype: object

In [78]:
Combine_Names['Full Name2'] = pd.concat(
    [Combine_Names['First Name'], 
     Combine_Names['Last Name']], axis=1).apply(' - '.join, axis=1)
Combine_Names

,First Name,Last Name,Hogwarts House,Full Name,Full Name2
0,Harry,Potter,Gryffindor,Harry Potter,Harry - Potter
1,Hermione,Granger,Gryffindor,Hermione Granger,Hermione - Granger
2,Ron,Weasley,Gryffindor,Ron Weasley,Ron - Weasley
3,Draco,Malfoy,Slytherin,Draco Malfoy,Draco - Malfoy
4,Luna,Lovegood,Ravenclaw,Luna Lovegood,Luna - Lovegood
5,Neville,Longbottom,Gryffindor,Neville Longbottom,Neville - Longbottom
6,Ginny,Weasley,Gryffindor,Ginny Weasley,Ginny - Weasley
7,Fred,Weasley,Gryffindor,Fred Weasley,Fred - Weasley
8,George,Weasley,Gryffindor,George Weasley,George - Weasley

---
---
---

<span style='color:green'>

# 7. PRACTICE LAB - Breaking Out Column

---

<span style='color:orange'>
    
**Breaking Out Column**

The addresses in this table are in a very strange format. We actually need them broken out into street address, city, state, and zip code, but currently it's pretty unusable.

Write a query to break out this column into street, city, state, and zip_code with those names exactly.

---

In [79]:
addresses = pd.DataFrame({'address':['123 Main St- Anytown- CA- 12345',
                                  '456 Elm St- Springfield- IL- 67890', 
                                  '789 Oak Ave- Newtown- PA- 23456',
                                  '1010 Maple Dr- Greensboro- NC- 34567',
                                  '1313 Pine St- Seattle- WA- 45678']})

addresses

                                address
0       123 Main St- Anytown- CA- 12345
1    456 Elm St- Springfield- IL- 67890
2       789 Oak Ave- Newtown- PA- 23456
3  1010 Maple Dr- Greensboro- NC- 34567
4      1313 Pine St- Seattle- WA- 45678

In [80]:
addresses[['street', 'city', 'state', 'zip_code']] = addresses['address'].str.split('- ', n=3, expand=True)
addresses

,address,street,city,state,zip_code
0,123 Main St- Anytown- CA- 12345,123 Main St,Anytown,CA,12345
1,456 Elm St- Springfield- IL- 67890,456 Elm St,Springfield,IL,67890
2,789 Oak Ave- Newtown- PA- 23456,789 Oak Ave,Newtown,PA,23456
3,1010 Maple Dr- Greensboro- NC- 34567,1010 Maple Dr,Greensboro,NC,34567
4,1313 Pine St- Seattle- WA- 45678,1313 Pine St,Seattle,WA,45678

In [81]:
addresses.drop(labels='address', axis=1, inplace=True)
addresses

          street         city state zip_code
0    123 Main St      Anytown    CA    12345
1     456 Elm St  Springfield    IL    67890
2    789 Oak Ave      Newtown    PA    23456
3  1010 Maple Dr   Greensboro    NC    34567
4   1313 Pine St      Seattle    WA    45678

---
---
---

<span style='color:red'>

# 8. WORKING WITH NULL VALUES

In [82]:
# Scenarion No. 1
data1 = {
    'First Name': ['Harry', 'Hermione', 'Ron', 'Draco', 'Luna', 
                   np.nan, np.nan],
    'Last Name': ['Potter', 'Granger', 'Weasley', 'Malfoy', np.nan, 
                  'Lovegood', np.nan],
    'Hogwarts House': ['Gryffindor', 'Gryffindor', 'Gryffindor', 
                       np.nan, 'Ravenclaw', 'Gryffindor', np.nan],
    'Age': [18, 17, np.nan, 16, 16, 18, np.nan]}
Nulls = pd.DataFrame(data1)

# ----------------------------------------------------------------------------------
# Scenario No. 2
data2= {
    'First name': ['Harry', 'Harry', 'Hermione', 'Hermione', 'Ron', 'Ron', 
                   'Draco', 'Draco', 'Luna', 'Luna', 'Neville', 'Neville', 
                   'Ginny', 'Ginny', 'Fred', 'Fred', 'George', 'George', 
                   'Cho', 'Cho', 'Cedric', 'Cedric', 'Sirius', 'Sirius', 
                   'Remus', 'Remus'],
    'Last name': ['Potter', np.nan, 'Granger', 'Granger', 'Weasley', 
                  'Weasley', 'Malfoy', 'Malfoy', 'Lovegood', 'Lovegood', 
                  'Longbottom', 'Longbottom', 'Weasley', 'Weasley', 
                  'Weasley', 'Weasley', 'Weasley', 'Weasley', 'Chang', 
                  'Chang', 'Diggory', 'Diggory', 'Black', 'Black', 
                  'Lupin', 'Lupin'],
    'Hogwarts house': ['Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', 
                       np.nan, 'Gryffindor', 'Slytherin', 'Slytherin', 
                       'Ravenclaw', 'Ravenclaw', 'Gryffindor', 'Gryffindor', 
                       'Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', 
                       'Gryffindor', 'Gryffindor', 'Ravenclaw', 'Ravenclaw', 
                       'Hufflepuff', 'Hufflepuff', 'Gryffindor', 'Gryffindor', 
                       'Gryffindor', 'Gryffindor'],
    'Transaction_ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, np.nan, 
                       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
    'Transaction_amount': [50, 75, 30, 20, 45, 60, 55, 80, 65, 70, 40, 85, 90, 
                           55, 60, 75, 80, 35, 40, 95, 50, 65, 70, 25, 30, 45]}
df = pd.DataFrame(data2)

In [83]:
Nulls

  First Name Last Name Hogwarts House   Age
0      Harry    Potter     Gryffindor  18.0
1   Hermione   Granger     Gryffindor  17.0
2        Ron   Weasley     Gryffindor   NaN
3      Draco    Malfoy            NaN  16.0
4       Luna       NaN      Ravenclaw  16.0
5        NaN  Lovegood     Gryffindor  18.0
6        NaN       NaN            NaN   NaN

In [84]:
one = Nulls.dropna(axis=1)
one

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [85]:
Nulls.dropna(axis=0)

  First Name Last Name Hogwarts House   Age
0      Harry    Potter     Gryffindor  18.0
1   Hermione   Granger     Gryffindor  17.0

In [86]:
Nulls.dropna(subset=['Age'])

  First Name Last Name Hogwarts House   Age
0      Harry    Potter     Gryffindor  18.0
1   Hermione   Granger     Gryffindor  17.0
3      Draco    Malfoy            NaN  16.0
4       Luna       NaN      Ravenclaw  16.0
5        NaN  Lovegood     Gryffindor  18.0

In [87]:
Nulls.dropna(subset=['Last Name'])

  First Name Last Name Hogwarts House   Age
0      Harry    Potter     Gryffindor  18.0
1   Hermione   Granger     Gryffindor  17.0
2        Ron   Weasley     Gryffindor   NaN
3      Draco    Malfoy            NaN  16.0
5        NaN  Lovegood     Gryffindor  18.0

In [97]:
Nulls.dropna(axis=1, subset=4)

  First Name Hogwarts House   Age
0      Harry     Gryffindor  18.0
1   Hermione     Gryffindor  17.0
2        Ron     Gryffindor   NaN
3      Draco            NaN  16.0
4       Luna      Ravenclaw  16.0
5        NaN     Gryffindor  18.0
6        NaN            NaN   NaN

In [98]:
Nulls.dropna(axis=1, subset=3)

  First Name Last Name   Age
0      Harry    Potter  18.0
1   Hermione   Granger  17.0
2        Ron   Weasley   NaN
3      Draco    Malfoy  16.0
4       Luna       NaN  16.0
5        NaN  Lovegood  18.0
6        NaN       NaN   NaN

In [99]:
Nulls.dropna(axis=1, subset=6)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [100]:
Nulls.dropna(how='all')

  First Name Last Name Hogwarts House   Age
0      Harry    Potter     Gryffindor  18.0
1   Hermione   Granger     Gryffindor  17.0
2        Ron   Weasley     Gryffindor   NaN
3      Draco    Malfoy            NaN  16.0
4       Luna       NaN      Ravenclaw  16.0
5        NaN  Lovegood     Gryffindor  18.0

---

**<span style='color:red'>FILLING "NA" VALUES WITH `ffill` AND `bfill`**

In [101]:
Nulls['Age'].fillna(value=Nulls['Age'].mean())

0    18.0
1    17.0
2    17.0
3    16.0
4    16.0
5    18.0
6    17.0
Name: Age, dtype: float64

In [102]:
Nulls.ffill()

  First Name Last Name Hogwarts House   Age
0      Harry    Potter     Gryffindor  18.0
1   Hermione   Granger     Gryffindor  17.0
2        Ron   Weasley     Gryffindor  17.0
3      Draco    Malfoy     Gryffindor  16.0
4       Luna    Malfoy      Ravenclaw  16.0
5       Luna  Lovegood     Gryffindor  18.0
6       Luna  Lovegood     Gryffindor  18.0

In [103]:
Nulls.bfill()

  First Name Last Name Hogwarts House   Age
0      Harry    Potter     Gryffindor  18.0
1   Hermione   Granger     Gryffindor  17.0
2        Ron   Weasley     Gryffindor  16.0
3      Draco    Malfoy      Ravenclaw  16.0
4       Luna  Lovegood      Ravenclaw  16.0
5        NaN  Lovegood     Gryffindor  18.0
6        NaN       NaN            NaN   NaN

In [104]:
Nulls.replace(np.nan, 'Unknown')

  First Name Last Name Hogwarts House      Age
0      Harry    Potter     Gryffindor     18.0
1   Hermione   Granger     Gryffindor     17.0
2        Ron   Weasley     Gryffindor  Unknown
3      Draco    Malfoy        Unknown     16.0
4       Luna   Unknown      Ravenclaw     16.0
5    Unknown  Lovegood     Gryffindor     18.0
6    Unknown   Unknown        Unknown  Unknown

---

**<span style='color:red'>FILLING "NA" VALUES - USING `groupby()` AND `transform()`**

In [105]:
df

   First name   Last name Hogwarts house  Transaction_ID  Transaction_amount
0       Harry      Potter     Gryffindor             1.0                  50
1       Harry         NaN     Gryffindor             2.0                  75
2    Hermione     Granger     Gryffindor             3.0                  30
3    Hermione     Granger     Gryffindor             4.0                  20
4         Ron     Weasley            NaN             5.0                  45
5         Ron     Weasley     Gryffindor             6.0                  60
6       Draco      Malfoy      Slytherin             7.0                  55
7       Draco      Malfoy      Slytherin             8.0                  80
8        Luna    Lovegood      Ravenclaw             9.0                  65
9        Luna    Lovegood      Ravenclaw            10.0                  70
10    Neville  Longbottom     Gryffindor            11.0                  40
11    Neville  Longbottom     Gryffindor            12.0                  85
12      Ginny     Weasley     Gryffindor            13.0                  90
13      Ginny     Weasley     Gryffindor            14.0                  55
14       Fred     Weasley     Gryffindor             NaN                  60
15       Fred     Weasley     Gryffindor            16.0                  75
16     George     Weasley     Gryffindor            17.0                  80
17     George     Weasley     Gryffindor            18.0                  35
18        Cho       Chang      Ravenclaw            19.0                  40
19        Cho       Chang      Ravenclaw            20.0                  95
20     Cedric     Diggory     Hufflepuff            21.0                  50
21     Cedric     Diggory     Hufflepuff            22.0                  65
22     Sirius       Black     Gryffindor            23.0                  70
23     Sirius       Black     Gryffindor            24.0                  25
24      Remus       Lupin     Gryffindor            25.0                  30
25      Remus       Lupin     Gryffindor            26.0                  45

In [106]:
df['Last name'].fillna(df.groupby(
        ['First name', 'Hogwarts house'])['Last name'].transform('first'))

0         Potter
1         Potter
2        Granger
3        Granger
4        Weasley
5        Weasley
6         Malfoy
7         Malfoy
8       Lovegood
9       Lovegood
10    Longbottom
11    Longbottom
12       Weasley
13       Weasley
14       Weasley
15       Weasley
16       Weasley
17       Weasley
18         Chang
19         Chang
20       Diggory
21       Diggory
22         Black
23         Black
24         Lupin
25         Lupin
Name: Last name, dtype: object

In [107]:
df['Last name'] = df['Last name'].fillna(df.groupby(
        ['First name', 'Hogwarts house'])['Last name'].transform('first'))

df

   First name   Last name Hogwarts house  Transaction_ID  Transaction_amount
0       Harry      Potter     Gryffindor             1.0                  50
1       Harry      Potter     Gryffindor             2.0                  75
2    Hermione     Granger     Gryffindor             3.0                  30
3    Hermione     Granger     Gryffindor             4.0                  20
4         Ron     Weasley            NaN             5.0                  45
5         Ron     Weasley     Gryffindor             6.0                  60
6       Draco      Malfoy      Slytherin             7.0                  55
7       Draco      Malfoy      Slytherin             8.0                  80
8        Luna    Lovegood      Ravenclaw             9.0                  65
9        Luna    Lovegood      Ravenclaw            10.0                  70
10    Neville  Longbottom     Gryffindor            11.0                  40
11    Neville  Longbottom     Gryffindor            12.0                  85
12      Ginny     Weasley     Gryffindor            13.0                  90
13      Ginny     Weasley     Gryffindor            14.0                  55
14       Fred     Weasley     Gryffindor             NaN                  60
15       Fred     Weasley     Gryffindor            16.0                  75
16     George     Weasley     Gryffindor            17.0                  80
17     George     Weasley     Gryffindor            18.0                  35
18        Cho       Chang      Ravenclaw            19.0                  40
19        Cho       Chang      Ravenclaw            20.0                  95
20     Cedric     Diggory     Hufflepuff            21.0                  50
21     Cedric     Diggory     Hufflepuff            22.0                  65
22     Sirius       Black     Gryffindor            23.0                  70
23     Sirius       Black     Gryffindor            24.0                  25
24      Remus       Lupin     Gryffindor            25.0                  30
25      Remus       Lupin     Gryffindor            26.0                  45

---

In [108]:
df.groupby(['First name', 'Last name'])['Hogwarts house'].transform('first')

0     Gryffindor
1     Gryffindor
2     Gryffindor
3     Gryffindor
4     Gryffindor
5     Gryffindor
6      Slytherin
7      Slytherin
8      Ravenclaw
9      Ravenclaw
10    Gryffindor
11    Gryffindor
12    Gryffindor
13    Gryffindor
14    Gryffindor
15    Gryffindor
16    Gryffindor
17    Gryffindor
18     Ravenclaw
19     Ravenclaw
20    Hufflepuff
21    Hufflepuff
22    Gryffindor
23    Gryffindor
24    Gryffindor
25    Gryffindor
Name: Hogwarts house, dtype: object

In [109]:
df['Hogwarts house'] = df['Hogwarts house'].fillna(df.groupby(['First name', 
                'Last name'])['Hogwarts house'].transform('first'))
df

   First name   Last name Hogwarts house  Transaction_ID  Transaction_amount
0       Harry      Potter     Gryffindor             1.0                  50
1       Harry      Potter     Gryffindor             2.0                  75
2    Hermione     Granger     Gryffindor             3.0                  30
3    Hermione     Granger     Gryffindor             4.0                  20
4         Ron     Weasley     Gryffindor             5.0                  45
5         Ron     Weasley     Gryffindor             6.0                  60
6       Draco      Malfoy      Slytherin             7.0                  55
7       Draco      Malfoy      Slytherin             8.0                  80
8        Luna    Lovegood      Ravenclaw             9.0                  65
9        Luna    Lovegood      Ravenclaw            10.0                  70
10    Neville  Longbottom     Gryffindor            11.0                  40
11    Neville  Longbottom     Gryffindor            12.0                  85
12      Ginny     Weasley     Gryffindor            13.0                  90
13      Ginny     Weasley     Gryffindor            14.0                  55
14       Fred     Weasley     Gryffindor             NaN                  60
15       Fred     Weasley     Gryffindor            16.0                  75
16     George     Weasley     Gryffindor            17.0                  80
17     George     Weasley     Gryffindor            18.0                  35
18        Cho       Chang      Ravenclaw            19.0                  40
19        Cho       Chang      Ravenclaw            20.0                  95
20     Cedric     Diggory     Hufflepuff            21.0                  50
21     Cedric     Diggory     Hufflepuff            22.0                  65
22     Sirius       Black     Gryffindor            23.0                  70
23     Sirius       Black     Gryffindor            24.0                  25
24      Remus       Lupin     Gryffindor            25.0                  30
25      Remus       Lupin     Gryffindor            26.0                  45

In [114]:
df['Transaction_ID'].fillna(df['Transaction_ID'].ffill() + 10)

0      1.0
1      2.0
2      3.0
3      4.0
4      5.0
5      6.0
6      7.0
7      8.0
8      9.0
9     10.0
10    11.0
11    12.0
12    13.0
13    14.0
14    24.0
15    16.0
16    17.0
17    18.0
18    19.0
19    20.0
20    21.0
21    22.0
22    23.0
23    24.0
24    25.0
25    26.0
Name: Transaction_ID, dtype: float64

In [113]:
df['Transaction_ID'].fillna(df['Transaction_ID'].bfill() - 5)

0      1.0
1      2.0
2      3.0
3      4.0
4      5.0
5      6.0
6      7.0
7      8.0
8      9.0
9     10.0
10    11.0
11    12.0
12    13.0
13    14.0
14    11.0
15    16.0
16    17.0
17    18.0
18    19.0
19    20.0
20    21.0
21    22.0
22    23.0
23    24.0
24    25.0
25    26.0
Name: Transaction_ID, dtype: float64

In [115]:
# Take a look the result we get if we don't use the 'fillna()' method...

df['Transaction_ID'].ffill() + 1

0      2.0
1      3.0
2      4.0
3      5.0
4      6.0
5      7.0
6      8.0
7      9.0
8     10.0
9     11.0
10    12.0
11    13.0
12    14.0
13    15.0
14    15.0
15    17.0
16    18.0
17    19.0
18    20.0
19    21.0
20    22.0
21    23.0
22    24.0
23    25.0
24    26.0
25    27.0
Name: Transaction_ID, dtype: float64

In [116]:
df['Transaction_ID'] = df['Transaction_ID'].fillna(
                            df['Transaction_ID'].ffill() + 1)
df

   First name   Last name Hogwarts house  Transaction_ID  Transaction_amount
0       Harry      Potter     Gryffindor             1.0                  50
1       Harry      Potter     Gryffindor             2.0                  75
2    Hermione     Granger     Gryffindor             3.0                  30
3    Hermione     Granger     Gryffindor             4.0                  20
4         Ron     Weasley     Gryffindor             5.0                  45
5         Ron     Weasley     Gryffindor             6.0                  60
6       Draco      Malfoy      Slytherin             7.0                  55
7       Draco      Malfoy      Slytherin             8.0                  80
8        Luna    Lovegood      Ravenclaw             9.0                  65
9        Luna    Lovegood      Ravenclaw            10.0                  70
10    Neville  Longbottom     Gryffindor            11.0                  40
11    Neville  Longbottom     Gryffindor            12.0                  85
12      Ginny     Weasley     Gryffindor            13.0                  90
13      Ginny     Weasley     Gryffindor            14.0                  55
14       Fred     Weasley     Gryffindor            15.0                  60
15       Fred     Weasley     Gryffindor            16.0                  75
16     George     Weasley     Gryffindor            17.0                  80
17     George     Weasley     Gryffindor            18.0                  35
18        Cho       Chang      Ravenclaw            19.0                  40
19        Cho       Chang      Ravenclaw            20.0                  95
20     Cedric     Diggory     Hufflepuff            21.0                  50
21     Cedric     Diggory     Hufflepuff            22.0                  65
22     Sirius       Black     Gryffindor            23.0                  70
23     Sirius       Black     Gryffindor            24.0                  25
24      Remus       Lupin     Gryffindor            25.0                  30
25      Remus       Lupin     Gryffindor            26.0                  45

In [117]:
# Scenario No. 3 - Checking if it works with more than one missing value 
# ...on the 'Transaction_ID' Column...
data3= {
    'First name': ['Harry', 'Harry', 'Hermione', 'Hermione', 'Ron', 'Ron', 
                   'Draco', 'Draco', 'Luna', 'Luna', 'Neville', 'Neville', 
                   'Ginny', 'Ginny', 'Fred', 'Fred', 'George', 'George', 
                   'Cho', 'Cho', 'Cedric', 'Cedric', 'Sirius', 'Sirius', 
                   'Remus', 'Remus'],
    'Last name': ['Potter', np.nan, 'Granger', 'Granger', 'Weasley', 
                  'Weasley', 'Malfoy', 'Malfoy', 'Lovegood', 'Lovegood', 
                  'Longbottom', 'Longbottom', 'Weasley', 'Weasley', 'Weasley', 
                  'Weasley', 'Weasley', 'Weasley', 'Chang', 'Chang', 'Diggory', 
                  'Diggory', 'Black', 'Black', 'Lupin', 'Lupin'],
    'Hogwarts house': ['Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', 
                       np.nan, 'Gryffindor', 'Slytherin', 'Slytherin', 
                       'Ravenclaw', 'Ravenclaw', 'Gryffindor', 'Gryffindor', 
                       'Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', 
                       'Gryffindor', 'Gryffindor', 'Ravenclaw', 'Ravenclaw', 
                       'Hufflepuff', 'Hufflepuff', 'Gryffindor', 'Gryffindor', 
                       'Gryffindor', 'Gryffindor'],
    'Transaction_ID': [1, 2, np.nan, 4, 5, np.nan, 7, 8, np.nan, 10, 11, 
                       np.nan, 13, 14, np.nan, 16, 17, np.nan, 19, 20, 
                       np.nan, 22, 23, np.nan, 25, 26],
    'Transaction_amount': [50, 75, 30, 20, 45, 60, 55, 80, 65, 70, 40, 85, 90, 
                           55, 60, 75, 80, 35, 40, 95, 50, 65, 70, 25, 30, 45]}
df2 = pd.DataFrame(data3)

In [118]:
df2

   First name   Last name Hogwarts house  Transaction_ID  Transaction_amount
0       Harry      Potter     Gryffindor             1.0                  50
1       Harry         NaN     Gryffindor             2.0                  75
2    Hermione     Granger     Gryffindor             NaN                  30
3    Hermione     Granger     Gryffindor             4.0                  20
4         Ron     Weasley            NaN             5.0                  45
5         Ron     Weasley     Gryffindor             NaN                  60
6       Draco      Malfoy      Slytherin             7.0                  55
7       Draco      Malfoy      Slytherin             8.0                  80
8        Luna    Lovegood      Ravenclaw             NaN                  65
9        Luna    Lovegood      Ravenclaw            10.0                  70
10    Neville  Longbottom     Gryffindor            11.0                  40
11    Neville  Longbottom     Gryffindor             NaN                  85
12      Ginny     Weasley     Gryffindor            13.0                  90
13      Ginny     Weasley     Gryffindor            14.0                  55
14       Fred     Weasley     Gryffindor             NaN                  60
15       Fred     Weasley     Gryffindor            16.0                  75
16     George     Weasley     Gryffindor            17.0                  80
17     George     Weasley     Gryffindor             NaN                  35
18        Cho       Chang      Ravenclaw            19.0                  40
19        Cho       Chang      Ravenclaw            20.0                  95
20     Cedric     Diggory     Hufflepuff             NaN                  50
21     Cedric     Diggory     Hufflepuff            22.0                  65
22     Sirius       Black     Gryffindor            23.0                  70
23     Sirius       Black     Gryffindor             NaN                  25
24      Remus       Lupin     Gryffindor            25.0                  30
25      Remus       Lupin     Gryffindor            26.0                  45

In [119]:
df2['Transaction_ID'].fillna(df2['Transaction_ID'].ffill() + 1)

0      1.0
1      2.0
2      3.0
3      4.0
4      5.0
5      6.0
6      7.0
7      8.0
8      9.0
9     10.0
10    11.0
11    12.0
12    13.0
13    14.0
14    15.0
15    16.0
16    17.0
17    18.0
18    19.0
19    20.0
20    21.0
21    22.0
22    23.0
23    24.0
24    25.0
25    26.0
Name: Transaction_ID, dtype: float64

In [120]:
df2['Transaction_ID'] = df2['Transaction_ID'].fillna(
                            df2['Transaction_ID'].ffill() + 1)
df2

   First name   Last name Hogwarts house  Transaction_ID  Transaction_amount
0       Harry      Potter     Gryffindor             1.0                  50
1       Harry         NaN     Gryffindor             2.0                  75
2    Hermione     Granger     Gryffindor             3.0                  30
3    Hermione     Granger     Gryffindor             4.0                  20
4         Ron     Weasley            NaN             5.0                  45
5         Ron     Weasley     Gryffindor             6.0                  60
6       Draco      Malfoy      Slytherin             7.0                  55
7       Draco      Malfoy      Slytherin             8.0                  80
8        Luna    Lovegood      Ravenclaw             9.0                  65
9        Luna    Lovegood      Ravenclaw            10.0                  70
10    Neville  Longbottom     Gryffindor            11.0                  40
11    Neville  Longbottom     Gryffindor            12.0                  85
12      Ginny     Weasley     Gryffindor            13.0                  90
13      Ginny     Weasley     Gryffindor            14.0                  55
14       Fred     Weasley     Gryffindor            15.0                  60
15       Fred     Weasley     Gryffindor            16.0                  75
16     George     Weasley     Gryffindor            17.0                  80
17     George     Weasley     Gryffindor            18.0                  35
18        Cho       Chang      Ravenclaw            19.0                  40
19        Cho       Chang      Ravenclaw            20.0                  95
20     Cedric     Diggory     Hufflepuff            21.0                  50
21     Cedric     Diggory     Hufflepuff            22.0                  65
22     Sirius       Black     Gryffindor            23.0                  70
23     Sirius       Black     Gryffindor            24.0                  25
24      Remus       Lupin     Gryffindor            25.0                  30
25      Remus       Lupin     Gryffindor            26.0                  45

---
---
---

<span style='color:red'>

# 9. DROPPING COLUMNS AND ROWS

In [121]:
data = {
    'First name': ['Harry', 'Harry', 'Hermione', 'Hermione', 'Ron', 'Ron', 
                   'Draco', 'Draco', 'Luna', 'Luna', 'Neville', 'Neville', 
                   'Ginny', 'Ginny', 'Fred', 'Fred', 'George', 'George', 
                   'Cho', 'Cho', 'Cedric', 'Cedric', 'Sirius', 'Sirius', 
                   'Remus', 'Remus'],
    'Last name': ['Potter', np.nan, 'Granger', 'Granger', 'Weasley', 
                  'Weasley', 'Malfoy', 'Malfoy', 'Lovegood', 'Lovegood', 
                  'Longbottom', 'Longbottom', 'Weasley', 'Weasley', 
                  'Weasley', 'Weasley', 'Weasley', 'Weasley', 'Chang', 
                  'Chang', 'Diggory', 'Diggory', 'Black', 'Black', 
                  'Lupin', 'Lupin'],
    'Hogwarts house': ['Gryffindor', 'Gryffindor', 'Gryffindor', 
                       'Gryffindor', np.nan, 'Gryffindor', 'Slytherin', 
                       'Slytherin', 'Ravenclaw', 'Ravenclaw', 'Gryffindor', 
                       'Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', 
                       'Gryffindor', 'Gryffindor', 'Gryffindor', 'Ravenclaw', 
                       'Ravenclaw', 'Hufflepuff', 'Hufflepuff', 'Gryffindor', 
                       'Gryffindor', 'Gryffindor', 'Gryffindor'],
    'Transaction_ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, np.nan, 
                       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
    'Transaction_amount': [50, 75, 30, 20, 45, 60, 55, 80, 65, 70, 40, 85, 90, 
                           55, 60, 75, 80, 35, 40, 95, 50, 65, 70, 25, 30, 45],
    'Favorite Color': ['red', 'blue', 'green', 'yellow', 'orange', 'red', 
                       'blue', 'green', 'yellow', 'orange', 'red', 'blue', 
                       'green', 'yellow', 'orange', 'red', 'blue', 'green', 
                       'yellow', 'orange', 'red', 'blue', 'green', 'yellow', 
                       'orange', 'red']}
df = pd.DataFrame(data)
df

,First name,Last name,Hogwarts house,Transaction_ID,Transaction_amount,Favorite Color
0,Harry,Potter,Gryffindor,1.0,50,red
1,Harry,NaN,Gryffindor,2.0,75,blue
2,Hermione,Granger,Gryffindor,3.0,30,green
3,Hermione,Granger,Gryffindor,4.0,20,yellow
4,Ron,Weasley,NaN,5.0,45,orange
5,Ron,Weasley,Gryffindor,6.0,60,red
6,Draco,Malfoy,Slytherin,7.0,55,blue
7,Draco,Malfoy,Slytherin,8.0,80,green
8,Luna,Lovegood,Ravenclaw,9.0,65,yellow
9,Luna,Lovegood,Ravenclaw,10.0,70,orange
10,Neville,Longbottom,Gryffindor,11.0,40,red
11,Neville,Longbottom,Gryffindor,12.0,85,blue
12,Ginny,Weasley,Gryffindor,13.0,90,green
13,Ginny,Weasley,Gryffindor,14.0,55,yellow
14,Fred,Weasley,Gryffindor,NaN,60,orange
15,Fred,Weasley,Gryffindor,16.0,75,red
16,George,Weasley,Gryffindor,17.0,80,blue
17,George,Weasley,Gryffindor,18.0,35,green
18,Cho,Chang,Ravenclaw,19.0,40,yellow
19,Cho,Chang,Ravenclaw,20.0,95,orange
20,Cedric,Diggory,Hufflepuff,21.0,50,red
21,Cedric,Diggory,Hufflepuff,22.0,65,blue
22,Sirius,Black,Gryffindor,23.0,70,green
23,Sirius,Black,Gryffindor,24.0,25,yellow
24,Remus,Lupin,Gryffindor,25.0,30,orange
25,Remus,Lupin,Gryffindor,26.0,45,red

In [122]:
df.drop(labels='Favorite Color', axis=1).head()

  First name Last name Hogwarts house  Transaction_ID  Transaction_amount
0      Harry    Potter     Gryffindor             1.0                  50
1      Harry       NaN     Gryffindor             2.0                  75
2   Hermione   Granger     Gryffindor             3.0                  30
3   Hermione   Granger     Gryffindor             4.0                  20
4        Ron   Weasley            NaN             5.0                  45

In [123]:
df.drop(labels=['Favorite Color', 'Hogwarts house'], axis=1).head()

  First name Last name  Transaction_ID  Transaction_amount
0      Harry    Potter             1.0                  50
1      Harry       NaN             2.0                  75
2   Hermione   Granger             3.0                  30
3   Hermione   Granger             4.0                  20
4        Ron   Weasley             5.0                  45

In [124]:
del df['Favorite Color']
df

   First name   Last name Hogwarts house  Transaction_ID  Transaction_amount
0       Harry      Potter     Gryffindor             1.0                  50
1       Harry         NaN     Gryffindor             2.0                  75
2    Hermione     Granger     Gryffindor             3.0                  30
3    Hermione     Granger     Gryffindor             4.0                  20
4         Ron     Weasley            NaN             5.0                  45
5         Ron     Weasley     Gryffindor             6.0                  60
6       Draco      Malfoy      Slytherin             7.0                  55
7       Draco      Malfoy      Slytherin             8.0                  80
8        Luna    Lovegood      Ravenclaw             9.0                  65
9        Luna    Lovegood      Ravenclaw            10.0                  70
10    Neville  Longbottom     Gryffindor            11.0                  40
11    Neville  Longbottom     Gryffindor            12.0                  85
12      Ginny     Weasley     Gryffindor            13.0                  90
13      Ginny     Weasley     Gryffindor            14.0                  55
14       Fred     Weasley     Gryffindor             NaN                  60
15       Fred     Weasley     Gryffindor            16.0                  75
16     George     Weasley     Gryffindor            17.0                  80
17     George     Weasley     Gryffindor            18.0                  35
18        Cho       Chang      Ravenclaw            19.0                  40
19        Cho       Chang      Ravenclaw            20.0                  95
20     Cedric     Diggory     Hufflepuff            21.0                  50
21     Cedric     Diggory     Hufflepuff            22.0                  65
22     Sirius       Black     Gryffindor            23.0                  70
23     Sirius       Black     Gryffindor            24.0                  25
24      Remus       Lupin     Gryffindor            25.0                  30
25      Remus       Lupin     Gryffindor            26.0                  45

In [125]:
data = {
    'Transaction ID': [101, np.nan , 103, 104, 105, 106],
    'Customer Name': ['Harry Potter',  np.nan, 'Ron Weasley', 
                      'Draco Malfoy', 'Luna Lovegood', 'Draco Malfoy'],
    'Wand': ['Elder Wand', np.nan , 'Hawthorn', 'Dragon Heartstring', 
             'Thestral Tail Hair', 'Dragon Heartstring'],
    'Price': [100,  np.nan, 50,  80, 6000000,  np.nan]}

Wand_Transactions = pd.DataFrame(data)
Wand_Transactions

   Transaction ID  Customer Name                Wand      Price
0           101.0   Harry Potter          Elder Wand      100.0
1             NaN            NaN                 NaN        NaN
2           103.0    Ron Weasley            Hawthorn       50.0
3           104.0   Draco Malfoy  Dragon Heartstring       80.0
4           105.0  Luna Lovegood  Thestral Tail Hair  6000000.0
5           106.0   Draco Malfoy  Dragon Heartstring        NaN

In [126]:
Wand_Transactions.dropna(subset=['Transaction ID'])

   Transaction ID  Customer Name                Wand      Price
0           101.0   Harry Potter          Elder Wand      100.0
2           103.0    Ron Weasley            Hawthorn       50.0
3           104.0   Draco Malfoy  Dragon Heartstring       80.0
4           105.0  Luna Lovegood  Thestral Tail Hair  6000000.0
5           106.0   Draco Malfoy  Dragon Heartstring        NaN

In [128]:
Wand_Transactions

   Transaction ID  Customer Name                Wand      Price
0           101.0   Harry Potter          Elder Wand      100.0
1             NaN            NaN                 NaN        NaN
2           103.0    Ron Weasley            Hawthorn       50.0
3           104.0   Draco Malfoy  Dragon Heartstring       80.0
4           105.0  Luna Lovegood  Thestral Tail Hair  6000000.0
5           106.0   Draco Malfoy  Dragon Heartstring        NaN

In [130]:
Wand_Transactions[Wand_Transactions['Price'] > 2000].index

Index([4], dtype='int64')

In [131]:
# Now I will try to drop the outliner row, which is the row No. 4...

Wand_Transactions.drop(Wand_Transactions[Wand_Transactions['Price'] > 2000].index)

   Transaction ID Customer Name                Wand  Price
0           101.0  Harry Potter          Elder Wand  100.0
1             NaN           NaN                 NaN    NaN
2           103.0   Ron Weasley            Hawthorn   50.0
3           104.0  Draco Malfoy  Dragon Heartstring   80.0
5           106.0  Draco Malfoy  Dragon Heartstring    NaN

---
---
---

<span style='color:green'>

# 10. PRACTICE LAB - Sandwich Generation

Yan is a sandwich enthusiast and is determined to try every combination of sandwich possible. He wants to start with every combination of bread and meats and then move on from there, but he wants to do it in a systematic way.

Below we have 2 tables, bread and meats

Output every possible combination of bread and meats to help Yan in his endeavors.

Order by the bread and then meat alphabetically. This is what Yan prefers.

In [132]:
d1 = {'bread_id': [1, 2, 3, 4], 
      'bread_name': ['Whole Wheat', 'White', 
                     'Sourdough', 'Brioche']}
bread_table = pd.DataFrame(d1)

d2 = {
    'meat_id': [1, 2, 3, 4, 5, 6, 7],
    'meat_name':['Turkey', 'Ham', 'Roast Beef', 
                 'Pastrami', 'Salami', 
                 'Chicken', 'Bacon']}
meat_table = pd.DataFrame(d2)

In [133]:
df1 = bread_table.assign(key=1)
df1

   bread_id   bread_name  key
0         1  Whole Wheat    1
1         2        White    1
2         3    Sourdough    1
3         4      Brioche    1

In [134]:
df2 = meat_table.assign(key=1)
df2

   meat_id   meat_name  key
0        1      Turkey    1
1        2         Ham    1
2        3  Roast Beef    1
3        4    Pastrami    1
4        5      Salami    1
5        6     Chicken    1
6        7       Bacon    1

In [135]:
merged_df = pd.merge(df1, df2, on='key', how='inner')
merged_df

    bread_id   bread_name  key  meat_id   meat_name
0          1  Whole Wheat    1        1      Turkey
1          1  Whole Wheat    1        2         Ham
2          1  Whole Wheat    1        3  Roast Beef
3          1  Whole Wheat    1        4    Pastrami
4          1  Whole Wheat    1        5      Salami
5          1  Whole Wheat    1        6     Chicken
6          1  Whole Wheat    1        7       Bacon
7          2        White    1        1      Turkey
8          2        White    1        2         Ham
9          2        White    1        3  Roast Beef
10         2        White    1        4    Pastrami
11         2        White    1        5      Salami
12         2        White    1        6     Chicken
13         2        White    1        7       Bacon
14         3    Sourdough    1        1      Turkey
15         3    Sourdough    1        2         Ham
16         3    Sourdough    1        3  Roast Beef
17         3    Sourdough    1        4    Pastrami
18         3    Sourdough    1        5      Salami
19         3    Sourdough    1        6     Chicken
20         3    Sourdough    1        7       Bacon
21         4      Brioche    1        1      Turkey
22         4      Brioche    1        2         Ham
23         4      Brioche    1        3  Roast Beef
24         4      Brioche    1        4    Pastrami
25         4      Brioche    1        5      Salami
26         4      Brioche    1        6     Chicken
27         4      Brioche    1        7       Bacon

In [140]:
# Trial No. 1
pd.merge(df1, df2, on='key', how='outer')

    bread_id   bread_name  key  meat_id   meat_name
0          1  Whole Wheat    1        1      Turkey
1          1  Whole Wheat    1        2         Ham
2          1  Whole Wheat    1        3  Roast Beef
3          1  Whole Wheat    1        4    Pastrami
4          1  Whole Wheat    1        5      Salami
5          1  Whole Wheat    1        6     Chicken
6          1  Whole Wheat    1        7       Bacon
7          2        White    1        1      Turkey
8          2        White    1        2         Ham
9          2        White    1        3  Roast Beef
10         2        White    1        4    Pastrami
11         2        White    1        5      Salami
12         2        White    1        6     Chicken
13         2        White    1        7       Bacon
14         3    Sourdough    1        1      Turkey
15         3    Sourdough    1        2         Ham
16         3    Sourdough    1        3  Roast Beef
17         3    Sourdough    1        4    Pastrami
18         3    Sourdough    1        5      Salami
19         3    Sourdough    1        6     Chicken
20         3    Sourdough    1        7       Bacon
21         4      Brioche    1        1      Turkey
22         4      Brioche    1        2         Ham
23         4      Brioche    1        3  Roast Beef
24         4      Brioche    1        4    Pastrami
25         4      Brioche    1        5      Salami
26         4      Brioche    1        6     Chicken
27         4      Brioche    1        7       Bacon

In [142]:
# Trial No. 2
pd.merge(df1, df2, on='key', how='left')

    bread_id   bread_name  key  meat_id   meat_name
0          1  Whole Wheat    1        1      Turkey
1          1  Whole Wheat    1        2         Ham
2          1  Whole Wheat    1        3  Roast Beef
3          1  Whole Wheat    1        4    Pastrami
4          1  Whole Wheat    1        5      Salami
5          1  Whole Wheat    1        6     Chicken
6          1  Whole Wheat    1        7       Bacon
7          2        White    1        1      Turkey
8          2        White    1        2         Ham
9          2        White    1        3  Roast Beef
10         2        White    1        4    Pastrami
11         2        White    1        5      Salami
12         2        White    1        6     Chicken
13         2        White    1        7       Bacon
14         3    Sourdough    1        1      Turkey
15         3    Sourdough    1        2         Ham
16         3    Sourdough    1        3  Roast Beef
17         3    Sourdough    1        4    Pastrami
18         3    Sourdough    1        5      Salami
19         3    Sourdough    1        6     Chicken
20         3    Sourdough    1        7       Bacon
21         4      Brioche    1        1      Turkey
22         4      Brioche    1        2         Ham
23         4      Brioche    1        3  Roast Beef
24         4      Brioche    1        4    Pastrami
25         4      Brioche    1        5      Salami
26         4      Brioche    1        6     Chicken
27         4      Brioche    1        7       Bacon

In [143]:
# Trial No. 3
pd.merge(df1, df2, on='key', how='right')

    bread_id   bread_name  key  meat_id   meat_name
0          1  Whole Wheat    1        1      Turkey
1          2        White    1        1      Turkey
2          3    Sourdough    1        1      Turkey
3          4      Brioche    1        1      Turkey
4          1  Whole Wheat    1        2         Ham
5          2        White    1        2         Ham
6          3    Sourdough    1        2         Ham
7          4      Brioche    1        2         Ham
8          1  Whole Wheat    1        3  Roast Beef
9          2        White    1        3  Roast Beef
10         3    Sourdough    1        3  Roast Beef
11         4      Brioche    1        3  Roast Beef
12         1  Whole Wheat    1        4    Pastrami
13         2        White    1        4    Pastrami
14         3    Sourdough    1        4    Pastrami
15         4      Brioche    1        4    Pastrami
16         1  Whole Wheat    1        5      Salami
17         2        White    1        5      Salami
18         3    Sourdough    1        5      Salami
19         4      Brioche    1        5      Salami
20         1  Whole Wheat    1        6     Chicken
21         2        White    1        6     Chicken
22         3    Sourdough    1        6     Chicken
23         4      Brioche    1        6     Chicken
24         1  Whole Wheat    1        7       Bacon
25         2        White    1        7       Bacon
26         3    Sourdough    1        7       Bacon
27         4      Brioche    1        7       Bacon

In [144]:
# Trial No. 4
pd.merge(df1, df2, on='key', how='cross')

MergeError: Can not pass on, right_on, left_on or set right_index=True or left_index=True

In [145]:
result = merged_df[['bread_name', 'meat_name']].sort_values(by=['bread_name', 'meat_name'])
result

     bread_name   meat_name
27      Brioche       Bacon
26      Brioche     Chicken
22      Brioche         Ham
24      Brioche    Pastrami
23      Brioche  Roast Beef
25      Brioche      Salami
21      Brioche      Turkey
20    Sourdough       Bacon
19    Sourdough     Chicken
15    Sourdough         Ham
17    Sourdough    Pastrami
16    Sourdough  Roast Beef
18    Sourdough      Salami
14    Sourdough      Turkey
13        White       Bacon
12        White     Chicken
8         White         Ham
10        White    Pastrami
9         White  Roast Beef
11        White      Salami
7         White      Turkey
6   Whole Wheat       Bacon
5   Whole Wheat     Chicken
1   Whole Wheat         Ham
3   Whole Wheat    Pastrami
2   Whole Wheat  Roast Beef
4   Whole Wheat      Salami
0   Whole Wheat      Turkey