<span style='color:red'>

# TITLE: `INTRODUCTION TO POLARS`

</span>

---
---
---

<span style='color:red'>

# 1. WHAT IS POLARS?

---

<div style='background-color:lightgray; padding:15px;'>

<span style='color:black'>

1. Polars is a DataFrame library in Python and is heavily inspired by `Pandas`.

2. Polars is meant to be a more advanced Pandas in speed of execution and handling larger amounts of data.

3. Polars is not as matures a `Pandas` and is not as widely supported, but is becomming more popular in the data world.

---

<center><img src='images/14.png' width=570></center>

---

</div>

---

---
---
---

<span style='color:red'>

# 2. POLARS BASICS?

In [1]:
! pip install polars

Requirement already satisfied: polars in d:\analyst_builder\buildenv\lib\site-packages (1.27.1)

In [2]:
import polars as pl

In [3]:
insurance = pl.read_csv('datasets/health_insurance.csv')
insurance.head()

shape: (5, 7)
┌─────┬────────┬────────┬──────────┬────────┬───────────┬─────────────┐
│ age ┆ sex    ┆ bmi    ┆ children ┆ smoker ┆ region    ┆ charges     │
│ --- ┆ ---    ┆ ---    ┆ ---      ┆ ---    ┆ ---       ┆ ---         │
│ i64 ┆ str    ┆ f64    ┆ i64      ┆ str    ┆ str       ┆ f64         │
╞═════╪════════╪════════╪══════════╪════════╪═══════════╪═════════════╡
│ 19  ┆ female ┆ 27.9   ┆ 0        ┆ yes    ┆ southwest ┆ 16884.924   │
│ 18  ┆ male   ┆ 33.77  ┆ 1        ┆ no     ┆ southeast ┆ 1725.5523   │
│ 28  ┆ male   ┆ 33.0   ┆ 3        ┆ no     ┆ southeast ┆ 4449.462    │
│ 33  ┆ male   ┆ 22.705 ┆ 0        ┆ no     ┆ northwest ┆ 21984.47061 │
│ 32  ┆ male   ┆ 28.88  ┆ 0        ┆ no     ┆ northwest ┆ 3866.8552   │
└─────┴────────┴────────┴──────────┴────────┴───────────┴─────────────┘

In [5]:
insurance.select(pl.col('smoker'))

shape: (1_338, 1)
┌────────┐
│ smoker │
│ ---    │
│ str    │
╞════════╡
│ yes    │
│ no     │
│ no     │
│ no     │
│ no     │
│ …      │
│ no     │
│ no     │
│ no     │
│ no     │
│ yes    │
└────────┘

In [6]:
insurance.select(pl.col('smoker', 'sex', 'age'))

shape: (1_338, 3)
┌────────┬────────┬─────┐
│ smoker ┆ sex    ┆ age │
│ ---    ┆ ---    ┆ --- │
│ str    ┆ str    ┆ i64 │
╞════════╪════════╪═════╡
│ yes    ┆ female ┆ 19  │
│ no     ┆ male   ┆ 18  │
│ no     ┆ male   ┆ 28  │
│ no     ┆ male   ┆ 33  │
│ no     ┆ male   ┆ 32  │
│ …      ┆ …      ┆ …   │
│ no     ┆ male   ┆ 50  │
│ no     ┆ female ┆ 18  │
│ no     ┆ female ┆ 18  │
│ no     ┆ female ┆ 21  │
│ yes    ┆ female ┆ 61  │
└────────┴────────┴─────┘

In [7]:
insurance.select(pl.col('*'))

shape: (1_338, 7)
┌─────┬────────┬────────┬──────────┬────────┬───────────┬─────────────┐
│ age ┆ sex    ┆ bmi    ┆ children ┆ smoker ┆ region    ┆ charges     │
│ --- ┆ ---    ┆ ---    ┆ ---      ┆ ---    ┆ ---       ┆ ---         │
│ i64 ┆ str    ┆ f64    ┆ i64      ┆ str    ┆ str       ┆ f64         │
╞═════╪════════╪════════╪══════════╪════════╪═══════════╪═════════════╡
│ 19  ┆ female ┆ 27.9   ┆ 0        ┆ yes    ┆ southwest ┆ 16884.924   │
│ 18  ┆ male   ┆ 33.77  ┆ 1        ┆ no     ┆ southeast ┆ 1725.5523   │
│ 28  ┆ male   ┆ 33.0   ┆ 3        ┆ no     ┆ southeast ┆ 4449.462    │
│ 33  ┆ male   ┆ 22.705 ┆ 0        ┆ no     ┆ northwest ┆ 21984.47061 │
│ 32  ┆ male   ┆ 28.88  ┆ 0        ┆ no     ┆ northwest ┆ 3866.8552   │
│ …   ┆ …      ┆ …      ┆ …        ┆ …      ┆ …         ┆ …           │
│ 50  ┆ male   ┆ 30.97  ┆ 3        ┆ no     ┆ northwest ┆ 10600.5483  │
│ 18  ┆ female ┆ 31.92  ┆ 0        ┆ no     ┆ northeast ┆ 2205.9808   │
│ 18  ┆ female ┆ 36.85  ┆ 0        ┆ no     ┆ southeast ┆ 1629.8335   │
│ 21  ┆ female ┆ 25.8   ┆ 0        ┆ no     ┆ southwest ┆ 2007.945    │
│ 61  ┆ female ┆ 29.07  ┆ 0        ┆ yes    ┆ northwest ┆ 29141.3603  │
└─────┴────────┴────────┴──────────┴────────┴───────────┴─────────────┘

In [9]:
insurance_month = insurance.with_columns((pl.col('charges')/12).alias('charges_per_month'))
insurance_month

shape: (1_338, 8)
┌─────┬────────┬────────┬──────────┬────────┬───────────┬─────────────┬───────────────────┐
│ age ┆ sex    ┆ bmi    ┆ children ┆ smoker ┆ region    ┆ charges     ┆ charges_per_month │
│ --- ┆ ---    ┆ ---    ┆ ---      ┆ ---    ┆ ---       ┆ ---         ┆ ---               │
│ i64 ┆ str    ┆ f64    ┆ i64      ┆ str    ┆ str       ┆ f64         ┆ f64               │
╞═════╪════════╪════════╪══════════╪════════╪═══════════╪═════════════╪═══════════════════╡
│ 19  ┆ female ┆ 27.9   ┆ 0        ┆ yes    ┆ southwest ┆ 16884.924   ┆ 1407.077          │
│ 18  ┆ male   ┆ 33.77  ┆ 1        ┆ no     ┆ southeast ┆ 1725.5523   ┆ 143.796025        │
│ 28  ┆ male   ┆ 33.0   ┆ 3        ┆ no     ┆ southeast ┆ 4449.462    ┆ 370.7885          │
│ 33  ┆ male   ┆ 22.705 ┆ 0        ┆ no     ┆ northwest ┆ 21984.47061 ┆ 1832.039217       │
│ 32  ┆ male   ┆ 28.88  ┆ 0        ┆ no     ┆ northwest ┆ 3866.8552   ┆ 322.237933        │
│ …   ┆ …      ┆ …      ┆ …        ┆ …      ┆ …         ┆ …           ┆ …                 │
│ 50  ┆ male   ┆ 30.97  ┆ 3        ┆ no     ┆ northwest ┆ 10600.5483  ┆ 883.379025        │
│ 18  ┆ female ┆ 31.92  ┆ 0        ┆ no     ┆ northeast ┆ 2205.9808   ┆ 183.831733        │
│ 18  ┆ female ┆ 36.85  ┆ 0        ┆ no     ┆ southeast ┆ 1629.8335   ┆ 135.819458        │
│ 21  ┆ female ┆ 25.8   ┆ 0        ┆ no     ┆ southwest ┆ 2007.945    ┆ 167.32875         │
│ 61  ┆ female ┆ 29.07  ┆ 0        ┆ yes    ┆ northwest ┆ 29141.3603  ┆ 2428.446692       │
└─────┴────────┴────────┴──────────┴────────┴───────────┴─────────────┴───────────────────┘

In [10]:
insurance_month.filter(pl.col('age') >= 30)

shape: (921, 8)
┌─────┬────────┬────────┬──────────┬────────┬───────────┬─────────────┬───────────────────┐
│ age ┆ sex    ┆ bmi    ┆ children ┆ smoker ┆ region    ┆ charges     ┆ charges_per_month │
│ --- ┆ ---    ┆ ---    ┆ ---      ┆ ---    ┆ ---       ┆ ---         ┆ ---               │
│ i64 ┆ str    ┆ f64    ┆ i64      ┆ str    ┆ str       ┆ f64         ┆ f64               │
╞═════╪════════╪════════╪══════════╪════════╪═══════════╪═════════════╪═══════════════════╡
│ 33  ┆ male   ┆ 22.705 ┆ 0        ┆ no     ┆ northwest ┆ 21984.47061 ┆ 1832.039217       │
│ 32  ┆ male   ┆ 28.88  ┆ 0        ┆ no     ┆ northwest ┆ 3866.8552   ┆ 322.237933        │
│ 31  ┆ female ┆ 25.74  ┆ 0        ┆ no     ┆ southeast ┆ 3756.6216   ┆ 313.0518          │
│ 46  ┆ female ┆ 33.44  ┆ 1        ┆ no     ┆ southeast ┆ 8240.5896   ┆ 686.7158          │
│ 37  ┆ female ┆ 27.74  ┆ 3        ┆ no     ┆ northwest ┆ 7281.5056   ┆ 606.792133        │
│ …   ┆ …      ┆ …      ┆ …        ┆ …      ┆ …         ┆ …           ┆ …                 │
│ 52  ┆ male   ┆ 38.6   ┆ 2        ┆ no     ┆ southwest ┆ 10325.206   ┆ 860.433833        │
│ 57  ┆ female ┆ 25.74  ┆ 2        ┆ no     ┆ southeast ┆ 12629.1656  ┆ 1052.430467       │
│ 52  ┆ female ┆ 44.7   ┆ 3        ┆ no     ┆ southwest ┆ 11411.685   ┆ 950.97375         │
│ 50  ┆ male   ┆ 30.97  ┆ 3        ┆ no     ┆ northwest ┆ 10600.5483  ┆ 883.379025        │
│ 61  ┆ female ┆ 29.07  ┆ 0        ┆ yes    ┆ northwest ┆ 29141.3603  ┆ 2428.446692       │
└─────┴────────┴────────┴──────────┴────────┴───────────┴─────────────┴───────────────────┘

In [11]:
insurance_month.filter((pl.col('age') >= 30) & (pl.col('sex') == 'male'))

shape: (460, 8)
┌─────┬──────┬────────┬──────────┬────────┬───────────┬─────────────┬───────────────────┐
│ age ┆ sex  ┆ bmi    ┆ children ┆ smoker ┆ region    ┆ charges     ┆ charges_per_month │
│ --- ┆ ---  ┆ ---    ┆ ---      ┆ ---    ┆ ---       ┆ ---         ┆ ---               │
│ i64 ┆ str  ┆ f64    ┆ i64      ┆ str    ┆ str       ┆ f64         ┆ f64               │
╞═════╪══════╪════════╪══════════╪════════╪═══════════╪═════════════╪═══════════════════╡
│ 33  ┆ male ┆ 22.705 ┆ 0        ┆ no     ┆ northwest ┆ 21984.47061 ┆ 1832.039217       │
│ 32  ┆ male ┆ 28.88  ┆ 0        ┆ no     ┆ northwest ┆ 3866.8552   ┆ 322.237933        │
│ 37  ┆ male ┆ 29.83  ┆ 2        ┆ no     ┆ northeast ┆ 6406.4107   ┆ 533.867558        │
│ 56  ┆ male ┆ 40.3   ┆ 0        ┆ no     ┆ southwest ┆ 10602.385   ┆ 883.532083        │
│ 30  ┆ male ┆ 35.3   ┆ 0        ┆ yes    ┆ southwest ┆ 36837.467   ┆ 3069.788917       │
│ …   ┆ …    ┆ …      ┆ …        ┆ …      ┆ …         ┆ …           ┆ …                 │
│ 31  ┆ male ┆ 25.935 ┆ 1        ┆ no     ┆ northwest ┆ 4239.89265  ┆ 353.324387        │
│ 61  ┆ male ┆ 33.535 ┆ 0        ┆ no     ┆ northeast ┆ 13143.33665 ┆ 1095.278054       │
│ 51  ┆ male ┆ 30.03  ┆ 1        ┆ no     ┆ southeast ┆ 9377.9047   ┆ 781.492058        │
│ 52  ┆ male ┆ 38.6   ┆ 2        ┆ no     ┆ southwest ┆ 10325.206   ┆ 860.433833        │
│ 50  ┆ male ┆ 30.97  ┆ 3        ┆ no     ┆ northwest ┆ 10600.5483  ┆ 883.379025        │
└─────┴──────┴────────┴──────────┴────────┴───────────┴─────────────┴───────────────────┘

In [12]:
insurance_month.group_by('sex').mean()

shape: (2, 8)
┌────────┬───────────┬───────────┬──────────┬────────┬────────┬──────────────┬───────────────────┐
│ sex    ┆ age       ┆ bmi       ┆ children ┆ smoker ┆ region ┆ charges      ┆ charges_per_month │
│ ---    ┆ ---       ┆ ---       ┆ ---      ┆ ---    ┆ ---    ┆ ---          ┆ ---               │
│ str    ┆ f64       ┆ f64       ┆ f64      ┆ str    ┆ str    ┆ f64          ┆ f64               │
╞════════╪═══════════╪═══════════╪══════════╪════════╪════════╪══════════════╪═══════════════════╡
│ female ┆ 39.503021 ┆ 30.377749 ┆ 1.074018 ┆ null   ┆ null   ┆ 12569.578844 ┆ 1047.464904       │
│ male   ┆ 38.91716  ┆ 30.943129 ┆ 1.115385 ┆ null   ┆ null   ┆ 13956.751178 ┆ 1163.062598       │
└────────┴───────────┴───────────┴──────────┴────────┴────────┴──────────────┴───────────────────┘

In [14]:
insurance_month.group_by('sex').len()

shape: (2, 2)
┌────────┬─────┐
│ sex    ┆ len │
│ ---    ┆ --- │
│ str    ┆ u32 │
╞════════╪═════╡
│ male   ┆ 676 │
│ female ┆ 662 │
└────────┴─────┘

In [15]:
insurance_month.group_by('sex').sum()

shape: (2, 8)
┌────────┬───────┬───────────┬──────────┬────────┬────────┬──────────┬───────────────────┐
│ sex    ┆ age   ┆ bmi       ┆ children ┆ smoker ┆ region ┆ charges  ┆ charges_per_month │
│ ---    ┆ ---   ┆ ---       ┆ ---      ┆ ---    ┆ ---    ┆ ---      ┆ ---               │
│ str    ┆ i64   ┆ f64       ┆ i64      ┆ str    ┆ str    ┆ f64      ┆ f64               │
╞════════╪═══════╪═══════════╪══════════╪════════╪════════╪══════════╪═══════════════════╡
│ male   ┆ 26308 ┆ 20917.555 ┆ 754      ┆ null   ┆ null   ┆ 9.4348e6 ┆ 786230.316345     │
│ female ┆ 26151 ┆ 20110.07  ┆ 711      ┆ null   ┆ null   ┆ 8.3211e6 ┆ 693421.766218     │
└────────┴───────┴───────────┴──────────┴────────┴────────┴──────────┴───────────────────┘

---

In [16]:
data1 = {
    'employee_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'name': ['Michael Scott', 'Jim Halpert', 'Pam Beesly', 'Dwight Schrute', 
             'Angela Martin', 'Kevin Malone', 'Oscar Martinez', 'Stanley Hudson'],
    'job_title': ['Regional Manager', 'Sales Representative', 'Receptionist', 
                  'Assistant to the Regional Manager', 'Head of Accounting', 
                  'Accountant', 'Accountant', 'Sales Representative'],
    'salary': [100000, 60000, 55000, 65000, 60000, 55000, 55000, 60000]}
df1 = pl.DataFrame(data1)

data2 = {
    'employee_id': [1, 2, 3, 5, 6, 7, 8, 9],
    'name': ['Michael Scott', 'Jim Halpert', 'Pam Beesly', 'Angela Martin', 
             'Kevin Malone', 'Oscar Martinez', 'Stanley Hudson', 'Phyllis Vance'],
    'department': ['Management', 'Sales', 'Reception', 'Accounting', 
                   'Accounting', 'Accounting', 'Sales', 'Sales']}
df2 = pl.DataFrame(data2)

In [17]:
df1

shape: (8, 4)
┌─────────────┬────────────────┬─────────────────────────────────┬────────┐
│ employee_id ┆ name           ┆ job_title                       ┆ salary │
│ ---         ┆ ---            ┆ ---                             ┆ ---    │
│ i64         ┆ str            ┆ str                             ┆ i64    │
╞═════════════╪════════════════╪═════════════════════════════════╪════════╡
│ 1           ┆ Michael Scott  ┆ Regional Manager                ┆ 100000 │
│ 2           ┆ Jim Halpert    ┆ Sales Representative            ┆ 60000  │
│ 3           ┆ Pam Beesly     ┆ Receptionist                    ┆ 55000  │
│ 4           ┆ Dwight Schrute ┆ Assistant to the Regional Mana… ┆ 65000  │
│ 5           ┆ Angela Martin  ┆ Head of Accounting              ┆ 60000  │
│ 6           ┆ Kevin Malone   ┆ Accountant                      ┆ 55000  │
│ 7           ┆ Oscar Martinez ┆ Accountant                      ┆ 55000  │
│ 8           ┆ Stanley Hudson ┆ Sales Representative            ┆ 60000  │
└─────────────┴────────────────┴─────────────────────────────────┴────────┘

In [18]:
df2

shape: (8, 3)
┌─────────────┬────────────────┬────────────┐
│ employee_id ┆ name           ┆ department │
│ ---         ┆ ---            ┆ ---        │
│ i64         ┆ str            ┆ str        │
╞═════════════╪════════════════╪════════════╡
│ 1           ┆ Michael Scott  ┆ Management │
│ 2           ┆ Jim Halpert    ┆ Sales      │
│ 3           ┆ Pam Beesly     ┆ Reception  │
│ 5           ┆ Angela Martin  ┆ Accounting │
│ 6           ┆ Kevin Malone   ┆ Accounting │
│ 7           ┆ Oscar Martinez ┆ Accounting │
│ 8           ┆ Stanley Hudson ┆ Sales      │
│ 9           ┆ Phyllis Vance  ┆ Sales      │
└─────────────┴────────────────┴────────────┘

In [20]:
df1.join(df2, on='employee_id', how='full')

shape: (9, 7)
┌─────────────┬────────────────┬────────────────────────────┬────────┬───────────────────┬────────────────┬────────────┐
│ employee_id ┆ name           ┆ job_title                  ┆ salary ┆ employee_id_right ┆ name_right     ┆ department │
│ ---         ┆ ---            ┆ ---                        ┆ ---    ┆ ---               ┆ ---            ┆ ---        │
│ i64         ┆ str            ┆ str                        ┆ i64    ┆ i64               ┆ str            ┆ str        │
╞═════════════╪════════════════╪════════════════════════════╪════════╪═══════════════════╪════════════════╪════════════╡
│ 1           ┆ Michael Scott  ┆ Regional Manager           ┆ 100000 ┆ 1                 ┆ Michael Scott  ┆ Management │
│ 2           ┆ Jim Halpert    ┆ Sales Representative       ┆ 60000  ┆ 2                 ┆ Jim Halpert    ┆ Sales      │
│ 3           ┆ Pam Beesly     ┆ Receptionist               ┆ 55000  ┆ 3                 ┆ Pam Beesly     ┆ Reception  │
│ 5           ┆ Angela Martin  ┆ Head of Accounting         ┆ 60000  ┆ 5                 ┆ Angela Martin  ┆ Accounting │
│ 6           ┆ Kevin Malone   ┆ Accountant                 ┆ 55000  ┆ 6                 ┆ Kevin Malone   ┆ Accounting │
│ 7           ┆ Oscar Martinez ┆ Accountant                 ┆ 55000  ┆ 7                 ┆ Oscar Martinez ┆ Accounting │
│ 8           ┆ Stanley Hudson ┆ Sales Representative       ┆ 60000  ┆ 8                 ┆ Stanley Hudson ┆ Sales      │
│ null        ┆ null           ┆ null                       ┆ null   ┆ 9                 ┆ Phyllis Vance  ┆ Sales      │
│ 4           ┆ Dwight Schrute ┆ Assistant to the Regional  ┆ 65000  ┆ null              ┆ null           ┆ null       │
│             ┆                ┆ Mana…                      ┆        ┆                   ┆                ┆            │
└─────────────┴────────────────┴────────────────────────────┴────────┴───────────────────┴────────────────┴────────────┘

ValueError: cross join should not pass join keys