<span style='color:red'>

# TITLE: `PANDAS QUESTIONS - ANALYST BUILDER`

</span>

---
---
---

<span style='color:red'>

# 1. MODERATE LEVEL

---
---

<span style='color:red'>

## 01. Margin Madness

---

<div style='background-color:darkblue; padding:15px;'>
    
<span style='color:orange'>
    
Ana started a new cheesecake company which now has a few orders completed!

She would like to better understand how profitable she is on average for any given order.

To help her calculate this, determine the order profit margin ( (order value - item cost) / order value)

Then, average this value across all of her orders.

Round the output to 1 decimal places, and append a percent sign (%) to the end (Ana doesn't want to have to do that later manually each time - I know....).

</div>

---

In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_excel('datasets/Questions/Moderate/01.Cheesecake_margins.xlsx')
df1.head()

  order_id               item  qty  order_value  item_cost
0   ORD001              Slice    2           10          4
1   ORD002  Cheesecake cookie    1            5          1
2   ORD003              Slice    5           25         10
3   ORD004       Birthday pie    1           20         15
4   ORD005  Cheesecake cookie   10           50         10

In [3]:
df1 = df1.assign(profit=(df1['order_value'] - df1['item_cost'])/ df1['order_value'] *100)
df1.head()

  order_id               item  qty  order_value  item_cost  profit
0   ORD001              Slice    2           10          4    60.0
1   ORD002  Cheesecake cookie    1            5          1    80.0
2   ORD003              Slice    5           25         10    60.0
3   ORD004       Birthday pie    1           20         15    25.0
4   ORD005  Cheesecake cookie   10           50         10    80.0

In [4]:
result = round(df1['profit'].mean(), 1)
value = str(result) + '%'
print(value)

62.5%

In [5]:
result_1 = pd.DataFrame({'avg_profit_margin':[value]})
result_1

  avg_profit_margin
0             62.5%

---
---

<span style='color:red'>

## 02. Carcinogens

---

<div style='background-color:darkblue; padding:15px;'>
    
<span style='color:orange'>
    
There's healthy food and then there's food that we are eating. Let's identify which of these products contain carcinogens (cancer causing substances).

Write a query to list all products that contain at least two carcinogenic ingredients.

The output should have just the Product_Name sorted alphabetically.

</div>

---

In [6]:
ingredients = pd.read_excel('datasets/Questions/Moderate/02.ingredients.xlsx')
products = pd.read_excel('datasets/Questions/Moderate/02.products.xlsx')

In [7]:
ingredients

   ingredient_id        ingredient_name is_carcinogenic  product_id
0             A1                 Potato             Yes           1
1             A2                  Sugar              No           2
2             A3            1,4-Dioxane             Yes           3
3             A4              Olive Oil              No           4
4             A5                Almonds              No           5
5             A6                  Yeast              No           6
6             A7                  Cocoa              No           7
7             A8  Sodium Lauryl Sulfate             Yes           3
8             A9           Benzophenone             Yes           2
9            A10             Acrylamide             Yes           1
10           A11               Glycerin              No           4
11           A12               Sea Salt              No           5
12           A13            Xanthan Gum              No           6
13           A14           Soy Lecithin              No           7

In [8]:
products

   product_id            product_name    category
0           1       Lays Potato Chips      Snacks
1           2           Coca-Cola Can   Beverages
2           3  Johnson's Baby Shampoo   Baby Care
3           4   Organic Handmade Soap    Skincare
4           5     Natural Almond Milk   Beverages
5           6       Gluten-Free Bread      Bakery
6           7     Vegan Chocolate Bar  Confection

In [9]:
eval_ingredients = ingredients.groupby('product_id')['is_carcinogenic'].sum().reset_index()
eval_ingredients

   product_id is_carcinogenic
0           1          YesYes
1           2           NoYes
2           3          YesYes
3           4            NoNo
4           5            NoNo
5           6            NoNo
6           7            NoNo

In [10]:
merged_df = products.merge(eval_ingredients, on='product_id', how='inner')
merged_df

   product_id            product_name    category is_carcinogenic
0           1       Lays Potato Chips      Snacks          YesYes
1           2           Coca-Cola Can   Beverages           NoYes
2           3  Johnson's Baby Shampoo   Baby Care          YesYes
3           4   Organic Handmade Soap    Skincare            NoNo
4           5     Natural Almond Milk   Beverages            NoNo
5           6       Gluten-Free Bread      Bakery            NoNo
6           7     Vegan Chocolate Bar  Confection            NoNo

In [11]:
merged_df[merged_df['is_carcinogenic'] == 'YesYes'][['product_name']].sort_values(by='product_name')

             product_name
2  Johnson's Baby Shampoo
0       Lays Potato Chips

---

In [12]:
carcinogenic = ingredients[ingredients['is_carcinogenic'] == 'Yes']

carcinogenic_count = carcinogenic.groupby('product_id').size().reset_index(name='carcinogenic_ingredients')
carcinogenic_count

   product_id  carcinogenic_ingredients
0           1                         2
1           2                         1
2           3                         2

In [13]:
carcinogenic_count = carcinogenic_count[carcinogenic_count['carcinogenic_ingredients'] >= 2]

result = pd.merge(products, carcinogenic_count, left_on='product_id', right_on='product_id')
result

   product_id            product_name   category  carcinogenic_ingredients
0           1       Lays Potato Chips     Snacks                         2
1           3  Johnson's Baby Shampoo  Baby Care                         2

In [14]:
result_product_names = result[['product_name']].sort_values('product_name')
result_product_names

             product_name
1  Johnson's Baby Shampoo
0       Lays Potato Chips

---
---

<span style='color:red'>

## 03. Holy Matrimony

---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
A couple was to be married and wanted to bring together their finances.

The wife wanted to only include purchases from 1/1/2024 and before because she made some large, embarrassing purchases after that.

The husband wanted to remove anything that included "Gambling" in his purchases.

Combine their purchases together based on those criteria.

Include all columns in the output and order on purchase_date and purchase_id descending.

</div>

---

In [15]:
wife = pd.read_excel('datasets/Questions/Moderate/03.Wife_purchases.xlsx')
wife.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   purchase_id    20 non-null     int64
 1   purchase_date  20 non-null     datetime64[ns]
 2   description    20 non-null     object
 3   amount         20 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 772.0+ bytes

In [16]:
wife.sort_values(by='purchase_date', ascending=False).head()

    purchase_id purchase_date  description    amount
19           20    2024-01-05         Boat  25000.00
18           19    2023-12-12  Electronics     96.15
17           18    2023-11-23        Books    291.70
16           17    2023-11-04        Gifts     42.90
15           16    2023-10-16  Electronics    370.42

In [17]:
wife_filtered = wife[wife['purchase_date'] <= '2024-01-01']
wife_filtered

    purchase_id purchase_date  description  amount
0             1    2023-01-01        Gifts  108.48
1             2    2023-01-20        Books   58.82
2             3    2023-02-08      Clothes  225.59
3             4    2023-02-27    Groceries  350.48
4             5    2023-03-18        Books   47.93
5             6    2023-04-07  Electronics  459.30
6             7    2023-04-26        Books  232.33
7             8    2023-05-15        Books  135.10
8             9    2023-06-03      Clothes   65.06
9            10    2023-06-22  Electronics  107.78
10           11    2023-07-12        Books  468.61
11           12    2023-07-31    Groceries  326.37
12           13    2023-08-19    Groceries  268.01
13           14    2023-09-07        Gifts  335.41
14           15    2023-09-26  Electronics  229.12
15           16    2023-10-16  Electronics  370.42
16           17    2023-11-04        Gifts   42.90
17           18    2023-11-23        Books  291.70
18           19    2023-12-12  Electronics   96.15

In [19]:
husband = pd.read_excel('datasets/Questions/Moderate/03.Husband_purchases.xlsx')
husband.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   purchase_id    20 non-null     int64
 1   purchase_date  20 non-null     datetime64[ns]
 2   description    20 non-null     object
 3   amount         20 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 772.0+ bytes

In [20]:
husband_filtered = husband[~husband['description'].str.startswith('G')]
husband_filtered

    purchase_id purchase_date      description  amount
0           101    2023-01-01           Dining  374.79
1           102    2023-01-20      Electronics  137.21
3           104    2023-02-27   Sporting Goods  345.84
4           105    2023-03-18  Car Maintenance  980.54
5           106    2023-04-07  Car Maintenance  216.56
6           107    2023-04-26   Sporting Goods   66.30
7           108    2023-05-15      Electronics  775.20
8           109    2023-06-03  Car Maintenance  816.57
10          111    2023-07-12      Electronics  491.44
12          113    2023-08-19           Dining   95.66
13          114    2023-09-07      Electronics  951.69
14          115    2023-09-26  Car Maintenance  892.35
15          116    2023-10-16      Electronics  297.85
16          117    2023-11-04      Electronics   64.54
17          118    2023-11-23      Electronics  936.76
18          119    2023-12-12      Electronics  525.99

In [21]:
result = pd.concat([wife_filtered, husband_filtered])
result.sort_values(by=['purchase_date', 'purchase_id'], ascending=[False, False])

    purchase_id purchase_date      description  amount
18          119    2023-12-12      Electronics  525.99
18           19    2023-12-12      Electronics   96.15
17          118    2023-11-23      Electronics  936.76
17           18    2023-11-23            Books  291.70
16          117    2023-11-04      Electronics   64.54
16           17    2023-11-04            Gifts   42.90
15          116    2023-10-16      Electronics  297.85
15           16    2023-10-16      Electronics  370.42
14          115    2023-09-26  Car Maintenance  892.35
14           15    2023-09-26      Electronics  229.12
13          114    2023-09-07      Electronics  951.69
13           14    2023-09-07            Gifts  335.41
12          113    2023-08-19           Dining   95.66
12           13    2023-08-19        Groceries  268.01
11           12    2023-07-31        Groceries  326.37
10          111    2023-07-12      Electronics  491.44
10           11    2023-07-12            Books  468.61
9            10    2023-06-22      Electronics  107.78
8           109    2023-06-03  Car Maintenance  816.57
8             9    2023-06-03          Clothes   65.06
7           108    2023-05-15      Electronics  775.20
7             8    2023-05-15            Books  135.10
6           107    2023-04-26   Sporting Goods   66.30
6             7    2023-04-26            Books  232.33
5           106    2023-04-07  Car Maintenance  216.56
5             6    2023-04-07      Electronics  459.30
4           105    2023-03-18  Car Maintenance  980.54
4             5    2023-03-18            Books   47.93
3           104    2023-02-27   Sporting Goods  345.84
3             4    2023-02-27        Groceries  350.48
2             3    2023-02-08          Clothes  225.59
1           102    2023-01-20      Electronics  137.21
1             2    2023-01-20            Books   58.82
0           101    2023-01-01           Dining  374.79
0             1    2023-01-01            Gifts  108.48

---

In [22]:
filtered_wife = wife[wife['purchase_date'] <= '2024-01-01']

filtered_husband = husband[~husband['description'].str.contains('Gambling', case=False, na=False)]

combined_purchases = pd.concat([filtered_wife, filtered_husband], ignore_index=True)

combined_purchases.sort_values(by=['purchase_date', 'purchase_id'], ascending=[False, False])

    purchase_id purchase_date      description  amount
34          119    2023-12-12      Electronics  525.99
18           19    2023-12-12      Electronics   96.15
33          118    2023-11-23      Electronics  936.76
17           18    2023-11-23            Books  291.70
32          117    2023-11-04      Electronics   64.54
16           17    2023-11-04            Gifts   42.90
31          116    2023-10-16      Electronics  297.85
15           16    2023-10-16      Electronics  370.42
30          115    2023-09-26  Car Maintenance  892.35
14           15    2023-09-26      Electronics  229.12
29          114    2023-09-07      Electronics  951.69
13           14    2023-09-07            Gifts  335.41
28          113    2023-08-19           Dining   95.66
12           13    2023-08-19        Groceries  268.01
11           12    2023-07-31        Groceries  326.37
27          111    2023-07-12      Electronics  491.44
10           11    2023-07-12            Books  468.61
9            10    2023-06-22      Electronics  107.78
26          109    2023-06-03  Car Maintenance  816.57
8             9    2023-06-03          Clothes   65.06
25          108    2023-05-15      Electronics  775.20
7             8    2023-05-15            Books  135.10
24          107    2023-04-26   Sporting Goods   66.30
6             7    2023-04-26            Books  232.33
23          106    2023-04-07  Car Maintenance  216.56
5             6    2023-04-07      Electronics  459.30
22          105    2023-03-18  Car Maintenance  980.54
4             5    2023-03-18            Books   47.93
21          104    2023-02-27   Sporting Goods  345.84
3             4    2023-02-27        Groceries  350.48
2             3    2023-02-08          Clothes  225.59
20          102    2023-01-20      Electronics  137.21
1             2    2023-01-20            Books   58.82
19          101    2023-01-01           Dining  374.79
0             1    2023-01-01            Gifts  108.48

---
---

<span style='color:red'>

## 04. Keep it Hush Hush

---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
Jimmy runs an illegal business in the undergrounds of New York City. He wants to look into some of his data, but of course doesn't want to share what he is selling so he keeps it pretty generic.

Here's what he wants:

  1. Fill in the missing values in the `Units_Sold` column with the **average units sold**.

  2. Fill in the missing values in the `Profit` column with **0s**.

The output should display all columns with the missing values filled as specified.


</div>

---

In [23]:
sales = pd.read_excel('datasets/Questions/Moderate/04.sales.xlsx')
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sale_id       100 non-null    int64
 1   product_name  100 non-null    object
 2   units_sold    90 non-null     float64
 3   profit        90 non-null     float64
dtypes: float64(2), int64(1), object(1)
memory usage: 3.3+ KB

In [24]:
sales.iloc[15:21]

    sale_id product_name  units_sold   profit
15       16   Product_15         NaN  9628.23
16       17    Product_2        99.0  2592.64
17       18   Product_16         NaN  5022.76
18       19    Product_8       151.0  3078.70
19       20   Product_13       130.0  2919.92
20       21    Product_1         NaN   465.18

In [25]:
avg_val = sales['units_sold'].mean()
sales['units_sold'] = sales['units_sold'].fillna(avg_val)
sales.iloc[15:21]

    sale_id product_name  units_sold   profit
15       16   Product_15  254.333333  9628.23
16       17    Product_2   99.000000  2592.64
17       18   Product_16  254.333333  5022.76
18       19    Product_8  151.000000  3078.70
19       20   Product_13  130.000000  2919.92
20       21    Product_1  254.333333   465.18

In [26]:
sales['profit'] = sales['profit'].fillna(0)

In [27]:
sales.isna().sum()

sale_id         0
product_name    0
units_sold      0
profit          0
dtype: int64

---
---

<span style='color:red'>

## 05. Taxes

---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
It's everyone's favorite time of the year! Tax season!

Let's help these business know how much taxes they owe for this year!

Calculate the taxes owed by each company for the most recent fiscal year. The taxes owed can be calculated as (Taxable Income * Tax Rate).

If a company doesn't have data for the most recent year they should not be included in the output.

The output should have the columns `Company_Name`, `Fiscal_Year`, and `Taxes_Owed`, and should be **ordered by Taxes_Owed in descending order**.


</div>

---

In [28]:
company_financials = pd.read_excel('datasets/Questions/Moderate/05.Taxes.xlsx')
company_financials

,company_id,company_name,fiscal_year,total_revenue,taxable_income,tax_rate
0,1,Don's BBQ,2021,135.07,107.46,0.24
1,1,Don's BBQ,2022,656.43,162.51,0.20
2,1,Don's BBQ,2023,402.90,311.24,0.20
3,1,Don's BBQ,2024,690.15,440.20,0.12
4,2,Sally's Hair Salon,2020,446.86,302.84,0.12
5,2,Sally's Hair Salon,2021,713.45,157.37,0.22
6,2,Sally's Hair Salon,2022,406.56,355.93,0.21
7,2,Sally's Hair Salon,2023,334.63,382.96,0.14
8,2,Sally's Hair Salon,2024,546.43,157.21,0.29
9,2,Sally's Hair Salon,2023,723.60,219.98,0.26
10,3,Computer Tech LLC,2020,413.50,290.45,0.12
11,3,Computer Tech LLC,2021,942.98,273.45,0.29
12,3,Computer Tech LLC,2022,135.27,225.33,0.29
13,3,Computer Tech LLC,2023,476.15,183.94,0.30
14,3,Computer Tech LLC,2024,970.82,94.99,0.11
15,4,Henry's Car Wash,2020,593.17,74.07,0.25
16,4,Henry's Car Wash,2021,481.12,481.34,0.21
17,4,Henry's Car Wash,2022,611.67,431.21,0.24
18,4,Henry's Car Wash,2023,618.33,209.71,0.29

In [29]:
filtered_df = company_financials[company_financials['fiscal_year'] == 2024]
filtered_df

,company_id,company_name,fiscal_year,total_revenue,taxable_income,tax_rate
3,1,Don's BBQ,2024,690.15,440.20,0.12
8,2,Sally's Hair Salon,2024,546.43,157.21,0.29
14,3,Computer Tech LLC,2024,970.82,94.99,0.11

In [30]:
filtered_df = filtered_df.assign(taxes_owed = filtered_df['taxable_income'] * filtered_df['tax_rate'])
result = filtered_df[['company_name', 'fiscal_year', 'taxes_owed']].sort_values(by='taxes_owed', ascending=False)
result

          company_name  fiscal_year  taxes_owed
3            Don's BBQ         2024     52.8240
8   Sally's Hair Salon         2024     45.5909
14   Computer Tech LLC         2024     10.4489

---
---

<span style='color:red'>

## 06. Traffic Control

---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
You were hired by a global airline to get all of their data into one place. Right now it's all over and isn't really usable.

Write a query to combine the flight records from both tables into a single list.

For the International_Flights table, only include flights from a specific international zone: **‘Zone A’**.

Ensure that the columns match in both select statements and that the final output has the columns `Flight_ID`, `Airline`, `Departure_City`, `Arrival_City`, and `Passenger_Count`.

Order the output on Flight_ID from smallest to largest.


</div>

---

In [31]:
domestic_flights = pd.read_excel('datasets/Questions/Moderate/06.domestic_flights.xlsx')
international_flights = pd.read_excel('datasets/Questions/Moderate/06.international_flights.xlsx')

In [32]:
domestic_flights.tail()

,flight_id,airline,departure_city,arrival_city,passenger_count
45,146,Skyward Express,Ogdenville,West Springfield,216
46,147,Urban Wings,Shelbyville,Cypress Creek,141
47,148,Horizon Air,North Haverbrook,West Springfield,291
48,149,Urban Wings,North Haverbrook,West Springfield,298
49,150,Horizon Air,North Haverbrook,Cypress Creek,58

In [33]:
international_flights.head()

,flight_number,carrier,origin_city,destination_city,passenger_total,international_zone
0,201,Pacific Jetways,Freedom City,Felicity Falls,208,Zone A
1,202,Global Voyagers,Harmony Hamlet,Serenity Summit,229,Zone C
2,203,Meridian Airlines,Harmony Hamlet,Felicity Falls,109,Zone D
3,204,Pacific Jetways,Harmony Hamlet,Serenity Summit,347,Zone E
4,205,Global Voyagers,Liberty Town,Placid Plains,289,Zone E

In [34]:
col_names = list(domestic_flights.columns)
col_names.append('international_zone')
international_flights.columns = col_names

filtered_df = international_flights[international_flights['international_zone'] == 'Zone A']
filtered_df

,flight_id,airline,departure_city,arrival_city,passenger_count,international_zone
0,201,Pacific Jetways,Freedom City,Felicity Falls,208,Zone A
9,210,Global Voyagers,Unity Village,Placid Plains,279,Zone A
22,223,Pacific Jetways,Liberty Town,Felicity Falls,308,Zone A
24,225,Pacific Jetways,Prosperity Port,Felicity Falls,296,Zone A
31,232,Equator Airways,Unity Village,Tranquility Base,217,Zone A
48,249,Pacific Jetways,Liberty Town,Placid Plains,226,Zone A

In [35]:
filtered_df = filtered_df.drop(labels='international_zone', axis=1)
filtered_df

,flight_id,airline,departure_city,arrival_city,passenger_count
0,201,Pacific Jetways,Freedom City,Felicity Falls,208
9,210,Global Voyagers,Unity Village,Placid Plains,279
22,223,Pacific Jetways,Liberty Town,Felicity Falls,308
24,225,Pacific Jetways,Prosperity Port,Felicity Falls,296
31,232,Equator Airways,Unity Village,Tranquility Base,217
48,249,Pacific Jetways,Liberty Town,Placid Plains,226

In [36]:
concat_df = pd.concat([domestic_flights, filtered_df], axis=0, join='outer').sort_values(
                                                    by='flight_id').reset_index(drop=True)
concat_df

,flight_id,airline,departure_city,arrival_city,passenger_count
0,101,Skyward Express,Springfield,New Springfield,87
1,102,Urban Wings,North Haverbrook,South Springfield,56
2,103,Horizon Air,North Haverbrook,East Springfield,72
3,104,Pioneer Skies,Shelbyville,East Springfield,79
4,105,Horizon Air,Capital City,West Springfield,133
5,106,Coastal Lines,Capital City,West Springfield,209
6,107,Coastal Lines,North Haverbrook,East Springfield,137
7,108,Skyward Express,Shelbyville,Cypress Creek,147
8,109,Horizon Air,Capital City,Cypress Creek,103
9,110,Horizon Air,Capital City,New Springfield,156
10,111,Skyward Express,Springfield,West Springfield,284
11,112,Urban Wings,Ogdenville,Cypress Creek,65
12,113,Coastal Lines,Capital City,East Springfield,156
13,114,Skyward Express,Springfield,East Springfield,172
14,115,Pioneer Skies,Springfield,East Springfield,261
15,116,Urban Wings,Shelbyville,South Springfield,293
16,117,Skyward Express,North Haverbrook,East Springfield,287
17,118,Pioneer Skies,Shelbyville,South Springfield,264
18,119,Skyward Express,Shelbyville,South Springfield,296
19,120,Urban Wings,Shelbyville,East Springfield,65
20,121,Urban Wings,Capital City,South Springfield,128
21,122,Horizon Air,Capital City,East Springfield,213
22,123,Skyward Express,North Haverbrook,New Springfield,56
23,124,Urban Wings,Capital City,South Springfield,166
24,125,Horizon Air,Springfield,East Springfield,51
25,126,Pioneer Skies,Capital City,East Springfield,58
26,127,Pioneer Skies,Springfield,New Springfield,260
27,128,Pioneer Skies,Capital City,New Springfield,61
28,129,Pioneer Skies,Springfield,West Springfield,158
29,130,Horizon Air,North Haverbrook,South Springfield,128
30,131,Horizon Air,Shelbyville,West Springfield,130
31,132,Coastal Lines,Shelbyville,Cypress Creek,142
32,133,Skyward Express,Capital City,New Springfield,217
33,134,Horizon Air,Capital City,New Springfield,56
34,135,Coastal Lines,Ogdenville,East Springfield,173
35,136,Coastal Lines,North Haverbrook,Cypress Creek,282
36,137,Horizon Air,Capital City,West Springfield,289
37,138,Horizon Air,Shelbyville,West Springfield,204
38,139,Pioneer Skies,Shelbyville,New Springfield,251
39,140,Horizon Air,Shelbyville,West Springfield,126
40,141,Skyward Express,Springfield,West Springfield,114
41,142,Pioneer Skies,Shelbyville,South Springfield,212
42,143,Horizon Air,Springfield,South Springfield,204
43,144,Coastal Lines,Capital City,New Springfield,157
44,145,Horizon Air,Ogdenville,West Springfield,260
45,146,Skyward Express,Ogdenville,West Springfield,216
46,147,Urban Wings,Shelbyville,Cypress Creek,141
47,148,Horizon Air,North Haverbrook,West Springfield,291
48,149,Urban Wings,North Haverbrook,West Springfield,298
49,150,Horizon Air,North Haverbrook,Cypress Creek,58
50,201,Pacific Jetways,Freedom City,Felicity Falls,208
51,210,Global Voyagers,Unity Village,Placid Plains,279
52,223,Pacific Jetways,Liberty Town,Felicity Falls,308
53,225,Pacific Jetways,Prosperity Port,Felicity Falls,296
54,232,Equator Airways,Unity Village,Tranquility Base,217
55,249,Pacific Jetways,Liberty Town,Placid Plains,226

---

In [37]:
df_international_flights_filtered = international_flights[
        international_flights['international_zone'] == 'Zone A'].rename(columns={
            'flight_number': 'flight_id', 'carrier': 'airline', 'origin_city': 'departure_city',
            'destination_city': 'arrival_city', 'passenger_total': 'passenger_count'})

df_domestic_flights_selected = domestic_flights[['flight_id', 'airline', 'departure_city', 
                                                 'arrival_city', 'passenger_count']]

df_combined = pd.concat([df_domestic_flights_selected,
                         df_international_flights_filtered[['flight_id', 'airline', 
                                                            'departure_city', 'arrival_city', 'passenger_count']]])

---
---

<span style='color:red'>

## 07. Above Average

---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
If you're looking for a tall handsome man this question is for you. If not... well it's a good learning opportunity. Let's figure out which countries have an above average height!

Write a query to find the countries where their average height is above the global average.

The output should have the columns `Country` and `Average_Height`, and should be **ordered by** `Average_Height` **in descending order**.


</div>

---

In [38]:
heights = pd.read_excel('datasets/Questions/Moderate/07.heights.xlsx')
heights

          country  average_height
0   United States          179.13
1       Argentina          156.53
2          Mexico          150.89
3         Germany          175.76
4           India          160.02
5          Canada          177.99
6          Sweden          186.77
7           Spain          181.22
8           Italy          165.93
9  United Kingdom          159.22

In [39]:
global_avg = heights['average_height'].mean()

heights[heights['average_height'] > global_avg].sort_values(by='average_height', ascending=False)

         country  average_height
6         Sweden          186.77
7          Spain          181.22
0  United States          179.13
5         Canada          177.99
3        Germany          175.76

---
---

<span style='color:red'>

## 08. Biggest Country Debts

---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
The world is taking on debt like there is no tomorrow, but which country is taking on the most?

Write a query to find the top 3 countries with the largest national debt for the most recent year.

The output should have the columns `Country` and `National_Debt` (*round to the nearest whole number*), and should be **ordered by National_Debt in descending order**.


</div>

---

In [40]:
df = pd.read_excel('datasets/Questions/Moderate/08.Country_Debts.xlsx')
df.sample(6)

    country  year  national_debt
142  Canada  2017        3609.88
30    Japan  2010       28915.63
102   India  2022       20170.84
94    India  2014        6145.09
107   Italy  2012       22353.06
90    India  2010        5470.07

In [41]:
df['country'].value_counts()

country
United States     15
China             15
Japan             15
Germany           15
United Kingdom    15
France            15
India             15
Italy             15
Brazil            15
Canada            15
Name: count, dtype: int64

In [42]:
df[df['year'] == 2010].sort_values(by='country')

            country  year  national_debt
120          Brazil  2010       28187.24
135          Canada  2010       17441.36
15            China  2010        8876.33
75           France  2010        3808.44
45          Germany  2010        2680.61
90            India  2010        5470.07
105           Italy  2010       23460.62
30            Japan  2010       28915.63
60   United Kingdom  2010       19348.96
0     United States  2010        1614.44

In [43]:
df[df['year'] == 2024].sort_values('country')

            country  year  national_debt
134          Brazil  2024        5095.43
149          Canada  2024        8669.23
29            China  2024       16235.40
89           France  2024       13466.40
59          Germany  2024       25335.99
104           India  2024       25662.61
119           Italy  2024        5816.89
44            Japan  2024        3747.26
74   United Kingdom  2024        7867.91
14    United States  2024        6872.75

---

**All of the countries have 15 years of data debt, fromm 2010 to 2024**

---

In [44]:
result = round(df[df['year'] == 2024][['country', 'national_debt']], 0).sort_values(by='national_debt', ascending=False).head(3)
result['national_debt'] = result['national_debt'].astype('int')

In [45]:
result

     country  national_debt
104    India          25663
59   Germany          25336
29     China          16235

---
---

<span style='color:red'>

## 09. Shrink-flation

---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
Write a query to identify products that have undergone shrink-flation over the last year. `Shrink-flation` is defined as a `reduction in product size while maintaining or increasing the price`.

**Include a flag for Shrinkflation**. This should be a boolean value (True or False) indicating whether the product has undergone shrink-flation

The output should have the columns `Product_Name`, `Size_Change_Percentage`, `Price_Change_Percentage`, and `Shrinkflation_Flag`.

**Round percentages to the nearest whole number** and `order the output on the product names alphabetically`


</div>

---

In [46]:
df = pd.read_excel('datasets/Questions/Moderate/09.Shrink-flation.xlsx')
df

,product_id,product_name,category,original_size,new_size,original_price,new_price,date_changed
0,1,Cheerioes,Cereals,349.73,321.7516,5.17,5.2217,2023-01-08
1,2,Mountain Dew,Beverages,103.17,99.0432,5.48,5.8636,2022-12-09
2,3,Whole Milk,Dairy,228.85,199.0995,3.36,3.6288,2022-10-25
3,4,Special K,Cereals,429.09,411.9264,4.84,5.1788,2022-09-10
4,5,Oreos,Snacks,444.48,382.2528,6.46,7.4290,2022-08-26
5,6,Cheese Its,Snacks,296.62,263.9918,5.24,5.8164,2022-04-28
6,7,Coke,Beverages,259.20,243.6480,2.37,2.6070,2022-02-27

In [47]:
df = df.assign(size_change_percentage = ((df['new_size']/df['original_size']*100).round(0) - 100).astype('int'))
df = df.assign(price_change_percentage = ((df['new_price']/df['original_price']*100).round(0) - 100).astype('int'))
df

,product_id,product_name,category,original_size,new_size,original_price,new_price,date_changed,size_change_percentage,price_change_percentage
0,1,Cheerioes,Cereals,349.73,321.7516,5.17,5.2217,2023-01-08,-8,1
1,2,Mountain Dew,Beverages,103.17,99.0432,5.48,5.8636,2022-12-09,-4,7
2,3,Whole Milk,Dairy,228.85,199.0995,3.36,3.6288,2022-10-25,-13,8
3,4,Special K,Cereals,429.09,411.9264,4.84,5.1788,2022-09-10,-4,7
4,5,Oreos,Snacks,444.48,382.2528,6.46,7.4290,2022-08-26,-14,15
5,6,Cheese Its,Snacks,296.62,263.9918,5.24,5.8164,2022-04-28,-11,11
6,7,Coke,Beverages,259.20,243.6480,2.37,2.6070,2022-02-27,-6,10

In [48]:
df = df.assign(shrinkflation_flag = (df['size_change_percentage'] < 1) & (df['price_change_percentage'] >= 1))
df

,product_id,product_name,category,original_size,new_size,original_price,new_price,date_changed,size_change_percentage,price_change_percentage,shrinkflation_flag
0,1,Cheerioes,Cereals,349.73,321.7516,5.17,5.2217,2023-01-08,-8,1,True
1,2,Mountain Dew,Beverages,103.17,99.0432,5.48,5.8636,2022-12-09,-4,7,True
2,3,Whole Milk,Dairy,228.85,199.0995,3.36,3.6288,2022-10-25,-13,8,True
3,4,Special K,Cereals,429.09,411.9264,4.84,5.1788,2022-09-10,-4,7,True
4,5,Oreos,Snacks,444.48,382.2528,6.46,7.4290,2022-08-26,-14,15,True
5,6,Cheese Its,Snacks,296.62,263.9918,5.24,5.8164,2022-04-28,-11,11,True
6,7,Coke,Beverages,259.20,243.6480,2.37,2.6070,2022-02-27,-6,10,True

In [49]:
result = df[['product_name', 'size_change_percentage', 'price_change_percentage', 
             'shrinkflation_flag']].sort_values('product_name')
result

,product_name,size_change_percentage,price_change_percentage,shrinkflation_flag
0,Cheerioes,-8,1,True
5,Cheese Its,-11,11,True
6,Coke,-6,10,True
1,Mountain Dew,-4,7,True
4,Oreos,-14,15,True
3,Special K,-4,7,True
2,Whole Milk,-13,8,True

---

---

In [ ]:
# --------------------------------------------------------------------------------------------------------
# This is the solution from the Teacher at Analyst Builder...
products['size_change_percentage'] = round(((products['new_size'] - products['original_size']) / products['original_size']) * 100, 0)
products['price_change_percentage'] = round(((products['new_price'] - products['original_price']) / products['original_price']) * 100, 0)
products['shrinkflation_flag'] = (products['new_size'] < products['original_size']) & (products['new_price'] >= products['original_price'])
products['shrinkflation_flag'] = products['shrinkflation_flag'].map({True: 'True', False: 'False'})

products_sorted = products.sort_values(by='product_name', ascending=True)

output_df = products_sorted[['product_name', 'size_change_percentage', 'price_change_percentage', 'shrinkflation_flag']]

# --------------------------------------------------------------------------------------------------------

---
---

<span style='color:red'>

## 10. Calculator Sales

---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
With the invention of the phone I'm sure you could imagine calculator sales have fallen over the past 20 years. Or have they?

Calculate, in percentages, the percentage change of how many calculators have been sold in 2023 compared to 2000.

**Round the percentage to 2 decimal places**.


</div>

---

In [51]:
calculators = pd.read_excel('datasets/Questions/Moderate/10.Calculator_Sales.xlsx')
calculators.head()

   year  calculator_sales
0  2000            472148
1  2001            479447
2  2002            447982
3  2003            459187
4  2004            462920

In [52]:
calculators = calculators.assign(percent_change = ((calculators['calculator_sales'] - 
                                                    calculators['calculator_sales'].iloc[0]) / 
                                                    calculators['calculator_sales'].iloc[0] * 100).round(2))
calculators

    year  calculator_sales  percent_change
0   2000            472148            0.00
1   2001            479447            1.55
2   2002            447982           -5.12
3   2003            459187           -2.75
4   2004            462920           -1.95
5   2005            408722          -13.43
6   2006            418161          -11.43
7   2007            375005          -20.57
8   2008            372145          -21.18
9   2009            318187          -32.61
10  2010            321716          -31.86
11  2011            333966          -29.27
12  2012            297449          -37.00
13  2013            288527          -38.89
14  2014            256762          -45.62
15  2015            239037          -49.37
16  2016            236945          -49.82
17  2017            186684          -60.46
18  2018            189696          -59.82
19  2019            184580          -60.91
20  2020            152717          -67.65
21  2021            126546          -73.20
22  2022            125560          -73.41
23  2023             95032          -79.87

In [53]:
result = pd.DataFrame({'percent_change': calculators[calculators['year'] == 2023]['percent_change']})
result

    percent_change
23          -79.87

---
---

<span style='color:red'>

## 11. Help Desk Manager

---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
James is a Help Desk Manager in their IT Department. He wants to know the `resolution rates for each of his employees`.

Each call the help desk receives is either marked as **`"Y"` for resolved** or **`"N"` for not resolved**.

Calculate each employees percentage of calls resolved compared to all their calls.

Output the `name of the employee` and their `resolution rate`. **Order on their name alphabetically**.

</div>

---

In [54]:
help_desk = pd.read_excel('datasets/Questions/Moderate/11.Help_Desk_Manager.xlsx')
help_desk

   employee_name call_outcome  call_time_in_minutes  call_date issue_category
0          Diana            N                    15 2023-01-14       Software
1          Ethan            Y                    11 2023-02-11       Hardware
2        Charlie            N                    17 2023-01-21        Account
3          Ethan            Y                    15 2023-01-04        Account
4          Ethan            N                     3 2023-01-31       Hardware
..           ...          ...                   ...        ...            ...
95         Alice            N                    16 2023-03-31          Email
96         Ethan            Y                    14 2023-03-08        Account
97           Bob            Y                    17 2023-03-05     Networking
98         Fiona            N                     4 2023-03-06       Software
99           Bob            Y                     4 2023-03-15       Software

[100 rows x 5 columns]

In [55]:
df_check = help_desk.groupby(by=['employee_name', 'call_outcome'])[
                'employee_name'].count().unstack(level=1)
df_check

call_outcome    N  Y
employee_name
Alice          13  6
Bob             7  9
Charlie        14  5
Diana          14  8
Ethan           8  5
Fiona           4  3
George          1  3

In [56]:
df_check['total'] = df_check['N'] + df_check['Y']
df_check

call_outcome    N  Y  total
employee_name
Alice          13  6     19
Bob             7  9     16
Charlie        14  5     19
Diana          14  8     22
Ethan           8  5     13
Fiona           4  3      7
George          1  3      4

In [57]:
df_check['Resolution_Rate'] = (df_check['Y'] / df_check['total']) *100
df_check

call_outcome    N  Y  total  Resolution_Rate
employee_name
Alice          13  6     19        31.578947
Bob             7  9     16        56.250000
Charlie        14  5     19        26.315789
Diana          14  8     22        36.363636
Ethan           8  5     13        38.461538
Fiona           4  3      7        42.857143
George          1  3      4        75.000000

In [58]:
result = pd.DataFrame(data=df_check[['Resolution_Rate']]).reset_index()
result

call_outcome employee_name  Resolution_Rate
0                    Alice        31.578947
1                      Bob        56.250000
2                  Charlie        26.315789
3                    Diana        36.363636
4                    Ethan        38.461538
5                    Fiona        42.857143
6                   George        75.000000

---
---

In [59]:
resolution_rate = help_desk.groupby(
    'employee_name')['call_outcome'].apply(lambda x: (
    x == 'Y').mean() * 100).reset_index(name='Resolution_Rate')

resolution_rate_sorted = resolution_rate.sort_values(by='employee_name')
resolution_rate_sorted

  employee_name  Resolution_Rate
0         Alice        31.578947
1           Bob        56.250000
2       Charlie        26.315789
3         Diana        36.363636
4         Ethan        38.461538
5         Fiona        42.857143
6        George        75.000000

In [60]:
help_desk.groupby('employee_name')['call_outcome'].count()

employee_name
Alice      19
Bob        16
Charlie    19
Diana      22
Ethan      13
Fiona       7
George      4
Name: call_outcome, dtype: int64

---
---

<span style='color:red'>

## 12. Multi-Level Marketing

---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
Sally is your average Stay at Home Mom so she decided to join an MLM (Multi Level Marketing) company.

She wants to **look at the months where she made a profit during the first 6 months of the year** (`January - June`).

Write a query to return the Month (number) and Profit that was made for each of those months.

**Order output by profit highest to lowest.**

Note: Any negative number in the "Profit" column are expenses for running the business.




</div>

---

In [61]:
profits = pd.read_excel('datasets/Questions/Moderate/12.Multi-Level Marketing.xlsx')
profits

         date  profit
0  2024-01-02   -2100
1  2024-01-07    1228
2  2024-01-08      84
3  2024-01-24    -654
4  2024-01-26    1436
..        ...     ...
56 2024-12-02    1966
57 2024-12-11    1273
58 2024-12-16   -1613
59 2024-12-21    1110
60 2024-12-27   -1405

[61 rows x 2 columns]

In [62]:
profits['Month'] = profits['date'].dt.month
profits

         date  profit  Month
0  2024-01-02   -2100      1
1  2024-01-07    1228      1
2  2024-01-08      84      1
3  2024-01-24    -654      1
4  2024-01-26    1436      1
..        ...     ...    ...
56 2024-12-02    1966     12
57 2024-12-11    1273     12
58 2024-12-16   -1613     12
59 2024-12-21    1110     12
60 2024-12-27   -1405     12

[61 rows x 3 columns]

In [63]:
profits.groupby('Month')['profit'].sum().reset_index()

    Month  profit
0       1      -6
1       2   -1333
2       3   -3527
3       4    1908
4       5   -2630
5       6     416
6       7    2013
7       8     993
8       9    -807
9      10    -666
10     11    3293
11     12    1331

In [64]:
df_group = profits.groupby(by='Month')['profit'].sum().reset_index(name='agg_profits')
df_group

    Month  agg_profits
0       1           -6
1       2        -1333
2       3        -3527
3       4         1908
4       5        -2630
5       6          416
6       7         2013
7       8          993
8       9         -807
9      10         -666
10     11         3293
11     12         1331

In [65]:
result = df_group[(df_group['Month'] <= 6) & (df_group['agg_profits'] > 0)].sort_values(by='agg_profits', ascending=False)
result

   Month  agg_profits
3      4         1908
5      6          416

---
---

In [ ]:
# ----------------------------------------Teachers Solution----------------------------------------
profits['date'] = pd.to_datetime(profits['date'])  
df_filtered = profits[profits['date'].dt.year == 2024]
df_filtered = df_filtered[df_filtered['date'].dt.month.between(1, 6)]

agg_profits = df_filtered.groupby(df_filtered['date'].dt.month)['profit'].sum().reset_index(name='agg_profits')
agg_profits = agg_profits[agg_profits['agg_profits'] > 0]
agg_profits.sort_values(by='agg_profits', ascending=False)

---
---

<span style='color:red'>

## 13. Unions

---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
Write a query to combine these 2 tables.

Output should include only the `Medication Name` and `Recommended Dosage`.

Do not remove duplicates if there are any.

Output should only be those 2 columns. **Order output on medication alphabetically**.


</div>

---

In [66]:
medication_information = pd.read_excel('datasets/Questions/Moderate/13.Medication_Info.xlsx', sheet_name='medication_information')
medication_information

,medication,classification,common_uses,side_effects,special_considerations,rec_dosage
0,Paracetamol,Analgesic,Pain relief - fever reduction,Nausea - rash - liver damage (high doses),Avoid alcohol; monitor liver function,500 to 1000 mg every 4 to 6 hours
1,Cetirizine (Zyrtec),Antihistamine,Allergies - hay fever,Drowsiness - dry mouth,Caution in elderly,10 mg once daily
2,Loratadine (Claritin),Antihistamine,Allergies - hay fever,Headache - fatigue - dry mouth,Non-drowsy; suitable for daily use,10 mg once daily
3,Amoxicillin,Antibiotic,Bacterial infections,Diarrhea - nausea - abdominal pain,Do not use for viral infections,250 to 500 mg every 8 hours
4,Clopidogrel (Plavix),Antiplatelet,Prevents blood clots,Bleeding - bruising,Avoid if you have bleeding disorders,75 mg once daily
5,Esomeprazole (Nexium),Proton pump inhibitor,Acid reflux - GERD,Headache - diarrhea - nausea,Short-term use recommended,20 to 40 mg once daily
6,Rosuvastatin (Crestor),Statin,Lower cholesterol,Muscle pain - diabetes risk - liver problems,Monitor liver function - lipid levels,5 to 40 mg once daily
7,Tamsulosin (Flomax),Alpha blocker,Enlarged prostate,Dizziness - ejaculation problems,Caution in cataract surgery,0.4 mg once daily
8,Venlafaxine (Effexor),Antidepressant,Depression - anxiety disorders,Nausea - dizziness - sexual dysfunction,Monitor blood pressure,75 to 225 mg once daily
9,Bupropion (Wellbutrin),Antidepressant,Depression - smoking cessation,Dry mouth - headache - insomnia,Seizure risk; avoid with eating disorders,150 to 300 mg once daily
10,Clonazepam (Klonopin),Benzodiazepine,Anxiety - seizure disorders,Drowsiness - dependency - withdrawal symptoms,Short-term use recommended,0.5 to 4 mg daily in divided doses
11,Pantoprazole (Protonix),Proton pump inhibitor,Acid reflux - GERD,Headache - diarrhea - nausea,Short-term use recommended,40 mg once daily

In [67]:
med_list = pd.read_excel('datasets/Questions/Moderate/13.Medication_Info.xlsx', sheet_name='med_list')
med_list

               medication_name                       recommended_dosage
0   Ibuprofen (Advil - Motrin)         200 to 400 mg every 4 to 6 hours
1      Acetaminophen (Tylenol)        500 to 1000 mg every 4 to 6 hours
2                      Aspirin              325 to 650 mg every 4 hours
3                  Amoxicillin              250 to 500 mg every 8 hours
4                   Lisinopril                   10 to 40 mg once daily
5                    Metformin  500 mg twice daily or 850 mg once daily
6       Atorvastatin (Lipitor)                   10 to 80 mg once daily
7                    Albuterol     2 puffs every 4 to 6 hours as needed
8          Simvastatin (Zocor)                   20 to 40 mg once daily
9         Amlodipine (Norvasc)                  2.5 to 10 mg once daily
10                  Metoprolol                 25 to 100 mg twice daily
11         Sertraline (Zoloft)                  50 to 200 mg once daily
12               Ciprofloxacin             250 to 750 mg every 12 hours
13         Fluoxetine (Prozac)                   20 to 80 mg once daily
14       Omeprazole (Prilosec)                         20 mg once daily
15         Hydrochlorothiazide                 12.5 to 50 mg once daily
16      Gabapentin (Neurontin)          300 to 600 mg three times daily
17                  Prednisone                    5 to 60 mg once daily
18   Levothyroxine (Synthroid)                 25 to 200 mcg once daily
19         Warfarin (Coumadin)  dosage varies- monitored by blood tests

In [68]:
medication_information = medication_information[['medication', 'rec_dosage']]
medication_information

                 medication                          rec_dosage
0               Paracetamol   500 to 1000 mg every 4 to 6 hours
1       Cetirizine (Zyrtec)                    10 mg once daily
2     Loratadine (Claritin)                    10 mg once daily
3               Amoxicillin         250 to 500 mg every 8 hours
4      Clopidogrel (Plavix)                    75 mg once daily
5     Esomeprazole (Nexium)              20 to 40 mg once daily
6    Rosuvastatin (Crestor)               5 to 40 mg once daily
7       Tamsulosin (Flomax)                   0.4 mg once daily
8     Venlafaxine (Effexor)             75 to 225 mg once daily
9    Bupropion (Wellbutrin)            150 to 300 mg once daily
10    Clonazepam (Klonopin)  0.5 to 4 mg daily in divided doses
11  Pantoprazole (Protonix)                    40 mg once daily

In [69]:
med_list.columns = ['medication', 'rec_dosage']
med_list

                    medication                               rec_dosage
0   Ibuprofen (Advil - Motrin)         200 to 400 mg every 4 to 6 hours
1      Acetaminophen (Tylenol)        500 to 1000 mg every 4 to 6 hours
2                      Aspirin              325 to 650 mg every 4 hours
3                  Amoxicillin              250 to 500 mg every 8 hours
4                   Lisinopril                   10 to 40 mg once daily
5                    Metformin  500 mg twice daily or 850 mg once daily
6       Atorvastatin (Lipitor)                   10 to 80 mg once daily
7                    Albuterol     2 puffs every 4 to 6 hours as needed
8          Simvastatin (Zocor)                   20 to 40 mg once daily
9         Amlodipine (Norvasc)                  2.5 to 10 mg once daily
10                  Metoprolol                 25 to 100 mg twice daily
11         Sertraline (Zoloft)                  50 to 200 mg once daily
12               Ciprofloxacin             250 to 750 mg every 12 hours
13         Fluoxetine (Prozac)                   20 to 80 mg once daily
14       Omeprazole (Prilosec)                         20 mg once daily
15         Hydrochlorothiazide                 12.5 to 50 mg once daily
16      Gabapentin (Neurontin)          300 to 600 mg three times daily
17                  Prednisone                    5 to 60 mg once daily
18   Levothyroxine (Synthroid)                 25 to 200 mcg once daily
19         Warfarin (Coumadin)  dosage varies- monitored by blood tests

In [70]:
concat_df = pd.concat([medication_information, med_list]).sort_values(by='medication')
concat_df

                    medication                               rec_dosage
1      Acetaminophen (Tylenol)        500 to 1000 mg every 4 to 6 hours
7                    Albuterol     2 puffs every 4 to 6 hours as needed
9         Amlodipine (Norvasc)                  2.5 to 10 mg once daily
3                  Amoxicillin              250 to 500 mg every 8 hours
3                  Amoxicillin              250 to 500 mg every 8 hours
2                      Aspirin              325 to 650 mg every 4 hours
6       Atorvastatin (Lipitor)                   10 to 80 mg once daily
9       Bupropion (Wellbutrin)                 150 to 300 mg once daily
1          Cetirizine (Zyrtec)                         10 mg once daily
12               Ciprofloxacin             250 to 750 mg every 12 hours
10       Clonazepam (Klonopin)       0.5 to 4 mg daily in divided doses
4         Clopidogrel (Plavix)                         75 mg once daily
5        Esomeprazole (Nexium)                   20 to 40 mg once daily
13         Fluoxetine (Prozac)                   20 to 80 mg once daily
16      Gabapentin (Neurontin)          300 to 600 mg three times daily
15         Hydrochlorothiazide                 12.5 to 50 mg once daily
0   Ibuprofen (Advil - Motrin)         200 to 400 mg every 4 to 6 hours
18   Levothyroxine (Synthroid)                 25 to 200 mcg once daily
4                   Lisinopril                   10 to 40 mg once daily
2        Loratadine (Claritin)                         10 mg once daily
5                    Metformin  500 mg twice daily or 850 mg once daily
10                  Metoprolol                 25 to 100 mg twice daily
14       Omeprazole (Prilosec)                         20 mg once daily
11     Pantoprazole (Protonix)                         40 mg once daily
0                  Paracetamol        500 to 1000 mg every 4 to 6 hours
17                  Prednisone                    5 to 60 mg once daily
6       Rosuvastatin (Crestor)                    5 to 40 mg once daily
11         Sertraline (Zoloft)                  50 to 200 mg once daily
8          Simvastatin (Zocor)                   20 to 40 mg once daily
7          Tamsulosin (Flomax)                        0.4 mg once daily
8        Venlafaxine (Effexor)                  75 to 225 mg once daily
19         Warfarin (Coumadin)  dosage varies- monitored by blood tests

---
---

<span style='color:red'>

## 14. Product Launch

---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
You are given a table of product launches for companies each year.

Write a query to count the **net difference between the **number of products companies launched in 2023** with the **number of products companies launched in the previous year**.

Output the `name of the companies` and the `net difference of products released` for 2023 compared to the previous year.

Order on company name alphabetically.


</div>

---

In [71]:
import pandas as pd
import numpy as np

In [72]:
df = pd.read_excel('datasets/Questions/Moderate/14.Product_Launch.xlsx')
df

    year company_name   product_name
0   2022        Apple      iPhone 13
1   2022        Apple      iPhone SE
2   2023        Apple      iPhone 14
3   2022      Samsung     Galaxy S21
4   2022      Samsung  Galaxy Note20
5   2022      Samsung     Galaxy A52
6   2023      Samsung     Galaxy S22
7   2022       Huawei            P50
8   2023       Huawei            P60
9   2023       Huawei        Mate 50
10  2022       Google        Pixel 6
11  2023       Google        Pixel 7
12  2022       Xiaomi          Mi 11
13  2023       Xiaomi          Mi 12
14  2023         Oppo        Find X3
15  2023         Oppo         Reno 5
16  2022         Oppo         Reno 6
17  2023         Sony       Xperia 2

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   year          18 non-null     int64
 1   company_name  18 non-null     object
 2   product_name  18 non-null     object
dtypes: int64(1), object(2)
memory usage: 564.0+ bytes

In [74]:
separate_df = df.groupby(by=['year', 'company_name'])['year'].count()
separate_df = separate_df.unstack(level=0).fillna(0).reset_index()
separate_df

year company_name  2022  2023
0           Apple   2.0   1.0
1          Google   1.0   1.0
2          Huawei   1.0   2.0
3            Oppo   1.0   2.0
4         Samsung   3.0   1.0
5            Sony   0.0   1.0
6          Xiaomi   1.0   1.0

In [75]:
print(separate_df.columns)

Index(['company_name', 2022, 2023], dtype='object', name='year')

In [76]:
separate_df['difference'] = separate_df[2023]- separate_df[2022] 
result = separate_df[['company_name', 'difference']].sort_values(by='company_name')
result

year company_name  difference
0           Apple        -1.0
1          Google         0.0
2          Huawei         1.0
3            Oppo         1.0
4         Samsung        -2.0
5            Sony         1.0
6          Xiaomi         0.0

---
---

<span style='color:red'>

## 15. Gmail Users

---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
Identify all of the customers that use gmail as their email provider.

Provide their `customer_id`, `name`, and `email`.

**Order the output by `customer_id` in ascending order**.

</div>

---

In [ ]:
import pandas as pd
import numpy as np

In [77]:
df = pd.read_excel('datasets/Questions/Moderate/15.Gmail_Users.xlsx')
df.head()

,customer_id,name,email,subscription_status,last_purchase_date
0,1,John Doe,john.doe@gmail.com,Active,2023-01-15
1,2,Jane Smith,jane.smith@yahoo.com,Inactive,2022-11-20
2,3,Mike Johnson,mike.johnson@gmail.com,Active,2023-02-05
3,4,Emily White,emily.white@gmail.com,Active,2023-03-10
4,5,David Brown,david.brown@hotmail.com,Inactive,2022-12-05

In [78]:
df[df['email'].str.contains('@gmail') == True]

,customer_id,name,email,subscription_status,last_purchase_date
0,1,John Doe,john.doe@gmail.com,Active,2023-01-15
2,3,Mike Johnson,mike.johnson@gmail.com,Active,2023-02-05
3,4,Emily White,emily.white@gmail.com,Active,2023-03-10
5,6,Sarah Taylor,sarah.taylor@gmail.com,Active,2023-02-28
6,7,Brian Davis,brian.davis@gmail.com,Active,2023-03-05
8,9,Kevin Clark,kevin.clark@gmail.com,Active,2023-01-20
9,10,Anna Lee,anna.lee@gmail.com,Active,2023-03-15
11,12,Jessica Turner,jessica.turner@gmail.com,Active,2023-02-10
12,13,Richard Moore,richard.moore@gmail.com,Active,2023-03-12
14,15,Chris Adams,chris.adams@gmail.com,Active,2023-01-25
15,16,Megan Cooper,megan.cooper@gmail.com,Active,2023-02-15
17,18,Rachel Parker,rachel.parker@gmail.com,Active,2023-03-08
18,19,Eric Turner,eric.turner@gmail.com,Active,2023-01-28
19,20,Olivia Baker,olivia.baker@gmail.com,Active,2023-03-18
21,22,Emily Turner,emily.turner@gmail.com,Active,2023-02-20
22,23,Michael Adams,michael.adams@gmail.com,Active,2023-03-02
24,25,Ryan Miller,ryan.miller@gmail.com,Active,2023-01-30
25,26,Lisa Turner,lisa.turner@gmail.com,Active,2023-02-22
26,27,Jordan Harris,jordan.harris@gmail.com,Active,2023-03-25
28,29,Matthew Johnson,matthew.johnson@gmail.com,Active,2023-01-05
29,30,Rachel Miller,rachel.miller@gmail.com,Active,2023-03-30
31,32,Emily Adams,emily.adams@gmail.com,Active,2023-02-18
32,33,Zachary Clark,zachary.clark@gmail.com,Active,2023-03-22
34,35,Brian Turner,brian.turner@gmail.com,Active,2023-01-10
35,36,Samantha Hall,samantha.hall@gmail.com,Active,2023-02-08
37,38,Amanda Davis,amanda.davis@gmail.com,Active,2023-03-16
38,39,Patrick Turner,patrick.turner@gmail.com,Active,2023-01-15
40,41,Joshua Baker,joshua.baker@gmail.com,Active,2023-02-25
41,42,Vanessa White,vanessa.white@gmail.com,Active,2023-03-28
43,44,Lauren Adams,lauren.adams@gmail.com,Active,2023-01-18
44,45,Justin Harris,justin.harris@gmail.com,Active,2023-03-10
46,47,Benjamin White,benjamin.white@gmail.com,Active,2023-02-28
47,48,Kimberly Davis,kimberly.davis@gmail.com,Active,2023-03-05
49,50,Morgan Miller,morgan.miller@gmail.com,Active,2023-01-22

---
---

<span style='color:red'>

## 16. Intern Problems

---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
We had two different interns manually inputting the data into our database.

Unfortunately they hadn't agreed on a format beforehand.... of course.

Standardize the output so all of the answers are either `"Y"` or `"N"`.


</div>

---

In [ ]:
import pandas as pd
import numpy as np

In [79]:
df = pd.read_excel('datasets/Questions/Moderate/16.Intern_Problems.xlsx')
df

   response
0       Yes
1       Yes
2       Yes
3        No
4        No
5       Yes
6        No
7       Yes
8        No
9         Y
10        N
11        Y
12        Y
13        Y
14        N
15        N
16        N
17        N
18        Y

In [80]:
df['standardized'] = df['response'].apply(lambda x: 'Y' if x.startswith('Y') else 'N')
result = df[['standardized']]
result

   standardized
0             Y
1             Y
2             Y
3             N
4             N
5             Y
6             N
7             Y
8             N
9             Y
10            N
11            Y
12            Y
13            Y
14            N
15            N
16            N
17            N
18            Y

---
---

<span style='color:red'>

## 17. SuperCoolElectronicsStore.com

---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
Customers on the SuperCoolElectronicsStore.com's website are having to manually check each laptop see whether it has SSD or HDD storage.

The Owner of the store wants to categorize his laptops so clients can filter on it. **We need to add this field to the table**.

**Add a column called `"storage_type"`**. If the Laptop is SSD give it an "SSD" label. If it is HDD give it an "HDD" label.

Include all columns from original table in your output with your new column at the end.

**Order the data on `laptop id` from smallest to largest**.


</div>

---

In [81]:
import pandas as pd
import numpy as np

In [82]:
df = pd.read_excel('datasets/Questions/Moderate/17.SuperCool.xlsx')
df.head()

   laptop_id                                       laptop_name    price
0          1                 Acer Aspire 5 - 1TB HDD - 8GB RAM   699.99
1          2                Dell XPS 13 - 512GB SSD - 16GB RAM  1299.99
2          3             HP Pavilion 15 - 500GB HDD - 12GB RAM   549.99
3          4  Lenovo ThinkPad X1 Carbon - 256GB SSD - 16GB RAM  1499.99
4          5      ASUS ROG Strix Scar III - 1TB HDD - 32GB RAM  1899.99

In [83]:
df['storage_type'] = df['laptop_name'].str.extract(r'\-\s[0-9A-Z]+\s([A-Z]+)')
df.sort_values('laptop_id', inplace=True)
df

,laptop_id,laptop_name,price,storage_type
0,1,Acer Aspire 5 - 1TB HDD - 8GB RAM,699.99,HDD
1,2,Dell XPS 13 - 512GB SSD - 16GB RAM,1299.99,SSD
2,3,HP Pavilion 15 - 500GB HDD - 12GB RAM,549.99,HDD
3,4,Lenovo ThinkPad X1 Carbon - 256GB SSD - 16GB RAM,1499.99,SSD
4,5,ASUS ROG Strix Scar III - 1TB HDD - 32GB RAM,1899.99,HDD
5,6,MacBook Air (M1 2020) - 512GB SSD - 8GB RAM,999.99,SSD
6,7,Dell Inspiron 14 - 1TB HDD - 8GB RAM,449.99,HDD
7,8,HP Spectre x360 - 512GB SSD - 16GB RAM,1299.99,SSD
8,9,Lenovo Legion Y540 - 1TB HDD - 16GB RAM,1199.99,HDD
9,10,MacBook Pro 13 (M1 2020) - 256GB SSD - 8GB RAM,1299.99,SSD
10,11,Acer Predator Helios 300 - 1TB HDD - 16GB RAM,1299.99,HDD
11,12,Dell G7 17 - 512GB SSD - 32GB RAM,1699.99,SSD
12,13,ASUS VivoBook 15 - 500GB HDD - 12GB RAM,599.99,HDD
13,14,Microsoft Surface Laptop 4 - 512GB SSD - 16GB RAM,1299.99,SSD
14,15,Lenovo Yoga C930 - 1TB HDD - 8GB RAM,1099.99,HDD
15,16,MSI GS66 Stealth - 1TB SSD - 32GB RAM,1999.99,SSD
16,17,HP Envy x360 - 256GB SSD - 16GB RAM,899.99,SSD
17,18,Dell Alienware m15 - 512GB SSD - 32GB RAM,2199.99,SSD
18,19,Acer Swift 3 - 500GB HDD - 8GB RAM,699.99,HDD
19,20,MacBook Pro 16 (Intel 2019) - 1TB SSD - 16GB RAM,2399.99,SSD
20,21,ASUS ZenBook 14 - 512GB SSD - 16GB RAM,899.99,SSD
21,22,HP Omen 15 - 1TB SSD - 32GB RAM,1499.99,SSD
22,23,Lenovo IdeaPad L340 - 1TB HDD - 12GB RAM,799.99,HDD
23,24,Microsoft Surface Pro 7 - 256GB SSD - 8GB RAM,899.99,SSD
24,25,Dell Precision 5750 - 2TB HDD - 64GB RAM,2999.99,HDD

In [85]:
df1 = pd.read_excel('datasets/Questions/Moderate/17.SuperCool.xlsx')

df1['storage_type'] = df1['laptop_name'].str.extract(r'(HDD|SSD)')
df1.sort_values('laptop_id', inplace=True)
df1

,laptop_id,laptop_name,price,storage_type
0,1,Acer Aspire 5 - 1TB HDD - 8GB RAM,699.99,HDD
1,2,Dell XPS 13 - 512GB SSD - 16GB RAM,1299.99,SSD
2,3,HP Pavilion 15 - 500GB HDD - 12GB RAM,549.99,HDD
3,4,Lenovo ThinkPad X1 Carbon - 256GB SSD - 16GB RAM,1499.99,SSD
4,5,ASUS ROG Strix Scar III - 1TB HDD - 32GB RAM,1899.99,HDD
5,6,MacBook Air (M1 2020) - 512GB SSD - 8GB RAM,999.99,SSD
6,7,Dell Inspiron 14 - 1TB HDD - 8GB RAM,449.99,HDD
7,8,HP Spectre x360 - 512GB SSD - 16GB RAM,1299.99,SSD
8,9,Lenovo Legion Y540 - 1TB HDD - 16GB RAM,1199.99,HDD
9,10,MacBook Pro 13 (M1 2020) - 256GB SSD - 8GB RAM,1299.99,SSD
10,11,Acer Predator Helios 300 - 1TB HDD - 16GB RAM,1299.99,HDD
11,12,Dell G7 17 - 512GB SSD - 32GB RAM,1699.99,SSD
12,13,ASUS VivoBook 15 - 500GB HDD - 12GB RAM,599.99,HDD
13,14,Microsoft Surface Laptop 4 - 512GB SSD - 16GB RAM,1299.99,SSD
14,15,Lenovo Yoga C930 - 1TB HDD - 8GB RAM,1099.99,HDD
15,16,MSI GS66 Stealth - 1TB SSD - 32GB RAM,1999.99,SSD
16,17,HP Envy x360 - 256GB SSD - 16GB RAM,899.99,SSD
17,18,Dell Alienware m15 - 512GB SSD - 32GB RAM,2199.99,SSD
18,19,Acer Swift 3 - 500GB HDD - 8GB RAM,699.99,HDD
19,20,MacBook Pro 16 (Intel 2019) - 1TB SSD - 16GB RAM,2399.99,SSD
20,21,ASUS ZenBook 14 - 512GB SSD - 16GB RAM,899.99,SSD
21,22,HP Omen 15 - 1TB SSD - 32GB RAM,1499.99,SSD
22,23,Lenovo IdeaPad L340 - 1TB HDD - 12GB RAM,799.99,HDD
23,24,Microsoft Surface Pro 7 - 256GB SSD - 8GB RAM,899.99,SSD
24,25,Dell Precision 5750 - 2TB HDD - 64GB RAM,2999.99,HDD

---
---

<span style='color:red'>

## 18. Must Buy it All

---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
A company is about to launch a new product and wants to estimate how many current customers will buy their new product.

To do this, they want to identify all of the past customers who have bought all of their products.

They currently only have 4 products.

**Write a query to identify `customer_IDs` that have bought all of their current products.**

Note: If a customer buys many of the same product that still only counts as buying one of their products.

`HINTS: If someone has purchased 4 unique product_ids they will be in the output.`


</div>

---

In [86]:
import pandas as pd
import numpy as np

In [87]:
df = pd.read_excel('datasets/Questions/Moderate/18.Must_Buy_it.xlsx')
df.head()

   customer_id  product_id purchase_date
0         1004           1    2018-08-15
1         1002           1    2019-07-01
2         1001           1    2019-08-20
3         1004           2    2019-09-06
4         1003           1    2019-10-26

In [88]:
eval_df = df.groupby(['customer_id', 'product_id'])['product_id'].count().unstack(level=1).fillna(0).reset_index()
eval_df

product_id  customer_id    1    2    3    4
0                  1001  1.0  1.0  1.0  1.0
1                  1002  1.0  1.0  3.0  0.0
2                  1003  2.0  1.0  0.0  0.0
3                  1004  1.0  1.0  0.0  0.0
4                  1005  2.0  1.0  1.0  1.0

In [89]:
eval_df = eval_df.assign(total_products = (eval_df[1] > 0).astype(int) + (eval_df[2] > 0).astype(int) + 
               (eval_df[3] > 0).astype(int) + (eval_df[4] > 0).astype(int))
eval_df

product_id  customer_id    1    2    3    4  total_products
0                  1001  1.0  1.0  1.0  1.0               4
1                  1002  1.0  1.0  3.0  0.0               3
2                  1003  2.0  1.0  0.0  0.0               2
3                  1004  1.0  1.0  0.0  0.0               2
4                  1005  2.0  1.0  1.0  1.0               4

In [90]:
result = eval_df[eval_df['total_products'] == 4][['customer_id']]
result

product_id  customer_id
0                  1001
4                  1005

---
---

<span style='color:red'>

## 19. TMI (Too Much Information)

---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
Often when you're working with customer information you'll want to sell that data to a third party. Sometimes it is illegal to give away sensitive information such as a full name.

Here you are given a table that contains a customer ID and their full name.

Return the customer ID with only the first name of each customer.


`HINTS: You'll need to split it on a delimiter (the space). Split on this and only keep the first name.`


</div>

---

In [91]:
import pandas as pd
import numpy as np

In [92]:
df = pd.read_excel('datasets/Questions/Moderate/19.TMI.xlsx')
df.head()

   customer_id      full_name
0         1001    John McGary
1         1002      Sally Sue
2         1003   Jenny McBlue
3         1004  Craig Johnson
4         1005      Henry Hue

In [93]:
df['first_name'] = df['full_name'].str.extract(r'(\w+)\s')
df

   customer_id      full_name first_name
0         1001    John McGary       John
1         1002      Sally Sue      Sally
2         1003   Jenny McBlue      Jenny
3         1004  Craig Johnson      Craig
4         1005      Henry Hue      Henry
5         1006  Alex Freebird       Alex

In [94]:
result = df[['customer_id', 'first_name']]
result

   customer_id first_name
0         1001       John
1         1002      Sally
2         1003      Jenny
3         1004      Craig
4         1005      Henry
5         1006       Alex

---
---

<span style='color:red'>

## 20. Separation

---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
Data was input incorrectly into the database. The ID was combined with the First Name.

Write a query to separate the ID and First Name into two separate columns.

Each ID is 5 characters long.

---

`HINTS:` 

 - Since we know the ID is exactly 5 characters long we need to take the first 5 characters as the ID column.

 - For the First Name column we need to start at position 6 and take everything after it. The name is a variable length so we can't be sure how many characters we will need to take.You'll need to split it on a delimiter (the space). Split on this and only keep the first name.`


</div>

---

In [95]:
import pandas as pd
import numpy as np

In [120]:
df = pd.read_excel('datasets/Questions/Moderate/20.Separation.xlsx')
df

             id
0   12345Johnny
1    93829Sally
2    20391Larry
3  29324Valerie

In [121]:
df[['ID', 'First_Name']] = df['id'].str.extract(r'(\d{5})(\w+)')
df

             id     ID First_Name
0   12345Johnny  12345     Johnny
1    93829Sally  93829      Sally
2    20391Larry  20391      Larry
3  29324Valerie  29324    Valerie

In [122]:
result = df[['ID', 'First_Name']]
result

      ID First_Name
0  12345     Johnny
1  93829      Sally
2  20391      Larry
3  29324    Valerie

---
---

<span style='color:red'>

## 21. Teach Layoffs

---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
Tech companies have been laying off employees after a large surge of hires in the past few years.

Write a query to determine the percentage of employees that were laid off from each company.

Output should include the company and the percentage (to 2 decimal places) of laid off employees.

Order by company name alphabetically.

---

`HINTS:` 

 - Percentage calculation is as follows: employees_fired / company_size * 100


</div>

---

In [127]:
df = pd.read_excel('datasets/Questions/Moderate/21.Tech_Layoffs.xlsx')
df

     company  company_size  employees_fired
0      Apple        147000                0
1  Microsoft        181000             6000
2     Google        139500            15000
3     Amazon       1300000            12000
4   Facebook         60750            11000
5      Tesla         70000             1000

In [128]:
df = df.assign(Percentage_Laid_Off = round((df['employees_fired'] / df['company_size']) * 100, 2))
df

     company  company_size  employees_fired  Percentage_Laid_Off
0      Apple        147000                0                 0.00
1  Microsoft        181000             6000                 3.31
2     Google        139500            15000                10.75
3     Amazon       1300000            12000                 0.92
4   Facebook         60750            11000                18.11
5      Tesla         70000             1000                 1.43

In [129]:
result = df[['company', 'Percentage_Laid_Off']].sort_values(by='company')
result

     company  Percentage_Laid_Off
3     Amazon                 0.92
0      Apple                 0.00
4   Facebook                18.11
2     Google                10.75
1  Microsoft                 3.31
5      Tesla                 1.43

---
---

<span style='color:red'>

## 22. Kroger's Members
---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>

Kroger's is a very popular grocery chain in the US. They offer a membership card in exchange for a discount on select items. Customers can still shop at Krogers without the card.

Write a query to **find the percentage of customers who shop at Kroger's who also have a Kroger's membership card**. Round to 2 decimal places.


</div>

---

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("datasets/Questions/Moderate/22.Kroger's_Members.xlsx")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kroger_id        30 non-null     int64
 1   has_member_card  17 non-null     object
dtypes: int64(1), object(1)
memory usage: 612.0+ bytes

In [3]:
df.fillna('N', inplace=True)
df.head()

   kroger_id has_member_card
0          1               Y
1          2               Y
2          3               N
3          4               Y
4          5               N

In [4]:
df['has_member_card'] = df['has_member_card'].apply(lambda x: 1 if x.startswith('Y') else 0)
df.head()

   kroger_id  has_member_card
0          1                1
1          2                1
2          3                0
3          4                1
4          5                0

In [5]:
round((df['has_member_card'].sum() / len(df['has_member_card'])) * 100, 2)

np.float64(56.67)

In [7]:
# Teacher Solution
customers = pd.read_excel('datasets/Questions/Moderate/22.Kroger\'s_Members.xlsx')
customers.head()

   kroger_id has_member_card
0          1               Y
1          2               Y
2          3             NaN
3          4               Y
4          5             NaN

In [9]:
customers[customers['has_member_card'] == 'Y'].shape[0]

17

In [13]:
customers[customers['kroger_id'].notnull()].shape[0]

30

In [14]:
result = (customers[customers['has_member_card'] == 'Y'].shape[0] / customers[
                customers['kroger_id'].notnull()].shape[0])*100
result

56.666666666666664

In [15]:
result = round(result,2)
result

56.67

---
---

<span style='color:red'>

## 23. Food Divides Us
---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
In the United States, fast food is the cornerstone of it's very society. Without it, it would cease to exist.

But which region spends the most money on fast food?

Write a query to `determine which region spends the most amount of money on fast food`.



</div>

---

In [17]:
df = pd.read_excel('datasets/Questions/Moderate/23.Food_Divides_Us.xlsx')
df.head()

        state region  fast_food_millions
0     Alabama  South                  83
1      Alaska   West                  80
2     Arizona   West                  81
3    Arkansas  South                  45
4  California   West                  52

In [27]:
result = df.groupby(by='region')['fast_food_millions'].sum().reset_index()
result

      region  fast_food_millions
0    Midwest                 582
1  Northeast                 506
2      South                1043
3       West                 907

In [32]:
result.nlargest(1, 'fast_food_millions')

  region  fast_food_millions
2  South                1043

In [34]:
result = result.nlargest(1, 'fast_food_millions')[['region']]
result

  region
2  South

---
---

<span style='color:red'>

## 24. Crew Overspending
---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>

A construction company gave each employee a $100 per diem for food for the week. If they spend over that amount they owe the company that money back.

Calculate how much each person spent and how much they owe the company. If they spent less than USD 100 they owe USD 0.

Provide the `employee_id`, `amount spent`, and `amount owed` (labeled "amount_owed") in the output.

Order by the `amount owed from highest to lowest`. Order by `employee id `if there are multiple people who owe the same amount.

</div>

---

In [35]:
df = pd.read_excel('datasets/Questions/Moderate/24.Crew_Overspending.xlsx')
df.head()

   employee_id  transaction_id  amount_spent
0         1003             119            20
1         1008             121            19
2         1007             196            13
3         1002             203            28
4         1007             217            14

In [43]:
filt_df = df.groupby(by='employee_id')['amount_spent'].sum().reset_index()
filt_df

   employee_id  amount_spent
0         1001            67
1         1002           103
2         1003            92
3         1004           125
4         1005           107
5         1006            95
6         1007            68
7         1008            69
8         1009           118

In [44]:
filt_df['amount_owed'] = filt_df['amount_spent'].apply(lambda x: x - 100 if x > 100 else 0)
filt_df

   employee_id  amount_spent  amount_owed
0         1001            67            0
1         1002           103            3
2         1003            92            0
3         1004           125           25
4         1005           107            7
5         1006            95            0
6         1007            68            0
7         1008            69            0
8         1009           118           18

In [46]:
result = filt_df.sort_values(by=['amount_owed'], ascending=False)
result

   employee_id  amount_spent  amount_owed
3         1004           125           25
8         1009           118           18
4         1005           107            7
1         1002           103            3
0         1001            67            0
2         1003            92            0
5         1006            95            0
6         1007            68            0
7         1008            69            0

---
---

<span style='color:red'>

## 25. Greenhouse Gases
---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
Write a query to determine which country produced the most total greenhouse gases from 2020 - 2022.

Include the country and their total Greenhouse Gases in your output.

`Note: round greenhouse gases to 1 decimal place.`


</div>

---

In [1]:
import pandas as pd

In [3]:
df = pd.read_excel('datasets/Questions/Moderate/25.GreenHouse_Gases.xlsx')
df.head()

   year        country  carbon_emissions_millions
0  2022          China                    10170.5
1  2022  United States                     5147.0
2  2022          India                     3207.6
3  2022         Russia                     1740.8
4  2022          Japan                     1197.5

In [5]:
df['year'].value_counts()

year
2022    15
2021    15
2020    15
Name: count, dtype: int64

In [4]:
result = df.groupby(
    by='country')['carbon_emissions_millions'].sum().sort_values(
    ascending=False).reset_index().head(1)
result

  country  carbon_emissions_millions
0   China                    31167.8

---
---

<span style='color:red'>

## 26. Direct Reports
---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
Write a query to determine how many direct reports each Manager has.

`Note: Managers will have "Manager" in their title.`

Report the Manager ID, Manager Title, and the number of direct reports in your output.

</div>

---

In [28]:
df = pd.read_excel('datasets/Questions/Moderate/26.Direct_Reports.xlsx')
df.head()

   employee_id            position  managers_id
0         1001   Analytics Manager       1013.0
1         1002       Data Engineer       1007.0
2         1003       Data Engineer       1001.0
3         1004  Database Developer       1017.0
4         1005        Data Analyst       1001.0

In [29]:
managers = df[df['position'].str.endswith('Manager')==True]
managers

    employee_id                  position  managers_id
0          1001         Analytics Manager       1013.0
6          1007  Data Engineering Manager       1013.0
16         1017      Data Science Manager       1013.0

In [38]:
total_reports = df.groupby(by='managers_id')['position'].count().reset_index(name='direct_reports')
total_reports

   managers_id  direct_reports
0       1001.0               6
1       1007.0               4
2       1013.0               3
3       1017.0               5

In [39]:
manager_reports = managers.merge(total_reports, left_on='employee_id', right_on='managers_id', how='left')
manager_reports

,employee_id,position,managers_id_x,managers_id_y,direct_reports
0,1001,Analytics Manager,1013.0,1001.0,6
1,1007,Data Engineering Manager,1013.0,1007.0,4
2,1017,Data Science Manager,1013.0,1017.0,5

In [42]:
manager_reports[['employee_id', 'position', 'direct_reports']].rename(columns={'employee_id':'manager_id',
                                                                               'position':'manager_position'})

   manager_id          manager_position  direct_reports
0        1001         Analytics Manager               6
1        1007  Data Engineering Manager               4
2        1017      Data Science Manager               5

---
---

<span style='color:red'>

## 27. Buying Less
---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
Amazon wants to identify customers who aren't spending much on their website to give them targeted discounts and ads.

Find customers who ordered `less than $250` worth of products or `placed 2 or less orders`.

</div>

---

In [43]:
df = pd.read_excel('datasets/Questions/Moderate/27.Buying_Less.xlsx')
df

    customer_id  order_total
0          1001          147
1          1001           45
2          1001           72
3          1001          114
4          1001           35
5          1001            7
6          1002           36
7          1002           62
8          1002           53
9          1002           75
10         1003           31
11         1003           12
12         1004           16
13         1004           80
14         1004           79
15         1004          150
16         1005           51
17         1005          112

In [46]:
money = df.groupby(by='customer_id')['order_total'].sum().reset_index(name='total_spend')
money

   customer_id  total_spend
0         1001          420
1         1002          226
2         1003           43
3         1004          325
4         1005          163

In [54]:
num_orders = df.groupby('customer_id').count().reset_index()
num_orders

   customer_id  order_total
0         1001            6
1         1002            4
2         1003            2
3         1004            4
4         1005            2

In [50]:
filtered_df = pd.merge(money, num_orders, on='customer_id')
filtered_df

   customer_id  total_spend  order_total
0         1001          420            6
1         1002          226            4
2         1003           43            2
3         1004          325            4
4         1005          163            2

In [53]:
result = filtered_df[(filtered_df['total_spend'] < 250) | (filtered_df['order_total'] <= 2)][['customer_id']]
result

   customer_id
1         1002
2         1003
4         1005

---

`Teacher's solution`

---

In [57]:
df.groupby('customer_id').filter(
    lambda group: group['order_total'].sum() < 250 or len(group) <= 2
        )[['customer_id']].drop_duplicates()

    customer_id
6          1002
10         1003
16         1005

---
---

<span style='color:red'>

## 28. Big Pharma
---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
A Pharmaceutical company wants to identify the drugs that are losing the most money.

Please write a query to find the `top 3 drugs that lost money`

---

**Note: If less than 3 drugs lost money, only output the drugs that lost money for the company.**

---


Output the `drug name`, `money spent`, `money made` and the `amount they lost` on that drug (rounded to one decimal place).

Order the output by largest loss to smallest loss.

</div>

---

In [58]:
df = pd.read_excel('datasets/Questions/Moderate/28.Big_Pharma.xlsx')
df

      drug_name  money_spent  money_made
0     Rituximab         10.2        35.8
1      Imatinib          4.5        22.1
2  Lenalidomide          8.7        28.9
3    Bortezomib          2.1        11.4
4     Ibrutinib         19.2         6.3
5     Nilotinib          3.2        16.5
6   Brentuximab          9.8        30.1
7   Carfilzomib          1.5         9.6
8  Pomalidomide         37.1        25.3
9    Enasidenib          5.6        20.9

In [60]:
df = df.assign(money_lost = df['money_made'] - df['money_spent'])
df

      drug_name  money_spent  money_made  money_lost
0     Rituximab         10.2        35.8        25.6
1      Imatinib          4.5        22.1        17.6
2  Lenalidomide          8.7        28.9        20.2
3    Bortezomib          2.1        11.4         9.3
4     Ibrutinib         19.2         6.3       -12.9
5     Nilotinib          3.2        16.5        13.3
6   Brentuximab          9.8        30.1        20.3
7   Carfilzomib          1.5         9.6         8.1
8  Pomalidomide         37.1        25.3       -11.8
9    Enasidenib          5.6        20.9        15.3

In [63]:
result = df[df['money_lost'] < 0]
result.loc[:, 'money_lost'] = abs(result['money_lost'])
result

      drug_name  money_spent  money_made  money_lost
4     Ibrutinib         19.2         6.3        12.9
8  Pomalidomide         37.1        25.3        11.8

---
---

<span style='color:red'>

## 29. Bike Price
---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
Sarah's Bike Shop sells a lot of bikes and wants to know what the average sale price is of her bikes.

She sometimes gives away a bike for free for a charity event and if she does she leaves the price of the bike as blank, but marks it sold.

Write a query to show her the average sale price of bikes for only bikes that were sold, and not donated.

Round answer to 2 decimal places.


</div>

---

In [64]:
df = pd.read_excel('datasets/Questions/Moderate/29.Bike_Price.xlsx')
df.head()

   bike_id  bike_price bike_sold
0     1001      329.99         Y
1     1002       99.99         Y
2     1003      109.99         Y
3     1004      299.99         Y
4     1005         NaN         N

In [65]:
filtered_df = df[df['bike_sold'] == 'Y']
filtered_df

    bike_id  bike_price bike_sold
0      1001      329.99         Y
1      1002       99.99         Y
2      1003      109.99         Y
3      1004      299.99         Y
5      1006      329.97         Y
7      1008       88.99         Y
8      1009         NaN         Y
9      1010      125.99         Y
12     1013      189.99         Y

In [68]:
result = filtered_df['bike_price'].astype(float).mean()
result = round(result, 2)
result

np.float64(196.86)

---
---

<span style='color:red'>

## 30. Gamer Tags
---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
Create a gamer tag for each player in the tournament.

Select the first 3 characters of their first name and combine that with the year they were born.

Your output should have their first name, last name, and gamer tag called "gamer_tag"

Order output on gamertag in alphabetical order.

</div>

---

In [79]:
df = pd.read_excel('datasets/Questions/Moderate/30.Gamer_Tag.xlsx')
print(df.info())
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   first_name  5 non-null      object
 1   last_name   5 non-null      object
 2   birth_date  5 non-null      datetime64[ns]
 3   game        5 non-null      object
dtypes: datetime64[ns](1), object(3)
memory usage: 292.0+ bytes
None

  first_name last_name birth_date               game
0  Alexander   Maxwell 1998-01-01  League of Legends
1     Johnny    Baxter 1997-11-05             Dota 2
2      Kelly    Zillen 1996-03-04  League of Legends
3      Kevin    Mallow 2000-12-12  League of Legends
4       Lisa      Larz 1997-03-04             Dota 2

In [81]:
df['birth_date'] = pd.to_datetime(df['birth_date'])

In [82]:
df['gamer_tag'] = df['first_name'].str[:3] + df['birth_date'].dt.year.astype(str)
df

  first_name last_name birth_date               game gamer_tag
0  Alexander   Maxwell 1998-01-01  League of Legends   Ale1998
1     Johnny    Baxter 1997-11-05             Dota 2   Joh1997
2      Kelly    Zillen 1996-03-04  League of Legends   Kel1996
3      Kevin    Mallow 2000-12-12  League of Legends   Kev2000
4       Lisa      Larz 1997-03-04             Dota 2   Lis1997

In [83]:
result = df.sort_values(by='gamer_tag')
result[['first_name', 'last_name', 'gamer_tag']]

  first_name last_name gamer_tag
0  Alexander   Maxwell   Ale1998
1     Johnny    Baxter   Joh1997
2      Kelly    Zillen   Kel1996
3      Kevin    Mallow   Kev2000
4       Lisa      Larz   Lis1997

---
---

<span style='color:red'>

## 31. Richie Rich
---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
Select all of the companies that had Total profits higher than 20 million over the past 3 years.

Assume today's date is 2023-1-1. Look back 3 years from this day.

Order companies alphabetically.

</div>

---

In [1]:
import pandas as pd
import numpy as np

In [3]:
df_31 = pd.read_excel('datasets/Questions/Moderate/31.Richie_Rich.xlsx')
df_31.head()

     company       year   profit
0  Techastro 2023-01-01  4000000
1  Techastro 2022-12-20  2000000
2  Techastro 2021-05-24  8000000
3  Techastro 2020-03-26  5000000
4  Techastro 2019-02-05  2000000

In [4]:
df_31.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   company  15 non-null     object
 1   year     15 non-null     datetime64[ns]
 2   profit   15 non-null     int64
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 492.0+ bytes

In [10]:
date_filter = df_31[df_31['year'] < '01/01/2023'].groupby('company')['profit'].sum().reset_index()
result = date_filter[date_filter['profit'] > 20000000][['company']]
result

         company
0  Delivery Pros

---
---

<span style='color:red'>

## 32. Boss
---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
My Boss wants a report that shows each employee and their bosses name so he can try to memorize it before our quarterly social event.

Provide an output that includes the employee name matched with the name of their boss.

If they don't have a boss still include them in the output.

Order output on employee name alphabetically.

</div>

---

In [24]:
df_32 = pd.read_excel('datasets/Questions/Moderate/32.Boss.xlsx')
df_32.head()

   employee_id    employee_name  boss_id
0            1      Josh Harper      NaN
1            2  Carolina Fancis      NaN
2            3    Gerald Butler      2.0
3            4      Richie Rich      3.0
4            5    Carol Danvers      NaN

In [25]:
df_32.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   employee_id    8 non-null      int64
 1   employee_name  8 non-null      object
 2   boss_id        4 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 324.0+ bytes

In [32]:
df_merged = df_32.merge(df_32[['employee_id', 'employee_name']], left_on='boss_id', 
                        right_on='employee_id', how='left', suffixes=('', '_boss'))
result = (df_merged[['employee_name', 'employee_name_boss']].sort_values(by='employee_name')
          .reset_index(drop=True))
result.columns = ['Employee_Name', 'Boss_Name']
result

     Employee_Name        Boss_Name
0    Carol Danvers              NaN
1  Carolina Fancis              NaN
2    Donald Glover              NaN
3    Gerald Butler  Carolina Fancis
4      Josh Harper              NaN
5   Peter McMillan  Carolina Fancis
6      Richie Rich    Gerald Butler
7   Sarah Burdauch    Carol Danvers

---
---

<span style='color:red'>

## 33. Stock Price
---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
Write a query to report the capital gain/loss for each stock.

The Capital gain/loss of a stock is the total gain or loss after buying and selling the stock one or many times.

Provide the stock name and Capital gain/loss as "capital_gain_loss".

</div>

---

In [33]:
df_33 = pd.read_excel('datasets/Questions/Moderate/33.Stock_Price.xlsx')
df_33.head()

  stock action  price       date
0  ASDE    Buy   1000 2022-01-01
1  RTYY    Buy   5000 2022-01-02
2  BVVR    Buy   2500 2022-01-03
3  ASDE    Buy   1000 2022-01-04
4  RTYY   Sell   8000 2022-01-05

In [38]:
df_buy = df_33[df_33['action'] == 'Buy'].groupby('stock')['price'].sum().reset_index()
df_buy

  stock  price
0  ASDE   2000
1  BVVR   2500
2  RTYY   8000

In [42]:
df_sell = df_33[df_33['action'] == 'Sell'].groupby('stock')['price'].sum().reset_index()
df_sell

  stock  price
0  ASDE   3000
1  BVVR   6500
2  RTYY   8000

In [47]:
df_merged = df_sell.merge(df_buy, on='stock', how='left', suffixes=('_sell', '_buy'))
df_merged['Total'] = df_merged['price_sell'] - df_merged['price_buy']
df_merged

  stock  price_sell  price_buy  Total
0  ASDE        3000       2000   1000
1  BVVR        6500       2500   4000
2  RTYY        8000       8000      0

In [49]:
result = df_merged[['stock', 'Total']]
result.columns =['Stock', 'Capital_Gain_Loss']
result

  Stock  Capital_Gain_Loss
0  ASDE               1000
1  BVVR               4000
2  RTYY                  0

---

<span style='color:orange'>
    
Teacher Solution

---

In [60]:
df_33.head(3)

  stock action  price       date  capital_gain_loss
0  ASDE    Buy   1000 2022-01-01              -1000
1  RTYY    Buy   5000 2022-01-02              -5000
2  BVVR    Buy   2500 2022-01-03              -2500

In [63]:
df_33['capital_gain_loss'] = df_33.apply(lambda x: -x['price'] if x['action']=='Buy' else x['price'], 
                                         axis=1)
df_33

  stock action  price       date  capital_gain_loss
0  ASDE    Buy   1000 2022-01-01              -1000
1  RTYY    Buy   5000 2022-01-02              -5000
2  BVVR    Buy   2500 2022-01-03              -2500
3  ASDE    Buy   1000 2022-01-04              -1000
4  RTYY   Sell   8000 2022-01-05               8000
5  BVVR   Sell   2000 2022-01-06               2000
6  ASDE   Sell   3000 2022-01-07               3000
7  RTYY    Buy   3000 2022-01-08              -3000
8  BVVR   Sell   4500 2022-01-09               4500

In [64]:
df_33.groupby('stock')['capital_gain_loss'].sum().reset_index()

  stock  capital_gain_loss
0  ASDE               1000
1  BVVR               4000
2  RTYY                  0

---
---

<span style='color:red'>

## 40. Must Buy it All
---

<div style='background-color:darkblue; padding:15px;'>

<span style='color:orange'>
    
The world is taking on debt like there is no tomorrow, but which country is taking on the most?

Write a query to find the top 3 countries with the largest national debt for the most recent year.

The output should have the columns `Country` and `National_Debt` (*round to the nearest whole number*), and should be **ordered by National_Debt in descending order**.


</div>

---